### PR TITLE
Fix Etcd launcher to tolerate docker errors better

### LINKED ISSUE #2508: agent etcd launcher might update_membership even though etcd is still running
If the agent [`Kontena::Launchers::Etcd#create_container`](https://github.com/kontena/kontena/blob/v1.3.1/agent/lib/kontena/launchers/etcd.rb#L107-L109) determines that the local `kontena-etcd` Docker container does not exist, it will run `update_membership` to determine if the etcd cluster needs to be reconfigured to accept the new container that it is about to create. If [`update_membership`](https://github.com/kontena/kontena/blob/v1.3.1/agent/lib/kontena/launchers/etcd.rb#L171-L178) determines that a node with the same `10.81.0.x` overlay IP already exists in the cluster, it it assumed to be a prior initial node that was removed (`kontena node rm`) after failing, and being replaced by this node. The etcd cluster will be reconfigured to remove that node, re-add the same node, and then create a new `kontena-etcd` container to join the `existing` cluster.

```
I, [2017-06-21T08:24:28.711601 #1] INFO -- Kontena::Agent: initializing agent (version 1.3.1)
I, [2017-06-21T08:24:28.732384 #1] INFO -- Kontena::Launchers::Etcd: initialized
I, [2017-06-21T08:24:32.451755 #1] INFO -- Kontena::Launchers::Etcd: checking if etcd previous membership needs to be updated
I, [2017-06-21T08:24:32.452526 #1] INFO -- Kontena::Launchers::Etcd: connecting to existing etcd at http://10.81.0.5:2379/v2/members
I, [2017-06-21T08:24:32.610367 #1] INFO -- Kontena::Launchers::Etcd: Removing existing etcd membership info with id e443fb807a098cc3
I, [2017-06-21T08:24:33.791392 #1] INFO -- Kontena::Launchers::Etcd: Adding new etcd membership info with peer URL http://10.81.0.3:2380
I, [2017-06-21T08:24:34.984753 #1] INFO -- Kontena::Launchers::Etcd: starting etcd service as a cluster member with initial state: existing
I, [2017-06-21T08:24:34.985953 #1] INFO -- Kontena::Launchers::Etcd: cluster members: node-1=http://10.81.0.1:2380,node-2=http://10.81.0.2:2380,node-3=http://10.81.0.3:2380,node-4=http://10.81.0.4:2380,node-5=http://10.81.0.5:2380
I, [2017-06-21T08:24:35.223833 #1] INFO -- Kontena::Launchers::Etcd: started etcd service
```

However, it turns out that this reconfiguration logic can get run by the agent even though the `kontena-etcd` container exists and is actually still running (on `node-3`):

```
[node-1 kontena-etcd] 2017-06-21 08:23:02.986861 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-2 kontena-etcd] 2017-06-21 08:23:07.820372 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-4 kontena-etcd] 2017-06-21 08:23:13.326850 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-1 kontena-etcd] 2017-06-21 08:23:32.987051 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-2 kontena-etcd] 2017-06-21 08:23:37.820556 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-4 kontena-etcd] 2017-06-21 08:23:43.327230 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-1 kontena-etcd] 2017-06-21 08:24:02.987264 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-2 kontena-etcd] 2017-06-21 08:24:07.820735 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-4 kontena-etcd] 2017-06-21 08:24:13.327491 W | rafthttp: the connection to peer e443fb807a098cc3 is unhealthy
[node-2 kontena-etcd] 2017-06-21 08:24:32.782277 N | etcdserver: removed member e443fb807a098cc3 from cluster 1408077d393bb9fc
[node-1 kontena-etcd] 2017-06-21 08:24:32.795588 N | etcdserver: removed member e443fb807a098cc3 from cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 08:24:32.638228 N | etcdserver: removed member e443fb807a098cc3 from cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 08:24:33.775229 N | etcdserver: added member a76e19ee4f28d8b7 [http://10.81.0.3:2380] to cluster 1408077d393bb9fc
[node-2 kontena-etcd] 2017-06-21 08:24:33.977924 N | etcdserver: added member a76e19ee4f28d8b7 [http://10.81.0.3:2380] to cluster 1408077d393bb9fc
[node-1 kontena-etcd] 2017-06-21 08:24:33.992300 N | etcdserver: added member a76e19ee4f28d8b7 [http://10.81.0.3:2380] to cluster 1408077d393bb9fc
[node-2 kontena-etcd] 2017-06-21 08:24:35.513985 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-1 kontena-etcd] 2017-06-21 08:24:35.520792 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-1 kontena-etcd] 2017-06-21 08:24:35.522007 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-2 kontena-etcd] 2017-06-21 08:24:35.531744 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-4 kontena-etcd] 2017-06-21 08:24:35.383757 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-4 kontena-etcd] 2017-06-21 08:24:35.385837 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-3 kontena-etcd] 2017-06-21 08:24:35.482792 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.483133 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.484663 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.484933 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.486100 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.486345 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.487126 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.487342 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:35.527964 E | etcdserver: the member has been permanently removed from the cluster
[node-3 kontena-etcd] 2017-06-21 08:24:35.528247 I | etcdserver: the data-dir used by this member must be removed.
```

The most likely explanation for this happening is that the `Docker::Container.get('kontena-etcd')` fails with some sporadic Docker API error. The agent etcd launcher code uses [`rescue nil`](https://github.com/kontena/kontena/blob/v1.3.1/agent/lib/kontena/launchers/etcd.rb#L93) to recover from the expected `Docker::Error::NotFound` case, but this style of error handling means that any other unrelated errors will also cause the agent to assume that the local etcd node is gone, and perform these undesired cluster reconfigurations.

---

The result of this kind of spurious etcd reconfiguration can vary, it seems to be possible for the `etcd` service to recover from being removed and re-added to the cluster at runtime, or as in this case, it may not:

```
[node-3 kontena-etcd] 2017-06-21 08:24:35.530738 W | rafthttp: failed to process raft message (raft: stopped)
[node-1 kontena-etcd] 2017-06-21 08:24:36.148458 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-1 kontena-etcd] 2017-06-21 08:24:36.153343 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-4 kontena-etcd] 2017-06-21 08:24:36.899025 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-4 kontena-etcd] 2017-06-21 08:24:36.900765 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-3 kontena-etcd] 2017-06-21 08:24:36.150007 E | etcdserver: the member has been permanently removed from the cluster
[node-3 kontena-etcd] 2017-06-21 08:24:36.150051 I | etcdserver: the data-dir used by this member must be removed.
[node-3 kontena-etcd] 2017-06-21 08:24:36.181222 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.184966 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.186211 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.187507 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.188376 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.189327 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.190433 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.191895 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.193814 E | etcdhttp: got unexpected response error (etcdserver: server stopped)
```

If the `etcd` service crashes and restarts, then it will be unable to recover, as the local etcd member ID differs from the member ID expected by the other members of the cluster:

```
[node-3 kontena-etcd] 2017-06-21 08:24:36.650312 W | flags: unrecognized environment variable ETCD_RELEASE=2.3.7
[node-3 kontena-etcd] 2017-06-21 08:24:36.652827 I | etcdmain: etcd Version: 2.3.7
[node-3 kontena-etcd] 2017-06-21 08:24:36.652868 I | etcdmain: Git SHA: fd17c91
[node-3 kontena-etcd] 2017-06-21 08:24:36.652883 I | etcdmain: Go Version: go1.6.2
[node-3 kontena-etcd] 2017-06-21 08:24:36.652894 I | etcdmain: Go OS/Arch: linux/amd64
[node-3 kontena-etcd] 2017-06-21 08:24:36.652906 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
[node-3 kontena-etcd] 2017-06-21 08:24:36.652965 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[node-3 kontena-etcd] 2017-06-21 08:24:36.653075 I | etcdmain: listening for peers on http://10.81.0.3:2380
[node-3 kontena-etcd] 2017-06-21 08:24:36.653417 I | etcdmain: listening for client requests on http://10.81.0.3:2379
[node-3 kontena-etcd] 2017-06-21 08:24:36.653497 I | etcdmain: listening for client requests on http://127.0.0.1:2379
[node-3 kontena-etcd] 2017-06-21 08:24:36.653575 I | etcdmain: listening for client requests on http://172.17.43.1:2379
[node-3 kontena-etcd] 2017-06-21 08:24:36.671556 I | etcdserver: recovered store from snapshot at index 2770277
[node-3 kontena-etcd] 2017-06-21 08:24:36.672788 I | etcdserver: name = node-3
[node-3 kontena-etcd] 2017-06-21 08:24:36.672827 I | etcdserver: data dir = /var/lib/etcd
[node-3 kontena-etcd] 2017-06-21 08:24:36.672844 I | etcdserver: member dir = /var/lib/etcd/member
[node-3 kontena-etcd] 2017-06-21 08:24:36.672856 I | etcdserver: heartbeat = 100ms
[node-3 kontena-etcd] 2017-06-21 08:24:36.672867 I | etcdserver: election = 1000ms
[node-3 kontena-etcd] 2017-06-21 08:24:36.672877 I | etcdserver: snapshot count = 10000
[node-3 kontena-etcd] 2017-06-21 08:24:36.672908 I | etcdserver: advertise client URLs = http://10.81.0.3:2379
[node-3 kontena-etcd] 2017-06-21 08:24:36.848392 I | etcdserver: restarting member e443fb807a098cc3 in cluster 1408077d393bb9fc at commit index 2772461
[node-3 kontena-etcd] 2017-06-21 08:24:36.851383 I | raft: e443fb807a098cc3 became follower at term 1455
[node-3 kontena-etcd] 2017-06-21 08:24:36.852294 I | raft: newRaft e443fb807a098cc3 [peers: [1196d82c110ae41d,534660f6dff019b4,7ee6bd497759c151,e443fb807a098cc3,f6605e14e1165799], term: 1455, commit: 2772461, applied: 2770277, lastindex: 2772461, lastterm: 1454]
[node-3 kontena-etcd] 2017-06-21 08:24:36.853464 I | etcdserver: added member 1196d82c110ae41d [http://10.81.0.5:2380] to cluster 1408077d393bb9fc from store
[node-3 kontena-etcd] 2017-06-21 08:24:36.855812 I | etcdserver: added member 534660f6dff019b4 [http://10.81.0.1:2380] to cluster 1408077d393bb9fc from store
[node-3 kontena-etcd] 2017-06-21 08:24:36.855855 I | etcdserver: added member 7ee6bd497759c151 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc from store
[node-3 kontena-etcd] 2017-06-21 08:24:36.855874 I | etcdserver: added member e443fb807a098cc3 [http://10.81.0.3:2380] to cluster 1408077d393bb9fc from store
[node-3 kontena-etcd] 2017-06-21 08:24:36.855887 I | etcdserver: added member f6605e14e1165799 [http://10.81.0.2:2380] to cluster 1408077d393bb9fc from store
[node-3 kontena-etcd] 2017-06-21 08:24:36.855931 I | etcdserver: set the cluster version to 2.3 from store
[node-3 kontena-etcd] 2017-06-21 08:24:36.943649 I | etcdserver: starting server... [version: 2.3.7, cluster version: 2.3]
[node-3 kontena-etcd] 2017-06-21 08:24:36.949384 I | raft: raft.node: e443fb807a098cc3 elected leader 1196d82c110ae41d at term 1455
[node-3 kontena-etcd] 2017-06-21 08:24:36.954011 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.954429 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.954799 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.954011 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.954429 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.954799 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.955160 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.983415 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.985532 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.990937 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:36.991807 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-2 kontena-etcd] 2017-06-21 08:24:37.033044 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-1 kontena-etcd] 2017-06-21 08:24:37.043141 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-1 kontena-etcd] 2017-06-21 08:24:37.044765 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-2 kontena-etcd] 2017-06-21 08:24:37.034665 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-4 kontena-etcd] 2017-06-21 08:24:37.984683 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-4 kontena-etcd] 2017-06-21 08:24:37.986581 W | rafthttp: rejected the stream from peer e443fb807a098cc3 since it was removed
[node-3 kontena-etcd] 2017-06-21 08:24:37.056536 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:37.056642 E | rafthttp: streaming request ignored (ID mismatch got a76e19ee4f28d8b7 want e443fb807a098cc3)
[node-3 kontena-etcd] 2017-06-21 08:24:37.061801 E | etcdserver: the member has been permanently removed from the cluster
[node-3 kontena-etcd] 2017-06-21 08:24:37.061815 I | etcdserver: the data-dir used by this member must be removed.
```

---

Similar case where the `etcd` node (`node-4`) was able to recover:

```
[node-5 kontena-etcd] 2017-06-21 05:37:24.183773 W | rafthttp: the connection to peer 502b6b592bf8ddb7 is unhealthy
[node-5 kontena-etcd] 2017-06-21 05:37:24.184025 W | rafthttp: the clock difference against peer 502b6b592bf8ddb7 is too high [2.267893678s > 1s]
[node-3 kontena-etcd] 2017-06-21 05:37:26.195452 W | etcdserver: failed to reach the peerURL(http://10.81.0.4:2380) of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: i/o timeout)
[node-3 kontena-etcd] 2017-06-21 05:37:26.195552 W | etcdserver: cannot get the version of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: i/o timeout)
[node-3 kontena-etcd] 2017-06-21 05:37:31.480803 W | etcdserver: failed to reach the peerURL(http://10.81.0.4:2380) of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: i/o timeout)
[node-3 kontena-etcd] 2017-06-21 05:37:31.480897 W | etcdserver: cannot get the version of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: i/o timeout)
[node-1 kontena-etcd] 2017-06-21 05:37:32.947531 W | rafthttp: the connection to peer 502b6b592bf8ddb7 is unhealthy
[node-3 kontena-etcd] 2017-06-21 05:37:36.316205 W | etcdserver: failed to reach the peerURL(http://10.81.0.4:2380) of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: getsockopt: no route to host)
[node-3 kontena-etcd] 2017-06-21 05:37:36.316299 W | etcdserver: cannot get the version of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: getsockopt: no route to host)
[node-3 kontena-etcd] 2017-06-21 05:37:36.316205 W | etcdserver: failed to reach the peerURL(http://10.81.0.4:2380) of member 502b6b592bf8ddb7 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: getsockopt: no route to host)
[node-3 kontena-etcd] 2017-06-21 05:37:38.690679 N | etcdserver: removed member 502b6b592bf8ddb7 from cluster 1408077d393bb9fc
[node-2 kontena-etcd] 2017-06-21 05:37:38.695056 N | etcdserver: removed member 502b6b592bf8ddb7 from cluster 1408077d393bb9fc
[node-1 kontena-etcd] 2017-06-21 05:37:38.692515 N | etcdserver: removed member 502b6b592bf8ddb7 from cluster 1408077d393bb9fc
[node-5 kontena-etcd] 2017-06-21 05:37:38.837485 N | etcdserver: removed member 502b6b592bf8ddb7 from cluster 1408077d393bb9fc
[node-2 kontena-etcd] 2017-06-21 05:37:38.695056 N | etcdserver: removed member 502b6b592bf8ddb7 from cluster 1408077d393bb9fc
[node-3 kontena-etcd] 2017-06-21 05:37:39.749662 N | etcdserver: added member 7ee6bd497759c151 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc
[node-1 kontena-etcd] 2017-06-21 05:37:39.757837 N | etcdserver: added member 7ee6bd497759c151 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc
[node-2 kontena-etcd] 2017-06-21 05:37:39.759123 N | etcdserver: added member 7ee6bd497759c151 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc
[node-5 kontena-etcd] 2017-06-21 05:37:39.917172 N | etcdserver: added member 7ee6bd497759c151 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc
[node-3 kontena-etcd] 2017-06-21 05:37:40.393799 W | etcdserver: failed to reach the peerURL(http://10.81.0.4:2380) of member 7ee6bd497759c151 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: getsockopt: connection refused)
[node-3 kontena-etcd] 2017-06-21 05:37:40.393889 W | etcdserver: cannot get the version of member 7ee6bd497759c151 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: getsockopt: connection refused)
[node-3 kontena-etcd] 2017-06-21 05:37:40.393799 W | etcdserver: failed to reach the peerURL(http://10.81.0.4:2380) of member 7ee6bd497759c151 (Get http://10.81.0.4:2380/version: dial tcp 10.81.0.4:2380: getsockopt: connection refused)
[node-3 kontena-etcd] 2017-06-21 05:37:42.825944 I | rafthttp: the connection with 7ee6bd497759c151 became active
[node-5 kontena-etcd] 2017-06-21 05:37:42.942833 I | rafthttp: the connection with 7ee6bd497759c151 became active
[node-1 kontena-etcd] 2017-06-21 05:37:42.867415 I | rafthttp: the connection with 7ee6bd497759c151 became active
[node-2 kontena-etcd] 2017-06-21 05:37:42.862787 I | rafthttp: the connection with 7ee6bd497759c151 became active
[node-4 kontena-etcd] 2017-06-21 05:37:42.804420 I | raft: 7ee6bd497759c151 became follower at term 1454
[node-4 kontena-etcd] 2017-06-21 05:37:42.804504 I | raft: raft.node: 7ee6bd497759c151 elected leader e443fb807a098cc3 at term 1454
[node-4 kontena-etcd] 2017-06-21 05:37:42.837080 I | rafthttp: the connection with 1196d82c110ae41d became active
[node-4 kontena-etcd] 2017-06-21 05:37:42.838458 I | rafthttp: the connection with e443fb807a098cc3 became active
[node-4 kontena-etcd] 2017-06-21 05:37:42.840224 I | rafthttp: the connection with 534660f6dff019b4 became active
[node-4 kontena-etcd] 2017-06-21 05:37:42.841216 I | rafthttp: the connection with f6605e14e1165799 became active
[node-4 kontena-etcd] 2017-06-21 05:37:43.210318 I | raft: 7ee6bd497759c151 [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 2750275, term: 1454]
[node-4 kontena-etcd] 2017-06-21 05:37:43.210445 I | raft: log [committed=0, applied=0, unstable.offset=1, len(unstable.Entries)=0] starts to restore snapshot [index: 2750275, term: 1454]
[node-4 kontena-etcd] 2017-06-21 05:37:43.210584 I | raft: 7ee6bd497759c151 restored progress of 1196d82c110ae41d [next = 2750276, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
[node-4 kontena-etcd] 2017-06-21 05:37:43.210653 I | raft: 7ee6bd497759c151 restored progress of 502b6b592bf8ddb7 [next = 2750276, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
[node-4 kontena-etcd] 2017-06-21 05:37:43.210832 I | raft: 7ee6bd497759c151 restored progress of 534660f6dff019b4 [next = 2750276, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
[node-4 kontena-etcd] 2017-06-21 05:37:43.210905 I | raft: 7ee6bd497759c151 restored progress of e443fb807a098cc3 [next = 2750276, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
[node-4 kontena-etcd] 2017-06-21 05:37:43.210956 I | raft: 7ee6bd497759c151 restored progress of f6605e14e1165799 [next = 2750276, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
[node-4 kontena-etcd] 2017-06-21 05:37:43.211036 I | raft: 7ee6bd497759c151 [commit: 2750275] restored snapshot [index: 2750275, term: 1454]
[node-4 kontena-etcd] 2017-06-21 05:37:43.219890 I | etcdserver: added member 534660f6dff019b4 [http://10.81.0.1:2380] to cluster 1408077d393bb9fc from store
[node-4 kontena-etcd] 2017-06-21 05:37:43.220038 I | etcdserver: added member e443fb807a098cc3 [http://10.81.0.3:2380] to cluster 1408077d393bb9fc from store
[node-4 kontena-etcd] 2017-06-21 05:37:43.220192 I | etcdserver: added member f6605e14e1165799 [http://10.81.0.2:2380] to cluster 1408077d393bb9fc from store
[node-4 kontena-etcd] 2017-06-21 05:37:43.220276 I | etcdserver: added member 1196d82c110ae41d [http://10.81.0.5:2380] to cluster 1408077d393bb9fc from store
[node-4 kontena-etcd] 2017-06-21 05:37:43.220354 I | etcdserver: added member 502b6b592bf8ddb7 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc from store
[node-4 kontena-etcd] 2017-06-21 05:37:43.220424 I | etcdserver: set the cluster version to 2.3 from store
[node-4 kontena-etcd] 2017-06-21 05:37:43.222115 E | rafthttp: failed to read 534660f6dff019b4 on stream MsgApp v2 (net/http: request canceled)
[node-4 kontena-etcd] 2017-06-21 05:37:43.222260 I | rafthttp: the connection with 534660f6dff019b4 became inactive
[node-4 kontena-etcd] 2017-06-21 05:37:43.232555 E | rafthttp: failed to read e443fb807a098cc3 on stream MsgApp v2 (net/http: request canceled)
[node-4 kontena-etcd] 2017-06-21 05:37:43.232698 I | rafthttp: the connection with e443fb807a098cc3 became inactive
[node-4 kontena-etcd] 2017-06-21 05:37:43.235798 E | rafthttp: failed to read f6605e14e1165799 on stream MsgApp v2 (net/http: request canceled)
[node-4 kontena-etcd] 2017-06-21 05:37:43.235953 I | rafthttp: the connection with f6605e14e1165799 became inactive
[node-4 kontena-etcd] 2017-06-21 05:37:43.262827 I | etcdserver: recovered from incoming snapshot at index 2750275
[node-4 kontena-etcd] 2017-06-21 05:37:43.268432 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.269548 I | rafthttp: the connection with 1196d82c110ae41d became active
[node-4 kontena-etcd] 2017-06-21 05:37:43.275611 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.335407 I | rafthttp: the connection with f6605e14e1165799 became active
[node-4 kontena-etcd] 2017-06-21 05:37:43.363585 I | etcdserver: raft applied incoming snapshot at index 2750275
[node-4 kontena-etcd] 2017-06-21 05:37:43.366712 I | rafthttp: the connection with 534660f6dff019b4 became active
[node-4 kontena-etcd] 2017-06-21 05:37:43.428870 I | rafthttp: the connection with e443fb807a098cc3 became active
[node-4 kontena-etcd] 2017-06-21 05:37:43.440893 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.441213 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.544039 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.545461 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.647516 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.648083 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.749742 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.751104 E | rafthttp: failed to find member 7ee6bd497759c151 in cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.935729 N | etcdserver: removed member 502b6b592bf8ddb7 from cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.936826 N | etcdserver: added local member 7ee6bd497759c151 [http://10.81.0.4:2380] to cluster 1408077d393bb9fc
[node-4 kontena-etcd] 2017-06-21 05:37:43.939093 I | etcdserver: published {Name:node-4 ClientURLs:[http://10.81.0.4:2379]} to cluster 1408077d393bb9fc
[node-3 kontena-etcd] 2017-06-21 06:13:38.599071 I | etcdserver: start to snapshot (applied: 2760276, lastsnap: 2750275)
[node-2 kontena-etcd] 2017-06-21 06:13:38.603561 I | etcdserver: start to snapshot (applied: 2760276, lastsnap: 2750275)
```

### PR DESCRIPTION
**Pull request by jnummelin**
If Docker gave unexpected error while getting etcd container info, agent decided to reconfigure etcd membership. 

image

This PR changes to use `start!` instead of plain `start` when starting etcd container to allow possible start errors to fall through and get at least logged.

fixes #2508

### CODE REVIEW

File: agent/lib/kontena/launchers/etcd.rb [hunk 1]
```diff
@@ -90,7 +90,12 @@ def create_container(image, node)
       cluster_state = 'new'
       weave_ip = node.overlay_ip
 
-      container = Docker::Container.get('kontena-etcd') rescue nil
+      container = nil
```
Comment (SpComb) [inline agent/lib/kontena/launchers/etcd.rb]: This would look nicer as `container = self.get_container()`

File: agent/lib/kontena/launchers/etcd.rb [hunk 2]
```diff
@@ -100,7 +105,7 @@ def create_container(image, node)
         return container
       elsif container && !container.running?
         info 'etcd container exists but not running, starting it'
-        container.start
+        container.start!
```
Comment (SpComb) [inline agent/lib/kontena/launchers/etcd.rb]: Also update the YARDoc?

```
@raises [Docker::Error] <what can fail>
```
