### PR TITLE
Fix CLI stack validate to output either interpolated stack YAML or API JSON

### LINKED ISSUE #2887: CLI stack validate outputs stack create API request instead of interpolated stack YAML
Looks like the spec is trying to match the wrong syntax for `links: ...`, it expects a list of plain of link names, not the `name/alias` objects:

```
stack validate
  service_link
 [done] Creating stack simple      
> Select link simple/redis
---
# /kontena/test/spec/fixtures/stack/service_link/kontena.yml
stack: test/test
version: 0.1.0
name: test
registry: file://
expose: 
services:
- instances: 
  image: nginx:1-alpine
  env: 
  links:
  - name: simple/redis
    alias: simple/redis
  external_links: []
  ports: []
  volumes: []
  volumes_from: []
  affinity: []
  stateful: false
  deploy_opts:
    wait_for_port: 
    min_health: 
    interval: 
  hooks: {}
  health_check:
    port: 
    protocol: 
    uri: 
    timeout: 
    interval: 
    initial_delay: 
  read_only: false
  log_driver: 
  log_opts: 
  name: nginx
volumes: []
dependencies: 
variables:
  lb: simple/redis
parent_name: 
 [done] Removing stack simple      
    allows to select matching service (FAILED - 1)

Failures:

  1) stack validate service_link allows to select matching service
     Failure/Error: expect(k.out.match(/links\:\r\n\s+- simple\/redis/)).to be_truthy
     
       expected: truthy value
            got: nil
     # ./spec/features/stack/validate_spec.rb:18:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/validate_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 3.69 seconds (files took 0.1726 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/stack/validate_spec.rb:7 # stack validate service_link allows to select matching service
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2887

Have `kontena stack validate` output the interpolated YAML by default. There's a new `--format=api-json` flag to output the API JSON instead.

### CODE REVIEW

File: cli/spec/kontena/cli/stacks/validate_command_spec.rb [hunk 1]
```diff
@@ -5,26 +5,71 @@
...
-    it 'validates a yaml file' do
-      expect{Kontena.run!('stack', 'validate', fixture_path('kontena_v3.yml'))}.not_to exit_with_error
-      expect{Kontena.run!('stack', 'validate', fixture_path('kontena_v3.yml'))}.to output(/stack:.*version:.*services:.*variables:/m).to_stdout
+    it 'outputs interpolated YAML' do
+      expect{Kontena.run!('stack', 'validate', fixture_path('stack-with-liquid.yml'))}.to output_yaml(
+        'stack' => 'user/stackname',
+        'version' => '0.1.1',
+        'variables' => {
+          'grid_name' => hash_including(
+              'value' => 'validate stackname',
```
Comment (SpComb) [inline cli/spec/kontena/cli/stacks/validate_command_spec.rb]: Very odd, because the `{{ GRID }}` -> `validate` shows up correctly here. But not in the actual variables, or the interpolated envs

**Comment by SpComb** [comment]
I don't know why the `reader.fully_interpolated_yaml` now suddenly also includes all the empty service fields. ATM it looks like this:

```yaml
---
# /home/kontena/kontena/kontena/cli/spec/fixtures/stack-with-liquid.yml
stack: user/stackname
version: 0.1.1
variables:
  grid_name:
    type: string
    required: true
    min_length: 10
    empty_is_nil: true
    value: validate stackname
  copies:
    type: integer
    value: 5
services:
  service-1:
    instances: 
    image: foo:1
    env:
    - TEST_VAR="{{ GRID }} stackname"
    links: []
    external_links: []
    ports: []
    volumes: []
    volumes_from: []
    affinity: []
    stateful: false
    deploy_opts:
      wait_for_port: 
      min_health: 
      interval: 
    hooks: {}
    health_check:
      port: 
      protocol: 
      uri: 
      timeout: 
      interval: 
      initial_delay: 
    read_only: false
    log_driver: 
    log_opts: 
    name: service-1
  service-2:
    instances: 
    image: foo:2
    env:
    - TEST_VAR="{{ GRID }} stackname"
    links: []
    external_links: []
    ports: []
    volumes: []
    volumes_from: []
    affinity: []
    stateful: false
    deploy_opts:
      wait_for_port: 
      min_health: 
      interval: 
    hooks: {}
    health_check:
      port: 
      protocol: 
      uri: 
      timeout: 
      interval: 
      initial_delay: 
    read_only: false
    log_driver: 
    log_opts: 
    name: service-2
```

**Comment by SpComb** [comment]
> I don't know why the reader.fully_interpolated_yaml now suddenly also includes all the empty service fields. ATM it looks like this:

Looks like this is because the `self.stack` => `StackReader#execute` => `StackReader#parse_services` actually modifies the `@services ||= fully_interpolated_yaml.fetch('services', {})` hash in-place...

File: cli/lib/kontena/cli/stacks/yaml/reader.rb [hunk 2]
```diff
@@ -274,6 +274,7 @@ def parse_volumes
       # @return [Hash]
       def parse_services(service_name = nil)
         if service_name.nil?
+          services = self.services.dup # do not modify the fully_interpolated_yaml['services'] hash in-place
           services.each do |name, config|
             services[name] = process_config(config, name)
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/yaml/reader.rb]: I really hope nothing depends on the side-effects of this here...

File: cli/lib/kontena/cli/stacks/validate_command.rb [hunk 3]
```diff
@@ -19,6 +19,7 @@ class ValidateCommand < Kontena::Command
     option '--dependency-tree', :flag, "Show dependency tree"
     option '--[no-]dependencies', :flag, "Validate dependencies", default: true
     option '--parent-name', '[PARENT_NAME]', "Set parent name", hidden: true
+    option '--output-json', :flag, "Output API JSON"
```
Comment (kke) [inline cli/lib/kontena/cli/stacks/validate_command.rb]: Maybe just `--json` or for consistency: `--format json` as in `kontena master config dump`:

```
    -f, --format [FORMAT]         Specify output format (json, yaml) (default: guess from PATH or json)
```

Comment (SpComb) [reply cli/lib/kontena/cli/stacks/validate_command.rb]: It's not just the syntax, but the actual structure and semantics of the output changes (stack YAML vs API JSON).

Maybe this should be something like `--api-json` then?

Comment (jakolehm) [reply cli/lib/kontena/cli/stacks/validate_command.rb]: How about `--format api-json` ?

Comment (SpComb) [reply cli/lib/kontena/cli/stacks/validate_command.rb]: Changed from `--output-json` to `--format=yaml|api-json`
