### PR TITLE
Fix stack yaml service instance resolver

### LINKED ISSUE #3145: Service instances resolver throws error
```
NoMethodError : Resolver 'service_instances' for 'seed_instances' : undefined method `fetch_stack' for #<Kontena::Cli::Stacks::ShowCommand:0x007fab1f342cf0>
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #3145

Makes service instances resolver work again instead of getting a NoMethodError:

```
NoMethodError : Resolver 'service_instances' for 'seed_instances' : undefined method `fetch_stack' for #<Kontena::Cli::Stacks::ShowCommand:0x007fab1f342cf0>
```

### CODE REVIEW

File: cli/lib/kontena/cli/stacks/yaml/opto/service_instances_resolver.rb [hunk 1]
```diff
@@ -6,8 +6,8 @@ class Opto::Resolvers::ServiceInstances < ::Opto::Resolver
       def resolve
         return nil unless current_master && current_grid
         require 'kontena/cli/stacks/show_command'
-        read_command = Kontena::Cli::Stacks::ShowCommand.new([self.stack])
-        stack = read_command.fetch_stack(self.stack)
+        read_command = Kontena::Cli::Stacks::ShowCommand.new([]).instance([self.stack])
+        stack = read_command.stack
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/yaml/opto/service_instances_resolver.rb]: Hmm... this method is just `client.get("stacks/#{current_grid}/#{name}")`.

Other resolvers like the `Certificates` resolver just `include Kontena::Cli::Common` and then call `client.get("grids/#{current_grid}/certificates")['certificates']` directly. Couldn't this do the same?

File: test/spec/features/stack/install_spec.rb [hunk 2]
```diff
@@ -143,4 +143,20 @@
       expect(k.out.split(/[\r\n]/)).to match array_including('twemproxy', 'twemproxy-redis_from_registry', 'twemproxy-redis_from_yml')
     end
   end
+
+  context 'For a stack using service_instances resolver' do
+    it 'interpolates the correct instance count' do
+      with_fixture_dir("stack/service_instances_resolver") do
+        k = run 'kontena stack install'
+        expect(k.code).to eq (0)
```
Comment (SpComb) [inline test/spec/features/stack/install_spec.rb]: This can just be `run! '...'` now

**Comment by kke** [comment]
Simplified still.
