### PR TITLE
Agent: Fix WeaveWorker wait on destroy event

### LINKED ISSUE #1369: Agent Weave#detach_network NoMethodError: undefined method `release_address' for nil:NilClass
The Agent `WeaveWorker` does not wait on the weave/IPAM to be ready before handling the Docker destroy event. The destroy event for a container may happen before the kontena-etcd and kontena-ipam are ready. 

```
kontena-agent | D, [2016-11-22T09:18:23.604518 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /kontena-cadvisor
kontena-agent | D, [2016-11-22T09:18:40.867260 #1] DEBUG -- RpcServer: rpc request: Kontena::Rpc::ServicePodsApi#terminate ["58340cbede3578244b000070", 1, {"lb"=>true}]
kontena-agent | I, [2016-11-22T09:18:40.876443 #1]  INFO -- Kontena::ServicePods::Terminator: terminating service: /default-redis-1
kontena-agent | D, [2016-11-22T09:18:41.042386 #1] DEBUG -- NetworkAdapters::Weave: releasing weave network address for container 1d95c64e50aca8116bf5e7b9a898bc5e329bb18f4918e620f6ab594743cb5823
kontena-agent | E, [2016-11-22T09:18:41.045502 #1] ERROR -- : Actor crashed!
kontena-agent | NoMethodError: undefined method `release_address' for nil:NilClass
kontena-agent | 	/app/lib/kontena/network_adapters/weave.rb:325:in `detach_network'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
kontena-agent | E, [2016-11-22T09:18:41.045645 #1] ERROR -- : Actor crashed!
kontena-agent | NoMethodError: undefined method `release_address' for nil:NilClass
kontena-agent | 	/app/lib/kontena/network_adapters/weave.rb:325:in `detach_network'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
kontena-agent | 	(celluloid):0:in `remote procedure call'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
kontena-agent | 	/app/lib/kontena/workers/weave_worker.rb:51:in `on_container_event'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1369

* Always initialize the `Weave@ipam_client`
* Cleanup the `WeaveWorker` wait logic to wait closer to the actual operation

    Hopefully make it more obvious when the wait is needed and when it isn't. Consider moving the wait right into the `Weave` actor itself?

* Also trap errors in `on_destroy_destroy`

```
kontena-agent | D, [2016-11-22T15:55:39.853177 #1] DEBUG -- RpcServer: rpc request: Kontena::Rpc::ServicePodsApi#terminate ["583446fede3578427000002a", 1, {"lb"=>true}]
kontena-agent | I, [2016-11-22T15:55:39.867025 #1]  INFO -- Kontena::ServicePods::Terminator: terminating service: /null-redis-1
kontena-agent | D, [2016-11-22T15:55:40.090674 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:40.598484 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:41.122169 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:41.632621 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:42.145753 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:42.681548 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:43.197776 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:43.729727 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:44.263652 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:44.803471 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:45.344866 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:45.855873 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:46.390916 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:46.905207 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:47.437354 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:47.972975 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:48.499063 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:49.035475 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:49.568937 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:50.101425 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:50.633696 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:51.169857 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:51.698412 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:52.156886 #1] DEBUG -- Workers::LogWorker: /kontena-ipam-plugin/{}
kontena-agent | D, [2016-11-22T15:55:52.157401 #1] DEBUG -- Workers::WeaveWorker: skip start for container=/kontena-ipam-plugin without overlay_cidr
kontena-agent | D, [2016-11-22T15:55:52.209964 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:52.735588 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:53.269115 #1] DEBUG -- Workers::WeaveWorker: waiting for all network components running
kontena-agent | D, [2016-11-22T15:55:53.396375 #1] DEBUG -- NetworkAdapters::IpamCleaner: ipam signalled ready, starting cleanup loop
kontena-agent | I, [2016-11-22T15:55:53.396646 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network existence
kontena-agent | D, [2016-11-22T15:55:53.399834 #1] DEBUG -- NetworkAdapters::IpamClient: reserving pool kontena with subnet 10.81.0.0/16 and iprange 10.81.128.0/17
kontena-agent | I, [2016-11-22T15:55:53.803584 #1]  INFO -- Kontena::NetworkAdapters::Weave: Remove container=6a496cd20a8a4c6ad365ca059958d322d168ade80b300b45b51a3f79fd2f7e65 from network=kontena at cidr=10.81.128.5/16
kontena-agent | D, [2016-11-22T15:55:53.803584 #1] DEBUG -- NetworkAdapters::IpamClient: releasing address 10.81.128.5/16 for network kontena
kontena-agent | D, [2016-11-22T15:55:53.826794 #1] DEBUG -- NetworkAdapters::IpamClient: response: 200/{}
```

### CODE REVIEW

File: agent/lib/kontena/workers/weave_worker.rb [hunk 1]
```diff
@@ -37,39 +37,61 @@ def on_dns_add(topic, event)
     # @param [Docker::Event] event
     def on_container_event(topic, event)
       if event.status == 'start'
-        wait_weave_running?
         container = Docker::Container.get(event.id) rescue nil
         if container
-          self.weave_attach(container)
+          self.start_container(container)
```
Comment (jakolehm) [inline agent/lib/kontena/workers/weave_worker.rb]: Maybe name could be `on_container_start` (to match destroy)

**Comment by jakolehm** [comment]
Rebased.
