### PR TITLE
Fix stack validate command and validity checking when installing

### LINKED ISSUE #2806: e2e specs: stack install from file returns error if file is invalid
Not sure what's happening here... the invalid stack is supposed to fail validation, but it's actually getting POST'd to the server?

```
stack install
  from file
 [fail] Creating stack simple      
 [error] 422 : Unprocessable Entity:
	services: Services isn't an array
	volumes: Volumes isn't an array
 [error] 404 : Not Found (/v1/stacks/e2e/simple)
    returns error if file is invalid (FAILED - 1)

Failures:

  1) stack install from file returns error if file is invalid
     Failure/Error: expect(k.out.match(/validation failed/i)).to be_truthy
     
       expected: truthy value
            got: nil
     # ./spec/features/stack/install_spec.rb:42:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/install_spec.rb:39:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #2806

(from #2707)

Before: 
- Invalid stacks were installed
- Invalid stacks passed `kontena stack validate`

After:
- Invalid stack installation halts before POSTing to master
- Invalid stack fails `kontena stack validate`

### CODE REVIEW

**Comment by SpComb** [comment]
Also fixes #2807?

**Comment by SpComb** [comment]
The #2807 case [raises `RuntimeError`](https://github.com/kontena/kontena/blob/f188ee54f30e7f5acced1dec29da8ad511fccc23/cli/lib/kontena/cli/stacks/yaml/reader.rb#L200), which results in an uglier error message, compared to the much nicer `abort_on_validation_errors` formatting:

```
/kontena/test # kontena stack validate spec/fixtures/stack/service_link/kontena.yml 
 [error] RuntimeError : Variable validation failed: {"lb"=>{:presence=>"Required value missing"}} in /kontena/test/spec/fixtures/stack/service_link/kontena.yml
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

Not sure how that case used to behave?

**Comment by SpComb** [comment]
The #2806 case is fixed nicely:

```
$ kontena stack install spec/fixtures/stack/simple/invalid.yml 
 YAML validation failed! Aborting.

- "/kontena/test/spec/fixtures/stack/simple/invalid.yml":
  - services:
      redis:
        omg: key not expected
  - services:
      redis:
        image: image is missing
```

**Comment by kke** [comment]
Extends is completely broken now if the image comes from the extended file.

File: cli/spec/kontena/cli/stacks/yaml/reader_spec.rb [hunk 1]
```diff
@@ -312,7 +310,12 @@
 
     it 'expands build option to absolute path' do
       outcome = subject.execute
-      expect(outcome['services']['webapp']['build']['context']).to eq(fixture_path(''))
```
Comment (kke) [inline cli/spec/kontena/cli/stacks/yaml/reader_spec.rb]: It's a bit of a mystery how this test ever passed after the #2707 (which turned services into an array)
