### PR TITLE
Fix agent ServicePodWorker to ignore old container events

### LINKED ISSUE #2766: Agent ServicePodWorker re-applies after any apply that triggers container events
Any Docker container actions done in `ServicePodWorker#apply` will also result `container:event` notifications. Because the `apply` function runs as an `Celluloid.exclusive { ... }` block, those notifications get queued up during the deploy, and get run once the `apply` returns:

```
D, [2017-09-05T12:50:35.514173 #1] DEBUG -- Kontena::RpcClient: waited 0.2s of 30.0s until: request /node_service_pods/list has response wth id=1165729746 yielded Array
D, [2017-09-05T12:50:35.515733 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of log-test-1: running
I, [2017-09-05T12:50:35.518770 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating log-test-1
...
I, [2017-09-05T12:50:37.949590 #1]  INFO -- Kontena::ServicePods::Creator: service started: log-test-1
D, [2017-09-05T12:50:38.085292 #1] DEBUG -- Kontena::Workers::ServicePodWorker: on_container_event create
D, [2017-09-05T12:50:38.088439 #1] DEBUG -- Kontena::Workers::ServicePodWorker: on_container_event start
```

With the way that the `@container_state_changed` works, that means that each `update` -> `apply if needs_apply?` essentially runs twice: once because the `@service_pod` changes, and then a second time because of the `@container_state_changed = true` triggerd by the `apply` itself:

```
D, [2017-09-05T12:50:48.685974 #1] DEBUG -- Kontena::RpcClient: waited 0.0s of 30.0s until: request /node_service_pods/list has response wth id=1628267283 yielded Array
D, [2017-09-05T12:50:48.948312 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of log-test-1: running
D, [2017-09-05T12:50:49.086853 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state is in-sync: running
```

The second `apply` is a no-op because the container is up to date: https://github.com/kontena/kontena/pull/2143#discussion_r111080598

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2766

Store the `@container` state in `#apply`, allowing the `ServicePodWorker#on_container_event` handler to accurately identify any events from the managed container, and ignore any queued up events from any previous container.

```
D, [2017-09-06T11:08:16.093978 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of redis-1: running
I, [2017-09-06T11:08:16.121786 #1]  INFO -- Kontena::Workers::ServicePodWorker: service updated at 2017-09-06T11:08:15+00:00 after service container created at 2017-09-06T10:09:59+00:00
I, [2017-09-06T11:08:16.122948 #1]  INFO -- Kontena::Workers::ServicePodWorker: re-creating redis-1

I, [2017-09-06T11:08:16.123115 #1]  INFO -- Kontena::ServicePods::Creator: creating service: redis-1
I, [2017-09-06T11:08:18.881112 #1]  INFO -- Kontena::ServicePods::Creator: removing previous version of service: redis-1
I, [2017-09-06T11:08:19.644048 #1]  INFO -- Kontena::ServicePods::Creator: service started: redis-1

D, [2017-09-06T11:08:19.756281 #1] DEBUG -- Kontena::Workers::ServicePodWorker: sync state update: {:service_id=>"599bee9bd431ec00137163c7", :instance_number=>1, :rev=>"2017-09-06 11:08:15 UTC", :state=>"running", :error=>nil}
D, [2017-09-06T11:08:19.757256 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: create
D, [2017-09-06T11:08:19.766258 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: start
```

No more `die` or `stop` events to trigger the restart logic from the old service container that got removed. The `create` and `start` events still cause a second/unnecessary call to `apply` on the next pod manager update loop, but that's okay.

### CODE REVIEW

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 1]
```diff
@@ -166,8 +165,13 @@ def ensure_desired_state
       else
         warn "unknown state #{service_pod.desired_state} for #{service_pod.name}"
       end
+
+      service_container = get_container(service_pod.service_id, service_pod.instance_number)
+      service_container.name if service_container # trigger cached_json
+      service_container
     end
 
+    # @return [Docker::Container]
```
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Not using the `Docker::Container` that gets returned by the `Kontena::ServicePods::Creator`, because the way that the `cached_json` vs `state` stuff works is too confusing. The `container.info` is from what `Docker::Container.create` returns, which would be from before the call to `start!`. What the various container methods return then depends on if something triggers `cached_json` before or after the call to `start!` - don't want to deal with that, just inspect the container again.

Doesn't really matter for `service_container.running?` though, because that re-queries the Docker API (twice) for each call.
