### PR TITLE
Fix random strategy, rescheduling of instances on removed nodes

### LINKED ISSUE #2244: Random strategy moves services constantly
Regression in 1.2.x

### LINKED ISSUE #2254: Random strategy fails to schedule stateful service with existing instances
Broken in Kontena 1.2 per #2141. The server `Scheduler::Strategy::Random#find_node` returns a `HostNode` model instead of a `Scheduler::Node` when searching for an existing instance of a stateful service.

```
I, [2017-05-03T16:41:34.032786 #11782]  INFO -- GridServiceDeployer: starting to deploy development/null/redis-random-stateful
E, [2017-05-03T16:41:34.051821 #11782] ERROR -- GridServiceDeployer: Unknown error (development/null/redis-random-stateful): NoMethodError undefined method `schedule_counter' for nil:NilClass
E, [2017-05-03T16:41:34.051911 #11782] ERROR -- GridServiceDeployer: /home/kontena/kontena/kontena/server/app/services/grid_service_scheduler.rb:57:in `select_node'
/home/kontena/kontena/kontena/server/app/services/grid_service_deployer.rb:133:in `block in instance_count'
/home/kontena/kontena/kontena/server/app/services/grid_service_deployer.rb:131:in `times'
/home/kontena/kontena/kontena/server/app/services/grid_service_deployer.rb:131:in `instance_count'
/home/kontena/kontena/kontena/server/app/services/grid_service_deployer.rb:52:in `deploy'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:52:in `deploy'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:42:in `perform'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:24:in `block in check_deploy_queue'
/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:24:in `with_lock'
/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:6:in `with_dlock'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:21:in `check_deploy_queue'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:12:in `block in watch'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `loop'
/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `watch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### LINKED ISSUE #2274: Kontena 1.2 fails to re-schedule stateful ha service instance on removed node
With a `--stateful` service using the default `--deploy-strategy ha`, with an instance deployed to a host node:

```
$ kontena service create --deploy-strategy ha --stateful redis-ha-stateful redis
 [done] Creating redis-ha-stateful service      
$ kontena service deploy redis-ha-stateful
 [done] Deploying service redis-ha-stateful      
⊛ Deployed instance development/null/redis-ha-stateful-1 to node core-02
```

After disconnecting and removing that host node, the service fails to deploy:

```
$ kontena service deploy redis-ha-stateful
 [fail] Deploying service redis-ha-stateful      
 [error] Kontena::Errors::StandardErrorArray : Cannot find applicable node for service instance development/null/redis-ha-stateful-1: Strategy Scheduler::Strategy::HighAvailability did not find any node:
```

Expected behaviour re Kontena 1.1 would be for the stateful service instance to get rescheduled to a different host node. After the host node is removed, Kontena 1.1 [would also destroy the containers](https://github.com/kontena/kontena/blob/v1.1.5/server/app/models/host_node.rb#L45-L47) for that host node, including the stateful volume containers used by the schduler.

In Kontena 1.2, destroying the `HostNode` only [marks the `GridServiceInstance.host_node` as `nil`](https://github.com/kontena/kontena/blob/v1.2/server/app/models/host_node.rb#L36), which means that the [`Scheduler::Strategy::HighAvailablility#find_stateful_node`](https://github.com/kontena/kontena/blob/v1.2.1/server/app/services/scheduler/strategy/high_availability.rb#L47) will still pick up that `GridServiceInstance`,  and find a `nil` host node:

```ruby
        prev_instance = grid_service.grid_service_instances.find_by(
          instance_number: instance_number
        )
        if prev_instance
          nodes.find{ |n| n.node == prev_instance.host_node }
        ...
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2244 
Fixes #2254 
Fixes #2274

More minimal fix compared to #2245

### CODE REVIEW

File: server/app/services/scheduler/strategy/random.rb [hunk 1]
```diff
@@ -13,22 +13,32 @@ def host_grace_period
...
+      # @param [GridService] grid_service
+      # @param [Integer] instance_number
+      # @param [Array<Scheduler::Node>] nodes
+      # @return [Scheduler::Node, NilClass]
+      def find_previous_or_new_node(grid_service, instance_number, nodes)
+        prev_instance = grid_service.grid_service_instances.find_by(
+          grid_service: grid_service, instance_number: instance_number
+        )
+        if prev_instance
+          nodes.find{ |n| n.node == prev_instance.host_node }
```
Comment (SpComb) [inline server/app/services/scheduler/strategy/random.rb]: How does this behave for instances on removed nodes, which have `prev_instance.host_node => nil`?

File: server/spec/services/scheduler/strategy/random_spec.rb [hunk 2]
```diff
@@ -8,21 +7,60 @@
...
+        expect(nodes.include?(node)).to be_truthy
+      end
+
+      it 'returns previously scheduled node if it exists' do
+        stateful_service.grid_service_instances.create!(instance_number: 2, host_node: nodes[2].node)
+        node = subject.find_node(stateful_service, 2, nodes)
+        expect(node).to eq(nodes[2])
+      end
+
+      it 'returns nil if previously scheduled node is not included in nodes array' do
```
Comment (SpComb) [inline server/spec/services/scheduler/strategy/random_spec.rb]: This is different from how the `ha` strategy behaves, though? If the host node that the stateful instance is deployed to is removed, or filtered away, then it just returns a new node to reschedule the stateful instance onto?

This would fail the deploy with an error in that case?

File: server/app/services/scheduler/strategy/random.rb [hunk 3]
```diff
@@ -13,22 +13,32 @@ def host_grace_period
...
-      ##
       # @param [GridService] grid_service
       # @param [Integer] instance_number
-      # @param [Array<HostNode>] nodes
+      # @param [Array<Scheduler::Node>] nodes
+      # @return [Scheduler::Node, NilClass]
       def find_node(grid_service, instance_number, nodes)
         if grid_service.stateless?
+          node = find_previous_or_new_node(grid_service, instance_number, nodes)
+          return node if node
```
Comment (jakolehm) [inline server/app/services/scheduler/strategy/random.rb]: It's not exactly the same.. for stateful we cannot sample if previous instance exists but node cannot be found from nodes list. Here we can always sample if `find_previous_or_new_node` returns `nil`.

File: server/app/services/scheduler/strategy/random.rb (hunk 1 above)
Comment (jakolehm) [inline server/app/services/scheduler/strategy/random.rb]: Not very well. I think we might have this same problem in other strategies also.

File: server/app/services/scheduler/strategy/random.rb (hunk 3 above)
Comment (jnummelin) [inline server/app/services/scheduler/strategy/random.rb]: Had to read this through few times also to get the difference. :) So basically `find_previous_or_new_node` returns nil in the case where the previous service instance exists but the node is gone and in this case it would do a new sampling. Right?

Comment (SpComb) [inline server/app/services/scheduler/strategy/random.rb]: That means that the stateful case behaves like this:

```
$ kontena service create --deploy-strategy random --stateful redis-random-stateful redis
[done] Creating redis-random-stateful service      
$ kontena service deploy redis-random-stateful
 [done] Deploying service redis-random-stateful      
⊛ Deployed instance development/null/redis-random-stateful-1 to node core-01
$ kontena service update --affinity node==core-02 redis-random-stateful
 [done] Updating redis-random-stateful service      
$ kontena service deploy redis-random-stateful
 [fail] Deploying service redis-random-stateful      
 [error] Kontena::Errors::StandardErrorArray : Cannot find applicable node for service instance development/null/redis-random-stateful-1: Strategy Scheduler::Strategy::Random did not find any node:
```

Is this intended?

Comment (SpComb) [inline server/app/services/scheduler/strategy/random.rb]: Comparing this to existing Kontena 1.1 behavior, it would just ignore the affinity filter in this case, and keep scheduling the stateful service onto the existing node. So I can't quite tell if this is any more or less broken for the slightly crazy case of a stateful random service with changing affinity filters.

File: server/app/services/scheduler/strategy/high_availability.rb [hunk 4]
```diff
@@ -28,19 +27,19 @@ def find_node(grid_service, instance_number, nodes)
...
       end
 
       # @param [GridService] grid_service
       # @param [Integer] instance_number
-      # @param [Array<HostNode>] nodes
-      # @return [HostNode,NilClass]
+      # @param [Array<Scheduler::Node>] nodes
+      # @return [Scheduler::Node,NilClass]
       def find_stateful_node(grid_service, instance_number, nodes)
-        prev_instance = grid_service.grid_service_instances.find_by(
```
Comment (SpComb) [inline server/app/services/scheduler/strategy/high_availability.rb]: Fixes  #2274

File: server/app/services/scheduler/strategy/random.rb (hunk 3 above)
Comment (SpComb) [inline server/app/services/scheduler/strategy/random.rb]: I suppose `kontena service remove --instance` would function as a workaround for this?

File: server/app/services/scheduler/strategy/high_availability.rb [hunk 5]
```diff
@@ -28,19 +27,19 @@ def find_node(grid_service, instance_number, nodes)
...
+        prev_instance = grid_service.grid_service_instances.has_node.find_by(
```
Comment (SpComb) [inline server/app/services/scheduler/strategy/high_availability.rb]: Fixes  #2274

#### `kontena service deploy redis-ha-stateful`
```
 [done] Deploying service redis-ha-stateful      
⊛ Deployed instance development/null/redis-ha-stateful-1 to node core-01
```

File: server/app/services/scheduler/strategy/random.rb (hunk 3 above)
Comment (SpComb) [inline server/app/services/scheduler/strategy/random.rb]: Turns out that this matches the existing Kontena 1.1 behavior for stateful `ha` services, so I suppose this is working as intended.
