### PR TITLE
Fix healtcheck port validation to check port in unix port range

### LINKED ISSUE #2491: health_check port can be set to 0
Should maybe validate and fail the stack..?

### PR DESCRIPTION
**Pull request by jnummelin**
fixes #2491

### CODE REVIEW

File: server/spec/mutations/grid_services/create_spec.rb [hunk 1]
```diff
@@ -352,6 +352,40 @@
...
+          stateful: false,
+          health_check: {
+            protocol: 'tcp',
+            interval: 10,
+            timeout: 5,
+            initial_delay: 10,
+            port: 0
+          }
+      ).run
+      expect(outcome.success?).to be(false)
```
Comment (SpComb) [inline server/spec/mutations/grid_services/create_spec.rb]: General nitpick: I would suggest also checking the `expect(outcome.errors.message).to eq 'health_check' => ...`, otherwise this spec might not end up testing the health check validation, if it turns out to fail on some other parameter.
