### PR TITLE
Make stack environment variable validation fail if array item has no equals sign

### LINKED ISSUE #2238: Syntax errors in kontena.yml cause API 500 errors
Hi,

I found out that if my stack definition file has incorrect syntax for the `environment:` key, the API server returns a 500 error and the only way to see the error is to get it from the docker logs for kontena-server-api.

For example, I get a 500 error when I have a missing equals sign:

```
    environment:
      - KONTENA_LB_INTERNAL_PORT=4000
      - KONTENA_LB_VIRTUAL_HOST=www.example.com
      - PORT 4000
```

But even worse, I get a 500 when I try to use the YAML key/value syntax instead of a list of strings.

Here's an example of the error in the API server logs:

```
NoMethodError (undefined method `empty?' for nil:NilClass):
  /app/app/mutations/grid_services/update.rb:123:in `block in build_grid_service_envs'
  /app/app/mutations/grid_services/update.rb:122:in `each'
  /app/app/mutations/grid_services/update.rb:122:in `build_grid_service_envs'
  /app/app/mutations/grid_services/update.rb:73:in `execute'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /app/app/mutations/stacks/deploy.rb:47:in `block in create_or_update_services'
  /app/app/mutations/stacks/deploy.rb:43:in `each'
  /app/app/mutations/stacks/deploy.rb:43:in `create_or_update_services'
  /app/app/mutations/stacks/deploy.rb:31:in `execute'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /app/app/routes/v1/stacks_api.rb:52:in `deploy_stack'
  /app/app/routes/v1/stacks_api.rb:76:in `block (4 levels) in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1/stacks_api.rb:75:in `block (3 levels) in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:522:in `post'
  /app/app/routes/v1/stacks_api.rb:74:in `block (2 levels) in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1/stacks_api.rb:66:in `block in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /app/app/routes/v1_api.rb:20:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1_api.rb:20:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /app/server.rb:54:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/server.rb:53:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /app/app/middlewares/version_injector.rb:12:in `call'
  /app/app/middlewares/token_authentication.rb:73:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:59:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #2238

### CODE REVIEW

File: server/app/mutations/grid_services/update.rb [hunk 1]
```diff
@@ -120,7 +120,7 @@ def build_grid_service_envs(env)
       new_env = GridService.new(env: env).env_hash
       current_env = self.grid_service.env_hash
       new_env.each do |k, v|
-        if v.empty? && current_env[k]
+        if (v.nil? || v.empty?) && current_env[k]
```
Comment (SpComb) [inline server/app/mutations/grid_services/update.rb]: It would be better to validate and reject invalid `env` strings earlier, rather than fixing the `execute` -> `build_grid_service_envs` to deal with the result of trying to parse invalid envs.... fix the [`GridServices::Common` validation for the `env` array](https://github.com/kontena/kontena/blob/v1.2.1/server/app/mutations/grid_services/common.rb#L175) to use something like `string matches: /.*=.*/`?

However, that would result in the stacks mutations outcome error handling stumbling over the resulting `Mutations::ErrorArray` as per https://github.com/kontena/kontena/issues/2238#issuecomment-298569759, but fixed in #2058.

File: cli/lib/kontena/cli/stacks/yaml/validations.rb [hunk 2]
```diff
@@ -31,7 +31,15 @@ def common_validations
         'external_links' => optional('array'),
         'mem_limit' => optional('string'),
         'mem_swaplimit' => optional('string'),
-        'environment' => optional(-> (value) { value.is_a?(Array) || value.is_a?(Hash) }),
+        'environment' => optional(-> (value) {
+          if value.is_a?(Hash)
+            value.all? { |k,v| k.kind_of?(String) && (v.kind_of?(String) || v.kind_of?(Integer) || v.nil?) }
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/yaml/validations.rb]: What about other YAML values like `true` or `false`, which would have worked before?

File: server/app/models/grid_service.rb [hunk 3]
```diff
@@ -179,7 +179,7 @@ def link_to(service, service_alias = nil)
   # @return [Hash]
   def env_hash
     if @env_hash.nil?
-      @env_hash = self.env.inject({}){|h, n| h[n.split('=', 2)[0]] = n.split('=', 2)[1]; h }
+      @env_hash = Hash[*self.env.flat_map { |kv_pair| kv_pair.split(/(?<!\\)=/, 2) }]
```
Comment (SpComb) [inline server/app/models/grid_service.rb]: This still fails with HTTP 500 errors on invalid envs...

```
ArgumentError (odd number of arguments for Hash):
  /home/kontena/kontena/kontena/server/app/models/grid_service.rb:182:in `[]'
  /home/kontena/kontena/kontena/server/app/models/grid_service.rb:182:in `env_hash'
  /home/kontena/kontena/kontena/server/app/mutations/grid_services/update.rb:120:in `build_grid_service_envs'
  /home/kontena/kontena/kontena/server/app/mutations/grid_services/update.rb:73:in `execute'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/deploy.rb:47:in `block in create_or_update_services'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/deploy.rb:43:in `each'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/deploy.rb:43:in `create_or_update_services'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/deploy.rb:31:in `execute'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks_api.rb:52:in `deploy_stack'
```

Would it be better to just `Hash[self.env.map{|env| env.split('=', 2) }]`? That seems to kinda work better (results in `nil` values for envs without `=`):

```ruby
Hash[['FOO'].map { |env| env.split('=', 2) }] => {"FOO"=>nil}
```

File: cli/lib/kontena/cli/stacks/yaml/validations.rb (hunk 2 above)
Comment (kke) [inline cli/lib/kontena/cli/stacks/yaml/validations.rb]: i hope they get `.to_s`:ed at some point

File: server/app/mutations/grid_services/update.rb (hunk 1 above)
Comment (kke) [inline server/app/mutations/grid_services/update.rb]: I was thinking about having invalid values there because of earlier bugs, this should avoid crashing in case you installed a stack with invalid envs.

File: server/app/services/logging.rb [hunk 4]
```diff
@@ -3,7 +3,7 @@
 module Logging
 
   def self.initialize_logger(log_target = STDOUT, log_level = Logger::INFO)
-    @logger = Logger.new(log_target)
+    @logger = Logger.new(ENV['RACK_ENV'] == 'test' ? StringIO.new : log_target)
```
Comment (SpComb) [inline server/app/services/logging.rb]: These should already be supressed by the `server/spec/spec_helper.rb` when running tests, while still allowing the use of envs to see the logs if required:

```ruby
Logging.initialize_logger((ENV['LOG_TARGET'] || '/dev/null'), (ENV['LOG_LEVEL'] || Logger::UNKNOWN).to_i)
```

Comment (kke) [inline server/app/services/logging.rb]: image

Comment (SpComb) [inline server/app/services/logging.rb]: What specs are those from? Looks like `roda`'s logging.

Comment (kke) [inline server/app/services/logging.rb]: I suppose they're coming from websocketbackend or something is reinitializing the Logging thing during tests without the LOG_TARGET.

File: server/app/mutations/grid_services/update.rb (hunk 1 above)
Comment (SpComb) [inline server/app/mutations/grid_services/update.rb]: Implemented the service env validation over in  #2058 (https://github.com/kontena/kontena/pull/2058/commits/2230cfb5e3fa814c8e20d9362b058aeeaea0be81).

Trying to do the same validation here would result in HTTP 500 errors as the `handle_service_outcome_errors`  would be unable to handle the resulting `Mutations::ErrorArray`.

File: cli/lib/kontena/cli/stacks/yaml/validations.rb [hunk 5]
```diff
@@ -31,7 +31,23 @@ def common_validations
...
+              k.kind_of?(String) && (
+                v.kind_of?(String) ||
+                v.kind_of?(Integer) ||
+                v.kind_of?(TrueClass) ||
+                v.kind_of?(FalseClass) ||
+                v.nil?
+              )
+            end
+          elsif value.is_a?(Array)
+            value.all? { |v| v =~ /\A\S+(?<!\\)=.*/ }
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/yaml/validations.rb]: This should probably also validate that each array value is a `String`... now it might use the `=~` operator on a `Hash` or `Array`, which seems to return `nil` and thus fail validation, but that's odd.
