### PR TITLE
Fix cli node list sorting, specs

### LINKED ISSUE #2510: CLI: node list sorts nodes incorrectly
The `kontena node list` command should sort nodes by `node_number`, such that initial nodes are first. That does not happen:

```
NAME        VERSION     STATUS   INITIAL   LABELS
⊛ core-02   1.4.0.dev   online   -         test=label
⊛ core-01   1.4.0.dev   online   1 / 1     test
```

This is because it uses [`grid_nodes.sort { |n| n['node_number'] }`](https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/nodes/list_command.rb#L73), whereas `Array#sort` expects a `{ |a, b| a <=> b}` block. It should use `sort_by` instead.

The CLI specs `OutputHelpers#output_table` matcher is also broken, so the specs are still passing even though they should catch this.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2510
Fixes the `output_lines` matcher used by the `node list` specs - it was broken and passing even though the output lines were wrong.

### CODE REVIEW

File: cli/spec/support/output_helpers.rb [hunk 1]
```diff
@@ -52,23 +54,25 @@ module OutputHelpers
         line = 0
         @real.zip(@expected) do |real, expected|
           line += 1
-          error = values_match?(real.split(/\S+/), expected)
-          if error
-            @error ||= ""
-            @error << "\n#{error}"
-            @error.strip!
+          fields = real.split(/\s{2,}/)
```
Comment (SpComb) [inline cli/spec/support/output_helpers.rb]: @kke is this a reasonable way to split the tty-table output fields? This just leaves out empty fields (`nil` or `''`), it would be nice to also have those included in `fields`.

Comment (kke) [inline cli/spec/support/output_helpers.rb]: Maybe there's some way to trick tty-table to use a formatter that adds some recognizable separators, such as `\0` or `\t`. 

Perhaps that should be an option anyway, something like `-0|--print0` to output a null separated table that would be a lot easier to `cut` too.

File: cli/spec/support/output_helpers.rb [hunk 2]
```diff
@@ -52,23 +54,25 @@ module OutputHelpers
...
+          unless values_match?(fields, expected)
```
Comment (kke) [inline cli/spec/support/output_helpers.rb]: This works great 👍

File: cli/spec/support/output_helpers.rb [hunk 3]
```diff
@@ -52,23 +54,25 @@ module OutputHelpers
...
+              " received: #{fields}",
+            ].join("\n")
           end
         end
       else
-        @error = "expected #{@expected.size} lines but got #{@real.size} lines instead:\n"
-        @error += "Expected:\n#{@expected.map(&:inspect).join("\n")}"
-        @error += "Received:\n#{@real.map(&:inspect).join("\n")}"
+        @errors << "expected #{@expected.size} lines but got #{@real.size} lines instead:\n"
+          + " Expected:\n#{@expected.map(&:inspect).join("\n")}"
```
Comment (kke) [inline cli/spec/support/output_helpers.rb]: I don't think these `+` lines are actually appended to the message

File: cli/lib/kontena/cli/nodes/list_command.rb [hunk 4]
```diff
@@ -70,7 +70,7 @@ def node_data
           end
         end
 
-        grid_nodes.sort { |n| n['node_number'] }
+        grid_nodes.sort_by { |n| n['node_number'] }
```
Comment (kke) [inline cli/lib/kontena/cli/nodes/list_command.rb]: LGTM on the main ingredient here.

File: cli/spec/support/output_helpers.rb (hunk 1 above)
Comment (kke) [inline cli/spec/support/output_helpers.rb]: For now it seems to work (a way better than the previous one, I wonder how it worked at all) as long as no field has two spaces in it.

File: cli/spec/support/output_helpers.rb (hunk 3 above)
Comment (SpComb) [inline cli/spec/support/output_helpers.rb]: Right, didn't test that. Fixed now:

```
  1) Kontena::Cli::Nodes::ListCommand#show_grid_nodes For a initial_size=3 grid with a single node outputs node with error
     Failure/Error:
       expect{subject.run([])}.to output_table [
         [':error node-1', '1.1-dev', 'online', '1 / 3', '-'],
         [':error node-2', '1.1-dev', 'online', '2 / 3', '-'],
       ]

       expected 2 lines but got 1 lines instead:
        Expected:
       [":error node-1", "1.1-dev", "online", "1 / 3", "-"]
       [":error node-2", "1.1-dev", "online", "2 / 3", "-"]
        Received:
       [":error node-1", "1.1-dev", "online", "1 / 3", "-"]
     # ./spec/kontena/cli/nodes/list_command_spec.rb:48:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:45:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:43:in `catch'
     # ./spec/spec_helper.rb:43:in `block (2 levels) in <top (required)>'
```
