### PR TITLE
Fix and enhance stack command CLI autocompletions

### LINKED ISSUE #3179: Missing / invalid completions for many stack commands
* `kontena stack validate` does not complete `.yml` -files
* `kontena stack registry pull|show|rm` do not complete registry stacks
* `kontena stack registry push` does not complete `.yml` -files
* `kontena stack list|build` incorrectly complete installed stack names
* `kontena stack install|upgrade` only complete `.yml`-files, they could include registry stacks (and complete available version numbers if word under cursor ends with `:`)
* `kontena stack restart` does not complete installed stacks

### LINKED ISSUE #3181: Deprecated "kontena app" still in completions
The app-subcommand was removed some versions ago. It still appears in the CLI tab completions.

### LINKED ISSUE #3234: CLI completer recursion on access token refresh
The completer can't [override `client`](https://github.com/kontena/kontena/blob/889537e68ee306a0c621fa935b91183c39c032de/cli/lib/kontena/scripts/completer.rb#L32) to call `require_token`, because [`require_token`](https://github.com/kontena/kontena/blob/889537e68ee306a0c621fa935b91183c39c032de/cli/lib/kontena/cli/common.rb#L185) can call `client.refresh_token`.

```
$ DEBUG=true bundle exec bin/kontena complete kontena stack show
DEBUG Kontena CLI 1.5.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Completing ["stack", "show"]
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Configuration loaded with 25 servers and 2 accounts.
DEBUG Current master: development
DEBUG Current grid: development
DEBUG Current account: kontena
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
...
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
bundler: failed to load command: bin/kontena (bin/kontena)
SystemStackError: stack level too deep
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/log_formatters/compact.rb:59:in `block in <class:Compact>'
  /usr/lib/ruby/2.3.0/logger.rb:546:in `format_message'
  /usr/lib/ruby/2.3.0/logger.rb:434:in `add'
  /usr/lib/ruby/2.3.0/logger.rb:455:in `debug'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:183:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
...
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:51:in `stacks'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:313:in `<top (required)>'
  bin/kontena:13:in `require'
  bin/kontena:13:in `<top (required)>'
DEBUG Execution took 2.59 seconds
DEBUG SystemExit status 1
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #3179 
Fixes #3181 
Fixes #3234 

- `kontena stack <validate | build>` now completes .yml -files
- `kontena stack registry <pull | show | rm>` now completes registry stacks
- `kontena stack registry push` now completes .yml files
- `kontena stack <install | upgrade>` completes .yml-files + registry stacks
- `kontena stack restart` now completes installed stacks
- Removes deprecated `kontena app` completions
- All abbreviations such as `ls`, `rm`, `reg` etc removed from all completions because they make no sense and mess up completion (`r<tab>` would return `remove` and `rm` and require double tab + more letters instead of completing `remove` directly from single `r<tab>`)

### CODE REVIEW

**Comment by SpComb** [comment]
Is this an existing bug?

```
$ DEBUG=true bundle exec bin/kontena complete kontena stack show
DEBUG Kontena CLI 1.5.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Completing ["stack", "show"]
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Configuration loaded with 25 servers and 2 accounts.
DEBUG Current master: development
DEBUG Current grid: development
DEBUG Current account: kontena
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
...
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
DEBUG Access token expired, trying to refresh
bundler: failed to load command: bin/kontena (bin/kontena)
SystemStackError: stack level too deep
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/log_formatters/compact.rb:59:in `block in <class:Compact>'
  /usr/lib/ruby/2.3.0/logger.rb:546:in `format_message'
  /usr/lib/ruby/2.3.0/logger.rb:434:in `add'
  /usr/lib/ruby/2.3.0/logger.rb:455:in `debug'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:183:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
...
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:185:in `rescue in require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:177:in `require_token'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:33:in `client'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:51:in `stacks'
  /home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:313:in `<top (required)>'
  bin/kontena:13:in `require'
  bin/kontena:13:in `<top (required)>'
DEBUG Execution took 2.59 seconds
DEBUG SystemExit status 1
```

**Comment by kke** [comment]
Haven't seen that.

File: cli/lib/kontena/scripts/completer.rb [hunk 1]
```diff
@@ -247,31 +279,40 @@ def subcommand_tree(cmd = nil, base = nil)
...
-          elsif words[1] && sub_commands.include?(words[1])
+            if words[1] == 'install'
+              completion.push helper.registry_stacks(words[2].to_s)
+            end
+          elsif words[1] == 'upgrade'
+            if words[3]
+              completion.push helper.yml_files
+              completion.push helper.registry_stacks(words[4].to_s)
+            else
+              completion.push.helper.stacks
```
Comment (SpComb) [inline cli/lib/kontena/scripts/completer.rb]: Extra `.` instead of ` `

```
DEBUG undefined method `helper' for []:Array (NoMethodError)
/home/kontena/kontena/kontena/cli/lib/kontena/scripts/completer.rb:310:in `<top (required)>'
bin/kontena:13:in `require'
bin/kontena:13:in `<top (required)>'
```
