### PR TITLE
Resolve notification message receivers properly when grid is deleted

### LINKED ISSUE #3213: MongoPubsub::Subscription: undefined method `users' for nil:NilClass (NoMethodError)
Just have caught the following stack trace in my Kontena Master's logs (v1.4.3).
```
<IP REDACTED> - - [12/Jan/2018:05:30:10 +0000] "DELETE /v1/grids/test HTTP/1.1" 200 2 0.3053
E, [2018-01-12T05:30:10.616183 #7] ERROR -- MongoPubsub::Subscription: undefined method `users' for nil:NilClass (NoMethodError)
/app/app/services/cloud/websocket_client.rb:295:in `resolve_users'
/app/app/services/cloud/websocket_client.rb:275:in `send_notification_message'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
(celluloid):0:in `remote procedure call'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
/app/app/services/cloud/websocket_client.rb:313:in `block in subscribe_events'
/app/app/services/mongo_pubsub.rb:46:in `send_message'
/app/app/services/mongo_pubsub.rb:37:in `process'
/app/app/services/mongo_pubsub.rb:65:in `block in process_subscription'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
I, [2018-01-12T05:30:10.622216 #7]  INFO -- CloudWebsocketClientManager: Client exited: undefined method `users' for nil:NilClass
E, [2018-01-12T05:30:10.612687 #7] ERROR -- : Actor crashed!
NoMethodError: undefined method `users' for nil:NilClass
	/app/app/services/cloud/websocket_client.rb:295:in `resolve_users'
	/app/app/services/cloud/websocket_client.rb:275:in `send_notification_message'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### PR DESCRIPTION
**Pull request by nevalla**
When grid is deleted cloud websocket client requests grid users but at that point grid does not exist anymore. This PR will add check that grid exists.
Fixes #3213

### CODE REVIEW

File: server/spec/services/cloud/websocket_client_spec.rb [hunk 1]
```diff
@@ -327,5 +327,67 @@
...
+      let(:jane) do
+        jane = User.create(email: 'jane.doe@example.org', external_id: '67890')
+        grid.users << jane
+        jane
+      end
+
+      context 'when passing grid_id' do
+        before(:each) do
+          grid
+          john
```
Comment (SpComb) [inline server/spec/services/cloud/websocket_client_spec.rb]: Use `let!` instead

File: server/spec/services/cloud/websocket_client_spec.rb [hunk 2]
```diff
@@ -327,5 +327,67 @@
...
+        context 'when grid is found' do
+          it 'returns master admins and grid users' do
+            users = subject.resolve_users(grid.name)
+            expect(users).to eq([john.external_id, jane.external_id])
+          end
+        end
+
+        context 'when grid is not found' do
+          it 'returns master admins' do
+            grid.destroy
```
Comment (SpComb) [inline server/spec/services/cloud/websocket_client_spec.rb]: This should be in the `context` -> `before do ...`

File: server/spec/services/cloud/websocket_client_spec.rb [hunk 3]
```diff
@@ -327,5 +327,67 @@
...
+      context 'when grid_id nil' do
+        before(:each) do
+          grid
+          john
+          jane
+        end
+
+
+        it 'returns master admins' do
+          grid.destroy
```
Comment (SpComb) [inline server/spec/services/cloud/websocket_client_spec.rb]: Does this even need the `before` and `grid.destroy` if we're passing `nil`?

File: server/spec/services/cloud/websocket_client_spec.rb (hunk 1 above)
Comment (nevalla) [reply server/spec/services/cloud/websocket_client_spec.rb]: yes, makes sense

File: server/spec/services/cloud/websocket_client_spec.rb (hunk 2 above)
Comment (nevalla) [reply server/spec/services/cloud/websocket_client_spec.rb]: fixed

File: server/spec/services/cloud/websocket_client_spec.rb (hunk 3 above)
Comment (nevalla) [reply server/spec/services/cloud/websocket_client_spec.rb]: nope, just some copy paste leftovers. Removed
