### PR TITLE
Fix CLI API client to ignore empty response JSON body

### LINKED ISSUE #3251: [1.5-dev] CLI raises JSON::ParseError for DELETE requests with empty response body
Regression from #3240 because the server returns an empty response body with `Content-Type: application/json`: #3250

```
$ DEBUG=api bundle exec bin/kontena master token remove 5a5e0dd3f77ecf000edb4c4f
DEBUG Kontena CLI 1.5.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-hello from /home/kontena/kontena/kontena/cli/examples/kontena-plugin-hello/lib/kontena_cli_plugin.rb
DEBUG Running Kontena::MainCommand with ["master", "token", "remove", "5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::MasterCommand with ["token", "remove", "5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::Master::TokenCommand with ["remove", "5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'nil'
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Configuration loaded with 25 servers and 2 accounts.
DEBUG Current master: development
DEBUG Current grid: development
DEBUG Current account: kontena
DEBUG Running Kontena::Cli::Master::Token::RemoveCommand with ["5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'token remove'
> Destructive command. You can skip this prompt by running this command with --force option. Are you sure? Yes
DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock, Excon::Middleware::Decompress], :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>nil, :ssl_verify_peer_host=>nil}
DEBUG [Request]: DELETE http://localhost:9292/oauth2/tokens/5a5e0dd3f77ecf000edb4c4f | Headers: {Accept: application/json, Accept-Encoding: gzip, Authorization: Bearer} 
DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.5.0.dev}  | Status: 201
bundler: failed to load command: bin/kontena (bin/kontena)
Kontena::Errors::StandardError: Invalid response JSON from server for /oauth2/tokens/5a5e0dd3f77ecf000edb4c4f: JSON::ParserError: 743: unexpected token at ''
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:519:in `rescue in parse_json'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:517:in `parse_json'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:490:in `parse_response'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:330:in `request'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:244:in `delete'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/master/token/remove_command.rb:15:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:20:in `<top (required)>'
DEBUG Execution took 1.871 seconds
DEBUG SystemExit status 1
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #3251 as triggered by #3250

### Fixed `kontena master token remove`

```
$ DEBUG=api bundle exec bin/kontena master token remove --force 5a7992e684943f000c9044bb
DEBUG Kontena CLI 1.5.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-hello from /home/kontena/kontena/kontena/cli/examples/kontena-plugin-hello/lib/kontena_cli_plugin.rb
DEBUG Running Kontena::MainCommand with ["master", "token", "remove", "--force", "5a7992e684943f000c9044bb"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::MasterCommand with ["token", "remove", "--force", "5a7992e684943f000c9044bb"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::Master::TokenCommand with ["remove", "--force", "5a7992e684943f000c9044bb"] -- callback matcher = 'nil'
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Using master token from env KONTENA_TOKEN
DEBUG Configuration loaded with 25 servers and 2 accounts.
DEBUG Current master: development
DEBUG Current grid: development
DEBUG Current account: kontena
DEBUG Running Kontena::Cli::Master::Token::RemoveCommand with ["--force", "5a7992e684943f000c9044bb"] -- callback matcher = 'token remove'
DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock, Excon::Middleware::Decompress], :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>nil, :ssl_verify_peer_host=>nil}
DEBUG [Request]: DELETE http://localhost:9292/oauth2/tokens/5a7992e684943f000c9044bb | Headers: {Accept: application/json, Accept-Encoding: gzip, Authorization: Bearer} 
DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.5.0.dev}  | Status: 201
DEBUG Execution took 0.257 seconds
```

### Failing spec
```
Failures:

  1) Kontena::Client#request with empty response JSON returns nil
     Failure/Error: raise Kontena::Errors::StandardError.new(520, "Invalid response JSON from server for #{response.path}: #{ex.class.name}: #{ex.message}")

     Kontena::Errors::StandardError:
       Invalid response JSON from server for : JSON::ParserError: 743: unexpected token at ''
     # ./lib/kontena/client.rb:519:in `rescue in parse_json'
     # ./lib/kontena/client.rb:517:in `parse_json'
     # ./lib/kontena/client.rb:490:in `parse_response'
     # ./lib/kontena/client.rb:330:in `request'
     # ./lib/kontena/client.rb:244:in `delete'
     # ./spec/kontena/client_spec.rb:250:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # JSON::ParserError:
     #   743: unexpected token at ''
     #   ./vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
```

### CODE REVIEW

File: cli/lib/kontena/client.rb [hunk 1]
```diff
@@ -514,7 +514,11 @@ def add_version_warning(server_version)
     # @param response [Excon::Response]
     # @return [Hash,Object,NilClass]
     def parse_json(response)
-      JSON.parse(response.body)
+      if response.body.empty?
+        return nil
```
Comment (kke) [inline cli/lib/kontena/client.rb]: Unnecessary `return`s

Comment (kke) [reply cli/lib/kontena/client.rb]: (or replace with `return nil if response.body.empty?` guard clause)

Comment (kke) [reply cli/lib/kontena/client.rb]: maybe add a `.strip` in there for good measure

**Comment by SpComb** [comment]
Should fix the e2e specs:

```
$ bundle exec rspec spec/features/master/token/

token create
  creates a token with description

token remove
  creates a token with description

Top 2 slowest examples (3.8 seconds, 99.9% of total time):
  token create  creates a token with description
    2.11 seconds ./spec/features/master/token/create_spec.rb:4
  token remove  creates a token with description
    1.69 seconds ./spec/features/master/token/remove_spec.rb:4

Top 2 slowest example groups:
  token create
    2.11 seconds average (2.11 seconds / 1 example) ./spec/features/master/token/create_spec.rb:3
  token remove
    1.69 seconds average (1.69 seconds / 1 example) ./spec/features/master/token/remove_spec.rb:3

Finished in 3.8 seconds (files took 0.15534 seconds to load)
2 examples, 0 failures
```
