### PR TITLE
Fix "kontena service containers" throwing on nil overlay_cidr

### LINKED ISSUE #597: kontena service containers with missing IP outputs "undefined method `split' for nil:NilClass"
When a service has an instance with no `ip`-value:
```
[user@my-node ~]$ kontena service show my-service
my-grid/my-service:
  status: running
  image: registry.kontena.local/my/image:latest
  stateful: yes
  scaling: 1
  strategy: ha
  deploy_opts:
    wait_for_port: -
    min_health: 0.8
  dns: my-service.my-grid.kontena.local
  affinity:
    - node==my-node
  net: bridge
  ports:
    - 8080:80/tcp
  instances:
    my-service-1:
      rev: 2016-03-30 08:52:48 UTC
      node: my-node
      dns: my-service-1.my-grid.kontena.local
      ip:    <= No IP here
      public ip: [redacted]
      status: dead
      reason: Error --snip--
```

running `DEBUG=true kontena service containers my-service` results in:

```
[user@my-node ~]$ DEBUG=true kontena service containers my-service
my-grid/my-service/my-service-1:
  rev: 2016-04-05 09:29:57 UTC
  node: my-node
  dns: my-service-1.my-grid.kontena.local
  ip: [redacted]
  public ip: [redacted]
  status: restarting

my-grid/my-service/my-service-1:
  rev: 2016-03-30 08:52:48 UTC
  node: my-node
  dns: my-service-1.my-grid.kontena.local
/home/user/.gem/ruby/gems/kontena-cli-0.11.7/lib/kontena/cli/services/containers_command.rb:20:in `block in execute': undefined method `split' for nil:NilClass (NoMethodError)
        from /home/user/.gem/ruby/gems/kontena-cli-0.11.7/lib/kontena/cli/services/containers_command.rb:15:in `each'
        from /home/user/.gem/ruby/gems/kontena-cli-0.11.7/lib/kontena/cli/services/containers_command.rb:15:in `execute'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /usr/local/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from /home/user/.gem/ruby/gems/kontena-cli-0.11.7/bin/kontena:68:in `<top (required)>'
        from /usr/local/bin/kontena:23:in `load'
        from /usr/local/bin/kontena:23:in `<main>'
```

Kontena version is `0.11.7`.

### PR DESCRIPTION
**Pull request by mikkopiu**
Fixes #597, though the issue might actually relate to something deeper than just a missing nil check.

Also added simple test cases.

### CODE REVIEW

File: cli/lib/kontena/cli/services/containers_command.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@ def execute
         puts "  rev: #{container['deploy_rev']}"
         puts "  node: #{container['node']['name']}"
         puts "  dns: #{container['name']}.#{current_grid}.kontena.local"
-        puts "  ip: #{container['overlay_cidr'].split('/')[0]}"
+        puts "  ip: #{container['overlay_cidr'].nil? ? '' : container['overlay_cidr'].split('/')[0]}"
```
Comment (jakolehm) [inline cli/lib/kontena/cli/services/containers_command.rb]: This can be simplified a little bit by casting value always to string: `container['overlay_cidr'].to_s.split('/')[0]`

**Comment by mikkopiu** [comment]
Thanks for the advise. Simplified the fix, and added the missing "_spec" to containers_command_spec.rb.

**Comment by jakolehm** [comment]
Looks good! Please sign the CLA so that we can merge this.

**Comment by mikkopiu** [comment]
Sorry, there was something wonky with the commit authors (and CLA Assistant wouldn't allow me to sign), but now it should be okay.

**Comment by jakolehm** [comment]
Thanks!
