### PR TITLE
Agent: fix cAdvisor stats to ignore systemd Docker container mount cgroups

### LINKED ISSUE #1656: Kontena service CPU & Memory stats may be zero-valued due to cAdvisor cgroup confusion
## Symptom

Some `kontena service stats` will show zero CPU/memory usage for random Docker containers.

## Background
cAdvisor works by collecting the Docker container stats directly from the `/sys/fs/cgroup` files, such as `/sys/fs/cgroup/cpu/*/cpu.cfs_period_us`: https://github.com/google/cadvisor/blob/v0.24.1/container/common/helpers.go#L77

It locates the Docker container cgroup by recursively scanning through all `/sys/fs/cgroup/*` directories, and matching any cgroup that contains an existing Docker container ID in the basename: https://github.com/google/cadvisor/blob/v0.24.1/container/docker/factory.go#L148

This means that with CoreOS 1235.6.0 + systemd 231 + Docker 1.12.3 + Linux 4.7.3-coreos-r2, the cAdvisor Docker driver will pick up two cgroups for each Docker container:

```
I0113 12:22:45.621838       1 factory.go:111] Using factory "docker" for container "/system.slice/var-lib-docker-containers-acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536-shm.mount"
I0113 12:22:45.626448       1 manager.go:874] Added container: "/system.slice/var-lib-docker-containers-acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536-shm.mount" (aliases: [null-stackless-whoami-1 acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536], namespace: "docker")

I0113 12:22:45.755197       1 factory.go:111] Using factory "docker" for container "/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536"
I0113 12:22:45.756418       1 manager.go:874] Added container: "/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536" (aliases: [null-stackless-whoami-1 acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536], namespace: "docker")
```

In this case, `/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536` is the correct cgroup, which contains the processes within the Docker container. The `/system.slice/var-lib-docker-containers-acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536-shm.mount` cgroup is empty, and associated with the `/var/lib/docker/containers/*/shm` mountpoint.

Both of these container entries will associate themselves with the information returned by the Docker API for that container ID, and will thus have an identical set of cAdvisor aliases. Both container entries will add identical `namespacedContainerName{"docker", "acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536"}` entries in the `github.com/google/cadvisor/manager:manager.containers` map, which override each other depending on the order that the cgroups are listed in, and may change as events come in?

The `/api/v1.2/docker/ID` will then semi-randomly return one of these two cgroup entries:

```
core@core-01 ~ $ curl -v http://localhost:8989/api/v1.2/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536
{"/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536":{"id":"acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536","name":"/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536","aliases":["null-stackless-whoami-1","acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536"],"namespace":"docker", ...
core@core-01 ~ $ docker restart kontena-cadvisor
kontena-cadvisor
core@core-01 ~ $ curl http://localhost:8989/api/v1.2/docker/acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536
{"/system.slice/var-lib-docker-containers-acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536-shm.mount":{"id":"acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536","name":"/system.slice/var-lib-docker-containers-acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536-shm.mount","aliases":["null-stackless-whoami-1","acf76f8a0cf47638f7ab7c7e033872672479017f7447f90d2d6d6d5c39bf7536"],"namespace":"docker", ...
```

See https://github.com/google/cadvisor/issues/1572

## Workaround
The `/api/v1.2/containers/CGROUP` API will always return the actual container cgroup stats, assuming that Docker places it's container cgroups directly under `/docker`.

Alternative is to somehow hide the systemd mount cgroups from cAdvisor.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1656

This replaces the `/api/v1.2/docker/...` queries with a single `/api/v1.2/subcontainers` query, which returns all containers that cAdvisor knows about. This response includes both `/docker/*` and `/system.slice/var-lib-docker-containers-*-shm.mount` entries for each Docker container.

The agent ignores the `*.mount` entries that have zero-valued stats.

### CODE REVIEW

File: agent/lib/kontena/workers/stats_worker.rb [hunk 1]
```diff
@@ -47,25 +47,26 @@ def start
...
       info 'starting collection'
-      begin
-        Docker::Container.all.each do |container|
-          if container.running?
-            data = self.collect_container_stats(container.id)
-            send_container_stats(data) if data
-            sleep 0.5
-          end
+
+      if response = get("/api/v1.2/subcontainers")
```
Comment (jakolehm) [inline agent/lib/kontena/workers/stats_worker.rb]: Interesting change.. what is the reason behind this?

Comment (SpComb) [inline agent/lib/kontena/workers/stats_worker.rb]: See the PR description, you were too quick :)

File: agent/lib/kontena/workers/stats_worker.rb [hunk 2]
```diff
@@ -117,7 +118,7 @@ def send_container_stats(container)
         }
       }
       self.queue << event
-      send_statsd_metrics(container.dig(slice_key, :aliases, 0), event[:data])
+      send_statsd_metrics(container.dig(:aliases, 0), event[:data])
```
Comment (SpComb) [inline agent/lib/kontena/workers/stats_worker.rb]: Is this assumption of `"aliases": [name, id]` sensible?

It looks like the current cAdvisor implementation always returns these in this order: https://github.com/google/cadvisor/blob/v0.24.1/container/docker/handler.go#L222

But it's certainly not part of the API...

Comment (jakolehm) [inline agent/lib/kontena/workers/stats_worker.rb]: Good point, do we have any better ways?

File: agent/lib/kontena/workers/stats_worker.rb (hunk 1 above)
Comment (jakolehm) [inline agent/lib/kontena/workers/stats_worker.rb]: Ok, makes sense :)

**Comment by SpComb** [comment]
It looks like upstream cAdvisor is fixing the original issue in https://github.com/google/cadvisor/pull/1573, but maybe this change makes sense anyways? I would expect the single `/subcontainers` API approach to be cheaper than the current approach of multiple API queries, and generate mostly the same results?

This is probably 1.1 if there's an fixed upstream release we can use instead.

**Comment by jakolehm** [comment]
Actually there has been reason for doing multiple calls. The `/api/v1.2/docker` did error out if one of the containers were in a bad state.. not sure if `subcontainers` handles this better.

**Comment by SpComb** [comment]
> Actually there has been reason for doing multiple calls. The /api/v1.2/docker did error out if one of the containers were in a bad state.. not sure if subcontainers handles this better.

Any example of what kind of errors it returned in that case? It may have been fixed since.

**Comment by jakolehm** [comment]
Api just throwed 500 error so agent did not get any metrics (#769).

**Comment by jnummelin** [comment]
Yes, the whole point of doing multiple cAdvisor calls was to avoid one container erroring out all the containers. I'm afraid that this PR brings those issues back as this gets all the stats in single call. Although the cAdvisor version was 0.23.0 at that point, so some of the things might be fixed:
https://github.com/google/cadvisor/releases/tag/v0.23.2
> Better handling of partial failures when fetching subcontainers

https://github.com/google/cadvisor/releases/tag/v0.24.0
> Improved robustness to partial failures

**Comment by SpComb** [comment]
> Api just throwed 500 error so agent did not get any metrics (#769).

Looking at the fixed issue (#678), it's `undefined method 'count' for nil:NilClass` at `num_cores = current_stat[:cpu][:usage][:per_cpu_usage].count` -  it can't have been a HTTP 500 response, because it wouldn't have actually parsed the JSON response and gotten even that far.

> Although the cAdvisor version was 0.23.0 at that point, so some of the things might be fixed

Yes, that's why it would be good to know what the actual reason behind the workaround was, we may not need that workaround anymore?

File: agent/lib/kontena/workers/stats_worker.rb (hunk 2 above)
Comment (SpComb) [inline agent/lib/kontena/workers/stats_worker.rb]: Changed to use `name = container[:aliases].select{|a| a != container[:id]}.first`

**Comment by jnummelin** [comment]
The cAdvisor 500 errors was fixed at the same PR, so the descriptions are not 100% accurate. :/

But in some cases where cAdvisor failed to collect some container stats (maybe dead containers, maybe containers gone missing during the collection) really gave 500 for the request. So one failing container made all others fail too and hence I did the "workaround" to get the stats one-by-one. I tried to find chat archives for more detailed error descriptions but failed. :/

**Comment by jnummelin** [comment]
Tried to break this by running continuous scale up&down which should cause containers to disappear during collection and now cAdvisor seems to be able to handle that. From agent point-of-view all the collections were ok, on cAdvisor logs one error can be seen:
```
W0116 09:29:50.499561       1 container.go:365] Failed to get RecentStats("/docker/763a22cb225d6e083951c36b4210f879dae3c97373e00e383c46f89a3f722516") while determining the next housekeeping: unable to find data for container /docker/763a22cb225d6e083951c36b4210f879dae3c97373e00e383c46f89a3f722516
```
But this did not cause the cAdvisor API to "misbehave".
