### PR TITLE
Raise puma worker boot timeout & remove background threads

### LINKED ISSUE #2164: CreateEventLog migration throws error if index is building
```
I, [2017-04-17T10:31:17.298161 #1459]  INFO -- Mongodb::Migrator: migrating CreateEventLog
The operation: #<Moped::Protocol::Command
  @length=104
  @request_id=73
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="kontena_server.$cmd"
  @skip=0
  @limit=-1
  @selector={:convertToCapped=>"event_logs", :capped=>true, :size=>104857600}
  @fields=nil>
failed with error 12586: "exception: cannot perform operation: a background operation is currently running for database kontena_server"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
The operation: #<Moped::Protocol::Command
  @length=104
  @request_id=73
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="kontena_server.$cmd"
  @skip=0
  @limit=-1
  @selector={:convertToCapped=>"event_logs", :capped=>true, :size=>104857600}
  @fields=nil>
failed with error 12586: "exception: cannot perform operation: a background operation is currently running for database kontena_server"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:63:in `block in execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `map'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:663:in `read'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:90:in `command'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:73:in `block in command'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb:25:in `execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:83:in `command'
/app/db/migrations/24_create_event_log.rb:7:in `up'
/app/app/services/mongodb/migration.rb:6:in `migrate'
/app/app/services/mongodb/migration_proxy.rb:4:in `migrate'
/app/app/services/mongodb/migrator.rb:86:in `block in migrate_without_lock'
/app/app/services/mongodb/migrator.rb:83:in `each'
/app/app/services/mongodb/migrator.rb:83:in `migrate_without_lock'
/app/app/services/mongodb/migrator.rb:72:in `block in migrate'
/app/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
/app/app/models/distributed_lock.rb:24:in `with_lock'
/app/app/helpers/distributed_locks.rb:6:in `with_dlock'
/app/app/services/mongodb/migrator.rb:71:in `migrate'
config/puma.rb:10:in `block in _load_from'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:178:in `check_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:444:in `run'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
/usr/bin/puma:22:in `load'
/usr/bin/puma:22:in `<main>'
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2164 (partially). Puma worker can still timeout if migrations takes more than 5 minutes to complete.

### CODE REVIEW

**Comment by SpComb** [comment]
> Puma worker can still timeout if migrations takes more than 5 minutes to complete.

If the 5-minute timeout hits, I'm guessing that the puma worker will restart, release the stale migration lock, and then re-try the migration operation that timed out? Does this allow the server to recover?

File: server/app/services/mongodb/migrator.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ class Migrator
     include DistributedLocks
 
     LOCK_NAME = 'mongodb_migrate'.freeze
-    LOCK_TIMEOUT = 60
+    LOCK_TIMEOUT = (60 * 5)
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Hmm... this timeout is also used for the `with_dlock(LOCK_NAME, LOCK_TIMEOUT)`. Does it make sense to use the same timeout for both the lock aquire and the cleanup?

BTW... if the `Migrator#migrate` -> `with_dlock` times out... then it just returns false, and continues booting up the server without running the migrations :scream:

File: server/db/migrations/19_add_indexes_to_container_log.rb [hunk 2]
```diff
@@ -1,8 +1,6 @@
 class AddIndexesToContainerLog < Mongodb::Migration
   def self.up
-    Thread.new {
-      Thread.current.abort_on_exception = true
-      ContainerLog.create_indexes # might take a long time
-    }
+    info "recreating container log indexes, this might take long time"
+    ContainerLog.create_indexes
```
Comment (SpComb) [inline server/db/migrations/19_add_indexes_to_container_log.rb]: If we're blocking the migrations for the duration of the index create, then should we also revert the `index(..., { background: true })` mode as well? It sounds like the normal foreground index builds are better in that case: https://docs.mongodb.com/v3.0/tutorial/build-indexes-in-the-background/

> Background index builds take longer to complete and result in an index that is initially larger, or less compact, than an index built in the foreground.

File: server/app/services/mongodb/migrator.rb (hunk 1 above)
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: I'm thinking we should not have any timeout for the migration lock, i.e. fix `Migrator#migrate` to use `with_dlock(LOCK_NAME, 0)`? Then the puma worker timeout will kill it, and allow it to re-aquire the lock after cleaning up any stale locks.

File: server/db/migrations/19_add_indexes_to_container_log.rb (hunk 2 above)
Comment (jakolehm) [inline server/db/migrations/19_add_indexes_to_container_log.rb]: If master is deployed with some rolling-upgrade mechanism then background index will help.

File: server/app/services/mongodb/migrator.rb [hunk 3]
```diff
@@ -68,13 +69,16 @@ def migrations
...
       release_stale_lock
-      with_dlock(LOCK_NAME, LOCK_TIMEOUT) do
-        migrate_without_lock
-      end
+      lock_id = wait_until!("lock #{name} is available", timeout: LOCK_TIMEOUT, interval: 0.5) { 
+        DistributedLock.obtain_lock(LOCK_NAME)
+      }
+      migrate_without_lock
+    ensure
+      DistributedLock.release_lock(LOCK_NAME, lock_id)
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Needs an `if lock_id` in case the wait times out, and there is no `lock_id` set?

Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Or better yet, only have a separate `begin ... ensure` block to do this release after we have the lock...

**Comment by SpComb** [comment]
Specs need fixing for the timeout changes:

```
  1) Mongodb::Migrator#release_stale_lock removes lock if stale

     Failure/Error: expect {

       expected result to have changed by -1, but was changed by 0

     # ./spec/services/mongodb/migrator_spec.rb:32:in `block (3 levels) in <top (required)>'
```

File: server/app/services/mongodb/migrator.rb [hunk 4]
```diff
@@ -68,13 +69,16 @@ def migrations
     def migrate
       ensure_indexes
       release_stale_lock
-      with_dlock(LOCK_NAME, LOCK_TIMEOUT) do
-        migrate_without_lock
-      end
+      lock_id = wait_until!("lock #{name} is available", timeout: LOCK_TIMEOUT, interval: 0.5) {
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: `/home/kontena/kontena/kontena/server/app/services/mongodb/migrator.rb:72:in 'migrate': undefined local variable or method 'name' for #<Mongodb::Migrator:0x00000002a933a8> (NameError)`

**Comment by SpComb** [comment]
Testing with a reduced 10s timeout (both puma worker and distributed lock wait), and the server seems to recover: the mgiration gets re-run until the mongo index build completes. However, it seems to take a long time for puma to timeout the worker, though, and distributed lock can get released and re-acquired without the original worker holding the lock being killed. Thus, multiple workers end up completing the migrations :bomb: 

```
I, [2017-04-20T12:04:27.249386 #23654]  INFO -- Mongodb::Migrator: migrating GridSubnet
I, [2017-04-20T12:04:27.312951 #23654]  INFO -- Mongodb::Migrator: migrated GridSubnet
I, [2017-04-20T12:04:27.316528 #23654]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:04:27.753236 #23650] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:04:27.753413 #23660] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:04:27.758042 #23658] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
...
W, [2017-04-20T12:04:37.318824 #23658]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
W, [2017-04-20T12:04:37.318833 #23660]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
W, [2017-04-20T12:04:37.319247 #23650]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
...
D, [2017-04-20T12:04:39.564485 #23721] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:04:39.566622 #23725] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:04:39.569509 #23727] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
...
W, [2017-04-20T12:04:49.140840 #23727]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
W, [2017-04-20T12:04:49.140920 #23721]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
W, [2017-04-20T12:04:49.140941 #23725]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
...
I, [2017-04-20T12:04:50.823571 #23779]  INFO -- Mongodb::Migrator: released stale distributed lock
I, [2017-04-20T12:04:50.850001 #23779]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:04:51.350345 #23781] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:04:51.520911 #23775] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
...
W, [2017-04-20T12:05:00.884905 #23781]  WARN -- Mongodb::Migrator: timeout after waiting 10.0s of 10.0s until: migration lock is available
W, [2017-04-20T12:05:01.118496 #23775]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:02.647932 #23829] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:02.844607 #23838] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
...
W, [2017-04-20T12:05:12.208932 #23829]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
W, [2017-04-20T12:05:12.457224 #23838]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
...
I, [2017-04-20T12:05:13.459425 #23866]  INFO -- Mongodb::Migrator: released stale distributed lock
I, [2017-04-20T12:05:13.477728 #23866]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:05:14.263453 #23875] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
...
W, [2017-04-20T12:05:23.814943 #23875]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:25.467412 #23901] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:25.988243 #23901] DEBUG -- Mongodb::Migrator: waiting 1.5s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:26.991370 #23901] DEBUG -- Mongodb::Migrator: waiting 2.5s of 10.0s until: migration lock is available
[23647] ! Terminating timed out worker: 23654
D, [2017-04-20T12:05:28.997799 #23901] DEBUG -- Mongodb::Migrator: waiting 4.5s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:31.543692 #23922] DEBUG -- Mongodb::Migrator: waiting 1.0s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:32.077858 #23922] DEBUG -- Mongodb::Migrator: waiting 1.5s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:33.023477 #23901] DEBUG -- Mongodb::Migrator: waiting 8.6s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:33.083783 #23922] DEBUG -- Mongodb::Migrator: waiting 2.5s of 10.0s until: migration lock is available
W, [2017-04-20T12:05:35.029503 #23901]  WARN -- Mongodb::Migrator: timeout after waiting 10.1s of 10.0s until: migration lock is available
D, [2017-04-20T12:05:35.090474 #23922] DEBUG -- Mongodb::Migrator: waiting 4.5s of 10.0s until: migration lock is available
...
I, [2017-04-20T12:05:36.282114 #23938]  INFO -- Mongodb::Migrator: released stale distributed lock
I, [2017-04-20T12:05:36.294838 #23938]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
I, [2017-04-20T12:05:36.342339 #23938]  INFO -- Mongodb::Migrator: migrated AddIndexesToContainerLog
...
I, [2017-04-20T12:05:36.595785 #23922]  INFO -- Mongodb::Migrator: waited 5.6s of 10.0s until: migration lock is available yielded String

[23647] - Worker 2 (pid: 23938) booted, phase: 0

I, [2017-04-20T12:05:40.082999 #23779]  INFO -- Mongodb::Migrator: migrated AddIndexesToContainerLog

[23647] - Worker 3 (pid: 23779) booted, phase: 0

I, [2017-04-20T12:05:40.518370 #23866]  INFO -- Mongodb::Migrator: migrated AddIndexesToContainerLog

[23647] - Worker 0 (pid: 23866) booted, phase: 0
```

**Comment by SpComb** [comment]
Testing again with a 20s `LOCK_TIMEOUT` + puma `worker_boot_timeout`, and a 10s puma `worker_timeout`, this behaves correctly:

```
I, [2017-04-20T12:30:34.750048 #25281]  INFO -- Mongodb::Migrator: migrating GridSubnet
I, [2017-04-20T12:30:34.972957 #25281]  INFO -- Mongodb::Migrator: migrated GridSubnet
I, [2017-04-20T12:30:34.974580 #25281]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:30:35.259341 #25293] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:35.296048 #25285] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:35.363384 #25289] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:30:50.860552 #25293] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:50.932556 #25285] DEBUG -- Mongodb::Migrator: waiting 16.7s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:50.960269 #25289] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
[25278] ! Terminating timed out worker: 25281
[25278] ! Terminating timed out worker: 25285
[25278] ! Terminating timed out worker: 25289
[25278] ! Terminating timed out worker: 25293
D, [2017-04-20T12:30:56.389786 #25378] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:56.507798 #25374] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:56.521657 #25366] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:30:56.529672 #25370] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:31:11.999663 #25378] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:12.110126 #25374] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:12.125217 #25366] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:12.125646 #25370] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
[25278] ! Terminating timed out worker: 25366
[25278] ! Terminating timed out worker: 25370
[25278] ! Terminating timed out worker: 25374
[25278] ! Terminating timed out worker: 25378
I, [2017-04-20T12:31:16.728849 #25457]  INFO -- Mongodb::Migrator: released stale distributed lock
I, [2017-04-20T12:31:16.750925 #25457]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:31:17.337633 #25449] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:17.387733 #25460] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:17.543145 #25453] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:31:33.075277 #25460] DEBUG -- Mongodb::Migrator: waiting 16.7s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:33.075429 #25449] DEBUG -- Mongodb::Migrator: waiting 16.8s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:33.152461 #25453] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
[25278] ! Terminating timed out worker: 25449
[25278] ! Terminating timed out worker: 25453
[25278] ! Terminating timed out worker: 25457
[25278] ! Terminating timed out worker: 25460
D, [2017-04-20T12:31:38.227061 #25532] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:38.238770 #25528] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:38.315572 #25524] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:38.452039 #25534] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:31:53.868543 #25532] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:53.920470 #25528] DEBUG -- Mongodb::Migrator: waiting 16.7s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:53.968421 #25524] DEBUG -- Mongodb::Migrator: waiting 16.7s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:54.095070 #25534] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
[25278] ! Terminating timed out worker: 25524
[25278] ! Terminating timed out worker: 25528
[25278] ! Terminating timed out worker: 25532
[25278] ! Terminating timed out worker: 25534
I, [2017-04-20T12:31:58.720800 #25603]  INFO -- Mongodb::Migrator: released stale distributed lock
I, [2017-04-20T12:31:58.742161 #25603]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:31:59.279009 #25607] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:59.436348 #25595] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:31:59.448077 #25599] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:32:14.890139 #25607] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:15.055137 #25599] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:15.069972 #25595] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
[25278] ! Terminating timed out worker: 25595
[25278] ! Terminating timed out worker: 25599
[25278] ! Terminating timed out worker: 25603
[25278] ! Terminating timed out worker: 25607
D, [2017-04-20T12:32:20.613727 #25663] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:20.654967 #25667] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:20.706643 #25674] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:20.736141 #25671] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:32:36.247454 #25663] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:36.298395 #25667] DEBUG -- Mongodb::Migrator: waiting 16.7s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:36.318062 #25674] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:36.355751 #25671] DEBUG -- Mongodb::Migrator: waiting 16.6s of 20.0s until: migration lock is available
[25278] ! Terminating timed out worker: 25663
[25278] ! Terminating timed out worker: 25667
[25278] ! Terminating timed out worker: 25671
[25278] ! Terminating timed out worker: 25674
I, [2017-04-20T12:32:40.837549 #25746]  INFO -- Mongodb::Migrator: released stale distributed lock
I, [2017-04-20T12:32:40.860819 #25746]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
recreating container log indexes, this might take long time
D, [2017-04-20T12:32:41.378880 #25754] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:41.462687 #25742] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:41.525335 #25750] DEBUG -- Mongodb::Migrator: waiting 1.0s of 20.0s until: migration lock is available
...
D, [2017-04-20T12:32:48.928957 #25754] DEBUG -- Mongodb::Migrator: waiting 8.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:49.024773 #25742] DEBUG -- Mongodb::Migrator: waiting 8.6s of 20.0s until: migration lock is available
D, [2017-04-20T12:32:49.081043 #25750] DEBUG -- Mongodb::Migrator: waiting 8.6s of 20.0s until: migration lock is available
I, [2017-04-20T12:32:50.003541 #25746]  INFO -- Mongodb::Migrator: migrated AddIndexesToContainerLog
I, [2017-04-20T12:32:50.004816 #25746]  INFO -- Mongodb::Migrator: migrating CreateGridServiceInstance
I, [2017-04-20T12:32:50.030163 #25746]  INFO -- Mongodb::Migrator: migrated CreateGridServiceInstance
I, [2017-04-20T12:32:50.031002 #25746]  INFO -- Mongodb::Migrator: migrating VolumeMigration
I, [2017-04-20T12:32:50.173755 #25746]  INFO -- Mongodb::Migrator: migrated VolumeMigration
I, [2017-04-20T12:32:50.175142 #25746]  INFO -- Mongodb::Migrator: migrating CreateContainerStatsCreatedAtIndex
recreating container stat indexes, this might take long time
I, [2017-04-20T12:32:50.184465 #25746]  INFO -- Mongodb::Migrator: migrated CreateContainerStatsCreatedAtIndex
I, [2017-04-20T12:32:50.185617 #25746]  INFO -- Mongodb::Migrator: migrating CreateHostNodeStatsCreatedAtIndex
recreating node stat indexes, this might take long time
I, [2017-04-20T12:32:50.198408 #25746]  INFO -- Mongodb::Migrator: migrated CreateHostNodeStatsCreatedAtIndex
I, [2017-04-20T12:32:50.199657 #25746]  INFO -- Mongodb::Migrator: migrating CreateEventLog
I, [2017-04-20T12:32:50.225180 #25746]  INFO -- Mongodb::Migrator: migrated CreateEventLog
...
[25278] - Worker 1 (pid: 25746) booted, phase: 0

I, [2017-04-20T12:32:50.435109 #25754]  INFO -- Mongodb::Migrator: waited 9.6s of 20.0s until: migration lock is available yielded String

I, [2017-04-20T12:32:50.553370 #25742]  INFO -- Mongodb::Migrator: waited 9.6s of 20.0s until: migration lock is available yielded String

[25278] - Worker 3 (pid: 25754) booted, phase: 0

[25278] - Worker 0 (pid: 25742) booted, phase: 0

I, [2017-04-20T12:32:51.094926 #25750]  INFO -- Mongodb::Migrator: waited 10.1s of 20.0s until: migration lock is available yielded String

[25278] - Worker 2 (pid: 25750) booted, phase: 0
```

File: server/app/services/mongodb/migrator.rb [hunk 5]
```diff
@@ -1,14 +1,15 @@
...
 
 module Mongodb
   class Migrator
     include Logging
-    include DistributedLocks
+    include WaitHelper
 
     LOCK_NAME = 'mongodb_migrate'.freeze
-    LOCK_TIMEOUT = 60
+    LOCK_TIMEOUT = (60 * 5)
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: This could have a comment mentioning something about the relation to the puma worker timeout. The `LOCK_TIMEOUT`has to be longer than the puma `worker_timeout` and `worker_boot_timeout`.

File: server/app/services/mongodb/migrator.rb [hunk 6]
```diff
@@ -68,13 +69,16 @@ def migrations
     def migrate
       ensure_indexes
       release_stale_lock
-      with_dlock(LOCK_NAME, LOCK_TIMEOUT) do
-        migrate_without_lock
-      end
+      lock_id = wait_until!("migration lock is available", timeout: LOCK_TIMEOUT, interval: 0.5) {
+        DistributedLock.obtain_lock(LOCK_NAME)
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Note refactoring debt for #2125
