### PR TITLE
Fix server deploy queuing

### LINKED ISSUE #2208: Server: GridServiceHealthMonitorJob can pile up deployments
Given a failing health check, `GridServiceHealthMonitorJob` will just blindly create new deployments if the service overall health drops too much. In case of mis-configured (or anyway heavily failing) health check this can cause service deployments to pile up heavily with these kind of log entries
```
I, [2017-04-24T11:48:10.369721 #11]  INFO -- GridServiceSchedulerWorker: delaying foo/bar/some-service deploy because there is another deploy in progress
```
These will probably also mean timeouts with distributed locks:
```
W, [2017-04-24T11:52:45.536157 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:45.763583 #9]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:45.794109 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:45.805272 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:46.810364 #9]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:46.812494 #9]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:46.845791 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:56.563669 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:56.793793 #9]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:56.815847 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
W, [2017-04-24T11:52:56.844696 #11]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:580ddcc376f5980007001319 is available
```

`GridServiceHealthMonitorJob` should check if there is already a pending deployment for the given service and only if not create the deployment.

### LINKED ISSUE #2212: Service deploys can get stuck if there are several queued deploys when a service finishes deploying
The server has multiple `GridServiceSchedulerWorker` actors running. Each `kontena service deploy` operation creates a `GridServiceDeploy`. The `GridServiceSchedulerWorker` actors pick up `GridServiceDeploy` and mark them as `started_at` using an atomic mongoid operation: `GridServiceDeploy.where(started_at: nil).asc(:created_at).find_and_modify({:$set => {started_at: Time.now.utc}}, {new: true})`.

However, before performing the `GridServiceDeployer`, the `GridServiceSchedulerWorker` will check if there are other deployments for the same grid service: `service_deploy.grid_service.deploying?(ignore: service_deploy.id)`. The intention of this check is to prevent running multiple simultaneous deploys for the same service. If there are, it will try re-performing the deploy 30s later: `after(30) { service_deploy.set(:started_at => nil) }`.

However, each of those "blocked" deploys will still be `started_at` for that entire 30s period, and thus also block any other deploys, because they will be counted by `GridService#deploying?`: `self.grid_service_deploys.where(:created_at.gt => 10.minutes.ago, :started_at.ne => nil, :finished_at => nil).where(:_id.ne => ignore).count > 0`.

This means that multiple deploys for a service that is already being deployed will leave the service stuck, unable to deploy, until all of those deploys expire (`created_at.gt => 10.minutes.ago`)...

---

Testing using repeated `kontena service deploy` of a service with a signle instace, with the agent modified to take 5s for the `ServicePods::Create`:

```
127.0.0.1 - - [24/Apr/2017:18:48:28 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.0802
D, [2017-04-24T18:48:28.286004 #4930] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e4cde35781346000009
I, [2017-04-24T18:48:28.302446 #4930]  INFO -- GridServiceDeployer: starting to deploy development/null/redis-test
I, [2017-04-24T18:48:28.340982 #4930]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T18:48:28.342014 #4930]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-1 to node core-01 at 2017-04-24 15:48:28 UTC...
D, [2017-04-24T18:48:28.866245 #4930] DEBUG -- GridServiceInstanceDeployer: waiting 1.0s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 15:48:28 UTC
D, [2017-04-24T18:48:29.367228 #4930] DEBUG -- GridServiceInstanceDeployer: waiting 1.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 15:48:28 UTC

127.0.0.1 - - [24/Apr/2017:18:48:29 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.0815
D, [2017-04-24T18:48:29.830106 #4930] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e4dde3578134a00000e
D, [2017-04-24T18:48:30.371521 #4930] DEBUG -- Module: waiting 0.6s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
D, [2017-04-24T18:48:30.375904 #4930] DEBUG -- GridServiceInstanceDeployer: waiting 2.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 15:48:28 UTC
D, [2017-04-24T18:48:30.857809 #4930] DEBUG -- Module: waiting 1.1s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available

127.0.0.1 - - [24/Apr/2017:18:48:31 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.0817
D, [2017-04-24T18:48:31.171135 #4938] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e4fde3578134a000010
D, [2017-04-24T18:48:31.716659 #4938] DEBUG -- Module: waiting 0.6s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
D, [2017-04-24T18:48:31.878958 #4930] DEBUG -- Module: waiting 2.1s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
I, [2017-04-24T18:48:31.886876 #4930]  INFO -- GridServiceInstanceDeployer: waited 3.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 15:48:28 UTC yielded GridServiceInstance
I, [2017-04-24T18:48:31.996104 #4930]  INFO -- GridServiceDeployer: service development/null/redis-test has been deployed

I, [2017-04-24T18:48:32.042111 #4930]  INFO -- Module: waited 2.2s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available yielded String
I, [2017-04-24T18:48:32.047781 #4930]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e4dde3578134a00000e because there is another deploy in progress

D, [2017-04-24T18:48:32.095177 #4938] DEBUG -- Module: waited 0.9s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available yielded String
I, [2017-04-24T18:48:32.101255 #4938]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e4fde3578134a000010 because there is another deploy in progress


127.0.0.1 - - [24/Apr/2017:18:48:32 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.0803
D, [2017-04-24T18:48:32.580190 #4938] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e50de3578133e000020
I, [2017-04-24T18:48:32.593513 #4938]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e50de3578133e000020 because there is another deploy in progress

127.0.0.1 - - [24/Apr/2017:18:48:33 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.0776
D, [2017-04-24T18:48:34.006890 #4930] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e51de3578134600000b
I, [2017-04-24T18:48:34.011866 #4930]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e51de3578134600000b because there is another deploy in progress



D, [2017-04-24T18:49:02.051513 #4930] DEBUG -- GridServiceSchedulerWorker: resetting delayed development/null/redis-test deploy 58fe1e4dde3578134a00000e


D, [2017-04-24T18:49:02.078138 #4926] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e4dde3578134a00000e
I, [2017-04-24T18:49:02.082834 #4926]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e4dde3578134a00000e because there is another deploy in progress

D, [2017-04-24T18:49:02.102754 #4938] DEBUG -- GridServiceSchedulerWorker: resetting delayed development/null/redis-test deploy 58fe1e4fde3578134a000010
D, [2017-04-24T18:49:02.213095 #4926] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e4fde3578134a000010
I, [2017-04-24T18:49:02.222175 #4926]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e4fde3578134a000010 because there is another deploy in progress

D, [2017-04-24T18:49:02.594388 #4938] DEBUG -- GridServiceSchedulerWorker: resetting delayed development/null/redis-test deploy 58fe1e50de3578133e000020
D, [2017-04-24T18:49:02.736743 #4938] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e50de3578133e000020
I, [2017-04-24T18:49:02.751486 #4938]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e50de3578133e000020 because there is another deploy in progress


D, [2017-04-24T18:49:04.015661 #4930] DEBUG -- GridServiceSchedulerWorker: resetting delayed development/null/redis-test deploy 58fe1e51de3578134600000b
D, [2017-04-24T18:49:04.048191 #4938] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe1e51de3578134600000b
I, [2017-04-24T18:49:04.058481 #4938]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe1e51de3578134600000b because there is another deploy in progress
```

### LINKED ISSUE #2213: Queued deploys time out after 10s if another deploy is running, leaving them stuck
After fetching a `GridServiceDeploy` and marking it as `started_at`, the `GridServiceSchedulerWorker` will attempt to take a `DistributedLock` for the `GridService` being deployed, using a 10s timeout. If the running service deploy takes more than 10s to complete, then this attempt to acquire the `check_deploy_queue` lock will time out: `WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available`

When the `with_dlock` times out, it just returns `false`, which the `GridServiceSchedulerWorker` ignores. The `GridServiceDeploy` is left as `started_at`, which blocks any further service deploys. This results in a similar condition to #2212, leaving further service deploys stuck in Kontena 1.2.

---

A service deploy is created, and a `GridServiceSchedulerWorker` starts running it:
```
127.0.0.1 - - [24/Apr/2017:19:05:53 +0300] "POST /v1/services/development/null/redis-test/scale HTTP/1.1" 200 226 0.0805
D, [2017-04-24T19:05:53.425954 #4926] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe2261de357813420000d5
I, [2017-04-24T19:05:53.433840 #4926]  INFO -- GridServiceDeployer: starting to deploy development/null/redis-test
I, [2017-04-24T19:05:53.476093 #4926]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T19:05:53.477917 #4926]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-1 to node core-01 at 2017-04-24 16:05:53 UTC...
D, [2017-04-24T19:05:54.010544 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 1.0s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:05:54.514023 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 1.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:05:55.519056 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 2.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
```

A second deploy is created, and a different `GridServiceSchedulerWorker` attempts to run it, but is blocked on the `check_deploy_queue` lock for that service:

```
127.0.0.1 - - [24/Apr/2017:19:05:56 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.0800
D, [2017-04-24T19:05:56.251923 #4926] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe2264de357813420000d8
D, [2017-04-24T19:05:56.806243 #4926] DEBUG -- Module: waiting 0.6s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
D, [2017-04-24T19:05:57.295298 #4926] DEBUG -- Module: waiting 1.1s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
```

The running deployment takes a long time:

```
D, [2017-04-24T19:05:57.528778 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 4.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:05:58.271217 #4926] DEBUG -- Module: waiting 2.1s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
D, [2017-04-24T19:06:00.305105 #4926] DEBUG -- Module: waiting 4.1s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
D, [2017-04-24T19:06:01.556559 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 8.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
I, [2017-04-24T19:06:02.558875 #4926]  INFO -- GridServiceInstanceDeployer: waited 9.1s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 16:05:53 UTC yielded GridServiceInstance
I, [2017-04-24T19:06:02.674449 #4926]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T19:06:02.675523 #4926]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-2 to node core-01 at 2017-04-24 16:05:53 UTC...
D, [2017-04-24T19:06:03.195340 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 1.0s of 300.0s until: service development/null/redis-test-2 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:06:03.696491 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 1.5s of 300.0s until: service development/null/redis-test-2 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:06:04.286509 #4926] DEBUG -- Module: waiting 8.1s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
D, [2017-04-24T19:06:04.701831 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 2.5s of 300.0s until: service development/null/redis-test-2 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
```

So the second `GridServiceSchedulerWorker` times out on the `check_deploy_queue` lock:

```
W, [2017-04-24T19:06:06.271178 #4926]  WARN -- Module: timeout after waiting 10.0s of 10.0s until: lock check_deploy_queue:58fe0e85de35780697000018 is available
```

Even after the initial deploy completes:

```
I, [2017-04-24T19:06:08.726884 #4926]  INFO -- GridServiceInstanceDeployer: waited 6.0s of 300.0s until: service development/null/redis-test-2 is running on node development/core-01 at 2017-04-24 16:05:53 UTC yielded GridServiceInstance
I, [2017-04-24T19:06:08.846101 #4926]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T19:06:08.847242 #4926]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-3 to node core-01 at 2017-04-24 16:05:53 UTC...
D, [2017-04-24T19:06:09.395863 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 1.0s of 300.0s until: service development/null/redis-test-3 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:06:09.898300 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 1.5s of 300.0s until: service development/null/redis-test-3 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:06:10.904114 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 2.5s of 300.0s until: service development/null/redis-test-3 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
D, [2017-04-24T19:06:12.922195 #4926] DEBUG -- GridServiceInstanceDeployer: waiting 4.5s of 300.0s until: service development/null/redis-test-3 is running on node development/core-01 at 2017-04-24 16:05:53 UTC
I, [2017-04-24T19:06:14.928497 #4926]  INFO -- GridServiceInstanceDeployer: waited 6.0s of 300.0s until: service development/null/redis-test-3 is running on node development/core-01 at 2017-04-24 16:05:53 UTC yielded GridServiceInstance
I, [2017-04-24T19:06:15.032867 #4926]  INFO -- GridServiceDeployer: service development/null/redis-test has been deployed
```

Further deployments for the service are blocked on the timed-out `GridServiceDeploy`, that remains marked as `started_at`:

```
D, [2017-04-24T19:06:21.331403 #4926] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe227dde3578133e000035
I, [2017-04-24T19:06:21.349277 #4926]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe227dde3578133e000035 because there is another deploy in progress
127.0.0.1 - - [24/Apr/2017:19:06:21 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 226 0.1190
```

### LINKED ISSUE #2214: Stopping service does not abort running deploy
If the server is running a `GridServiceDeployer`, it polls `self.grid_service.reload.deploying?` before each instance to abort. Before Kontena 1.2, this would check the `GridService.state`, and thus, a `kontena service stop` would abort any running deploy.

However, with Kontena 1.2, `GridService#deploying?` no longer checks the `GridService.state`, so a running deploy for a `stopped` service will continue until all instances have been deployed.

The `GridServices::Stop` will mark any already-deployed `GridServiceInstances` as `desired_state = stopped`, but the ongoing `GridServiceDeployer` will update any remaining `GridServiceInstance`s to `desired_state = running` as part of the deployment.

### LINKED ISSUE #2215: Server GridServiceDeployer can run for longer than 5-10 minutes, allowing further deploys to run simultaneously
The server `GridServiceDeployer` does not impose any total timeout on a complete service deploy operation. Only the `GridServiceInstanceDeployer` imposes a per-instance timeout. For a service with a large number of instances (30) that all take a long time to deploy (`sleep 30` in the agent `ServicePods::Creator`), this means that a `GridServiceDeployer` operation can run for longer than 5-10 minutes.

Sometime after 5-10 minutes, the server `DistributedLockCleanupJob` will run, and release the `check_deploy_queue` dlock used by the `GridServiceSchedulerWorker`. This allows a second service deploy to be started, but before running the `GridServiceDeployer`, it will check `GridService.deploying?`. However, this ignores sufficiently old deploys which are not `:created_at.gt => 10.minutes.ago`.

So once the second deploy bounces in `delaying development/null/redis-test deploy because there is another deploy in progress` for a further 0-5 minutes, the server allows a second `GridServiceDeployer` to start running.

---

```
127.0.0.1 - - [24/Apr/2017:20:07:53 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 227 0.0853
D, [2017-04-24T20:07:54.022492 #7754] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe30e9de35781fa2000078
I, [2017-04-24T20:07:54.029937 #7754]  INFO -- GridServiceDeployer: starting to deploy development/null/redis-test
I, [2017-04-24T20:07:54.333233 #7754]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T20:07:54.334204 #7754]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-1 to node core-01 at 2017-04-24 17:07:54 UTC...
D, [2017-04-24T20:07:54.864175 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 1.0s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 17:07:54 UTC
...
D, [2017-04-24T20:15:46.232953 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 16.6s of 300.0s until: service development/null/redis-test-15 is running on node development/core-01 at 2017-04-24 17:07:54 UTC
```

At this point, the `DistributedLockCleanupJob` releases the `check_deploy_queue` lock for the service, and a second deploy can start queueing up:

```
127.0.0.1 - - [24/Apr/2017:20:15:55 +0300] "POST /v1/services/development/null/redis-test/deploy HTTP/1.1" 200 227 0.0837
D, [2017-04-24T20:15:55.812856 #7754] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe32cbde35781e4a000050
I, [2017-04-24T20:15:55.840556 #7754]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe32cbde35781e4a000050 because there is another deploy in progress
...
I, [2017-04-24T20:16:02.448180 #7754]  INFO -- GridServiceInstanceDeployer: waited 32.3s of 300.0s until: service development/null/redis-test-15 is running on node development/core-01 at 2017-04-24 17:07:54 UTC yielded GridServiceInstance
...
D, [2017-04-24T20:17:24.117799 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 16.7s of 300.0s until: service development/null/redis-test-18 is running on node development/core-01 at 2017-04-24 17:07:54 UTC
...
D, [2017-04-24T20:17:26.087830 #7754] DEBUG -- GridServiceSchedulerWorker: resetting delayed development/null/redis-test deploy 58fe32cbde35781e4a000050
D, [2017-04-24T20:17:26.225411 #7767] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe32cbde35781e4a000050
I, [2017-04-24T20:17:26.232540 #7767]  INFO -- GridServiceSchedulerWorker: delaying development/null/redis-test deploy 58fe32cbde35781e4a000050 because there is another deploy in progress
...
D, [2017-04-24T20:17:48.396582 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 8.5s of 300.0s until: service development/null/redis-test-19 is running on node development/core-01 at 2017-04-24 17:07:54 UTC
```

Until the initial running deploy has been queued+running for more than 10 minutes, at which point the second deploy can start running.

```
D, [2017-04-24T20:17:56.233453 #7767] DEBUG -- GridServiceSchedulerWorker: resetting delayed development/null/redis-test deploy 58fe32cbde35781e4a000050
D, [2017-04-24T20:17:56.341311 #7767] DEBUG -- GridServiceSchedulerWorker: checking development/null/redis-test deploy 58fe32cbde35781e4a000050
I, [2017-04-24T20:17:56.351941 #7767]  INFO -- GridServiceDeployer: starting to deploy development/null/redis-test
```

Now both deployments for the same service are running..

```
D, [2017-04-24T20:17:56.436207 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 16.6s of 300.0s until: service development/null/redis-test-19 is running on node development/core-01 at 2017-04-24 17:07:54 UTC

I, [2017-04-24T20:17:56.725043 #7767]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-1 to node core-01 at 2017-04-24 17:17:56 UTC...
D, [2017-04-24T20:17:57.242256 #7767] DEBUG -- GridServiceInstanceDeployer: waiting 1.0s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 17:17:56 UTC

I, [2017-04-24T20:18:03.267631 #7767]  INFO -- GridServiceInstanceDeployer: waited 6.5s of 300.0s until: service development/null/redis-test-1 is running on node development/core-01 at 2017-04-24 17:17:56 UTC yielded GridServiceInstance
I, [2017-04-24T20:18:03.420258 #7767]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T20:18:03.420641 #7767]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-2 to node core-01 at 2017-04-24 17:17:56 UTC...
...
D, [2017-04-24T20:18:12.230454 #7767] DEBUG -- GridServiceInstanceDeployer: waiting 2.5s of 300.0s until: service development/null/redis-test-6 is running on node development/core-01 at 2017-04-24 17:17:56 UTC
D, [2017-04-24T20:18:12.505146 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 32.6s of 300.0s until: service development/null/redis-test-19 is running on node development/core-01 at 2017-04-24 17:07:54 UTC
I, [2017-04-24T20:18:13.006581 #7754]  INFO -- GridServiceInstanceDeployer: waited 32.6s of 300.0s until: service development/null/redis-test-19 is running on node development/core-01 at 2017-04-24 17:07:54 UTC yielded GridServiceInstance
```

In this case, the second deploy catches up much faster, since it's not re-creating the containers, and hitting the `sleep 30` in the agent:

```

I, [2017-04-24T20:18:50.202529 #7754]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-21 to node core-01 at 2017-04-24 17:07:54 UTC...

I, [2017-04-24T20:18:51.017917 #7767]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-21 to node core-01 at 2017-04-24 17:17:56 UTC...

I, [2017-04-24T20:19:23.431711 #7754]  INFO -- GridServiceInstanceDeployer: waited 33.2s of 300.0s until: service development/null/redis-test-21 is running on node development/core-01 at 2017-04-24 17:07:54 UTC yielded GridServiceInstance
I, [2017-04-24T20:19:23.561253 #7754]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T20:19:23.563024 #7754]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-22 to node core-01 at 2017-04-24 17:07:54 UTC...

I, [2017-04-24T20:19:23.749446 #7767]  INFO -- GridServiceInstanceDeployer: waited 32.6s of 300.0s until: service development/null/redis-test-21 is running on node development/core-01 at 2017-04-24 17:17:56 UTC yielded GridServiceInstance
D, [2017-04-24T20:19:23.821072 #8098] DEBUG -- TokenAuthentication: Access token found
I, [2017-04-24T20:19:23.994828 #7767]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T20:19:23.995568 #7767]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-22 to node core-01 at 2017-04-24 17:17:56 UTC...
```

Eventually they seem to race somehow, and one of them [fails](https://github.com/kontena/kontena/blob/v1.2.0/server/app/services/grid_service_instance_deployer.rb#L116):

```
D, [2017-04-24T20:20:29.144586 #7754] DEBUG -- GridServiceInstanceDeployer: waiting 32.7s of 300.0s until: service development/null/redis-test-23 is running on node development/core-01 at 2017-04-24 17:07:54 UTC
D, [2017-04-24T20:20:29.185243 #7767] DEBUG -- GridServiceInstanceDeployer: waiting 32.7s of 300.0s until: service development/null/redis-test-23 is running on node development/core-01 at 2017-04-24 17:17:56 UTC
I, [2017-04-24T20:20:29.645509 #7754]  INFO -- GridServiceInstanceDeployer: waited 32.7s of 300.0s until: service development/null/redis-test-23 is running on node development/core-01 at 2017-04-24 17:07:54 UTC yielded GridServiceInstance
W, [2017-04-24T20:20:29.645741 #7754]  WARN -- GridServiceInstanceDeployer: Failed to deploy service instance development/null/redis-test-23 to node core-01: GridServiceInstanceDeployer::StateError: Service instance was re-deployed
/home/kontena/kontena/kontena/server/app/services/grid_service_instance_deployer.rb:116:in `deploy_service_instance'
/home/kontena/kontena/kontena/server/app/services/grid_service_instance_deployer.rb:58:in `ensure_service_instance'
/home/kontena/kontena/kontena/server/app/services/grid_service_instance_deployer.rb:29:in `deploy'
/home/kontena/kontena/kontena/server/app/services/grid_service_deployer.rb:113:in `block in deploy_service_instance'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
E, [2017-04-24T20:20:29.652484 #7754] ERROR -- GridServiceDeployer: halting deploy of development/null/redis-test, one or more instances failed
I, [2017-04-24T20:20:29.686425 #7767]  INFO -- GridServiceInstanceDeployer: waited 32.7s of 300.0s until: service development/null/redis-test-23 is running on node development/core-01 at 2017-04-24 17:17:56 UTC yielded GridServiceInstance
I, [2017-04-24T20:20:29.819685 #7767]  INFO -- GridServiceDeployer: throttling service instance development/null/redis-test deploy because of min_health limit (1 instances in-progress)
I, [2017-04-24T20:20:29.820574 #7767]  INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-test-24 to node core-01 at 2017-04-24 17:17:56 UTC...
```

and the other eventually completes:

```
I, [2017-04-24T20:24:23.721635 #7767]  INFO -- GridServiceInstanceDeployer: waited 33.2s of 300.0s until: service development/null/redis-test-30 is running on node development/core-01 at 2017-04-24 17:17:56 UTC yielded GridServiceInstance
I, [2017-04-24T20:24:23.827351 #7767]  INFO -- GridServiceDeployer: service development/null/redis-test has been deployed
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2208 Server: GridServiceHealthMonitorJob can pile up deployments
Fixes #2212 Service deploys can get stuck if there are several queued deploys when a service finishes deploying
Fixes #2213 Queued deploys time out after 10s if another deploy is running, leaving them stuck
Fixes #2214 Stopping service does not abort running deploy
Fixes #2215 Server GridServiceDeployer can run for longer than 5-10 minutes, allowing further deploys to run simultaneously 

This introduces a new `queued_at` timestamp for `GridServiceDeploy`s. The `GridServiceSchedulerWorker` picks up `created` deploys that do not yet have any `queued_at` set, and atomically sets their `queued_at` timestamp. While holding the `check_deploy_queue` dlock, the worker then checks if the service is `deploy_running?` (has deploys with `started_at` set but not `finished_at`). If the there are no running deploys, then the worker sets `started_at` and releases the dlock. This prevents other deploys from being started while the worker proceeds to run the `GridServiceDeployer`, which sets the state to `ongoing`. Once the `GridServiceDeployer` is done, it sets `finished_at`, and the deploy is complete in either the `success` or `error` state.

In the case of multiple pending deploys for the same service, the pending deploys simply remain queued up with their `queued_at` timestamp set, but not having any `started_at` timestamp set. These queued deploys will get picked up again once their `queued_at` timestamp is more than 30s in the past, if they are still not `started_at`. This also works in the case of dlock timeouts or server crashes, allowing the queued deploy to be retried. The 30s re-queueing interval must be long enough to ensure that any failed attempts at acquiring the dlock have timed out.

The `ServiceDeployQueuedAt` migration will set the `queued_at` timestamp for any existing deploys, causing them to be ignored by the new `GridServiceSchedulerWorker`, provided that they have a `started_at` set. This takes care of existing deploys that have been left in the `created` state with `started_at` set, which can currently be caused by dlock timeouts (see #2213) or the earlier queueing logic if the server was stopped before the `after(30) { ... }` task was run. These should be much less frequent with the changes in this PR, since any `queued_at` deploys will be picked up again after 30s. The migration should also behave correctly in the case of any pending deployments when the server was shut down: they will be run 30s after the migration happens, because they have not yet been marked as `started_at` :)

The `GridService` `deploying?` state has been simplified to be a combination of `deploy_pending? || deploy_running?`, which is based on the `started_at` and `finished_at` timestamps. When deploys are created in the `created` state, the service will be `deploy_pending?` if those deploys have not yet been `started_at`. Once a deploy is `started_at`, the service will be `deploy_running?` as it enters the `ongoing` state. Once all pending deploys have been `started_at`, and those running deploys have `finished_at`, the service will no longer be `deploying?`:

* `deploy_pending? == !started && !finished`
* `deploy_running? == started && !finished`
* `deploying? == (deploy_pending? || deploy_running?) == !finished`

Deployments can now also be cancelled by the `GridServiceSchedulerWorker` by calling  `GridServiceDeploy#abort!`: it will leave the `GridServiceDeploy` in whatever state it is, but mark it as `finished`, and thus it will no longer be `pending`, or elegible for `queued`. Each `GridServiceDeploy` now also has a `TIMEOUT = 30.minutes`, if the `started_at` of a `running` deploy is over the timeout, the it is no longer `running`. For such an aborted or timed-out deploy, any running `GridSerivceDeployer` will now notice that the deploy is no longer `running`, and stop before deploying any more instances, and put the `GridServiceDeploy` into an `error` state.

* Change the `GridService.deploy_outstanding?` used by `GridServiceHealthMonitorJob` to just `GridService.deploying?`
* Fix the `GridServiceDeployer` to stop if the `GridService` is stopped, or if the `GridServiceDeploy` is `!running?` 
* Fix the `GridServiceSchedulerWorker` to just create deploys for dependent services, and allow them to run via the normal queueing/locking mechanisms, instead of running them directly

    This has the effect of now running dependent service deploys in parallel, as opposed to an arbitrary sequential order.

## TODO 

* Figure out how the `GridServiceDeploy#abort!` should behave...

    How should the `StackDeployWorker` or CLI behave as regards aborted deploys in the various states? The the `abort` reason message will not be shown unless the `GridServiceDeploy` enters the `error` state before the CLI notices the `finished_at`.

### CODE REVIEW

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 1]
```diff
@@ -9,58 +9,67 @@ def initialize(autostart = true)
...
     end
   end
 
+  # Mark created/queued deploys as queued, and return for processing.
+  # The caller has 30s to process the returned deploy, or it will be re-fetched.
+  #
   # @return [GridServiceDeploy, NilClass]
   def fetch_deploy_item
-    GridServiceDeploy.where(started_at: nil)
+    GridServiceDeploy.any_of({:_deploy_state => :created}, {:_deploy_state => :queued, :queued_at.lt => 30.seconds.ago})
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: This needs both the `deploy_state=queued` as well as the `queued_at` in order to avoid the requirement for an `after(30) { .... }` action, which might never get run. Now the `deploy_state` will normally change to `ongoing` before the `:queued_at.lt => 30.seconds.ago` expires.

Might be able to simplify this if we used a migration to populate the the `deployed_at` for all existing deploys, and this just bumped `queued_at` if the `queued_at` was old and `started_at` was still nil?

**Comment by SpComb** [comment]
Updated to simplify the combination of states and timestamps... the `GridServiceSchedulerWorker` no longer sets any `GridServiceDeploy.deploy_state`, and instead, the service's deployment queueing/running state is entirely in the `GridServiceDeploy` timestamps.

The `GridServiceDeploy.deploy_state` is only used for the `GridServiceDeployer` progress.

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 2]
```diff
@@ -9,58 +9,59 @@ def initialize(autostart = true)
...
   end
 
   def deploy_dependant_services(grid_service)
-    grid_service.dependant_services.each do |serv|
-      info "deploying dependent service #{serv.to_path} of deployed service #{grid_service.to_path}"
-      service_deploy = GridServiceDeploy.create(
-        grid_service: serv,
-        started_at: Time.now.utc
-      )
-      self.class.new.perform(service_deploy)
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: This was weird... it bypassed the `check_deploy_queue` dlock, and there is nothing preventing this from running a deploy for a dependent service while a different deploy was queued/running for the same service?

I don't see why this can't just be run the normal way, via the worker queueing.

File: server/app/models/grid_service.rb [hunk 3]
```diff
@@ -146,8 +137,29 @@ def stack_exposed?
...
+  # Equvialent to deploy_pending? || deploy_running?
+  #
+  # @return [Boolean]
+  def deploying?
+    self.grid_service_deploys.where(:finished_at => nil).count > 0
+  end
+
+  # The service has deploys created or queued, but not yet started.
+  #
+  # XXX: an aborted deploy might be pending, even though it is finished?
```
Comment (SpComb) [inline server/app/models/grid_service.rb]: Still need to figure out how this should work.

File: server/app/services/grid_service_deployer.rb [hunk 4]
```diff
@@ -53,7 +53,12 @@ def deploy
     self.grid_service.grid_service_instances.where(:instance_number.gt => total_instances).destroy
     total_instances.times do |i|
       instance_number = i + 1
-      unless self.grid_service.reload.deploying?
+      self.grid_service_deploy.reload
+      if self.grid_service_deploy.abort?
+        raise "halting deploy of #{self.grid_service.to_path}, deploy was aborted: #{self.deploy_state.reason}"
+      end
+      self.grid_service.reload
+      unless self.grid_service.running? || self.grid_service.initialized?
```
Comment (SpComb) [inline server/app/services/grid_service_deployer.rb]: May this should just be `if self.grid_service.stopped?` - I think that's the only possible alternative state?

File: server/db/migrations/25_service_deploy_queued_at.rb [hunk 5]
```diff
@@ -0,0 +1,6 @@
+class ServiceDeployQueuedAt < Mongodb::Migration
+  def self.up
+    GridServiceDeploy.create_indexes
+    GridServiceDeploy.all.set(queued_at: Time.now.utc)
```
Comment (SpComb) [inline server/db/migrations/25_service_deploy_queued_at.rb]: This could also be something like `1970-01-01 12:00:00` or whatever.... I don't think it makes any difference, unless there is some `GridServiceDeploy` without any `started_at` set hanging around... those should always be very recent deploys, and it's okay to just run those?

**Comment by SpComb** [comment]
Merged with  #2211... the `GridService.deploying?` and `deploy_outstanding?` now do more or less the same thing... need to combine the two either way.

Also moved the `ensure` `self.grid_service_deploy.set(:finished_at => ...)` into the `GridServiceSchedulerWorker`... now all of the `GridServiceDeploy` timestamp logic is in the `GridServiceSchedulerWorker`, and all of the `deploy_state` logic is in the `GridServiceDeployer`.

**Comment by SpComb** [comment]
Improved the `GridServiceSchedulerWorker` specs, now just TODO to figure out how aborted/expired deploys should be handled

```
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:267 # GridServiceSchedulerWorker for an aborted deploy #fetch_deploy_item ignores the deploy
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:258 # GridServiceSchedulerWorker for an aborted deploy service is not deploy_pending
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:322 # GridServiceSchedulerWorker for an expired deploy with a newer created deploy #check_deploy_queue starts and returns the deploy
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:316 # GridServiceSchedulerWorker for an expired deploy with a newer created deploy service is not deploy_running
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:295 # GridServiceSchedulerWorker for an expired deploy #fetch_deploy_item ignores the deploy
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:289 # GridServiceSchedulerWorker for an expired deploy service is not deploy_running
rspec ./spec/jobs/grid_service_scheduler_worker_spec.rb:283 # GridServiceSchedulerWorker for an expired deploy service is not deploying
```

File: server/app/jobs/grid_service_scheduler_worker.rb (hunk 2 above)
Comment (jakolehm) [inline server/app/jobs/grid_service_scheduler_worker.rb]: I think it does change order of service deployments if it's pushed to queue?

Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: I was thinking about that... but it wasn't deploying the dependent services in any specific order either. Which might be a problem if those dependent services also have dependencies on eachother?

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 6]
```diff
@@ -9,58 +9,63 @@ def initialize(autostart = true)
...
 
+  # Pick up the oldest non-queued deploy, mark it as queued, and return for processing.
+  # The caller has 30s to process the returned deploy, or it can be picked up again.
+  #
+  # XXX: this can pick up an aborted deploy if it not started_at?
+  #
   # @return [GridServiceDeploy, NilClass]
   def fetch_deploy_item
-    GridServiceDeploy.where(started_at: nil)
+    GridServiceDeploy.any_of({:queued_at => nil}, {:queued_at.lt => 30.seconds.ago, :started_at => nil})
```
Comment (jakolehm) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Could we simplify this logic somehow, maybe separate cleanup for `queued_at` ?

File: server/app/jobs/grid_service_scheduler_worker.rb (hunk 2 above)
Comment (jakolehm) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Yes, but now it queues deploy and it will be deployed after other service deployments in a stack. And in worst case after deployments in other stacks (if there are many pending stacks/services)

Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Not quite sure if I understand the ordering... AFAIK previously once the `GridServiceDeployer#deploy` marked `finished_at` and returned, then the `StackDeployWorker` would notice that immediately, and enqueue further stack service deploys, even while this `GridServiceSchedulerWorker#deploy_dependent_services` started running the dependent service deploys.... so they would all run in parallel across multiple workers?

AFAICT that would be similar to what happens here, assuming more `GridServiceSchedulerWorker`s than services being deployed.

File: server/app/jobs/grid_service_scheduler_worker.rb (hunk 6 above)
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: AFAIK this works as intended, it's a single moped command using indexed fields:

```
DEBUG -- :   MOPED: 127.0.0.1:27017 COMMAND      database=kontena_development command={:findAndModify=>"grid_service_deploys", :query=>{"$or"=>[{"queued_at"=>nil}, {"queued_at"=>{"$lt"=>2017-04-27 15:16:07 UTC}, "started_at"=>nil}]}, :new=>true, :sort=>{"created_at"=>1}, :update=>{:$set=>{:queued_at=>2017-04-27 15:16:37 UTC}}} runtime: 1.3541ms
```

The significant design choice here is that it's safe against worker failure after having dequeued the deploy... the deploy will naturally be re-dequeued in time.

Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: This is probably equivalent to something like

```ruby
    GridServiceDeploy.where(:queued_at.lt => 30.seconds.ago, :started_at => nil).find_and_modify({:$set => {:queued_at => Time.now.utc}})
    GridServiceDeploy.where(:queued_at => nil)
      .asc(:created_at)
      .find_and_modify({:$set => {:queued_at => Time.now.utc}}, {new: true})
```

But I don't see how two mongo queries is better than one?

Comment (jakolehm) [inline server/app/jobs/grid_service_scheduler_worker.rb]: If those lines are in the same place then it's not better in any way. I just wonder if it would make sense to have separate method for cleaning that gets called in the loop and then this method can just focus on items which `queued_at` is `nil`?

Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: If we introduce some cleanup for `:started_at.lt => X.minutes.go, :finished_at => nil`, then yes, it could make sense to also "release" the `queued_at` separately in a similar way. It's more moving parts, though, this operation is effectively a very succinct implementation of "give me a 30s lease on that".

File: server/app/jobs/grid_service_scheduler_worker.rb (hunk 2 above)
Comment (jakolehm) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Ok, maybe you are right. This needs a bit actual testing to fully understand the effects of this change.

Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Agreed, I don't really understand how complex cases with ordered + dependent services would behave prior to or even with this change... but I think the difference in behavior can't be too big, because:

* There is no defined order for the `grid_service.dependant_services`
* There are always multiple `GridServiceSchedulerWorker`s that will run queued deploys in parallel

So the major difference is that the dependent services will now be deployed in an arbitrary parallel order, as opposed to an arbitrary (?) sequential order.

File: server/app/jobs/grid_service_scheduler_worker.rb (hunk 6 above)
Comment (jakolehm) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Yeah, and this is not a blocker in any way.. just sharing my thoughts. And this can be refactored later if we see need for splitting up the logic.

**Comment by SpComb** [comment]
Tweaked the `GridServiceDeploy` states a bit...

* `pending? => !started && !finished`
* `running? => started && !finished`
* `started && finished => done?`
* `!started && finished => aborted?`

**Comment by SpComb** [comment]
Updated to concentrate all of the `GridServiceDeploy` state logic into the `GridServiceDeploy` model, using `GridServiceDeploy.deploying`, `GridServiceDeploy.pending`, and `GridServiceDeploy.running` scopes for the `GridService.deploying?`, `GridService.deploy_pending?`, `GridService.deploy_running?` queries.

The `GridServiceDeploy` now enforces a 30 minute timeout on the `deploying?` and `deploy_running` states. This now also causes the `GridServiceDeployer` to fail after the 30-minute timeout, as the `GridServiceDeploy` will no longer be running, fixing #2215.

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 7]
```diff
@@ -9,58 +9,61 @@ def initialize(autostart = true)
...
     end
   end
 
+  # Pick up the oldest non-queued deploy, mark it as queued, and return for processing.
+  # The caller has 30s to process the returned deploy, or it can be picked up again.
+  #
   # @return [GridServiceDeploy, NilClass]
   def fetch_deploy_item
-    GridServiceDeploy.where(started_at: nil)
+    GridServiceDeploy.any_of({:queued_at => nil}, {:queued_at.lt => 30.seconds.ago, :started_at => nil, :finished_at => nil})
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Thinking of making this `GridServiceDeploy.pending.any_of({:queued_at => nil}, {:queued_at.lt => 30.seconds.ago})` - it should be the same, and perhaps more readable?

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 8]
```diff
@@ -9,58 +9,69 @@ def initialize(autostart = true)
...
 
+  # Fetch deploy from queue, and return it if it should be run
+  #
+  # @return [GridServiceDeploy, nil] deploy to run
   def check_deploy_queue
     service_deploy = fetch_deploy_item
-    return unless service_deploy
+    return nil unless service_deploy
+
+    fail "deploy not pending" unless service_deploy.pending?
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: This should be impossible, but if it did happen, it it would result in finished deploy being re-run...

* broken migration that didn't set `queued_at`
* invalid spec cases

**Comment by SpComb** [comment]
Two flaky specs that this might also fix?

```
  1) GridServiceSchedulerWorker#check_deploy_queue picks oldest item from deploy queue

     Failure/Error: expect(newest.reload.started_at).to be_nil
       expected: nil
            got: Wed, 26 Apr 2017 13:40:07 +0000

     # ./spec/jobs/grid_service_scheduler_worker_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:88:in `block (2 levels) in <top (required)>'
```

```
  2) GridServices::Scale#run sets state to deploy_pending
     Failure/Error: expect {
       expected result to have changed from false to true, but did not change

     # ./spec/mutations/grid_services/scale_spec.rb:35:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:88:in `block (2 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
I just noticed that the server `GridScheduler` also has its own implementations of `pending_deploys?`, `active_deploys?` and `active_deploys_within_stack?`. Perhaps those should also be changed to use `service.deploy_pending?`?

File: server/app/services/grid_scheduler.rb [hunk 9]
```diff
@@ -66,18 +65,6 @@ def should_reschedule_service?(service)
 
   # @param [GridService] service
   # @return [Boolean]
-  def pending_deploys?(service)
-    service.grid_service_deploys.where(started_at: nil).count > 0
```
Comment (SpComb) [inline server/app/services/grid_scheduler.rb]: With the changes to set `queued_at` instead of `started_at` (which might now remain unset if the service was stopped before the deploy started), this could have left the service in a state where it would never get rescheduled anymore.

File: server/app/services/grid_scheduler.rb [hunk 10]
```diff
@@ -66,18 +65,6 @@ def should_reschedule_service?(service)
...
-  end
-
-  # @param [GridService] service
-  # @return [Boolean]
-  def active_deploys?(service)
-    service.grid_service_deploys.where(:started_at.gt => 30.minutes.ago, :deploy_state.in => [:created, :ongoing]).count > 0
```
Comment (SpComb) [inline server/app/services/grid_scheduler.rb]: This seems mostly equivalent to what `GridSevice.deploying?` now does, except that `:finished_at => nil` is now required for the case of aborted deploys for non-running services.
