### PR TITLE
e2e: Fix hanging upgrade specs

### LINKED ISSUE #2879: e2e stack ugprade specs fail on the new confirm prompts
```
  8) stack upgrade from file prompts if the stack is different
     Failure/Error: expect(k.out).to match /Replacing stack.*Are you sure\?.*Aborted command/m
     
       expected "    *   Reading stack \e[36mredis\e[0m from master .. \\\r                                          ...ng this command with --force option. Are you sure? \e[36mno\e[0m\r\n\e[31mAborted command.\e[0m\r\n" to match /Replacing stack.*Are you sure\?.*Aborted command/m
       Diff:
       @@ -1,2 +1,22 @@
       -/Replacing stack.*Are you sure\?.*Aborted command/m
 [done] Reading stack redis from master     ter .. \
 [done] Parsing different.yml     yml .. \
 [done] Analyzing upgrade     
       +SERVICES:
       +----------------------------------------
       +These services will be upgraded:
       +- redis/redis
       +
       +STACKS:
       +----------------------------------------
       +These stacks will be replaced by other stacks:
       +- redis from test/redis to test/notredis
       +
       +These stacks will be upgraded and deployed:
       +- redis
       +
       +
       +Warning: This can not be undone, data will be lost.
> Destructive command. You can skip this prompt by running this command with --force option. Are you sure? no
       +Aborted command.
       
     # ./spec/features/stack/upgrade_spec.rb:39:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/upgrade_spec.rb:32:in `block (3 levels) in <top (required)>'

  9) stack upgrade for a stack that is linked to externally fails to upgrade if linked
     Failure/Error: expect(k.out).to match /Cannot delete service that is linked to another service/
     
       expected "    *   Reading stack \e[36mlinks-external-linked\e[0m from master .. \\\r                          ...u can skip this prompt by running this command with --force option. Are you sure? \e[37m(Y/n)\e[0m " to match /Cannot delete service that is linked to another service/
       Diff:
       @@ -1,2 +1,20 @@
       -/Cannot delete service that is linked to another service/
 [done] Reading stack links-external-linked from master     ter .. \
 [done] Parsing external-linked_2.yml     yml .. \
 [done] Analyzing upgrade     
       +SERVICES:
       +----------------------------------------
       +These services will be removed from master:
       + - links-external-linked/bar
       +
       +These services will be upgraded:
       +- links-external-linked/foo
       +
       +STACKS:
       +----------------------------------------
       +These stacks will be upgraded:
       +- links-external-linked
       +
       +
       +Warning: This can not be undone, data will be lost.
       +> Destructive command. You can skip this prompt by running this command with --force option. Are you sure? (Y/n) 
       
     # ./spec/features/stack/upgrade_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/upgrade_spec.rb:61:in `block (3 levels) in <top (required)>'

  10) stack upgrade for a stack that is linked to externally fails to deploy if linked
      Failure/Error: expect(k.code).to eq(0), k.out
      
 [done] Reading stack links-external-linked from master     ter .. \
 [done] Parsing external-linked_2.yml     yml .. \
 [done] Analyzing upgrade     
        SERVICES:
        ----------------------------------------
        These services will be removed from master:
         - links-external-linked/bar
        
        These services will be upgraded:
        - links-external-linked/foo
        
        STACKS:
        ----------------------------------------
        These stacks will be upgraded:
        - links-external-linked
        
        
        Warning: This can not be undone, data will be lost.
        > Destructive command. You can skip this prompt by running this command with --force option. Are you sure? (Y/n) 
      # ./spec/features/stack/upgrade_spec.rb:71:in `block (4 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/upgrade_spec.rb:69:in `block (3 levels) in <top (required)>'
```

```
rspec ./spec/features/stack/upgrade_spec.rb:31 # stack upgrade from file prompts if the stack is different
rspec ./spec/features/stack/upgrade_spec.rb:57 # stack upgrade for a stack that is linked to externally fails to upgrade if linked
rspec ./spec/features/stack/upgrade_spec.rb:68 # stack upgrade for a stack that is linked to externally fails to deploy if linked
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #2879

### CODE REVIEW

File: test/spec/features/stack/upgrade_spec.rb [hunk 1]
```diff
@@ -3,14 +3,16 @@
 describe 'stack upgrade' do
   context 'from file' do
     before(:each) do
+      run 'kontena stack rm --force redis'
+      run 'kontena stack rm --force links-external-linked'
       with_fixture_dir("stack/upgrade") do
-        k = run 'kontena stack install version1.yml'
-        expect(k.code).to eq(0)
+        run 'kontena stack install version1.yml'
```
Comment (SpComb) [inline test/spec/features/stack/upgrade_spec.rb]: No more `k.code` exit code check? TBH these really really need some kind of `run!` that raises on non-zero exit codes, the explicit checks are terrible...

Comment (kke) [reply test/spec/features/stack/upgrade_spec.rb]: It was a pain to figure out why the thing was saying:

```
expected 0 got 1
```

when my spec clearly said: `expect(k.code).to eq 1`, but it was the before block expectation that failed
