### PR TITLE
Fix missing server Rpc::GridSerializer fields

### LINKED ISSUE #2012: #1873 server Rpc::GridSerializer is missing stats, logs fields
These are needed by the agent `StatsWorker` and `FluentdWorker`

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2012

### CODE REVIEW

File: server/spec/services/agent/node_plugger_spec.rb [hunk 1]
```diff
@@ -1,31 +1,74 @@
...
+          id: 'test-grid',
+          name: 'test-grid',
+          stats: { statsd: nil },
+          logs: nil,
+        ),
+      ))
+      subject.send_node_info
+    end
+
+    context "for a grid with stats and logs" do
```
Comment (jakolehm) [inline server/spec/services/agent/node_plugger_spec.rb]: I think it would be better to move these tests to Rpc::GridSerializer spec, like this: https://gist.github.com/jakolehm/7516eab27dfcf69de2545770135cf39c

Comment (SpComb) [inline server/spec/services/agent/node_plugger_spec.rb]: Improved the RPC serializer specs.
