### PR TITLE
Fix migration timeout issues

### LINKED ISSUE #2120: Re-creating indexes in migrations may timeout puma worker boot
And this leaves stale distributed lock to mongo. Probably we should spawn these index creations to background and handle stale locks somehow (if migration happens to fail).

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2120

### CODE REVIEW

File: server/app/services/mongodb/migrator.rb [hunk 1]
```diff
@@ -64,17 +67,27 @@ def migrations
...
     def migrate
       ensure_indexes
-      with_dlock('mongodb_migrate', 60) do
+      release_stale_lock
+      with_dlock(LOCK_NAME, LOCK_TIMEOUT) do
         migrate_without_lock
       end
     end
 
+    def release_stale_lock
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Should this be some `DistributedLock.cleanup` method, with specs?

File: server/db/migrations/19_add_indexes_to_container_log.rb [hunk 2]
```diff
@@ -1,5 +1,5 @@
 class AddIndexesToContainerLog < Mongodb::Migration
   def self.up
-    ContainerLog.create_indexes
+    Thread.new { ContainerLog.create_indexes } # might take a long time
```
Comment (SpComb) [inline server/db/migrations/19_add_indexes_to_container_log.rb]: The `Thread.new { ... }` silently hides any exceptions... I'd have suggested a `Celluloid::Future`, but it also does that :/

File: server/app/services/mongodb/migrator.rb (hunk 1 above)
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Or better yet... drop the entire "cleanup" thing, and replace it with something like

```ruby
with_dlock('mongodb_migrate', timeout: 60, expires: 3 * 60) do
    ...
end
```

Advantage: the lock expiry is right there in the same place where the lock is created so it's much clearer to understand how it will behave, as opposed to having the cleanup in some different place.

Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: We can deal with this in #2125 after 1.2

**Comment by SpComb** [comment]
Dropping the `ContainerLogs` indexes and re-running the 19 migration, the background index builds seem to work:

```
2017-04-10T07:35:18.084+0000 I INDEX    [conn27] build index on: kontena_development.container_logs properties: { v: 1, key: { grid_id: 1 }, name: "grid_id_1", ns: "kontena_development.container_logs", background: true }
2017-04-10T07:35:21.004+0000 I -        [conn27]   Index Build (background): 627200/3361504 18%
2017-04-10T07:35:24.004+0000 I -        [conn27]   Index Build (background): 1455500/3361504 43%
2017-04-10T07:35:27.012+0000 I -        [conn27]   Index Build (background): 1750900/3361504 52%
2017-04-10T07:35:30.004+0000 I -        [conn27]   Index Build (background): 2331000/3361504 69%
2017-04-10T07:35:33.004+0000 I -        [conn27]   Index Build (background): 2863900/3361504 85%
2017-04-10T07:35:34.740+0000 I INDEX    [conn27] build index done.  scanned 3361504 total records. 16 secs

```2017-04-10T07:35:34.742+0000 I INDEX    [conn27] build index on: kontena_development.container_logs properties: { v: 1, key: { host_node_id: 1 }, name: "host_node_id_1", ns: "kontena_development.container_logs", background: true }
2017-04-10T07:35:37.005+0000 I -        [conn27]   Index Build (background): 671700/3361504 19%
2017-04-10T07:35:40.005+0000 I -        [conn27]   Index Build (background): 1374400/3361504 40%
2017-04-10T07:35:43.097+0000 I -        [conn27]   Index Build (background): 2372700/3361504 70%
2017-04-10T07:35:45.909+0000 I INDEX    [conn27] build index done.  scanned 3361504 total records. 11 secs
...
```

The server is available and `kontena grid logs` seems to also work during the background index build.

> db.currentOp()
{
	"inprog" : [
		{
			"desc" : "conn27",
			"threadId" : "0x3c0ed80",
			"connectionId" : 27,
			"opid" : 1157,
			"active" : true,
			"secs_running" : 7,
			"microsecs_running" : NumberLong(7958582),
			"op" : "insert",
			"ns" : "kontena_development.system.indexes",
			"insert" : {
				
			},
			"client" : "172.17.0.1:56874",
			"msg" : "Index Build (background) Index Build (background): 2256731/3361504 67%",
			"progress" : {
				"done" : 2256732,
				"total" : 3361504
			},
			"numYields" : 17647,
			"locks" : {
				"Global" : "w",
				"MMAPV1Journal" : "w",
				"Database" : "w",
				"Collection" : "W"
			},
			"waitingForLock" : false,
			"lockStats" : {
				"Global" : {
					"acquireCount" : {
						"r" : NumberLong(17648),
						"w" : NumberLong(17648)
					}
				},
				"MMAPV1Journal" : {
					"acquireCount" : {
						"w" : NumberLong(2274385)
					},
					"acquireWaitCount" : {
						"w" : NumberLong(68)
					},
					"timeAcquiringMicros" : {
						"w" : NumberLong(936864)
					}
				},
				"Database" : {
					"acquireCount" : {
						"w" : NumberLong(17648),
						"W" : NumberLong(1)
					}
				},
				"Collection" : {
					"acquireCount" : {
						"W" : NumberLong(17648)
					},
					"acquireWaitCount" : {
						"W" : NumberLong(3)
					},
					"timeAcquiringMicros" : {
						"W" : NumberLong(146)
					}
				},
				"Metadata" : {
					"acquireCount" : {
						"W" : NumberLong(9)
					}
				}
			}
		},
```

**Comment by SpComb** [comment]
Without the `Thread.new { ContainerLog.create_indexes }`, puma does indeed timeout the workers during the `on_worker_boot` -> `Mongodb::Migrator.new.migrate`:

```
I, [2017-04-10T10:42:25.718919 #27980]  INFO -- Mongodb::Migrator: migrating AddIndexesToContainerLog
D, [2017-04-10T10:42:26.273141 #27984] DEBUG -- Module: waiting 0.6s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:26.273141 #27976] DEBUG -- Module: waiting 0.6s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:26.273877 #27988] DEBUG -- Module: waiting 0.6s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:26.744020 #27988] DEBUG -- Module: waiting 1.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:26.744443 #27976] DEBUG -- Module: waiting 1.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:26.796416 #27984] DEBUG -- Module: waiting 1.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:27.752565 #27988] DEBUG -- Module: waiting 2.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:27.753308 #27984] DEBUG -- Module: waiting 2.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:27.753781 #27976] DEBUG -- Module: waiting 2.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:29.725353 #27988] DEBUG -- Module: waiting 4.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:29.725353 #27976] DEBUG -- Module: waiting 4.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:29.777539 #27984] DEBUG -- Module: waiting 4.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:33.724888 #27988] DEBUG -- Module: waiting 8.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:33.725443 #27976] DEBUG -- Module: waiting 8.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:33.777985 #27984] DEBUG -- Module: waiting 8.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:41.777167 #27976] DEBUG -- Module: waiting 16.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:41.777167 #27988] DEBUG -- Module: waiting 16.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:41.777632 #27984] DEBUG -- Module: waiting 16.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:57.758375 #27988] DEBUG -- Module: waiting 32.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:57.762123 #27984] DEBUG -- Module: waiting 32.1s of 60.0s until: lock mongodb_migrate is available
D, [2017-04-10T10:42:57.763084 #27976] DEBUG -- Module: waiting 32.1s of 60.0s until: lock mongodb_migrate is available
[27973] ! Terminating timed out worker: 27976
[27973] ! Terminating timed out worker: 27980
[27973] ! Terminating timed out worker: 27984
[27973] ! Terminating timed out worker: 27988
```

This is because even a background index build will block the connection:

> Background indexing operations run in the background so that other database operations can run while creating the index. However, the mongo shell session or connection where you are creating the index will block until the index build is complete. To continue issuing commands to the database, open another connection or mongo instance.

File: server/app/services/mongodb/migrator.rb [hunk 3]
```diff
@@ -64,17 +67,27 @@ def migrations
...
+      lock = DistributedLock.where(name: LOCK_NAME).first
+      if lock && lock.created_at < (LOCK_TIMEOUT * 3).seconds.ago
+        info "releasing stale distributed lock (locked at #{lock.created_at})"
+        lock.destroy
```
Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: Isn't this racey? With four puma workers, two of them release the lock...

```
W, [2017-04-10T10:45:28.929117 #28311]  WARN -- Mongodb::Migrator: releasing stale distributed lock (locked at 2017-04-10T07:42:25+00:00)
W, [2017-04-10T10:45:28.929168 #28309]  WARN -- Mongodb::Migrator: releasing stale distributed lock (locked at 2017-04-10T07:42:25+00:00)
```

AFAIK this race could potentially wipe out the actual active migrator lock?

Comment (SpComb) [inline server/app/services/mongodb/migrator.rb]: This needs to use an atomic find-and-destroy operation... The `DistributedLockCleanupJob` uses something like this, is it atomic?

```ruby
      DistributedLock.where(created_at: {:$lt => 5.minutes.ago}).destroy
```

File: server/db/migrations/19_add_indexes_to_container_log.rb (hunk 2 above)
Comment (jakolehm) [inline server/db/migrations/19_add_indexes_to_container_log.rb]: Added `abort_on_exception`

File: server/app/services/mongodb/migrator.rb (hunk 3 above)
Comment (jakolehm) [inline server/app/services/mongodb/migrator.rb]: Fixed.

File: server/db/migrations/19_add_indexes_to_container_log.rb (hunk 2 above)
Comment (SpComb) [inline server/db/migrations/19_add_indexes_to_container_log.rb]: Hmm... where? I can't see any `abort_on_exception` :)

Comment (jakolehm) [inline server/db/migrations/19_add_indexes_to_container_log.rb]: Maybe better visibility after I actually pushed those changes.

**Comment by SpComb** [comment]
The new `DistributedLock.where(...).delete` seems to be better. Testing with `Moped.logger.level = Logger::DEBUG` shows a single `DELETE       database=kontena_development collection=distributed_locks selector={"name"=>"mongodb_migrate", "created_at"=>{"$lt"=>2017-04-10 10:29:45 UTC}} flags=[]` command. There's still some separate `count` command, not sure if that matters.

```
D, [2017-04-10T13:32:45.127328 #13608] DEBUG -- :   MOPED: 127.0.0.1:27017 INSERT       database=kontena_development collection=system.indexes documents=[{:unique=>true, :ns=>"kontena_development.distributed_locks", :key=>{:name=>1}, :name=>"name_1"}] flags=[]
D, [2017-04-10T13:32:45.127410 #13608] DEBUG -- :                          COMMAND      database=kontena_development command={:getlasterror=>1, :w=>1} runtime: 0.7518ms
D, [2017-04-10T13:32:45.128778 #13608] DEBUG -- :   MOPED: 127.0.0.1:27017 COMMAND      database=kontena_development command={:count=>"distributed_locks", :query=>{"name"=>"mongodb_migrate", "created_at"=>{"$lt"=>2017-04-10 10:29:45 UTC}}} runtime: 0.6959ms
D, [2017-04-10T13:32:45.129738 #13608] DEBUG -- :   MOPED: 127.0.0.1:27017 DELETE       database=kontena_development collection=distributed_locks selector={"name"=>"mongodb_migrate", "created_at"=>{"$lt"=>2017-04-10 10:29:45 UTC}} flags=[]
D, [2017-04-10T13:32:45.129817 #13608] DEBUG -- :                          COMMAND      database=kontena_development command={:getlasterror=>1, :w=>1} runtime: 0.6886ms
D, [2017-04-10T13:32:45.129962 #13612] DEBUG -- :   MOPED: 127.0.0.1:27017 INSERT       database=kontena_development collection=system.indexes documents=[{:unique=>true, :ns=>"kontena_development.distributed_locks", :key=>{:name=>1}, :name=>"name_1"}] flags=[]
D, [2017-04-10T13:32:45.130138 #13612] DEBUG -- :                          COMMAND      database=kontena_development command={:getlasterror=>1, :w=>1} runtime: 0.6328ms
D, [2017-04-10T13:32:45.131478 #13612] DEBUG -- :   MOPED: 127.0.0.1:27017 COMMAND      database=kontena_development command={:count=>"distributed_locks", :query=>{"name"=>"mongodb_migrate", "created_at"=>{"$lt"=>2017-04-10 10:29:45 UTC}}} runtime: 0.4949ms
D, [2017-04-10T13:32:45.131610 #13608] DEBUG -- :   MOPED: 127.0.0.1:27017 COMMAND      database=kontena_development command={:findAndModify=>"distributed_locks", :query=>{"name"=>"mongodb_migrate", "lock_id"=>{:$exists=>false}}, :upsert=>true, :new=>true, :update=>{"$set"=>{:name=>"mongodb_migrate", :lock_id=>"b1235d76417177bb18c70fa4311eaf4f", :created_at=>2017-04-10 10:32:45 UTC}}} runtime: 1.0713ms
D, [2017-04-10T13:32:45.132549 #13612] DEBUG -- :   MOPED: 127.0.0.1:27017 DELETE       database=kontena_development collection=distributed_locks selector={"name"=>"mongodb_migrate", "created_at"=>{"$lt"=>2017-04-10 10:29:45 UTC}} flags=[]
D, [2017-04-10T13:32:45.132774 #13612] DEBUG -- :                          COMMAND      database=kontena_development command={:getlasterror=>1, :w=>1} runtime: 0.5703ms
D, [2017-04-10T13:32:45.134682 #13612] DEBUG -- :   MOPED: 127.0.0.1:27017 COMMAND      database=kontena_development command={:findAndModify=>"distributed_locks", :query=>{"name"=>"mongodb_migrate", "lock_id"=>{:$exists=>false}}, :upsert=>true, :new=>true, :update=>{"$set"=>{:name=>"mongodb_migrate", :lock_id=>"e25356cc4e95579ff29bb927ad381b84", :created_at=>2017-04-10 10:32:45 UTC}}} runtime: 1.1123ms
D, [2017-04-10T13:32:45.138460 #13608] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=kontena_development collection=schema_migrations selector={"version"=>1} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.6156ms
```
