### PR TITLE
Fix CLI exec --tty for valid non-ASCII unicode input

### LINKED ISSUE #2871: CLI tty exec fails with non-ASCII input
With `kontena service exec -it`, and entering some UTF-8/non-ASCII input (high bit set):

```
DEBUG websocket exec write: {"stdin"=>"\xC3\xA4"} 
ERROR "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `encode'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:90:in `websocket_exec_write'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:109:in `block (2 levels) in websocket_exec_write_thread'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:41:in `block (2 levels) in read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:39:in `loop'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:39:in `block in read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:37:in `raw'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:37:in `read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:108:in `block in websocket_exec_write_thread'
```

The non-tty `kontena service exec -i` does handle UTF-8:

```
$ echo 'fåå' > unicode.txt
$ sha1sum unicode.txt 
8f9c3ee212dc345afa87c5aa7c3d6ccdf9511b19  unicode.txt
$ bin/kontena service exec -i redis cat < unicode.txt | sha1sum 
8f9c3ee212dc345afa87c5aa7c3d6ccdf9511b19  -
```

But it does not handle arbitrary binary input:

```
$ dd if=/dev/urandom of=random.bin bs=1k count=1
1+0 records in
1+0 records out
1024 bytes (1,0 kB, 1,0 KiB) copied, 0,00329882 s, 310 kB/s
$ sha1sum random.bin 
c0c07e2da48d871ed1f5d2d46ab5e14bb838190a  random.bin
$ bundle exec bin/kontena service exec -i redis cat < random.bin | sha1sum 
 [error] RuntimeError : stdin read JSON::GeneratorError: source sequence is illegal/malformed utf-8
         See /home/kontena/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
da39a3ee5e6b4b0d3255bfef95601890afd80709  -
```
```
DEBUG websocket exec write: {"stdin"=>"\xF9\xB4\xFA\xE1\xE9E\x81\x9B\xD8\u000F\xC9Ƿ8v\u001E3\xF4DS\u0002\u0010\xE9\xA36\xF9!\u0005\x87\xC5\u00151s\\c\xCE-w\xC3$M\u001D=o\u0016\u0010\x87\xB8%x\xE2\tL\x9D\u00194,,N\u001E\x93\xE6\u0011w?\xBC\x9A\xCCy\xAE5Gk\xC5\u001F\xD4`\xAAZ\x83>\x9D\u001A\xBDmf\x8E\x96\u0010\xF2\u0006Qx[:\n"}
ERROR source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:90:in `websocket_exec_write'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:109:in `block (2 levels) in websocket_exec_write_thread'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:47:in `read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:108:in `block in websocket_exec_write_thread'
ERROR websocket exec error: stdin read JSON::GeneratorError: source sequence is illegal/malformed utf-8
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2871

While `STDIN.gets` returns strings using ruby's `external_encoding` (UTF-8), `STDIN.raw {|io| io.readpartial(...) }` returns binary strings (encoding `ASCII-8BIT`). Encoding the input as JSON will also encode the strings to UTF-8, which fails for binary strings, even if they contain valid UTF-8: `"\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)`

Fixes the JSON encoding by assuming that all `kontena container|service exec -it` input is encoded with ruby's default external encoding (typically UTF-8). This isn't necessarily the case, but it's also similarly broken for non-tty input: `STDIN.gets` will return non-UTF8 input as strings with UTF-8 encoding.

```
$ hd test/latin1.txt 
00000000  66 e5 e5                                          |f..|
00000003
$ kontena service exec -i redis cat < test/latin1.txt 
...
DEBUG websocket exec connect... ws://localhost:9292/v1/containers/development/core-01/redis-1/exec?interactive=true
DEBUG websocket exec open
DEBUG websocket exec write: {"cmd"=>["cat"]}
DEBUG read stdin with encoding=UTF-8: "f\xE5\xE5"
DEBUG websocket exec write: {"stdin"=>"f\xE5\xE5"}
ERROR partial character in source, but hit end (JSON::GeneratorError)
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:97:in `websocket_exec_write'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:117:in `block (2 levels) in websocket_exec_write_thread'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:54:in `read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:115:in `block in websocket_exec_write_thread'
```

This will still fail if the input is not actually valid UTF-8, or if the `io.readpartial(1024)` chunk boundary splits a valid UTF-8 character. However, I don't think we can actually fix that case without changing the websocket protocol to either use binary frames with some non-JSON protocol, or use something like base64-encoded strings in JSON. Alternatively, the CLI could buffer up input one byte at a time until it gets a complete UTF-8 character.

### CODE REVIEW

**Comment by SpComb** [comment]
The ruby `Encoding.default_external` depends on the `LANG`, so `LANG=C.UTF-8` will work, but `LANG=C` will fail. This is expected... you need to have a UTF-8 locale to use non-ASCII text.

```
DEBUG websocket exec stdin with encoding=US-ASCII: "echo f\xC3\xA4\xC3\xA4\n"
DEBUG websocket exec write: {"stdin"=>"echo f\xC3\xA4\xC3\xA4\n"}
ERROR "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `encode'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:97:in `websocket_exec_write'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:117:in `block (2 levels) in websocket_exec_write_thread'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:54:in `read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:115:in `block in websocket_exec_write_thread'
```

**Comment by SpComb** [comment]
e2e specs seem to work with unicode chars in the kommando command/input:

```
service exec
  runs a command inside a service
  exits with error if command fails
  exits with command error
  returns an error if command not found
  --tty
    runs a command inside a service
    runs a command with tty control input
    runs a command with non-ascii input
  --interactive
    runs a command with piped stdin
    runs a command with piped non-ascii stdin
  with multiple instances
    runs a command inside a service on a given instances
    runs a command on every instance with --all
    fails early if running a command on every instances with --all fails
    keeps going if running a command on every instances with --all --skip

Finished in 42.62 seconds (files took 0.32429 seconds to load)
13 examples, 0 failures
```

```
service exec
 [done] Creating test-1 service      
 [done] Deploying service test-1      
⊛ Deployed instance e2e/null/test-1-1 to node localhost
  --tty
# echo fåå | LANG=C.UTF-8 rev
exit
ååf
#     runs a command with non-ascii input
  --interactive
ååf
    runs a command with piped non-ascii stdin
 [done] Removing service test-1      

Finished in 13.1 seconds (files took 0.3944 seconds to load)
2 examples, 0 failures
```

```
service exec
 [done] Creating test-1 service      
 [done] Deploying service test-1      
⊛ Deployed instance e2e/null/test-1-1 to node localhost
  --tty
# sleep 10 && echo ok
^C
# 
    runs a command with tty control input
 [done] Removing service test-1      

Finished in 10.46 seconds (files took 0.28959 seconds to load)
1 example, 0 failures
```

File: test/spec/features/service/exec_spec.rb [hunk 1]
```diff
@@ -36,22 +36,77 @@
...
+        k.out.on("#") do
+          k.in << "exit\r"
+        end
+      end
+
+      expect(k.run).to be_truthy
+      expect(k.out).to match /\u00e5\u00e5f/
+    end
+
+    # RuntimeError : stdin read JSON::GeneratorError: partial character in source, but hit end
```
Comment (SpComb) [inline test/spec/features/service/exec_spec.rb]: > This will fail if the input is not actually valid UTF-8, or if the io.readpartial(1024) chunk boundary splits a valid UTF-8 character.

Yes, easy enough to repro like this:

```

service exec
 [done] Creating test-1 service      
 [done] Deploying service test-1      
⊛ Deployed instance e2e/null/test-1-1 to node localhost
  --tty
#  [error] RuntimeError : stdin read JSON::GeneratorError: partial character in source, but hit end
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
    runs a command with UTF-8 input across block boundries (PENDING: No reason given)
 [done] Removing service test-1      

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) service exec --tty runs a command with UTF-8 input across block boundries
     # No reason given
     Failure/Error: expect(k.out).to match /^\u00e5{512}$/
     
       expected "#  [\e[31merror\e[0m] RuntimeError : stdin read JSON::GeneratorError: partial character in source, b.../kontena.log or run the command again with environment DEBUG=true set to see the full exception\r\n" to match /^\u00e5{512}$/
       Diff:
       @@ -1,2 +1,3 @@
       -/^\u00e5{512}$/
       +#  [error] RuntimeError : stdin read JSON::GeneratorError: partial character in source, but hit end
       +         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
       
     # ./spec/features/service/exec_spec.rb:93:in `block (3 levels) in <top (required)>'
```

File: test/spec/features/service/exec_spec.rb [hunk 2]
```diff
@@ -36,22 +36,77 @@
...
+    pending 'runs a command with UTF-8 input across block boundries' do
+      k = kommando("kontena service exec -it test-1 sh")
+
+      k.out.on("#") do
+        # with an odd number of bytes in the 'echo ', the 2-byte UTF-8 chars will get split across the 1024-byte chunk boundary
```
Comment (SpComb) [inline test/spec/features/service/exec_spec.rb]: > This will fail if the input is not actually valid UTF-8, or if the io.readpartial(1024) chunk boundary splits a valid UTF-8 character.

Yes, easy enough to repro like this:

```

service exec
 [done] Creating test-1 service      
 [done] Deploying service test-1      
⊛ Deployed instance e2e/null/test-1-1 to node localhost
  --tty
#  [error] RuntimeError : stdin read JSON::GeneratorError: partial character in source, but hit end
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
    runs a command with UTF-8 input across block boundries (PENDING: No reason given)
 [done] Removing service test-1      

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) service exec --tty runs a command with UTF-8 input across block boundries
     # No reason given
     Failure/Error: expect(k.out).to match /^\u00e5{512}$/
     
       expected "#  [\e[31merror\e[0m] RuntimeError : stdin read JSON::GeneratorError: partial character in source, b.../kontena.log or run the command again with environment DEBUG=true set to see the full exception\r\n" to match /^\u00e5{512}$/
       Diff:
       @@ -1,2 +1,3 @@
       -/^\u00e5{512}$/
       +#  [error] RuntimeError : stdin read JSON::GeneratorError: partial character in source, but hit end
       +         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
       
     # ./spec/features/service/exec_spec.rb:93:in `block (3 levels) in <top (required)>'
```

File: test/spec/features/service/exec_spec.rb [hunk 3]
```diff
@@ -36,22 +36,83 @@
...
+    pending 'runs a command with chunked UTF-8 input' do
+      k = kommando("kontena service exec -it test-1 sh")
+
+      k.out.on("#") do
+        data = "echo f\u00e5\u00e5\r"
+
+        # write slowly, one byte at a time
+        data.encode('UTF-8').force_encoding('ASCII-8BIT').each_char do |c|
+          k.in << c
+          sleep 0.05
```
Comment (SpComb) [inline test/spec/features/service/exec_spec.rb]: This is more realistic: if some of the UTF-8 input bytes are slower to arrive, then the CLI will fail with partial character errors.
