### PR TITLE
Fix server websocket backend to not overwrite node labels on initial connection

### LINKED ISSUE #2986: Websocket backend overwrites custom labels on first connect
If node is created with node token.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2986 using mongo `{:$addToSet => {labels: { :$each => labels } } }`

### Before (broken)
```
$ bin/kontena node create --label region=test core-02
 [done] Creating core-02 node      
$ bin/kontena node list
NAME        VERSION     STATUS       INITIAL   LABELS
⊛ core-01   1.4.0.dev   online 54s   1 / 1     region=test
⊝ core-02   -           created 5s   -         region=test
$ bin/kontena node list
NAME        VERSION     STATUS      INITIAL   LABELS
⊛ core-01   1.4.0.dev   online 1m   1 / 1     region=test
⊛ core-02   1.4.0.dev   online 3s   -         test=label
```

### After (fixed)

```
$ bin/kontena node create --label region=test core-02
 [done] Creating core-02 node      
$ bin/kontena node list
NAME        VERSION     STATUS        INITIAL   LABELS
⊛ core-01   1.4.0.dev   online 36s    1 / 1     region=test
⊝ core-02   -           created 31s   -         region=test
$ bin/kontena node list
NAME        VERSION     STATUS       INITIAL   LABELS
⊛ core-01   1.4.0.dev   online 53s   1 / 1     region=test
⊛ core-02   1.4.0.dev   online 6s    -         region=test,test=label
```

### CODE REVIEW

File: server/app/middlewares/websocket_backend.rb [hunk 1]
```diff
@@ -121,7 +121,10 @@ def find_node_by_node_token(node_id, node_token, init_attrs)
     if !node_by_id
       # atomically initialize the node_id
       created_node = HostNode.where(:id => node.id, :node_id => nil)
-        .find_one_and_update(:$set => {node_id: node_id, **init_attrs})
+        .find_one_and_update(
+          :$set => {node_id: node_id, **init_attrs},
```
Comment (jakolehm) [inline server/app/middlewares/websocket_backend.rb]: `init_attrs` seems a bit funny because it's currently just one attribute?

Comment (SpComb) [reply server/app/middlewares/websocket_backend.rb]: It's also used for `find_node_by_grid_token`, and that handles both of the attrs via just `$set`.
