### PR TITLE
Fix agent ServicePodWorker to ignore stale container events

### LINKED ISSUE #2766: Agent ServicePodWorker re-applies after any apply that triggers container events
Any Docker container actions done in `ServicePodWorker#apply` will also result `container:event` notifications. Because the `apply` function runs as an `Celluloid.exclusive { ... }` block, those notifications get queued up during the deploy, and get run once the `apply` returns:

```
D, [2017-09-05T12:50:35.514173 #1] DEBUG -- Kontena::RpcClient: waited 0.2s of 30.0s until: request /node_service_pods/list has response wth id=1165729746 yielded Array
D, [2017-09-05T12:50:35.515733 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of log-test-1: running
I, [2017-09-05T12:50:35.518770 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating log-test-1
...
I, [2017-09-05T12:50:37.949590 #1]  INFO -- Kontena::ServicePods::Creator: service started: log-test-1
D, [2017-09-05T12:50:38.085292 #1] DEBUG -- Kontena::Workers::ServicePodWorker: on_container_event create
D, [2017-09-05T12:50:38.088439 #1] DEBUG -- Kontena::Workers::ServicePodWorker: on_container_event start
```

With the way that the `@container_state_changed` works, that means that each `update` -> `apply if needs_apply?` essentially runs twice: once because the `@service_pod` changes, and then a second time because of the `@container_state_changed = true` triggerd by the `apply` itself:

```
D, [2017-09-05T12:50:48.685974 #1] DEBUG -- Kontena::RpcClient: waited 0.0s of 30.0s until: request /node_service_pods/list has response wth id=1628267283 yielded Array
D, [2017-09-05T12:50:48.948312 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of log-test-1: running
D, [2017-09-05T12:50:49.086853 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state is in-sync: running
```

The second `apply` is a no-op because the container is up to date: https://github.com/kontena/kontena/pull/2143#discussion_r111080598

### LINKED ISSUE #2781: Agent ServicePodWorker gets confused by service restarts
The `ServicePodWorker` does not know anything about the [`ContainerHealthCheckWorker#restart_container`](https://github.com/kontena/kontena/blob/3891ac5ee1d680213ae895e67123345298ad40b1/agent/lib/kontena/workers/container_health_check_worker.rb#L110) / [RPC `/service_pods/restart`](https://github.com/kontena/kontena/blob/45cf5ffaa02493ff0ee180fbcae33379d5f41c5b/agent/lib/kontena/rpc/service_pods_api.rb#L11) -> `ServicePods::Restarter` calls. It sees the container `die` event and thinks that the container has exited and needs to be restarted.

That logs `Kontena::Workers::ServicePodWorker: restarting sleep-test-1 because it has stopped` and triggers a no-op `apply`, where it just determines that the container is actually already running again. Then it sees the `stop`, `start` and `restart` events.

```
D, [2017-09-07T12:59:51.961906 #1] DEBUG -- Kontena::RpcServer: rpc request: Kontena::Rpc::ServicePodsApi#restart ["59b14290abe74500089e03e6", 1]
I, [2017-09-07T12:59:51.982587 #1]  INFO -- Kontena::ServicePods::Restarter: restarting service: /sleep-test-1
D, [2017-09-07T12:59:52.005168 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: kill
D, [2017-09-07T13:00:02.008805 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: kill
D, [2017-09-07T13:00:02.041565 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: die
I, [2017-09-07T13:00:02.042057 #1]  INFO -- Kontena::Workers::ServicePodWorker: restarting sleep-test-1 because it has stopped
D, [2017-09-07T13:00:02.042428 #1] DEBUG -- Kontena::Workers::ServicePodWorker: restart triggered (from 2017-09-07 13:00:02 UTC)
D, [2017-09-07T13:00:02.042806 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of sleep-test-1: running
D, [2017-09-07T13:00:03.276990 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state is in-sync: running
D, [2017-09-07T13:00:03.380802 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: stop
D, [2017-09-07T13:00:03.399293 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: start
D, [2017-09-07T13:00:03.399550 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: restart
```

### PR DESCRIPTION
**Pull request by SpComb**
Split out of #2780
Really fixes #2766 to avoid double-applies by removing `@container_state_changed` and ignoring the `start` events

### Agent
* Simplify usage of `@service_pod.name_for_humans`
* The `ServicePodWorker` compares the event timestamp to the container `started_at` timestamp, and ignores container events from before the container was (re)started
* The `ServicePodWorker` only reacts to container `die` events
* Replace `@container_state_changed` with retry-apply-on-errors logic

### CODE REVIEW

**Comment by SpComb** [comment]
Note that this does NOT fix #2781

```
D, [2018-02-09T08:57:56.178901 #1] DEBUG -- Kontena::Workers::ContainerHealthCheckWorker: checking health for container: /healthcheck-restart.redis-1 using tcp ip and port: 10.81.128.68:6378
I, [2018-02-09T08:57:57.209697 #1]  INFO -- Kontena::Workers::ContainerHealthCheckWorker: About to restart container healthcheck-restart.redis-1 as it's reported to be unhealthy
I, [2018-02-09T08:57:57.552185 #1]  INFO -- Kontena::ServicePods::Restarter: restarting service: /healthcheck-restart/redis-1
D, [2018-02-09T08:57:57.634514 #1] DEBUG -- Kontena::Workers::ServicePodWorker: healthcheck-restart/redis-1 container event: kill at 2018-02-09T08:57:57.572997808Z
D, [2018-02-09T08:57:57.859737 #1] DEBUG -- Kontena::Workers::ServicePodWorker: healthcheck-restart/redis-1 container event: die at 2018-02-09T08:57:57.764769077Z
I, [2018-02-09T08:57:57.864287 #1]  INFO -- Kontena::Workers::ServicePodWorker: restarting healthcheck-restart/redis-1 because it has stopped
D, [2018-02-09T08:57:57.864674 #1] DEBUG -- Kontena::Workers::ServicePodWorker: restart triggered (from 2018-02-09 08:57:57 UTC)
D, [2018-02-09T08:57:57.864743 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of healthcheck-restart.redis-1: running
I, [2018-02-09T08:57:58.778578 #1]  INFO -- Kontena::Workers::ContainerHealthCheckWorker: stopped to check status from /healthcheck-restart.redis-1
D, [2018-02-09T08:57:58.928823 #1] DEBUG -- Kontena::Workers::LogWorker: /healthcheck-restart.redis-1/{"io.kontena.container.deploy_rev"=>"2018-02-09 08:57:50 UTC", "io.kontena.container.name"=>"healthcheck-restart.redis-1", "io.kontena.container.overlay_cidr"=>"10.81.128.68/16", "io.kontena.container.overlay_network"=>"kontena", "io.kontena.container.pod"=>"healthcheck-restart.redis-1", "io.kontena.container.service_revision"=>"1", "io.kontena.container.stop_grace_period"=>"10", "io.kontena.container.type"=>"container", "io.kontena.grid.name"=>"development", "io.kontena.health_check.initial_delay"=>"1", "io.kontena.health_check.interval"=>"1", "io.kontena.health_check.port"=>"6378", "io.kontena.health_check.protocol"=>"tcp", "io.kontena.health_check.timeout"=>"1", "io.kontena.platform.name"=>"development", "io.kontena.service.id"=>"5a7d602284ffb800080504b6", "io.kontena.service.instance_number"=>"1", "io.kontena.service.name"=>"redis", "io.kontena.stack.name"=>"healthcheck-restart"}
I, [2018-02-09T08:57:58.959122 #1]  INFO -- Kontena::Workers::ContainerHealthCheckWorker: starting to watch health of container /healthcheck-restart.redis-1
D, [2018-02-09T08:57:59.045164 #1] DEBUG -- Kontena::Workers::ContainerLogWorker: starting to stream logs from /healthcheck-restart.redis-1
D, [2018-02-09T08:57:59.349731 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state is in-sync: running
D, [2018-02-09T08:57:59.508252 #1] DEBUG -- Kontena::Workers::ServicePodWorker: skip healthcheck-restart/redis-1 state sync at 2018-02-09 08:57:50 UTC: unchanged
D, [2018-02-09T08:57:59.508792 #1] DEBUG -- Kontena::Workers::ServicePodWorker: healthcheck-restart/redis-1 stale container event: stop at 2018-02-09T08:57:58.021696090Z < 2018-02-09T08:57:58.697438501+00:00
D, [2018-02-09T08:57:59.688978 #1] DEBUG -- Kontena::Workers::ServicePodWorker: healthcheck-restart/redis-1 container event: start at 2018-02-09T08:57:58.712140321Z
D, [2018-02-09T08:57:59.692528 #1] DEBUG -- Kontena::Workers::ServicePodWorker: healthcheck-restart/redis-1 container event: restart at 2018-02-09T08:57:58.712406635Z
```

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 1]
```diff
@@ -44,14 +44,34 @@ def update(service_pod)
...
 
+    def apply_started!
+      @apply_started_at = Time.now
+    end
+    def apply_finished!
+      @apply_finished_at = Time.now
+    end
+
+    # @return [Boolean]
+    def apply_started?
```
Comment (jakolehm) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Is this used anywhere?

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 2]
```diff
@@ -121,6 +148,8 @@ def apply
       container = nil
 
       exclusive {
+        apply_started!
```
Comment (jakolehm) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Could this `apply_started!` / `apply_finished!` be refactored into a block `apply!` that internally handles settings timestamps?

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 1 above)
Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: Nope

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 2 above)
Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: I don't immediately see how that could be refactored sensibly... this is already in the method named  `apply`, and it's not used anywhere else.

Comment (kke) [reply agent/lib/kontena/workers/service_pod_worker.rb]:
```ruby
def apply!
  apply_started!
  yield
rescue
  raise
else
  apply_finished!
end
```

```ruby
exclusive do
  apply! do
  end
end
```

? :)

Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: Yeah, but I think that just ends up being less clear...?

Comment (jakolehm) [reply agent/lib/kontena/workers/service_pod_worker.rb]: `apply!` is probably bad name (or `apply` should be renamed). Anyway with block you don't need to expose `apply_started!` and `apply_finished!` methods at all?

Comment (jakolehm) [reply agent/lib/kontena/workers/service_pod_worker.rb]: That said I'm ok with merging current implementation. I was only pointing out that this current logic adds a bit unnecessary noise to the class.

Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: I agree that `apply` wants some refactoring, but I don't think the `apply_started/finished!` would be the place to start... it needs something else to simplify the `exclusive`/`applying` block entirely
