### PR TITLE
Fix server stack view to not crash for orphaned child stacks

### LINKED ISSUE #2883: child stack install fails on stack.parent.to_path
From #2866: Installing a new stack with dependencies will create the child stacks with a `parent_name`, such that the [`stack.has_parent?`](https://github.com/kontena/kontena/blob/c29a5a5f2da95fd412d55632e3ff798378d988d1/server/app/views/v1/stacks/_stack.json.jbuilder#L19) is true, but the `stack.parent` is `nil`, which causes the request to fail on [`stack.parent.to_path`](https://github.com/kontena/kontena/blob/c29a5a5f2da95fd412d55632e3ff798378d988d1/server/app/views/v1/stacks/_stack.json.jbuilder#L21):

```
NoMethodError (undefined method `to_path' for nil:NilClass):
  /app/app/views/v1/stacks/_stack.json.jbuilder:21:in `block (3 levels) in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:35:in `block in set!'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:258:in `block in _merge_block'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:258:in `_merge_block'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:35:in `set!'
  /app/app/views/v1/stacks/_stack.json.jbuilder:20:in `block (2 levels) in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /app/app/views/v1/stacks/show.json.jbuilder:1:in `block (2 levels) in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/render.rb:265:in `render'
  /app/app/routes/v1/grids/grid_stacks.rb:16:in `block (3 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:460:in `is'
  /app/app/routes/v1/grids/grid_stacks.rb:7:in `block (2 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:758:in `_verb'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:540:in `post'
  /app/app/routes/v1/grids/grid_stacks.rb:6:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `route'
  /app/app/routes/v1/grids_api.rb:60:in `block (3 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:59:in `block (2 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:55:in `block in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/error_handler.rb:66:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:857:in `match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `block in match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `all?'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:831:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/server.rb:54:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/server.rb:53:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /app/app/middlewares/version_injector.rb:12:in `call'
  /app/app/middlewares/token_authentication.rb:70:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:74:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

172.17.0.1 - - [29/Sep/2017:11:51:49 +0000] "POST /v1/grids/development/stacks HTTP/1.1" 500 35 0.1525
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #2883

### CODE REVIEW

File: server/spec/api/v1/stacks_spec.rb [hunk 1]
```diff
@@ -151,6 +151,16 @@
         expect(json_response['parent']).to match hash_including('name' => stack.name, 'id' => "#{stack.grid.name}/#{stack.name}")
       end
 
+      context 'when parent stack does not exist' do
+        it 'returns stack json with parent name excluding parent id' do
+          child_stack_1.destroy
+          get "/v1/stacks/#{child_stack_1_2.to_path}", nil, request_headers
+          expect(json_response['parent'].key?('name')).to be_truthy
+          expect(json_response['parent'].key?('id')).to be_falsey
+          expect(json_response['parent']).to match hash_including('name' => stack.name)
```
Comment (SpComb) [inline server/spec/api/v1/stacks_spec.rb]: I suggest the more explicit `expect(json_response['parent']).to eq { 'id' => nil, 'name' => ...}` without the `hash_including`.

Comment (kke) [reply server/spec/api/v1/stacks_spec.rb]: Using the `hash_including` is future proofier.

In case the future adds some other fields to the parent object, the spec would fail for no good reason.

File: server/spec/api/v1/stacks_spec.rb [hunk 2]
```diff
@@ -151,6 +151,14 @@
         expect(json_response['parent']).to match hash_including('name' => stack.name, 'id' => "#{stack.grid.name}/#{stack.name}")
       end
 
+      context 'when parent stack does not exist' do
+        it 'returns stack json with parent name excluding parent id' do
+          child_stack_1.destroy
+          get "/v1/stacks/#{child_stack_1_2.to_path}", nil, request_headers
+          expect(json_response['parent']).to match hash_including('name' => stack.name, 'id' => nil)
```
Comment (SpComb) [inline server/spec/api/v1/stacks_spec.rb]: I suggest using explicit `'name' => 'child-stack-1` matches in specs when reasonable, rather than trying to re-use the `let` variables like this.

```
  1) /v1/stacks GET /:name nested stacks when parent stack does not exist returns stack json with parent name excluding parent id
     Failure/Error: expect(json_response['parent']).to match hash_including('name' => stack.name, 'id' => nil)
       expected {"id"=>nil, "name"=>"child-stack-1"} to match #<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x00000004d190d0 @expected={"name"=>"stack", "id"=>nil}>
       Diff:
       @@ -1,3 +1,3 @@
       -#<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x00000004d190d0
       - @expected={"name"=>"stack", "id"=>nil}>
       +"id" => nil,
       +"name" => "child-stack-1",
       
     # ./spec/api/v1/stacks_spec.rb:158:in `block (5 levels) in <top (required)>'
```
