### PR TITLE
Fix CLI exec to use TTY::Screen.size

### LINKED ISSUE #3060: e2e spec service exec --tty sending invalid tty_size
Seems the CLI exec is sending an invalid `{"tty_size"=>{:width=>0, :height=>0}}` when running in the e2e rspecs.

```
  13) service exec --tty runs a command with tty control input
      Failure/Error: expect(k.out).to match /\^C/
      
        expected " [\e[31merror\e[0m] connection closed with code 4000: ArgumentError: width and height must be integers > 0\n" to match /\^C/
        Diff:
        @@ -1,2 +1,2 @@
        -/\^C/
        + [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
        
      # ./spec/features/service/exec_spec.rb:64:in `block (3 levels) in <top (required)>'

  14) service exec --tty runs a command with non-ascii input
      Failure/Error: expect(k.out).to match /\u00e5\u00e5f/
      
        expected " [\e[31merror\e[0m] connection closed with code 4000: ArgumentError: width and height must be integers > 0\n" to match /\u00e5\u00e5f/
        Diff:
        @@ -1,2 +1,2 @@
        -/\u00e5\u00e5f/
        + [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
        
      # ./spec/features/service/exec_spec.rb:78:in `block (3 levels) in <top (required)>'
```

```
  2) service exec --tty runs a command with non-ascii input
     Failure/Error: expect(k.out).to match /\u00e5\u00e5f/
     
       expected "\e[7;94mDEBUG\e[0m Kontena CLI 1.4.1.pre1 (ruby-2.3.5+x86_64-linux-musl)\r\n\e[7;94mDEBUG\e[0m Runni... > 0\n\e[7;94mDEBUG\e[0m Execution took 2.283 seconds\r\n\e[7;94mDEBUG\e[0m SystemExit status 1\r\n" to match /\u00e5\u00e5f/
       Diff:
       @@ -1,2 +1,20 @@
       -/\u00e5\u00e5f/
       +DEBUG Kontena CLI 1.4.1.pre1 (ruby-2.3.5+x86_64-linux-musl)
       +DEBUG Running Kontena::MainCommand with ["service", "exec", "-it", "test-1", "sh"] -- callback matcher = 'nil'
       +DEBUG Running Kontena::Cli::ServiceCommand with ["exec", "-it", "test-1", "sh"] -- callback matcher = 'nil'
       +DEBUG Loading configuration from /root/.kontena_client.json
       +DEBUG Configuration loaded with 1 servers.
       +DEBUG Current master: compose-e2e
       +DEBUG Current grid: e2e
       +DEBUG Running Kontena::Cli::Services::ExecCommand with ["-it", "test-1", "sh"] -- callback matcher = 'services exec'
       +DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>nil, :ssl_verify_peer_host=>nil}
       +DEBUG [Request]: GET http://localhost:9292/v1/services/e2e/null/test-1/containers | Headers: {Accept: application/json, Authorization: Bearer} 
       +DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.1.pre1}  | Status: 200 | Body: 
       +{"containers":[{"id":"e2e/localhost/test-1-1","name":"test-1-1","container_id":"048be7cc9445e031b04daa5594db0774f69ef3c39bf0aa5864631f0ac1b5aa69","grid_id":"e2e","node":{"id":"5UNJ:XBVI:2MKI:EGDV:GY6L:J3KR:AWXR:BKRZ:XJS2:GPHN:7UVT:KPFD","connected":true,"last_seen_at":"2017-11-17T12:46:22.048Z","name":"localhost","labels":null,"public_ip":"82.181.210.184","private_ip":"172.17.8.100","node_number":1,"grid":{"id":"e2e","name":"e2e","initial_size":1}},"service_id":"e2e/null/test-1","created_at":"2017-11-17T12:46:27.152Z","updated_at":"2017-11-17T12:46:39.306Z","started_at":"2017-11-17T12:46:27.454Z","finished_at":"0001-01-01T00:00:00.000Z","deleted_at":null,"status":"running","state":{"error":"","exit_code":0,"pid":19823,"oom_killed":false,"paused":false,"restarting":false,"dead":false,"running":true},"deploy_rev":"2017-11-17 12:46:18 UTC","service_rev":"1","instance_number":1,"image":"redis:3.0","cmd":["docker-entrypoint.sh","redis-server"],"env":["KONTENA_SERVICE_ID=5a0eda18abdabe000b3e6584","KONTENA_SERVICE_NAME=test-1","KONTENA_GRID_NAME=e2e","KONTENA_PLATFORM_NAME=e2e","KONTENA_STACK_NAME=null","KONTENA_NODE_NAME=localhost","KONTENA_SERVICE_INSTANCE_NUMBER=1","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","GOSU_VERSION=1.10","REDIS_VERSION=3.0.7","REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-3.0.7.tar.gz","REDIS_DOWNLOAD_SHA=e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c"],"volumes":[],"ip_address":"10.81.128.0","hostname":"test-1-1","domainname":"e2e.kontena.local","network_settings":{"bridge":"","gateway":"172.18.0.1","ip_address":"172.18.0.2","ip_prefix_len":16,"mac_address":"02:42:ac:12:00:02","port_mapping":null,"ports":{}}}]}
       +DEBUG websocket exec connect... ws://localhost:9292/v1/containers/e2e/localhost/test-1-1/exec?interactive=true&tty=true
       +DEBUG websocket exec open
       +DEBUG websocket exec write: {"cmd"=>["sh"]}
       +DEBUG websocket exec write: {"tty_size"=>{:width=>0, :height=>0}}
       + [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
       +DEBUG Execution took 2.283 seconds
       +DEBUG SystemExit status 1
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #3060

It seems like `TTY::Screen.size` behaves better than `IO.console.winsize` in some scenarios. Since we're already depending on `tty-screen` in the CLI, no reason to not use it.

This also seems to fix the e2e exec specs for me... but I'm not sure how dependent that is on how the e2e specs are being run exactly?

### CODE REVIEW

File: test/spec/features/service/exec_spec.rb [hunk 1]
```diff
@@ -47,6 +47,7 @@
         end
       end
       expect(k.run).to be_truthy
+      expect(k.out).to match /lib64/
```
Comment (SpComb) [inline test/spec/features/service/exec_spec.rb]: Something fishy going on here. The test spec was passing even though the output was just ` [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0`... is the CLI not exiting with an error?

File: cli/spec/spec_helper.rb [hunk 2]
```diff
@@ -16,6 +16,7 @@
 require 'ruby_dig'
 require 'kontena_cli'
 require 'webmock/rspec'
+require 'tmpdir'
```
Comment (SpComb) [inline cli/spec/spec_helper.rb]: Running on the `exec_helper_spec.rb` and nothing else was failing:

```
  1) Kontena::Cli::Helpers::ExecHelper#websocket_exec connects and reads messages to stderr until exit error
     Failure/Error: @_temp_home_dir = Dir.mktmpdir

     NoMethodError:
       undefined method `mktmpdir' for Dir:Class
       Did you mean?  mkdir
     # ./spec/spec_helper.rb:30:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:54:in `block (2 levels) in <top (required)>'
```

File: test/spec/features/service/exec_spec.rb (hunk 1 above)
Comment (SpComb) [reply test/spec/features/service/exec_spec.rb]: Seems like `expect(k.run).to be_truthy` is not enough... you need `expect(k.code).to be_zero`?

Comment (SpComb) [reply test/spec/features/service/exec_spec.rb]: Fixed in the e2e specs to actually have these exec specs fail.

```
service exec
  runs a command inside a service
  exits with error if command fails
  exits with command error
  returns an error if command not found
  --tty
    runs a command inside a service (FAILED - 1)
    runs a command with tty control input (FAILED - 2)
    runs a command with non-ascii input (FAILED - 3)
    runs a command with chunked UTF-8 input (PENDING: No reason given)
  --interactive
    runs a command with piped stdin
    runs a command with piped non-ascii stdin
  with multiple instances
    runs a command inside a service on a given instances
    runs a command on every instance with --all
    fails early if running a command on every instances with --all fails
    keeps going if running a command on every instances with --all --skip

container exec
  executes command in a given container
  exits with error if command fails
  exits with command error
  fails if container does not exist
  runs a command inside a container with tty (FAILED - 4)

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) service exec --tty runs a command with chunked UTF-8 input
     # No reason given
     Failure/Error: expect(k.code).to be_zero, k.out
        [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
     # ./spec/features/service/exec_spec.rb:104:in `block (3 levels) in <top (required)>'

Failures:

  1) service exec --tty runs a command inside a service
     Failure/Error: expect(k.code).to be_zero, k.out
        [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
     # ./spec/features/service/exec_spec.rb:51:in `block (3 levels) in <top (required)>'

  2) service exec --tty runs a command with tty control input
     Failure/Error: expect(k.out).to match /\^C/
     
       expected " [\e[31merror\e[0m] connection closed with code 4000: ArgumentError: width and height must be integers > 0\n" to match /\^C/
       Diff:
       @@ -1,2 +1,2 @@
       -/\^C/
       + [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
       
     # ./spec/features/service/exec_spec.rb:67:in `block (3 levels) in <top (required)>'

  3) service exec --tty runs a command with non-ascii input
     Failure/Error: expect(k.code).to be_zero, k.out
        [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
     # ./spec/features/service/exec_spec.rb:81:in `block (3 levels) in <top (required)>'

  4) container exec runs a command inside a container with tty
     Failure/Error: expect(k.code).to be_zero, k.out
        [error] connection closed with code 4000: ArgumentError: width and height must be integers > 0
     # ./spec/features/container/exec_spec.rb:49:in `block (2 levels) in <top (required)>'

Finished in 53.14 seconds (files took 0.55529 seconds to load)
19 examples, 4 failures, 1 pending

Failed examples:

rspec ./spec/features/service/exec_spec.rb:41 # service exec --tty runs a command inside a service
rspec ./spec/features/service/exec_spec.rb:54 # service exec --tty runs a command with tty control input
rspec ./spec/features/service/exec_spec.rb:70 # service exec --tty runs a command with non-ascii input
rspec ./spec/features/container/exec_spec.rb:37 # container exec runs a command inside a container with tty
```
