### PR TITLE
Fix CLI stack source not found error from "can't determine origin" to generic "no such file"

### LINKED ISSUE #2805: e2e specs: stack install from file returns error if file not found
Looks like the error message has changed; the new `Can't determine stack file origin for '...'` is maybe also less clear than "no such file"?

```
stack install
  from file
 [error] RuntimeError : Can't determine stack file origin for 'foo.yml'
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
 [error] 404 : Not Found (/v1/stacks/e2e/simple)
    returns error if file not found (FAILED - 1)

Failures:

  1) stack install from file returns error if file not found
     Failure/Error: expect(k.out.match(/no such file/i)).to be_truthy
     
       expected: truthy value
            got: nil
     # ./spec/features/stack/install_spec.rb:34:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/install_spec.rb:31:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #2805 

(from #2707)

### CODE REVIEW

File: cli/lib/kontena/cli/stacks/yaml/stack_file_loader.rb [hunk 1]
```diff
@@ -27,7 +27,9 @@ def self.loaders
       # @return [StackFileLoader]
       def self.for(source, parent = nil)
         loader = loaders.find { |l| l.match?(source, parent) }
-        raise "Can't determine stack file origin for '#{source}'" if loader.nil?
+        if loader.nil?
+          raise RuntimeError, "Not found: no such file #{source} or invalid uri scheme"
```
Comment (kke) [inline cli/lib/kontena/cli/stacks/yaml/stack_file_loader.rb]: perhaps could be `Errno::ENOENT`

Comment (SpComb) [reply cli/lib/kontena/cli/stacks/yaml/stack_file_loader.rb]: The `RuntimeError : Not found: no such file ... or invalid uri scheme` probably isn't any less weird than `Errno::ENOENT : No such file or directory @ rb_sysopen`. Ideally this would exit with some even friendlier error as opposed to the DEBUG= etc hinting for unexpected errors, but this is fine.

### 1.3.4
```
/kontena/test # kontena stack install foo.yml
 [error] Errno::ENOENT : No such file or directory @ rb_sysopen - /kontena/test/foo.yml
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

### After
```
/kontena/test # kontena stack install foo.yml
 [error] RuntimeError : Not found: no such file foo.yml or invalid uri scheme
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```
