### PR TITLE
Fix app init command when app.json is not present

### LINKED ISSUE #253: `kontena app init` products "undefined method `[]' for nil:NilClass"
Dockerfile gets created but nothing else does
Ubuntu 14.10

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #253

### CODE REVIEW

File: cli/lib/kontena/cli/apps/common.rb [hunk 1]
```diff
@@ -90,6 +90,8 @@ def create_yml(services, file='kontena.yml')
     def app_json
       if !@app_json && File.exist?('app.json')
         @app_json = JSON.parse(File.read('app.json'))
+      else
+        @app_json = {}
```
Comment (jakolehm) [inline cli/lib/kontena/cli/apps/common.rb]: Is it ok to initialize `@app_json` to empty hash on every call (if file is missing)?

**Comment by miskun** [comment]
Should work. Merge please.
