### PR TITLE
Tell why plugin install failed

### LINKED ISSUE #1508: Plugin install should detect if sudo is needed
```sh
$ kontena plugin install digitalocean
[fail] Installing plugin digitalocean     
$ gem install kontena-plugin-digitalocean
ERROR:  While executing gem ... (Gem::FilePermissionError)
   You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

Happens with system ruby on osx.

### PR DESCRIPTION
**Pull request by kke**
Fixes #1508

```bash
$ chmod u-w /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/
$ kontena plugin install aws

 [fail] Installing plugin aws
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-plugin-aws-0.2.3
```

### CODE REVIEW

**Comment by SpComb** [comment]
Hmm, still not seeing the actual gem error output without `DEBUG=true`?

```
tehobari:~/kontena/kontena/cli :: kontena plugin install digialocean
 [fail] Installing plugin digialocean     
tehobari:~/kontena/kontena/cli :: DEBUG=true kontena plugin install digialocean
D, [2016-12-20T11:26:22.729733 #10115] DEBUG -- CONFIG: Loading configuration from /home/kontena/.kontena_client.json
D, [2016-12-20T11:26:22.730118 #10115] DEBUG -- CONFIG: Configuration loaded with 3 servers.
D, [2016-12-20T11:26:22.730142 #10115] DEBUG -- CONFIG: Current master: development
D, [2016-12-20T11:26:22.730176 #10115] DEBUG -- CONFIG: Current grid: development
Running #<Kontena::MainCommand:0x00000002c3ac60> -- callback matcher = 'nil'
Running #<Kontena::Cli::PluginCommand:0x00000002c2d8f8> -- callback matcher = 'nil'
Running #<Kontena::Cli::Plugins::InstallCommand:0x00000002c21dc8> -- callback matcher = 'plugins install'
 [fail] Installing plugin digialocean     
ERROR:  Could not find a valid gem 'kontena-plugin-digialocean' (>= 0) in any repository
ERROR:  Possible alternatives: kontena-plugin-digitalocean, kontena-plugin-azure, kontena-plugin-packet, kontena-plugin-upcloud, kontena-plugin-vagrant
 ERROR:  Could not find a valid gem 'kontena-plugin-digialocean' (>= 0) in any repository
ERROR:  Possible alternatives: kontena-plugin-digitalocean, kontena-plugin-azure, kontena-plugin-packet, kontena-plugin-upcloud, kontena-plugin-vagrant

/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/cli/plugins/install_command.rb:28:in `block in install_plugin'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/cli/spinner.rb:124:in `spin'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/cli/common.rb:278:in `spinner'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/cli/plugins/install_command.rb:25:in `install_plugin'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/cli/plugins/install_command.rb:14:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.0.0/bin/kontena:16:in `<top (required)>'
/home/kontena/.local/bin/kontena:23:in `load'
/home/kontena/.local/bin/kontena:23:in `<main>'
```

File: cli/lib/kontena/cli/plugins/install_command.rb [hunk 1]
```diff
@@ -21,13 +21,12 @@ def install_plugin(name)
...
       install_options << "--pre" if pre?
       install_command = "#{gem_bin} install #{install_options.join(' ')} #{plugin}"
-      success = false
-      spinner "Installing plugin #{name.colorize(:cyan)}" do
+      stderr = spinner "Installing plugin #{name.colorize(:cyan)}" do |spin|
         stdout, stderr, status = Open3.capture3(install_command)
-        unless stderr.empty?
-          raise stderr
-        end
+        spin.fail unless stderr.empty?
```
Comment (nevalla) [inline cli/lib/kontena/cli/plugins/install_command.rb]: +1 for status code check

**Comment by kke** [comment]
image
