### PR TITLE
Fix agent ServicePodWorker to not block on wait_for_port

### LINKED ISSUE #2415: agent: sometimes agent does not remove containers causing deploys to fail
Possible cause: restart loop containers

```
W, [2017-06-04T12:16:56.532658 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync kontena-funk.web-1 at 2017-06-04 12:16:55 UTC: Conflict. The name "/kontena-funk.web-1" is already in use by container 7798b1c038379107db4f4ddee564e61f2088b4841a55bc4f19c2258f60e26435. You have to remove (or rename) that container to be able to reuse that name.

W, [2017-06-04T12:16:56.537631 #1]  WARN -- Kontena::Workers::ServicePodWorker: Conflict. The name "/kontena-funk.web-1" is already in use by container 7798b1c038379107db4f4ddee564e61f2088b4841a55bc4f19c2258f60e26435. You have to remove (or rename) that container to be able to reuse that name.
 (Docker::Error::ConflictError)
```

https://github.com/kontena/kontena/blob/master/agent/lib/kontena/workers/service_pod_manager.rb#L106

### LINKED ISSUE #2625: stack rm and install of a container that is in restart loop does  not create a new container
1. vault write invalid SSL cert
2. stack install kontena/lb-ingress and select the invalid cert
3. restart loop starts
4. vault upsert SSL cert to be valid
5. kontena stack rm --force lb-ingress; kontena stack install --values-from values.yml kontena/lb-ingress
6. stack is successfully installed, container is not removed (created timestamp is older than the stack rm && install and thus has the old invalid cert
7. repeat rm && install (scripted so that it's fast), happens every time

fix: wait "5 seconds" before installing again.

### LINKED ISSUE #2775: [1.4] ServicePodWorker cannot restart container if it crashes during wait_for_port
The new 1.4 `ServicePodWorker` based restart policies do not interact well with the use of `wait_for_port` in service container deployments. If deploying a new service container, and the container crashes while the `ServicePodWorker` -> `ServicePods::Creator` is stuck in the `wait_for_port` loop, then the container will not be restarted until after the 5-minute timeout.

```
$ kontena service create --cmd 'sleep 3' --deploy-wait-for-port 6379 redis-waitforport redis 
 [done] Creating redis-waitforport service      
$ kontena service deploy redis-waitforport
 [fail] Deploying service redis-waitforport      
 [error] 500 : halting deploy of development/null/redis-waitforport, one or more instances failed:
	⊗ Failed to deploy instance development/null/redis-waitforport-1 to node core-01: Timeout::Error: Timeout after waiting 300.0s until: service development/null/redis-waitforport-1 is running on node development/core-01 at 2017-09-06 13:26:01 UTC
```

```
I, [2017-09-06T13:26:01.971726 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating redis-waitforport-1
I, [2017-09-06T13:26:01.971821 #1]  INFO -- Kontena::ServicePods::Creator: creating service: redis-waitforport-1
...
I, [2017-09-06T13:26:06.401003 #1]  INFO -- Kontena::ServicePods::Creator: service started: redis-waitforport-1
I, [2017-09-06T13:26:06.401925 #1]  INFO -- Kontena::ServicePods::Creator: waiting for port redis-waitforport-1:6379 to respond


W, [2017-09-06T13:31:06.407741 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync redis-waitforport-1 at 2017-09-06 13:26:01 UTC: execution expired
W, [2017-09-06T13:31:06.408051 #1]  WARN -- Kontena::Workers::ServicePodWorker: execution expired (Timeout::Error)
/app/lib/kontena/service_pods/creator.rb:195:in `sleep'
/app/lib/kontena/service_pods/creator.rb:195:in `block in wait_for_port'
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/app/lib/kontena/service_pods/creator.rb:194:in `wait_for_port'
/app/lib/kontena/service_pods/creator.rb:73:in `perform'
/app/lib/kontena/workers/service_pod_worker.rb:174:in `ensure_running'
/app/lib/kontena/workers/service_pod_worker.rb:151:in `ensure_desired_state'
/app/lib/kontena/workers/service_pod_worker.rb:125:in `block in apply'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/workers/service_pod_worker.rb:123:in `apply'
I, [2017-09-06T13:31:06.438808 #1]  INFO -- Kontena::Workers::ServicePodWorker: restarting redis-waitforport-1 because it has stopped
D, [2017-09-06T13:31:06.440276 #1] DEBUG -- Kontena::Workers::ServicePodWorker: restart triggered (from 2017-09-06 13:31:06 UTC)
D, [2017-09-06T13:31:06.440385 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of redis-waitforport-1: running
I, [2017-09-06T13:31:06.461033 #1]  INFO -- Kontena::Workers::ServicePodWorker: starting redis-waitforport-1
```

The `ServicePodWorker#apply` -> `ensure_running` happens in exclusive mode, which blocks the actor from seeing the `on_container_event` notifications. Even if it wasn't in exclusive mode, the `sleep` happens in the `ServicePods::Creator` class, so it's an actual blocking `Kernel#sleep`, not a suspending `Celluloid#sleep`.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2775 by having the deploy fail if the container restarts during `wait_for_port`
Fixes #2415 by allowing the `ServicePodWorker` actor to terminate during `wait_for_port`
Maybe fixes #2625?
Mitigates #2710 by allowing deploys pending on `wait_for_port` to be aborted by stopping the service

Splits apart the `apply` `exclusive { ensure_desired_state; sync_state_to_master }` block, with an optional `wait_for_port` in between. The `wait_for_port` -> `wait_until!` -> `sleep` in the actor class allows the actor to see later `update` calls, and the `wait_for_port` `wait_until!` -> `check_starting!` can pick these up to cancel the wait.

Needs extra logic to protect `sync_state_to_master` against sending stale state from a suspended `apply` task, after a new `update` state has been applied and sent.

## Workaround for cancelling a deploy stuck on `wait_for_port`

This allows interrupting a service deploy with a broken `wait_for_port` by using `kontena service stop`, which will immediately fail the ongoing deploy, as the agent will sync the `service_pod` state with the current `deploy_rev` and `state: stopped` - although there's also a race here with the `wait_for_port` task syncing its `error` state:

```
I, [2017-09-06T16:03:37.567719 #18]  INFO -- GridServiceInstanceDeployer: waited 13.7s of 300.0s until: service development/null/redis-waitforport-1 is running on node development/core-01 at 2017-09-06 16:03:23 UTC yielded GridServiceInstance
W, [2017-09-06T16:03:37.568076 #18]  WARN -- GridServiceInstanceDeployer: Failed to deploy service instance development/null/redis-waitforport-1 to node core-01: GridServiceInstanceDeployer::StateError: Service instance is not running, but stopped
```

```
W, [2017-09-06T16:03:37.600901 #1]  WARN -- Kontena::Workers::ServicePodWorker: wait_for_port failed: service stopped
```

# TODO
- [ ] fix dual-`async.wait_for_port`?
- [x] specs
- [ ] more specs?

### CODE REVIEW

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 1]
```diff
@@ -128,17 +130,53 @@ def apply
...
 
+        if service_pod.terminated?
           # Only terminate this actor after we have succesfully ensure_terminated the Docker container
           # Otherwise, stick around... the manager will notice we're still there and re-signal to destroy
-          self.terminate if service_pod.terminated?
+          self.terminate
+        elsif service_pod.running? && service_pod.wait_for_port
+          # delay sync_state_to_master until started
+          # XXX: apply() gets called twice for each deploy_rev, and this launches two wait_for_port tasks...
+          async.wait_for_port(service_pod, @container)
```
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: This is a side effect of the  #2766 container `create`/`start` events setting `@container_state_changed = true` and thus triggering two calls to `apply` for each `service_pod.deploy_rev`:

```
Celluloid::Actor 0x1de478ea90
Celluloid::Cell 0x1de478ecac: Kontena::Workers::ServicePodWorker
State: Running (executing tasks)
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:33:in `while_time_remaining'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:11:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'


	Tasks:
	  1) Celluloid::Task::Fibered[call]: sleeping
	      {:dangerous_suspend=>false, :method_name=>:wait_for_port}
		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.


	  2) Celluloid::Task::Fibered[call]: sleeping
	      {:dangerous_suspend=>false, :method_name=>:wait_for_port}
		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
```

Very annoying to try and fix...

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 2]
```diff
@@ -128,17 +130,53 @@ def apply
...
         else
           @container_state_changed = false
-          sync_state_to_master(@container)
+        end
 
+        if service_pod.terminated?
           # Only terminate this actor after we have succesfully ensure_terminated the Docker container
           # Otherwise, stick around... the manager will notice we're still there and re-signal to destroy
-          self.terminate if service_pod.terminated?
+          self.terminate
```
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Subtle change here: no longer calls `sync_state_to_master` after the call to `destroy`. That's probably a good thing, the server won't care anymore, and it would always log an error when terminating service pods:

```
E, [2017-09-06T13:25:41.627773 #8] ERROR -- RpcServer: RuntimeError: Instance not found
D, [2017-09-06T13:25:41.627884 #8] DEBUG -- RpcServer: /app/app/services/rpc/node_service_pod_handler.rb:48:in `set_state'
/app/app/services/rpc_server.rb:63:in `handle_request'
/app/app/services/rpc_server.rb:47:in `process!'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
This is the minimal fix. I think a more complete fix would be to delegate the `wait_for_port` checking to a `ContainerHealthCheckWorker` supervised by the `ServicePodWorker`, and then also allow waiting on any service health checks for the rolling deploys. It would also be easier to properly deal with the various state changes as an actor, rather than in the `async` task `wait_until!` loop.

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 3]
```diff
@@ -128,17 +130,53 @@ def apply
...
+      ip = container.overlay_ip
+      port = service_pod.wait_for_port
+
+      info "waiting for container #{name} port #{ip}:#{port} to respond"
+
+      wait_until!("container #{name} port #{ip}:#{port} is responding", interval: 1.0, timeout: timeout) {
+         raise "service stopped" if !@service_pod.running?
+         raise "service redeployed" if @service_pod.deploy_rev != service_pod.deploy_rev
+         raise "container recreated" if @container.id != container.id
+         raise "container restarted" if @container.started_at != container.started_at
```
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: This isn't optimal: it doesn't trigger on the container `die` event: it triggers on the restart after that, which may be delayed.

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 1 above)
Comment (jakolehm) [inline agent/lib/kontena/workers/service_pod_worker.rb]: I don't like that `wait_for_port` is such a special case here.. could it return state (container) that is reported normally back to master (not inside wait_for_port)?

Comment (jakolehm) [reply agent/lib/kontena/workers/service_pod_worker.rb]: Or maybe this could be a separate class/actor that checks pod readiness.

Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: WIP on a health check actor managed by the service pod worker that tracks the service container ready/healthy state, where the server deploy waits for the service instance to go `initialized` -> `starting` -> `running`...

Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: > I don't like that wait_for_port is such a special case here.. could it return state (container) that is reported normally back to master (not inside wait_for_port)?

It has to be an `async` call if it's in the `exclusive` block, and I'm hesitant to break apart the `exclusive { ... sync_state_to_master }` block because the way the `@service_pod` works is rather unclear. It has to avoid calling `sync_state_to_master` if the `@service_pod` has changed, because that would report the status of the old service rev with the newer deploy rev.

Maybe it would be better to use the same non-exclusive `if @service_pod.deploy_rev == service_pod.deploy_rev` check in all cases, though, both with and without `wait_for_port`.

Comment (SpComb) [reply agent/lib/kontena/workers/service_pod_worker.rb]: Changed to move the `sync_state_to_master` out of the `exclusive` block.

File: agent/spec/lib/kontena/workers/service_pod_worker_spec.rb [hunk 4]
```diff
@@ -4,18 +4,101 @@
...
+        subject.apply
+      end
+
+      it 'aborts if the container crashes and restarts' do
+        expect(subject.wrapped_object).to receive(:ensure_desired_state).once.and_return(container)
+        expect(subject.wrapped_object).to receive(:port_open?).with(overlay_ip, 1337, timeout: 1.0).once do
+          expect(subject.wrapped_object).to receive(:ensure_desired_state).once.and_return(restarted_container)
+          expect(subject.wrapped_object).to receive(:wait_for_port)
+          # XXX: in this case both the failing initial wait_for_port, and the restart will report state...
+          expect(subject.wrapped_object).to receive(:sync_state_to_master).with(service_pod, restarted_container)
```
Comment (SpComb) [inline agent/spec/lib/kontena/workers/service_pod_worker_spec.rb]: If the restarted container completes `wait_for_port` immediately without sleeping, then it might report `state: 'running'` right away. The initial `apply` -> `wait_for_port` task will then race with that to report `error: "container restarted"`, because the `@service_pod.deploy_rev` is still the same.

File: agent/lib/docker/container.rb [hunk 5]
```diff
@@ -76,6 +76,11 @@ def suspiciously_dead?
       false
     end
 
+    # @return DatetTime
```
Comment (jakolehm) [inline agent/lib/docker/container.rb]: `DateTime`

**Comment by SpComb** [comment]
Let's merge and see if the double-apply ends up causing any issues. I suspect the fix for that is just getting rid of the `@container_state_changed` entirely.
