### PR TITLE
Validate volumes before stack gets created or updated

### LINKED ISSUE #2039: Server stack create does not validate volume options, leaves incomplete stack
Creating a stack with an invalid volume configuration that is missing a `driver` passes both CLI and server validation, but fails during execution, leaving a broken stack in place:

```yaml
stack: test/volumes
services:
  redis:
    image: redis:3.2
    instances: 1
    volumes:
      - redis:/data
volumes:
  redis:
    scope: instance
```

```
    *   Creating stack volumes1  .. \[API Client Request]: POST http://localhost:9292/v1/grids/development/stacks | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: 
{"name":"volumes1","stack":"test/volumes","expose":null,"version":"0.0.1","source":"stack: test/volumes\nservices:\n  redis:\n    image: redis:3.2\n    instances: 1\n    volumes:\n      - redis:/data\nvolumes:\n  redis:\n    scope: instance\n","registry":"file://","services":[{"instances":1,"image":"redis:3.2","links":[],"external_links":[],"ports":[],"volumes":["redis:/data"],"volumes_from":[],"affinity":[],"stateful":false,"deploy_opts":{"wait_for_port":null,"min_health":null,"interval":null},"hooks":{},"health_check":{"port":null,"protocol":null,"uri":null,"timeout":null,"interval":null,"initial_delay":null},"log_driver":null,"log_opts":null,"name":"redis"}],"volumes":[{"scope":"instance","name":"redis"}],"variables":{}}
    *   Creating stack volumes1  .. |[API Client Error]: 
D, [2017-03-31T14:02:27.377292 #20735] DEBUG -- CLIENT: Request POST /v1/grids/development/stacks: 422 Unprocessable Entity: {"error":{"volumes":{"redis":{"driver":"Driver is required"}}}}
 [fail] Creating stack volumes1      
{"volumes"=>{"redis"=>{"driver"=>"Driver is required"}}} {"volumes"=>{"redis"=>{"driver"=>"Driver is required"}}}
```

Fixing the stack file and trying to re-install fails:

```
D, [2017-03-31T14:02:33.075225 #20762] DEBUG -- CLIENT: Request POST /v1/grids/development/stacks: 422 Unprocessable Entity: {"error":{"name":"volumes1 already exists"}}
 [fail] Creating stack volumes1      
{"name"=>"volumes1 already exists"} {"name"=>"volumes1 already exists"}
```

The stack, and all of its services, do still get created, but the services seem to end up with an invalid `GridServiceVolume` that is missing the named volume?

```yaml
volumes2:
  created: 2017-03-31T11:06:23.467Z
  updated: 2017-03-31T11:06:23.470Z
  state: initialized
  stack: test/volumes
  version: 0.0.1
  revision: 1
  expose: -
  services:
    redis:
      created: 2017-03-31T11:06:23.483Z
      updated: 2017-03-31T11:06:23.483Z
      image: redis:3.2
      revision: 
      state: initialized
      stateful: no
      scaling: 1
      strategy: ha
      deploy_opts:
        min_health: 
      dns: redis.volumes2.development.kontena.local
      volumes:
        - /data
```

### PR DESCRIPTION
**Pull request by jnummelin**
Volumes are now fully validated before the stack is created and stack create/update fails if volume validation fails.

fixes #2039

### CODE REVIEW

**Comment by SpComb** [comment]
Could we have some quick e2e spec for these CLI stackfile -> server bits?

**Comment by jnummelin** [comment]
I'm writing some e2e cases for this ATM

**Comment by jnummelin** [comment]
added some e2e tests. @SpComb @jakolehm  PTAL

File: test/spec/features/volume/stack_volumes.rb [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+  it 'stack creates volumes' do
+    with_fixture_dir("stack/volumes") do
+      k = run 'kontena stack install redis-simple.yml'
+      expect(k.code).to eq(0), k.out
+    end
+    k = run 'kontena volume ls'
+    expect(k.out.match(/redis-data/)).to be_truthy
+    container = find_container('redis.redis-1')
+    puts "****** #{container}"
```
Comment (SpComb) [inline test/spec/features/volume/stack_volumes.rb]: debugging?

File: test/spec/features/volume/service_volumes.rb [hunk 2]
```diff
@@ -14,10 +17,9 @@
     expect(k.code).to eq(0)
     k = run "kontena service deploy redis"
     expect(k.code).to eq(0)
-    k = run "kontena container inspect moby/redis-1"
-
-    json = JSON.parse(k.out)
-    mount = json.dig('Mounts').find { |m| m['Name'] =~ /testVol/}
+    
+    mount = container_mounts(find_container('redis-1')).find { |m| m['Name'] =~ /testVol/}
+    #mount = json.dig('Mounts').find { |m| m['Name'] =~ /testVol/}
```
Comment (SpComb) [inline test/spec/features/volume/service_volumes.rb]: dead code

**Comment by jnummelin** [comment]
linting done
