### PR TITLE
Make kontena master ssh work without server.provider set

### LINKED ISSUE #2373: Kontena master ssh fails if no server.provider set
If masters `server.provider` is not set, `kontena master ssh` fails with:
```
$ kontena master ssh
 [error] Kontena::Errors::StandardError : Not Found
```
Not very user friendly error. :)

Running things with debug on reveals that it fails to get `server.provider` config value:
```
[API Client Error]: 
D, [2017-05-27T00:04:33.522879 #74679] DEBUG -- CLIENT: Request GET /v1/config/server.provider: 404 Not Found: "Not found"
D, [2017-05-27T00:04:33.523092 #74679] DEBUG -- CLIENT: JSON parse exception: JSON::ParserError : 757: unexpected token at '"Not found"'
Command raised Kontena::Errors::StandardError with message: Not Found
```

I think it would be good for the CLI to still try with some sane defaults if the `server.provider` is not set.

### PR DESCRIPTION
**Pull request by kke**
Fixes #2373

Uses fuzzy logic to use vagrant  anyway (vagrant plugin is installed and master url has '192.168.66').

### CODE REVIEW

File: cli/lib/kontena/cli/master/config/get_command.rb [hunk 1]
```diff
@@ -12,16 +12,14 @@ class GetCommand < Kontena::Command
...
     option ['-p', '--pair'], :flag, "Print key=value instead of only value"
 
-    option '--return', :flag, "Return the value", hidden: true
+    def response
+      client.get("config/#{key}")
+    end
 
     def execute
-      if self.pair?
-        puts client.get("config/#{self.key}").inspect
```
Comment (kke) [inline cli/lib/kontena/cli/master/config/get_command.rb]: it used to output a hash inspect instead of what the help text implies. `{ "key" => "value" }`

File: cli/lib/kontena/cli/master/ssh_command.rb [hunk 2]
```diff
@@ -15,25 +15,50 @@ def master_host
...
-      if master_provider == 'vagrant'
-        unless Kontena::PluginManager.instance.plugins.find { |plugin| plugin.name == 'kontena-plugin-vagrant' }
+    def vagrant_plugin_installed?
+      Kontena::PluginManager.instance.plugins.any? { |plugin| plugin.name == 'kontena-plugin-vagrant' }
+    end
+
+    def master_is_vagrant?
+      if master_provider_vagrant?
+        unless vagrant_plugin_installed?
           exit_with_error 'You need to install vagrant plugin to ssh into this node. Use kontena plugin install vagrant'
```
Comment (kke) [inline cli/lib/kontena/cli/master/ssh_command.rb]: it says "node", maybe it should say "master".

Comment (jnummelin) [inline cli/lib/kontena/cli/master/ssh_command.rb]: yes, please :)

**Comment by kke** [comment]
```ruby
    option ["-i", "--identity-file"], "IDENTITY_FILE", "Path to ssh private key"
    # ...
    cmd += ["-i", identity_file] if identity_file
```

we could remove that option, you can do: `kontena master ssh -- -i id_rsa`

**Comment by jnummelin** [comment]
I'd deprecate the option first. I think there's bunch of people, including myself :), used to use that option.
