### PR TITLE
cli node list: spec and fix initializing node with nil name

### LINKED ISSUE #2447: CLI: kontena node ls will cause TypeError when looped and new nodes appear
```
while true; do
  kontena node ls
done
```

--> add 3 nodes:
```
 [error] TypeError : no implicit conversion of nil into String
         See /Users/mpa/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

```
E, [2017-06-08T13:35:57.896119 #30552] ERROR -- CLI: no implicit conversion of nil into String (TypeError)
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:69:in `+'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:69:in `block (2 levels) in node_data'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:68:in `each'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:68:in `block in node_data'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:54:in `each'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:54:in `flat_map'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:54:in `node_data'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:78:in `execute'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/command.rb:201:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/command.rb:201:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/command.rb:201:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/bin/kontena:18:in `<top (required)>'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/kontena:23:in `load'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/kontena:23:in `<main>'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2447

### CODE REVIEW

File: cli/lib/kontena/cli/nodes/list_command.rb [hunk 1]
```diff
@@ -66,7 +66,7 @@ def node_data
         unless quiet?
           grid_health = grid_health(grid, grid_nodes)
           grid_nodes.each do |node|
-            node['name'] = health_icon(node_health(node, grid_health)) + " " + node['name']
+            node['name'] = health_icon(node_health(node, grid_health)) + " " + (node['name'] || '')
```
Comment (kke) [inline cli/lib/kontena/cli/nodes/list_command.rb]: Should the default be something like '(initializing)' instead of blank?

Comment (SpComb) [inline cli/lib/kontena/cli/nodes/list_command.rb]: I think it used to just get rendered as blank before the CLI table formatting changes, but yes, using something like that as a placeholder might be a good improvement.

**Comment by SpComb** [comment]
Tested by disabling the `/nodes/update` RPC and connecting a new node:

```
NAME               VERSION   STATUS   INITIAL   LABELS
⊛ core-01          1.3.0     online   1 / 1     test
⊛ (initializing)             online   -         test=label
```
