### PR TITLE
Serialize all pubsub payloads to avoid issues with dotted fields

### LINKED ISSUE #2340: New Mongoid doesn't accept dots in fields
The mongoid update broke RPC related pubsub as e.g. labels are using dots in the field names.
```
E, [2017-05-18T10:27:53.338743 #16] ERROR -- : Actor crashed!
api_1      | BSON::String::IllegalKey: 'io.kontena.service.id' is an illegal key in MongoDB. Keys may not start with '$' or contain a '.'.
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/string.rb:69:in `to_bson_key'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:45:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:49:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each_with_index'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:49:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each_with_index'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:49:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each_with_index'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/serializers.rb:163:in `serialize'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:213:in `block in serialize_fields'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:201:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:201:in `serialize_fields'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:104:in `serialize'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:193:in `block in write'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:192:in `each'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:192:in `write'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:162:in `deliver'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:108:in `block in dispatch'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/monitoring/publishable.rb:47:in `publish_command'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:107:in `dispatch'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/command/writable.rb:39:in `block in execute'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection_pool.rb:107:in `with_connection'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server.rb:242:in `with_connection'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/command/writable.rb:38:in `execute'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/insert.rb:55:in `execute_write_command'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/write_command_enabled.rb:41:in `execute'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/collection.rb:365:in `block in insert_one'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/retryable.rb:112:in `write_with_retry'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/collection.rb:356:in `insert_one'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:182:in `insert_one_with_clear_cache'
api_1      |    /app/app/services/mongo_pubsub.rb:98:in `publish'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
api_1      |    /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
````
Tracked this down to `rcp_client` channel pubsub messages:
```
api_1      | Channel: rpc_client
api_1      | data: {:type=>"request", :id=>"BZYD:ODII:NAHP:ZYZJ:FVDJ:YM2L:VKS6:EV2R:MTSM:JLH3:ZSRH:ITQ7", :message=>[0, 1322185281, "/load_balancers/remove_service", [{:id=>"591d726fd14e590010976cb6/1", :desired_state=>"running", :service_id=>"591d726fd14e590010976cb6", :service_name=>"simple-nginx", :service_revision=>1, :updated_at=>"2017-05-18 10:07:43 UTC", :instance_number=>1, :image_name=>"nginx:1-alpine", :image_credentials=>nil, :deploy_rev=>"2017-05-18 10:08:55 UTC", :stateful=>false, :user=>nil, :cmd=>nil, :entrypoint=>nil, :memory=>nil, :memory_swap=>nil, :cpu_shares=>nil, :privileged=>nil, :cap_add=>[], :cap_drop=>[], :devices=>[], :ports=>[], :volumes=>[], :volumes_from=>[], :net=>"bridge", :hostname=>"simple-nginx-1", :domainname=>"e2e.kontena.local", :exposed=>false, :log_driver=>nil, :log_opts=>{}, :pid=>nil, :wait_for_port=>nil, :env=>["KONTENA_SERVICE_ID=591d726fd14e590010976cb6", "KONTENA_SERVICE_NAME=simple-nginx", "KONTENA_GRID_NAME=e2e", "KONTENA_STACK_NAME=null", "KONTENA_NODE_NAME=moby", "KONTENA_SERVICE_INSTANCE_NUMBER=1"], :secrets=>[], :labels=>{"io.kontena.service.id"=>"591d726fd14e590010976cb6", "io.kontena.service.name"=>"simple-nginx", "io.kontena.stack.name"=>"null", "io.kontena.grid.name"=>"e2e", "io.kontena.load_balancer.name"=>"simple-lb", "io.kontena.load_balancer.internal_port"=>"80", "io.kontena.load_balancer.mode"=>"http"}, :hooks=>[], :networks=>[{:name=>"kontena", :subnet=>"10.81.0.0/16", :multicast=>true, :internal=>false}]}]]}
```

### PR DESCRIPTION
**Pull request by jnummelin**
fixes #2340 

Newer mongoid doesn't allow dotted fields in hashes. There are multiple RPC cases where the hash payload has dotted fields.

This PR adds generic payload serialization on pubsub messages to avoid any such issues.

### CODE REVIEW

File: server/app/services/mongo_pubsub.rb [hunk 1]
```diff
@@ -93,7 +101,7 @@ def unsubscribe(subscription)
   def publish(channel, data)
     self.collection.insert_one(
       channel: channel,
-      data: data,
+      data: BSON::Binary.new(Marshal::dump(data)),
```
Comment (jakolehm) [inline server/app/services/mongo_pubsub.rb]: Why not msgpack?

Comment (jnummelin) [inline server/app/services/mongo_pubsub.rb]: That should work too. 

In the first try encountered some issues with msgpack UTF-8 in-compliance, tried with plain Ruby `Marshal` (which has the same issue btw) and left it there. :)

So no real reason, can change this to use msgpack if wanted?

Comment (jnummelin) [inline server/app/services/mongo_pubsub.rb]: msgpack seems to be quite a bit faster than `Marshal`: https://gist.github.com/aishfenton/480059

So I'll go and change this to use it.

Comment (jakolehm) [inline server/app/services/mongo_pubsub.rb]: And with `msgpack` hash keys are always strings, right?

Comment (jnummelin) [inline server/app/services/mongo_pubsub.rb]: yes, seems to be:
```
2.3.3 :001 > require 'msgpack'
 => true 
2.3.3 :002 > h = {foo: 'bar'}
 => {:foo=>"bar"} 
2.3.3 :003 > packed = MessagePack.pack(h)
 => "\x81\xA3foo\xA3bar" 
2.3.3 :004 > unpacked = MessagePack.unpack(packed)
 => {"foo"=>"bar"} 

```

Comment (jnummelin) [inline server/app/services/mongo_pubsub.rb]: oh, it actually kinda breaks things:
```
2.3.3 :008 > h = {foo: 'bar', message: ['foo', :foo, :bar], other: :other}
 => {:foo=>"bar", :message=>["foo", :foo, :bar], :other=>:other} 
2.3.3 :009 > packed = MessagePack.pack(h)
 => "\x83\xA3foo\xA3bar\xA7message\x93\xA3foo\xA3foo\xA3bar\xA5other\xA5other" 
2.3.3 :010 > unpacked = MessagePack.unpack(packed)
 => {"foo"=>"bar", "message"=>["foo", "foo", "bar"], "other"=>"other"} 
```
So it not only changes the hash keys but also values

Comment (jakolehm) [inline server/app/services/mongo_pubsub.rb]: Msgpack does not have symbols, they are also deprecated in bson spec.

Comment (jnummelin) [inline server/app/services/mongo_pubsub.rb]: But they are stored properly in mongo:
```
2.3.3 :007 > PubsubChannel.create(channel: 'foobar', data: {foo: 'bar', arr: [:foo, :bar], inner_hash: {other: :other}})
 => #<PubsubChannel _id: 591ee1e12fab7461994e44e0, created_at: nil, channel: "foobar", data: {:foo=>"bar", :arr=>[:foo, :bar], :inner_hash=>{:other=>:other}}> 
2.3.3 :008 > PubsubChannel.find('591ee1e12fab7461994e44e0')
 => #<PubsubChannel _id: 591ee1e12fab7461994e44e0, created_at: nil, channel: "foobar", data: {"foo"=>"bar", "arr"=>[:foo, :bar], "inner_hash"=>{"other"=>:other}}>
```

Just worried if this change would create any nasty surprises :/

Comment (SpComb) [inline server/app/services/mongo_pubsub.rb]: > Just worried if this change would create any nasty surprises :/

That's why we're merging the mongoid updates early in the 1.3 release :)
