### PR TITLE
Service instance deploy state, errors

### LINKED ISSUE #1907: Server: Service deploy does not report RPC errors to the CLI
With  #1607, the server's `Docker::*` -> `RpcClient` will raise an `RpcClient::Error` containing any errors reported by the agent. The server `GridServiceInstanceDeployer` does not propagate errors back to the `GridServiceDeployer`. They are written to the server error log, but the CLI does not see them.

```
E, [2017-02-28T15:47:00.492475 #18452] ERROR -- GridServiceInstanceDeployer: failed to deploy service instance development/test/redis-1 to node core-01
E, [2017-02-28T15:47:00.492553 #18452] ERROR -- GridServiceInstanceDeployer: Docker::Error::NotFoundError: No such image: redis:nonexist
E, [2017-02-28T15:47:00.492891 #18452] ERROR -- GridServiceInstanceDeployer: /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:126:in `get'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:121:in `create'
/app/lib/kontena/workers/image_pull_worker.rb:34:in `pull_image'
/app/lib/kontena/workers/image_pull_worker.rb:18:in `ensure_image'
...
E, [2017-02-28T15:47:00.493191 #18452] ERROR -- GridServiceDeployer: halting deploy of development/test/redis, one or more instances failed
```

This means that the CLI `kontena service deploy` still shows a useless error message:
```
 [fail] Deploying service test/redis      
 [error] halting deploy of development/test/redis, one or more instances failed
```

Instead, the RPC error should be propagated to the `GridServiceDeployer` and stored in the `grid_service_deploy.set(deploy_state => :error, :reason => ...)`, allowing the CLI to show the `No such image: redis:nonexist` error.

### LINKED ISSUE #2032: Missing Agent ServicePodWorker error handling to report ServiceInstance error states
The current agent `ServicePodWorker` does not behave well in the case of service configuration errors, such as missing images:

```
I, [2017-03-29T13:49:11.078470 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating test.bar-1
I, [2017-03-29T13:49:11.086063 #1]  INFO -- Kontena::ServicePods::Creator: creating service: test.bar-1
I, [2017-03-29T13:49:11.086558 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: redis:nonexist
W, [2017-03-29T13:49:15.486843 #1]  WARN -- Kontena::Workers::ImagePullWorker: image pull failed: No such image: redis:nonexist
. Retrying still for 9 times.
...
W, [2017-03-29T13:49:56.325101 #1]  WARN -- Kontena::Workers::ImagePullWorker: image pull failed: No such image: redis:nonexist
. Retrying still for 1 times.
E, [2017-03-29T13:50:02.614845 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: No such image: redis:nonexist

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:126:in `get'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:121:in `create'
	/app/lib/kontena/workers/image_pull_worker.rb:34:in `pull_image'
	/app/lib/kontena/workers/image_pull_worker.rb:18:in `ensure_image'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/service_pods/creator.rb:172:in `ensure_image'
	/app/lib/kontena/service_pods/creator.rb:29:in `perform'
	/app/lib/kontena/workers/service_pod_worker.rb:74:in `ensure_running'
	/app/lib/kontena/workers/service_pod_worker.rb:42:in `block in ensure_desired_state'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/service_pod_worker.rb:37:in `ensure_desired_state'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-03-29T13:50:02.615130 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: No such image: redis:nonexist

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:126:in `get'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:121:in `create'
	/app/lib/kontena/workers/image_pull_worker.rb:34:in `pull_image'
	/app/lib/kontena/workers/image_pull_worker.rb:18:in `ensure_image'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/service_pods/creator.rb:172:in `ensure_image'
	/app/lib/kontena/service_pods/creator.rb:29:in `perform'
	/app/lib/kontena/workers/service_pod_worker.rb:74:in `ensure_running'
	/app/lib/kontena/workers/service_pod_worker.rb:42:in `block in ensure_desired_state'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/service_pod_worker.rb:37:in `ensure_desired_state'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/workers/service_pod_manager.rb:105:in `ensure_service_worker'
	/app/lib/kontena/workers/service_pod_manager.rb:57:in `block (2 levels) in populate_workers_from_master'
	/app/lib/kontena/workers/service_pod_manager.rb:56:in `each'
	/app/lib/kontena/workers/service_pod_manager.rb:56:in `block in populate_workers_from_master'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/service_pod_manager.rb:44:in `populate_workers_from_master'
	/app/lib/kontena/workers/service_pod_manager.rb:28:in `block in start'
	/app/lib/kontena/workers/service_pod_manager.rb:27:in `loop'
	/app/lib/kontena/workers/service_pod_manager.rb:27:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-03-29T13:50:02.620345 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: No such image: redis:nonexist

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:126:in `get'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:121:in `create'
	/app/lib/kontena/workers/image_pull_worker.rb:34:in `pull_image'
	/app/lib/kontena/workers/image_pull_worker.rb:18:in `ensure_image'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/service_pods/creator.rb:172:in `ensure_image'
	/app/lib/kontena/service_pods/creator.rb:29:in `perform'
	/app/lib/kontena/workers/service_pod_worker.rb:74:in `ensure_running'
	/app/lib/kontena/workers/service_pod_worker.rb:42:in `block in ensure_desired_state'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/service_pod_worker.rb:37:in `ensure_desired_state'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/workers/service_pod_manager.rb:105:in `ensure_service_worker'
	/app/lib/kontena/workers/service_pod_manager.rb:57:in `block (2 levels) in populate_workers_from_master'
	/app/lib/kontena/workers/service_pod_manager.rb:56:in `each'
	/app/lib/kontena/workers/service_pod_manager.rb:56:in `block in populate_workers_from_master'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/service_pod_manager.rb:44:in `populate_workers_from_master'
	/app/lib/kontena/workers/service_pod_manager.rb:28:in `block in start'
	/app/lib/kontena/workers/service_pod_manager.rb:27:in `loop'
	/app/lib/kontena/workers/service_pod_manager.rb:27:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

See #2009 #2011 for the `ServicePodManager` recovery on restart:

```
D, [2017-03-29T13:50:03.962067 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 1.4s of 300.0s until: have node info
D, [2017-03-29T13:50:04.063060 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 1.5s of 300.0s until: have node info
D, [2017-03-29T13:50:04.164506 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 1.6s of 300.0s until: have node info
D, [2017-03-29T13:50:04.265673 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 1.7s of 300.0s until: have node info
D, [2017-03-29T13:50:04.367084 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 1.8s of 300.0s until: have node info
D, [2017-03-29T13:50:04.467909 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 1.9s of 300.0s until: have node info
D, [2017-03-29T13:50:04.568618 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 2.0s of 300.0s until: have node info
D, [2017-03-29T13:50:04.673946 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 2.2s of 300.0s until: have node info
D, [2017-03-29T13:50:04.775670 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 2.3s of 300.0s until: have node info
....
D, [2017-03-29T13:55:02.510605 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 300.0s of 300.0s until: have node info
D, [2017-03-29T13:55:02.612476 #1] DEBUG -- Kontena::Workers::ServicePodManager: waiting 300.1s of 300.0s until: have node info
D, [2017-03-29T13:55:02.713933 #1] DEBUG -- Kontena::Workers::ServicePodManager: timeout after waiting 300.1s until: have node info
E, [2017-03-29T13:55:02.714612 #1] ERROR -- : Actor crashed!
Timeout::Error: Timeout after waiting 300.0s until: have node info
	/app/lib/kontena/helpers/wait_helper.rb:53:in `wait_until!'
	/app/lib/kontena/workers/service_pod_manager.rb:25:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2032, fixes  #1907

If creating the Docker container for a service instance failed during deployment, previous versions of Kontena would only log the errors on the agent, and they would not be reported back to the server or shown in the CLI. With #1607, the agent `/service_pods/create` errors would be reported back to the server, but the `GridServiceDeployer` would not return them to the CLI (#1907). With #1873, the agent  `ServicePodWorker` no longer reported the Docker API errors back to the server, and would crash instead (#2032).

This PR provides end-to-end per-instance error handling for service deployments, with the agent reporting  `ServiceInstance.error` states back to the server, the server tracks the `GridServiceInstanceDeploy.error` state, the API includes `/v1/services/:grid/:stack/:service/deploys/:deploy` `{"instance_deploys": {"error": ...}}` states, and the CLI can render those (WIP).

The `ServiceInstance` now also has a new `error `field. This is updated independently of the `state` field: a new `deploy_rev` with a `desired_state: stopped` might still result in `state: running` with `error: failed to stop...`. Then later, the agent might independently re-apply and update that `deploy_rev` to `state: stopped` `error: null`.

## Agent

* Refactor `ServicePodWorker#apply` to handle the `ensure_desired_state` success and error cases, protocol state and actor lifecycle
* Simplify `@prev_state` to just compare on the complete state update in `sync_state_to_master`

   The agent will also sync state to the master if the `error` state changes, like on a later `update` cycle.

## Server
* Add a new `error` field to the `ServiceInstance` model
* Add a new `GridServiceInstanceDeploy` model embedded in the `GridServiceDeploy`, with per-instance state and errors
* Change `GridServiceInstanceDeployer#ensure_service_instance` to update and wait for the `deploy_rev`, also when stopping an old instance on a different node

    This ensures that the instance was actually stopped. This also now warns if it was unable to stop it.
* Log warnings if unable to stop existing service instance

    ```
    INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-2 to node core-02 at 2017-03-30 14:01:30 UTC...
    INFO -- GridServiceInstanceDeployer: Stopping existing service service development/null/redis instance 2 on previous node core-01...
    ```

    ```
    INFO -- GridServiceInstanceDeployer: Deploying service instance development/null/redis-2 to node core-01 at 2017-03-30 14:02:59 UTC...
    INFO -- GridServiceInstanceDeployer: Stopping existing service service development/null/redis instance 2 on previous node core-02...
    WARN -- GridServiceInstanceDeployer: Failed to stop existing service development/null/redis instance 2 on previous node core-02: Host node is offline
    ```
    ```
    WARN -- GridServiceInstanceDeployer: Replacing orphaned service development/null/redis instance 2 on destroyed node
    ```

* Refactor the `GridServiceInstanceDeployer` around the new `GridServiceInstanceDeploy` model

## API
* Add a new `instance_deploys` field to the `/v1/services/:grid/:stack/:service/deploys/:deploy` API

####  `/v1/services/:grid/:stack/:service/deploys/:deploy`

```json
{
   "reason" : "GridServiceDeployer::DeployError: one or more instances failed",
   "id" : "58dcf836de3578252b000001",
   "finished_at" : null,
   "state" : "error",
   "instance_deploys" : [
      {
         "state" : "error",
         "instance_number" : 1,
         "node" : "core-02",
         "error" : "GridServiceInstanceDeployer::AgentError: Docker::Error::NotFoundError: No such image: redis:nonexist\n"
      },
      {
         "node" : "core-01",
         "instance_number" : 2,
         "error" : null,
         "state" : "ongoing"
      },
      {
         "state" : "ongoing",
         "error" : null,
         "node" : "core-02",
         "instance_number" : 3
      },
      {
         "state" : "ongoing",
         "error" : null,
         "instance_number" : 4,
         "node" : "core-01"
      }
   ],
   "started_at" : "2017-03-30T12:21:10.801+00:00",
   "created_at" : "2017-03-30T12:21:10.616Z",
   "service_id" : "development/null/redis-fail"
}
```

## CLI
Rough hack for `kontena service deploy` to report the per-instance errors.

TODO support for `kontena stack deploy`

#### `kontena service scale redis 4`
```
 [done] Scaling redis to 4 instances      
⊛ Deployed instance development/null/redis-1 to node core-01
⊛ Deployed instance development/null/redis-2 to node core-02
⊛ Deployed instance development/null/redis-3 to node core-01
⊛ Deployed instance development/null/redis-4 to node core-02
```

#### `kontena service scale redis-fail 2`
```
 [fail] Scaling redis-fail to 1 instances      
 [error] GridServiceDeployer::DeployError: one or more instances failed:
	⊗ Failed to deploy instance development/null/redis-fail-1 to node core-01: GridServiceInstanceDeployer::ServiceError: Docker::Error::NotFoundError: No such image: redis-nonexist:latest
```

### CODE REVIEW

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 1]
```diff
@@ -126,16 +128,21 @@ def current_state
...
+        rev: service_pod.deploy_rev,
         state: current_state,
-        rev: service_pod.deploy_rev
+        error: error ? "#{error.class}: #{error}" : nil,
       }
-      rpc_client.async.notification('/node_service_pods/set_state', [node.id, data])
-      @prev_state = current_state
+
+      if state != @prev_state
+        rpc_client.async.notification('/node_service_pods/set_state', [node.id, state])
```
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Because this is an async notification, we won't notice if the RPC gets dropped, and the server is left waiting... if this was changed to a `rpc_client.request` instead, we would get an error if the RPC fails... then we could crash and retry sooner? OTOH, I suppose right now we'll eventually re-send this notification, so it should still make progress ATM.

File: server/app/services/grid_service_deployer.rb [hunk 2]
```diff
@@ -39,53 +39,67 @@ def selected_nodes
...
-    info "starting to deploy #{self.grid_service.to_path}"
-    self.grid_service_deploy.set(:deploy_state => :ongoing)
     deploy_rev = Time.now.utc.to_s
+    info "starting to deploy #{self.grid_service.to_path} at #{deploy_rev}"
+    self.grid_service_deploy.set(:deploy_state => :ongoing)
     self.grid_service.set(:deployed_at => deploy_rev)
 
-    deploy_futures = []
     total_instances = self.instance_count
     self.grid_service.grid_service_instances.where(:instance_number.gt => total_instances).destroy
```
Comment (SpComb) [inline server/app/services/grid_service_deployer.rb]: Perhaps this should only happen after all instances have been deployed...?

File: server/app/services/grid_service_instance_deployer.rb [hunk 3]
```diff
@@ -4,82 +4,117 @@ class GridServiceInstanceDeployer
...
+  # @return [GridServiceInstance]
+  def ensure_service_instance(service_instance, node, deploy_rev, desired_state)
+    raise NodeError, "Host node is missing" unless node
+    raise NodeError, "Host node is offline" unless node.connected?
+
+    service_instance.set(
+      host_node_id: node.id,
+      deploy_rev: deploy_rev,
+      desired_state: desired_state,
+      rev: nil, # reset
```
Comment (SpComb) [inline server/app/services/grid_service_instance_deployer.rb]: This is problematic because both the `ensure_service_instance(..., 'stopped')` and `ensure_service_instance(..., 'running')` happen with the same `deploy_rev`... Ideally, each `ensure_service_instance` operation would just set its own `deploy_rev: Time.now.utc` (XXX: with sub-second percision?), but then I'm not sure what affect that would have on the actual Docker container `deploy_rev`?

File: agent/lib/kontena/workers/service_pod_worker.rb [hunk 4]
```diff
@@ -16,58 +16,60 @@ class ServicePodWorker
...
+          ensure_desired_state
+        rescue => error
+          warn "failed to sync #{service_pod.name}: #{error}"
+          sync_state_to_master(current_state, error)
         else
-          warn "unknown state #{service_pod.desired_state} for #{service_pod.name}"
+          sync_state_to_master(current_state)
         end
+
+        self.terminate if service_pod.terminated?
```
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Should not terminate the actor if the `ensure_terminated` fails.

File: server/app/services/grid_service_deployer.rb (hunk 2 above)
Comment (jnummelin) [inline server/app/services/grid_service_deployer.rb]: Yes, I think it's safer that way. Maybe also so that it would send the notification to the nodes

File: server/app/services/grid_service_instance_deployer.rb (hunk 3 above)
Comment (jnummelin) [inline server/app/services/grid_service_instance_deployer.rb]: Why is that problematic?

File: server/app/services/grid_service_deployer.rb [hunk 5]
```diff
@@ -39,53 +39,67 @@ def selected_nodes
...
+
+      pending_deploys = deploy_futures.select{|f| !f.ready?}
+      if pending_deploys.size >= (total_instances * self.min_health).floor || pending_deploys.size >= 20
+        info "throttling service instance #{self.grid_service.to_path} deploy because of min_health limit (#{pending_deploys.size} instances in-progress)"
+        sleep 0.1 until pending_deploys.any?{|f| f.ready? }
+      end
+
+      # bail out early if anything fails
+      if deploy_futures.select{|f| f.ready? }.map{|f| f.value }.any?{|d| d.error? } # raises on any Future exceptions
+        raise DeployError, "one or more instances failed"
```
Comment (jnummelin) [inline server/app/services/grid_service_deployer.rb]: maybe `min_instances_to_fail = (1 - min_health) * instance_count` ? So with `0.8` min health 20% of the deployed instances can fail

File: server/app/services/grid_service_deployer.rb (hunk 2 above)
Comment (SpComb) [inline server/app/services/grid_service_deployer.rb]: If we go full-on, then the deploy operation would also wait for those extra instances to get terminated, and also report any failures there...

**Comment by jnummelin** [comment]
Design-wise looks good IMO

File: server/app/services/grid_service_instance_deployer.rb (hunk 3 above)
Comment (SpComb) [inline server/app/services/grid_service_instance_deployer.rb]: Well, setting it to `nil` is a workaround for that issue, but it feels slightly wrong... The problematic thing is that we we have to do two "deploys" using the same `deploy_rev`, because the service instance moves across two nodes.

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 1 above)
Comment (jakolehm) [inline agent/lib/kontena/workers/service_pod_worker.rb]: See #2050

File: server/app/services/grid_service_deployer.rb (hunk 2 above)
Comment (jakolehm) [inline server/app/services/grid_service_deployer.rb]: Why after? Imho these should be terminated before the actual deploy (to make room for scheduling).

File: server/app/services/grid_service_deployer.rb (hunk 5 above)
Comment (jakolehm) [inline server/app/services/grid_service_deployer.rb]: Imho this could be a deploy_opt, cancel or continue on error. Calculation based on min_health is too magical.

File: server/app/services/grid_service_deployer.rb (hunk 2 above)
Comment (SpComb) [inline server/app/services/grid_service_deployer.rb]: Hmm... the scheduler still uses the `Container` info for scheduling decisions, not the `ServiceInstance` models? Would need to fix that if you want the scheduler to re-schedule the new instances based on the old instances being gone, plus wait for the containers to terminate and release their resources.

**Comment by SpComb** [comment]
Still WIP on the CLI `kontena stack deploy` and possibly better `kontena service deploy` output, but otheriwse ready for review.

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 1 above)
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Merged

**Comment by SpComb** [comment]
Took out the `GridServiceDeployer` changes, including the part waiting for ongoing instance deploy futures to complete. Fixing the `GridServiceDeployer` future stuff can be a separate PR, making this easier to review.

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 4 above)
Comment (jnummelin) [inline agent/lib/kontena/workers/service_pod_worker.rb]: `terminate` is  bit confusing as it's used to terminate the pod, container and the actor itself.

**Comment by SpComb** [comment]
I suggest we merge this with the agent/server/api changes, and the basic `kontena service deploy` output, and then have a separate PR to improve the CLI stack/service deploy output further.

File: agent/lib/kontena/workers/service_pod_worker.rb (hunk 4 above)
Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: The `terminate` term is from celluloid, so we would have to rename the `service_pods.desired_state` :)

BTW what happens here now is that the server destroys the `GridServiceInstance`, and the agent signals `ServicePodWorker.destroy`... then if the `docker rm` fails, then the `ServicePodWorker` just logs a warning, and terminates itself. The docker container remains running, and the `ServicePodManager` doesn't pick that up until you restart the agent.

I'm not sure the existing implementation behaves better either... it will crash the `ServicePodWorker`, and then the `ServicePodManager` will not restart it.

Comment (SpComb) [inline agent/lib/kontena/workers/service_pod_worker.rb]: Now we stick around if the `ensure_terminated` fails, so the `ServicePodManager` will re-try the `destroy` on the next update loop.

Comment (jnummelin) [inline agent/lib/kontena/workers/service_pod_worker.rb]: I think it a good idea to stick around and try again on next update loop
