### PR TITLE
Fix e2e service start/stop tests

### LINKED ISSUE #2115: e2e service start/stop specs broken
Broken by #2101 adding two `state: ...` fields to `kontena service show`:

```
  1) service start starts stopped service
     Failure/Error: expect(k.out.scan('state: running').size).to eq(1)
     
       expected: 1
            got: 2
     
       (compared using ==)
     # ./spec/features/service/start_spec.rb:21:in `block (2 levels) in <top (required)>'

  2) service stop stops running service
     Failure/Error: expect(k.out.scan('state: stopped').size).to eq(1)
     
       expected: 1
            got: 2
     
       (compared using ==)
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2115

### CODE REVIEW

File: test/spec/features/service/start_spec.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@
     expect(k.run).to be_truthy
     sleep 1
     k = run("kontena service show test-1")
-    expect(k.out.scan('state: running').size).to eq(1)
+    expect(k.out.scan('desired_state: running').size).to eq(1)
```
Comment (SpComb) [inline test/spec/features/service/start_spec.rb]: If these were `expect(k.out).to match /desired_state: running/` it would be easier to diagnose spec failures, because it would log the output if it didn't match.
