### PR TITLE
Fix Authentication API debug message

### LINKED ISSUE #2428: Authentication API raises error on debug mode
Authentication API outputs message in debug mode when authentication request is successful. However in debug message `user` is referenced which is in most cases nil and thus causing error

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #2428

### CODE REVIEW

File: server/app/routes/oauth2/authenticate_api.rb [hunk 1]
```diff
@@ -62,7 +62,8 @@ class AuthenticateApi < Roda
           user = current_user
         end
 
-        debug { "User authentication request for #{user.email} accepted, redirecting to auth provider" }
+        email =  !user.nil? ? user.email : 'anonymous'
```
Comment (kke) [inline server/app/routes/oauth2/authenticate_api.rb]: User has username which should not be nil I think.

Comment (nevalla) [inline server/app/routes/oauth2/authenticate_api.rb]: the issue is that `user` is nil

Comment (kke) [inline server/app/routes/oauth2/authenticate_api.rb]: Right.
