### PR TITLE
Agent: Fix Kontena::ServicePods::Creator to not configure weavewait for net=host containers

### LINKED ISSUE #1371: kontena service create --net=host containers are stuck in weavewait
The kontena agent seems to include the weave-wait entrypoint when creating `net=host` containers. This causes those service containers to remain stuck in weavewait, because the host will should have an `ethwe` interface.

```
$ kontena service create --net=host redis redis
 [done] Creating redis service      
$ kontena service deploy redis
 [done] Deploying service redis    
$ kontena service show redis
development/default/redis:
  stack: development/default
  status: running
  image: redis:latest
  revision: 1
  stateful: no
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 0.8
  dns: default-redis.development.kontena.local
  net: host
  instances:
    default-redis-1:
      rev: 2016-11-22 11:32:15 UTC
      service_rev: 1
      node: core-01
      dns: core-01.
      ip: 
      public ip: 82.181.116.101
      status: running
      exit code: 0
```

On the agent:

```
$ docker exec -it default-redis-1 ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        23  0.0  0.2  17496  2060 ?        Rs+  11:33   0:00 ps auxf
root         1  0.0  0.5  23132  5388 ?        Ssl  11:32   0:00 /w/w docker-ent
```

No redis-server process.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1371

```
kontena-agent | I, [2016-11-22T16:39:17.987290 #1]  INFO -- Kontena::ServicePods::Creator: creating service: null-redis-1
kontena-agent | I, [2016-11-22T16:39:17.987928 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: redis:latest
kontena-agent | I, [2016-11-22T16:39:21.583709 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: redis:latest
kontena-agent | D, [2016-11-22T16:39:21.599660 #1] DEBUG -- ServicePods::Creator: creating container: null-redis-1
kontena-agent | D, [2016-11-22T16:39:21.616598 #1] DEBUG -- ServicePods::Creator: container created: null-redis-1
kontena-agent | I, [2016-11-22T16:39:21.701941 #1]  INFO -- Kontena::ServicePods::Creator: service started: null-redis-1
kontena-agent | D, [2016-11-22T16:39:21.731156 #1] DEBUG -- Workers::LogWorker: /null-redis-1/{"io.kontena.container.deploy_rev"=>"2016-11-22 16:39:17 UTC", "io.kontena.container.id"=>"583474b5de35781865000095", "io.kontena.container.name"=>"null-redis-1", "io.kontena.container.pod"=>"null-redis-1", "io.kontena.container.service_revision"=>"1", "io.kontena.container.type"=>"container", "io.kontena.grid.name"=>"development", "io.kontena.service.id"=>"58347144de3578186500007a", "io.kontena.service.instance_number"=>"1", "io.kontena.service.name"=>"redis", "io.kontena.stack.name"=>"null"}
kontena-agent | D, [2016-11-22T16:39:21.735656 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /null-redis-1
kontena-agent | D, [2016-11-22T16:39:21.762000 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /null-redis-1, not attaching to weave
```

```
core@core-01 ~ $ docker inspect -f '{{ .HostConfig.NetworkMode }}' null-redis-1
host
core@core-01 ~ $ docker exec -it null-redis-1 ip addr show weave
23: weave: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default qlen 1000
    link/ether c6:3f:e0:48:25:8d brd ff:ff:ff:ff:ff:ff
    inet 10.81.0.1/16 scope global weave
       valid_lft forever preferred_lft forever
    inet6 fe80::c43f:e0ff:fe48:258d/64 scope link 
       valid_lft forever preferred_lft forever
core@core-01 ~ $ docker exec -it null-redis-1 ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        15  0.0  0.2  17496  2068 ?        Rs+  16:39   0:00 ps auxf
redis        1  0.2  0.9  33308  9240 ?        Ssl  16:39   0:00 redis-server *:
```

### CODE REVIEW

File: agent/lib/kontena/network_adapters/weave.rb [hunk 1]
```diff
@@ -143,13 +143,14 @@ def modify_create_opts(opts)
...
       modify_host_config(opts)
-      opts
-    end
 
-    # @param [Hash] opts
-    def modify_network_opts(opts)
-      opts['Labels']['io.kontena.container.overlay_cidr'] = @ipam_client.reserve_address('kontena')
-      opts['Labels']['io.kontena.container.overlay_network'] = 'kontena'
+      # IPAM
+      overlay_cidr = @ipam_client.reserve_address(DEFAULT_NETWORK)
```
Comment (jakolehm) [inline agent/lib/kontena/network_adapters/weave.rb]: I sense a great conflict here with #1379 ..
