### PR TITLE
Fix server RpcServer to be supervised and restart on crashes

### LINKED ISSUE #2348: Server WebsocketBackend NameError logging deadlock on RpcServer#inspect
A typo causing a `NameError` in any `WebsocketBackend` handler method that logs the resulting `exc.message` results in a deadlock, as the `did_you_mean` core extension invokes `WebsocketBackend#inspect`. This triggers a celluloid call to `@rpc_server.inspect`, which deadlocks because the `RpcServer` actor is blocked on the `@queue.pop`, and does not dispatch the `inspect` call.

Caught by the watchdog:

```
W, [2017-05-22T15:47:55.001171 #28640]  WARN -- Watchdog<WebsocketBackend>: watchdog delayed by 1.001s @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:16:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_str'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `message'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `rescue in on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:69:in `on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:45:in `block in call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:106:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:139:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:105:in `start'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:87:in `block in start_driver'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:237:in `block in schedule'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

Some celluloid call tracing reveals the culprit:

```
I, [2017-05-22T15:53:51.003617 #30001]  INFO -- WebsocketBackend: node XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5 opened connection
CELLULOID Celluloid::Proxy::Cell CALL -> RpcServer#inspect @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:16:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_str'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `message'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `rescue in on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:69:in `on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:45:in `block in call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:106:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:139:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:105:in `start'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:87:in `block in start_driver'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:237:in `block in schedule'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

The horrible patch that fixes the issue, and proves that it's the `@rpc_server.inspect`:

```patch
--- a/server/app/middlewares/websocket_backend.rb
+++ b/server/app/middlewares/websocket_backend.rb
@@ -38,6 +38,14 @@ class WebsocketBackend
     watchdog
   end
 
+  def inspect
+    rpc_server = @rpc_server
+    @rpc_server = nil
+    super.tap {
+      @rpc_server = rpc_server
+    }
+  end
+
   def call(env)
```

### LINKED ISSUE #3035: Agent RPC request timeouts on a server RpcServer actor crash
Simulating an unhandled exception in the server [`RpcServer`](https://github.com/kontena/kontena/blob/v1.4.0/server/app/services/rpc_server.rb), the actor will crash:

```
E, [2017-11-13T13:13:10.806116 #17] ERROR -- : Actor crashed!
RuntimeError: oops
	/app/app/services/rpc_server.rb:88:in `handle_notification'
	/app/app/services/rpc_server.rb:45:in `process!'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

If the `RpcServer` actor crashes, it does not get supervised, because it is spawned in the `WebsocketBackend` middleware without `supervise`: https://github.com/kontena/kontena/blob/b9428ffc718da5427d6356705e830b127269bc6c/server/app/middlewares/websocket_backend.rb#L41-L42

The server worker with the crashed `RpcServer` actor will behave badly: agents connected to that worker will still remain connected, and even things like `kontena node health` will work, because the server -> agent RPC `/etcd/health` requests do not pass through the `RpcServer` actor. However, any RPC requests from the agent will just get stuck in the [`@queue`](https://github.com/kontena/kontena/blob/v1.4.0/server/app/middlewares/websocket_backend.rb#L295) because the actor is no longer processing them... that shows up as RPC timeouts on the agent:

```
W, [2017-11-13T13:18:50.498394 #1]  WARN -- Kontena::RpcClient: observe timeout 30.00s: Kontena::RpcClient::RequestObservable</node_service_pods/list@203381531>? (Kontena::RpcClient::TimeoutError)
/app/lib/kontena/rpc_client.rb:77:in `rescue in request'
/app/lib/kontena/rpc_client.rb:74:in `request'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

One possible crash cause for the server `RpcServer` actor is the mongo [`Grid.find(...)`](https://github.com/kontena/kontena/blob/v1.4.0/server/app/services/rpc_server.rb#L106) query used to initialize the RPC handlers.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #3035 by allowing the `RpcServer` to restart on crashes and continue processing RPC requests from the queue
Also kinda fixes #2348 because there is no more `WebsocketBackend@rpc_server`... however now the Celluloid `@supervisor.inspect` will hang for the same reason... replacing that issue with #3040

Supervise the `RpcServer` globally via `boot_jobs.rb` like `MongoPubsub`, instead of spawning it as an un-supervised actor in `WebsocketBackend#initialize`. The RPC server queue is now a global `RpcServer.queue` class-instance variable, which persists across any `RpcServer` actor crash-and-restart.

### CODE REVIEW

File: server/app/boot_jobs.rb [hunk 1]
```diff
@@ -4,6 +4,8 @@
 
 unless ENV['RACK_ENV'] == 'test' || ENV['NO_MONGO_PUBSUB']
   MongoPubsub.start!(PubsubChannel)
+  RpcServer.supervise(as: :rpc_server)
```
Comment (jakolehm) [inline server/app/boot_jobs.rb]: Could this be bundled to `JobSupervisor` ?

Comment (SpComb) [reply server/app/boot_jobs.rb]: Yes... although maybe `WorkerSupervisor` is vaguely more appropriate?

I'm also fixing the `MongoPubsub.start!`... the way it uses the Celluloid `@supervisor` is rather broken ATM.

Comment (jakolehm) [reply server/app/boot_jobs.rb]: `WorkerSupervisor` has pools, but ofc this could be different worker.
