### PR TITLE
Fix server to only deploy pending/active domain authorization challenge certs

### LINKED ISSUE #2963: No way to remove `tls-sni-01` authorizations from the load balancer?
Related to #2924.

I tried freeing up some space for certificates by combining multiple names into a single certificate authorized using the `tls-sni-01` method.

Unfortunately, I failed to realize each authorization adds one phantom certificate to the load balancer.

Even after `kontena certificate rm`ing all the names I added using `kontena certificate add --type=tls-sni-01`, the maximum amount of actual certificates my load balancer can handle before failing (as detailed in #2924) seems to have permanently decreased from 25 to 22.

(Unfortunately, I need 24 certificates to support all services I currently have :) )

There seems to be no obvious way to query the `tls-sni-01` authorizations present in a load balancer, let alone remove them.

### LINKED ISSUE #3025: TLS-SNI challenge certificates get deployed as the default LB certificate, breaking non-SNI connections
The SSL cert bundles in the `kontena/lb` `SSL_CERTS` env get split up into  `/etc/haproxy/certs/cert*_gen.pem` files, preserving the ordering. If haproxy receives a SSL connection without a SNI hostname, or with a SNI hostname that does not match any certificate, then the first `/etc/haproxy/certs/cert00_gen.pem` certificate will be loaded: https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#5.1-crt

> If no SNI is provided by the client or if the SSL library does not support TLS extensions, or if the client provides an SNI hostname which does not match any certificate, then the first loaded certificate will be presented. This means that when loading certificates from a directory, it is highly recommended to load the default one first as a file or to ensure that it will always be the first one in the directory.

I think Kontena should preserve the ordering of the service `certificates`, so placing the default certificate first should be enough to make sure it gets handled as the default certificate:

```yaml
  certificates: 
    - subject: test.188.226.131.23.xip.io
      name: SSL_CERTS
      type: env
    - subject: test2.188.226.131.23.xip.io
      name: SSL_CERTS
      type: env
```

```
$ curl -vk https://test.188.226.131.23.xip.io |& grep 'subject'
* 	 subject: CN=test.188.226.131.23.xip.io
$ curl -vk https://test2.188.226.131.23.xip.io |& grep 'subject'
* 	 subject: CN=test2.188.226.131.23.xip.io
$ curl -vk https://test4.188.226.131.23.xip.io |& grep 'subject'
* 	 subject: CN=test.188.226.131.23.xip.io
$ curl -vk https://188.226.131.23.nip.io |& grep 'subject'
* 	 subject: CN=test.188.226.131.23.xip.io
```

However, this goes horribly wrong if you use `kontena certificate authorize --type tls-sni-01`, because it turns out that the internal `SSL_CERT` secrets for the challenge certificates get generated before the `certificate` secrets: https://github.com/kontena/kontena/blob/724c94f779ed86c220e02db66cf60510ce21037c/server/app/serializers/rpc/service_pod_serializer.rb#L72-L86
```
$ bin/kontena certificate authorize --type tls-sni-01 --linked-service ingress-lb/lb test4.188.226.131.23.xip.io
 [done] Waiting for tls-sni-01 certificate to be deployed into development/ingress-lb/lb      
TLS-SNI challenge certificate is deployed, you can now request the actual certificate
$ curl -vk https://test4.188.226.131.23.xip.io
* gnutls_handshake() failed: Error in the certificate.
* Closing connection 0
curl: (35) gnutls_handshake() failed: Error in the certificate.
$ curl -vk https://test5.188.226.131.23.xip.io
* gnutls_handshake() failed: Error in the certificate.
* Closing connection 0
curl: (35) gnutls_handshake() failed: Error in the certificate.
```

The challenge certs are specifically crafted to be invalid, so non-SNI connections will break.

```
$ docker exec -it ingress-lb.lb-1 cat /etc/haproxy/certs/cert00_gen.pem | openssl x509 -noout -text
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 0 (0x0)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: 
        Validity
            Not Before: Nov  8 13:51:04 2017 GMT
            Not After : Dec  8 14:51:04 2017 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a7:ae:33:26:44:09:e1:8e:28:b5:d3:47:4f:0c:
                    29:ab:7f:6e:d7:24:93:e7:2f:c6:b5:f4:bc:9f:ff:
                    ad:d9:bd:cb:39:9a:1d:30:b4:1a:05:f1:f8:5f:62:
                    c5:34:41:6f:de:4a:7f:0b:3c:0a:72:48:fe:e6:06:
                    a8:c2:3f:f8:12:87:0b:e2:5a:4c:16:bc:39:b3:28:
                    86:a1:a4:1a:1f:46:81:16:e0:35:71:f3:f2:36:9e:
                    28:3e:8c:a8:4b:79:af:1a:59:a7:56:8d:19:b3:b7:
                    a6:ed:90:7e:46:b5:3c:2e:88:0a:aa:c8:2c:ed:5d:
                    ec:2a:7f:fd:55:61:ef:ff:66:67:67:42:07:4e:f5:
                    30:00:f8:e9:46:0f:ff:a4:bc:25:a5:81:f4:d3:62:
                    ba:03:25:b5:85:ce:76:69:1a:ad:14:80:1a:56:9b:
                    5f:67:de:87:a6:ea:e8:e4:c8:23:15:ec:02:8d:bc:
                    47:68:d9:fd:2a:bb:03:0f:b6:3a:1d:c8:ac:a3:b2:
                    2c:12:79:b8:88:bd:23:9a:7b:cb:09:f9:e7:67:be:
                    5b:3b:17:e8:1e:93:56:49:99:3b:de:b0:ef:5a:5b:
                    e4:6e:a7:33:4d:5a:d1:9b:aa:a8:25:43:76:5f:61:
                    6a:67:0a:07:c9:1b:bd:3f:bc:b4:f7:de:ea:87:e3:
                    02:e5
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:bd75207aab08533e0c1d85005a1ec43e.fe52c18653354be40fdeffa5cad17fa7.acme.invalid
    Signature Algorithm: sha256WithRSAEncryption
         37:3d:1d:90:43:cd:06:27:a5:11:28:7a:99:28:5e:79:c6:f1:
         77:19:97:68:0f:92:8e:49:f0:41:bc:96:2b:fb:e9:aa:76:d7:
         6b:f9:15:a3:90:4a:24:1b:9c:74:46:f4:0d:81:fe:e3:8a:25:
         e4:7d:25:ba:d3:bd:4e:d6:09:89:be:97:fe:7b:3c:5c:c6:ff:
         94:67:df:a1:58:43:69:ba:f9:ba:be:81:3b:fb:9e:bc:8a:43:
         35:cf:f3:e9:ba:8c:2a:81:5c:7e:8f:a8:7b:2d:1f:96:9f:13:
         10:80:c5:e4:54:10:1b:e3:20:49:9d:c4:c6:83:bc:56:10:54:
         ae:d0:b2:76:5b:fd:29:6a:b3:86:b7:63:dc:22:af:d6:c3:1a:
         dd:05:5c:a8:b1:57:8d:b7:a5:04:20:97:4f:8a:a5:d5:ac:a9:
         13:18:af:98:d1:c0:84:78:ad:ca:d0:c5:d7:e0:f1:ff:1a:b9:
         ad:8a:be:a5:3a:22:fd:d0:f2:65:31:8d:59:77:75:21:fd:22:
         51:e5:cf:44:23:5f:ea:35:26:ac:e0:68:de:ba:e2:0a:92:9d:
         e8:e2:e0:ee:fe:42:ed:b7:12:d5:2d:4d:fa:4f:58:07:99:4c:
         83:dc:73:76:76:89:92:f2:4f:25:b6:77:26:36:23:4c:1c:be:
```

### LINKED ISSUE #3044: GridDomainAuthorization remains in :requested state if challenge verify fails
The `GridCertificates::Request` mutation attempts to set [`domain_authorization.state = :invalid`](https://github.com/kontena/kontena/blob/61b6f5ce2924032aed911ed44fdbf2dcce578bb1/server/app/mutations/grid_certificates/request_certificate.rb#L59) when the acme `challenge.verify_status` becomes `invalid`, but that doesn't actually work because `:invalid` is not a valid `GridDomainAuthorization#state`... this is because defining `:invalid` as a `mongoid-enum` value collides some mongoid `invalid?` method:

```
  1) Rpc::ServicePodSerializer#to_hash [:secrets] with a validated TLS-SNI-01 domain authorization does not include the challenge cert as a secret
     Failure/Error: GridDomainAuthorization.create!(grid: grid,
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # (eval):1:in `invalid?'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:115:in `prepare_insert'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:23:in `insert'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:180:in `block in create!'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/threaded/lifecycle.rb:161:in `_creating'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:175:in `create!'
     # ./spec/serializers/rpc/service_pod_serializer_spec.rb:254:in `block (5 levels) in <top (required)>'
```

The mutation should probably use the `error` or some new `rejected` state instead.

This is hard to notice during testing because the [`domain_authorization.save`](https://github.com/kontena/kontena/blob/61b6f5ce2924032aed911ed44fdbf2dcce578bb1/server/app/mutations/grid_certificates/request_certificate.rb#L63) fails silently, as the return value is ignored. Changing it to use `save!` demonstrates this issue:

```
Mongoid::Errors::Validations (
message:
  Validation of GridDomainAuthorization failed.
summary:
  The following errors were found: State is not included in the list
resolution:
  Try persisting the document with valid data or remove the validations.):
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable.rb:78:in `fail_due_to_validation!'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/savable.rb:45:in `save!'
  /app/app/mutations/grid_certificates/request_certificate.rb:65:in `verify_domain'
  /app/app/mutations/grid_certificates/request_certificate.rb:82:in `block in execute'
  /app/app/mutations/grid_certificates/request_certificate.rb:81:in `each'
  /app/app/mutations/grid_certificates/request_certificate.rb:81:in `execute'
  /usr/lib/ruby/gems/2.4.0/gems/mutations-0.8.1/lib/mutations/command.rb:80:in `run'
  /usr/lib/ruby/gems/2.4.0/gems/mutations-0.8.1/lib/mutations/command.rb:32:in `run'
  /app/app/routes/v1/grids/grid_certificates.rb:8:in `block (2 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:758:in `_verb'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:540:in `post'
  /app/app/routes/v1/grids/grid_certificates.rb:5:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `route'
  /app/app/routes/v1/grids_api.rb:110:in `block (3 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:109:in `block (2 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:55:in `block in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/error_handler.rb:66:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:857:in `match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `block in match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `all?'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:831:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/server.rb:54:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/server.rb:53:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /app/app/middlewares/version_injector.rb:12:in `call'
  /app/app/middlewares/token_authentication.rb:70:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:74:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2963 to only have the server deploy pending domain authorization challenge certs to the LB service
Also fixes #3025 to order the TLS-SNI challenge certs after any other `secrets`/`certificates`
Also fixes #3044 to mark invalid challenges as `error` and no longer deploy them after verification fails

Domain authorizations that have been validated, rejected or expired will be omitted from the next LB service deploy. Note that this doesn't actually trigger a deploy or service update to perturb the LB service: any deployed challenge certs will remain deployed, and get lazily cleaned up on the next actual deploy.

This should be enough for the Kontena master to automatically reduce the TLS-SNI-01 challenge cert bloat that causes issues re #2924 `SSL_CERTS` env size limits.

The domain authorization list/delete API/commands in #2964 may still be relevant in some more specialized cases, like accidentally trying to authorize the wrong domain, and wanting to cancel the domain authorization.

### CODE REVIEW

File: server/app/mutations/grid_certificates/request_certificate.rb [hunk 1]
```diff
@@ -17,56 +16,7 @@ class RequestCertificate < Mutations::Command
...
-
-      wait_until!("domain verification for #{domain} is valid", interval: 1, timeout: 30, threshold: 10) {
-        challenge.verify_status != 'pending'
-      }
-
-      case challenge.verify_status
-      when 'valid'
-        domain_authorization.state = :validated
-      when 'invalid'
-        domain_authorization.state = :invalid
```
Comment (SpComb) [inline server/app/mutations/grid_certificates/request_certificate.rb]: Can't use `:invalid` as a mongoid enum valid, it will result in an `invalid?` method on the model that overrides some mongoid API:

```
  1) Rpc::ServicePodSerializer#to_hash [:secrets] with a validated TLS-SNI-01 domain authorization does not include the challenge cert as a secret
     Failure/Error: GridDomainAuthorization.create!(grid: grid,
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # (eval):1:in `invalid?'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:115:in `prepare_insert'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:23:in `insert'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:180:in `block in create!'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/threaded/lifecycle.rb:161:in `_creating'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:175:in `create!'
     # ./spec/serializers/rpc/service_pod_serializer_spec.rb:254:in `block (5 levels) in <top (required)>'
```

File: server/app/mutations/grid_certificates/common.rb [hunk 2]
```diff
@@ -64,5 +69,84 @@ def validate_dns_record(domain, expected_record)
...
     end
+
+    # @param domain_authorization [GridDomainAuthorization]
+    def validate_domain_authorization(authz)
+
+      case authz.authorization_type
+      when 'dns-01'
+        # Check that the expected DNS record is already in place
+        unless check_dns_record(authz.domain, authz.challenge_opts['record_content'])
+          add_error(:dns_record, :invalid, "Expected DNS record not present for domain #{authz.domain}") # XXX: validations error type
```
Comment (SpComb) [inline server/app/mutations/grid_certificates/common.rb]: The mutations error should be related to the input fields... so these should really be like `add_error(:domains, :dns_verification_challenge, "...")`

File: server/app/mutations/grid_certificates/common.rb [hunk 3]
```diff
@@ -64,5 +69,84 @@ def validate_dns_record(domain, expected_record)
...
+        end
+      end
+    end
+
+    # @param domains [Array<String>]
+    def validate_authorizations_for_domains(domains)
+      domains.each do |domain|
+        unless domain_authorization = get_authz_for_domain(self.grid, domain)
+          add_error(:authorization, :not_found, "Domain authorization not found for domain #{domain}") # XXX: validations error type
```
Comment (SpComb) [inline server/app/mutations/grid_certificates/common.rb]: The mutations error should be related to the input fields... so these should really be like `add_error(:domains, :domain_authorization, "...")`

File: server/app/mutations/grid_certificates/common.rb [hunk 4]
```diff
@@ -64,5 +69,84 @@ def validate_dns_record(domain, expected_record)
...
+        else
+          add_error(:request_verification, :failed, "Requesting verification failed")
+        end
+      end
+
+      wait_until!("domain verification for #{domain} is valid", interval: 1, timeout: 30, threshold: 10) {
+        challenge.verify_status != 'pending'
+      }
+
+      domain_authorization.expires = nil # XXX: old version of acme-client does not update authorization expiration
```
Comment (SpComb) [inline server/app/mutations/grid_certificates/common.rb]: The old 0.3.6 acme-client with `Acme::Client::Resources::Challenges::*.verify_status` does not allow us to see the updated `Acme::Client::Resources::Authorization.expires`, which changes when the ACME domain authorization goes from `pending` => `valid`.

The newer 0.6 version replaces the `challenge.verify_status` with [`authorization.verify_status`](https://github.com/unixcharles/acme-client/blob/bc5688bdc405053a864b7b50a22dee9b55bb6e05/lib/acme/client/resources/challenges/base.rb#L13) which does [update](https://github.com/unixcharles/acme-client/blob/bc5688bdc405053a864b7b50a22dee9b55bb6e05/lib/acme/client/resources/authorization.rb#L17) the `@expired` attribute.

That would be necessary for us to know when the validated domain authz expires. that would be relevant if we later re-request/renewing certificates for the same domains: the domains don't need to be re-authorized if the previous domain authz is still valid.

File: server/app/mutations/grid_certificates/common.rb (hunk 2 above)
Comment (jakolehm) [reply server/app/mutations/grid_certificates/common.rb]: I agree.

File: server/app/mutations/grid_certificates/common.rb (hunk 4 above)
Comment (jakolehm) [reply server/app/mutations/grid_certificates/common.rb]: Could we update `acme-client`?

Comment (SpComb) [reply server/app/mutations/grid_certificates/common.rb]: There's other breaking changes in the newer acme-client: https://github.com/kontena/kontena/pull/2565#issuecomment-321798538

The way that the `GridDomainAuthorization.challenge` has is used no long works... the model needs to be changed to store the `authorization.uri` for `client.fetch_authorization(...)` instead. Not something I want to do in a 1.4.x patch release...

That change also isn't strictly relevant for the fix here... only if we want to track `expires` for validated domain authorizations.

**Comment by SpComb** [comment]
Maybe I'll do a smaller version of this without the refactoring, with just enough changes to track the `expires`. The refactoring can happen later together with the acme-client upgrade to track the authz expiry after the validation.

**Comment by SpComb** [comment]
Simplified this for 1.4.1. The refactoring really isn't worth the trouble until we also update acme-client to track authz expiry after validation, but that's an extra feature, not a fix.

**Comment by SpComb** [comment]
Also bundled a fix for #3025 here - with the spec cleanup, it's too much wasted effort to try and make a separate PR for it.

**Comment by SpComb** [comment]
I remembered that there's a `GET /v1/grids/:grid/domain_authorizations` API, so that should probably also include the new `expires` field, although it won't actually be used anywhere yet.

File: server/app/views/v1/domain_authorizations/_domain_authorization.json.jbuilder [hunk 5]
```diff
@@ -4,6 +4,7 @@ json.status authorization.status
 json.challenge authorization.challenge
 json.challenge_opts authorization.challenge_opts
 json.authorization_type authorization.authorization_type
+json.expires authorization.expires
```
Comment (jakolehm) [inline server/app/views/v1/domain_authorizations/_domain_authorization.json.jbuilder]: Should it be `expires_at` ?

Comment (SpComb) [reply server/app/views/v1/domain_authorizations/_domain_authorization.json.jbuilder]: Yes, it should... and I figure the model field should also be `expires_at`?

File: server/app/mutations/grid_certificates/request_certificate.rb (hunk 1 above)
Comment (SpComb) [reply server/app/mutations/grid_certificates/request_certificate.rb]: This is actually broken, but the `save` fails silently:  #3044

File: server/app/views/v1/domain_authorizations/_domain_authorization.json.jbuilder (hunk 5 above)
Comment (SpComb) [reply server/app/views/v1/domain_authorizations/_domain_authorization.json.jbuilder]: Changed both the JSON API and the model to use `expires_at`.

**Comment by SpComb** [comment]
Also fixed  #3044

```
$ bin/kontena certificate authorize --type tls-sni-01 --linked-service ingress-lb/lb 192.0.2.1.xip.io
 [done] Waiting for tls-sni-01 certificate to be deployed into development/ingress-lb/lb      
TLS-SNI challenge certificate is deployed, you can now request the actual certificate
irb(main):008:0> GridDomainAuthorization.where(domain: '192.0.2.1.xip.io').each do |a| puts "#{a.to_path} #{a.status} (pending=#{a.pending?} expires_at=#{a.expires_at} deployable=#{a.deployable?})" end     
development/192.0.2.1.xip.io created (pending=true expires_at=2017-11-21T12:51:20+00:00 deployable=true)
```

```
$ bin/kontena certificate request 192.0.2.1.xip.io [fail] Requesting certificate for 192.0.2.1.xip.io      
 [error] 422 : Unprocessable Entity:
	challenge: No valid IP addresses found for 192.0.2.1.xip.io
irb(main):010:0> GridDomainAuthorization.where(domain: '192.0.2.1.xip.io').each do |a| puts "#{a.to_path} #{a.status} (pending=#{a.pending?} expires_at=#{a.expires_at} deployable=#{a.deployable?})" end                                                                                                                                                                                                                               
development/192.0.2.1.xip.io error (pending=false expires_at= deployable=false)
```

The invalid challenge certs will no longer get deployed and clutter the LB services either.

File: server/app/models/grid_domain_authorization.rb [hunk 6]
```diff
@@ -13,6 +13,7 @@ class GridDomainAuthorization
   field :challenge, type: Hash
   field :challenge_opts, type: Hash # TODO encrypt?
   field :authorization_type, type: String, default: 'tls-sni-01'
+  field :expires_at, type: DateTime
```
Comment (jakolehm) [inline server/app/models/grid_domain_authorization.rb]: `Time` vs `DateTime` ?

Comment (SpComb) [reply server/app/models/grid_domain_authorization.rb]: Right... must have been copypasta from the `Certificate.valid_until` model.

**Comment by kke** [comment]
Re-review requested @jakolehm

File: server/docs/source/index.html.md [hunk 7]
```diff
@@ -1490,6 +1491,7 @@ Let's Encrypt domain authorization management for certificate handling.
 - `created`: authorization has been created, no firther actions yet taken
 - `deploying`: The related tls-sni certificate is currently being deployed to linked service. Only valid for tls-sni type of authorizations
 - `deploy_error`: The deployment of the linked service has errored out, more details can be found from the linked services event logs
+- `expired`: The domain authorization can no longer be used to request a certificate, the domain must be re-authorized
```
Comment (jakolehm) [inline server/docs/source/index.html.md]: Should this be `expires_at` ?

Comment (SpComb) [reply server/docs/source/index.html.md]: That's the `status` value, not the JSON `expired_at` field.

Comment (jakolehm) [reply server/docs/source/index.html.md]: Right, but it seems that not all object attributes are documented.

Comment (SpComb) [reply server/docs/source/index.html.md]: Not sure what you mean - only the `challenge_opts` and `status` fields have some kind of extra docs apart from the JSON example?

I guess the domain authz/certificates are missing the attribute/description table.
