### PR TITLE
Validate tls-sni domain authorization linked service port

### LINKED ISSUE #3128: Tls-sni authorize should error out if linked lb does not expose port 443
Because it cannot work.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #3128

### CODE REVIEW

File: server/app/mutations/domain_authorizations/authorize.rb [hunk 1]
```diff
@@ -23,11 +23,16 @@ def validate
...
-        add_error(:linked_service, :missing, "Service link needs to be given for tls-sni-01 authorization type") unless self.linked_service
+      if self.authorization_type == 'tls-sni-01' && self.linked_service.nil?
+        add_error(:linked_service, :missing, "Service link needs to be given for tls-sni-01 authorization type")
       end
       if self.linked_service
-        add_error(:linked_service, :not_found, "Linked service needs to point to existing service") unless @linked_service = resolve_service(self.grid, linked_service)
+        @lb_service = resolve_service(self.grid, linked_service)
+        if @lb_service.nil?
+          add_error(:linked_service, :not_found, "Linked service needs to point to existing service")
+        elsif @lb_service && !@lb_service.ports.include?(443)
```
Comment (jnummelin) [inline server/app/mutations/domain_authorizations/authorize.rb]: or if the service is in `net: host` mode

File: server/app/mutations/domain_authorizations/authorize.rb [hunk 2]
```diff
@@ -23,11 +23,16 @@ def validate
...
         add_error(:le_registration, :missing, "Let's Encrypt registration missing")
       end
-      if self.authorization_type == 'tls-sni-01'
-        add_error(:linked_service, :missing, "Service link needs to be given for tls-sni-01 authorization type") unless self.linked_service
+      if self.authorization_type == 'tls-sni-01' && self.linked_service.nil?
+        add_error(:linked_service, :missing, "Service link needs to be given for tls-sni-01 authorization type")
       end
       if self.linked_service
-        add_error(:linked_service, :not_found, "Linked service needs to point to existing service") unless @linked_service = resolve_service(self.grid, linked_service)
+        @lb_service = resolve_service(self.grid, linked_service)
```
Comment (jnummelin) [inline server/app/mutations/domain_authorizations/authorize.rb]: Originally, I tried to avoid using `lb_*` as variable names :), technically one can map the tls-sni cert into any service. Yes, in 99.99% of the cases it will be a LB

File: server/app/mutations/domain_authorizations/authorize.rb (hunk 1 above)
Comment (SpComb) [inline server/app/mutations/domain_authorizations/authorize.rb]: The `GridService.ports` is not an array of integers:

```
irb(main):002:0> GridService.find_by(name: 'lb').ports
=> [{"ip"=>"0.0.0.0", "protocol"=>"tcp", "node_port"=>80, "container_port"=>80}, {"ip"=>"0.0.0.0", "protocol"=>"tcp", "node_port"=>443, "container_port"=>443}]
```

**Comment by SpComb** [comment]
And technically you could also be exposing the TLS service on a different non-443 port, if you have some external loadbalancer that's mapping it to port :443.

Dunno if this needs some kind of override flag for the validation check?

**Comment by SpComb** [comment]
Maybe a better way to validate this would be in the `GridCertificates::RequestCertificate`, similarly to how it's done for `dns-01` challenges: have the server connect to the authorized domain on port :443

File: server/app/mutations/domain_authorizations/authorize.rb (hunk 2 above)
Comment (jakolehm) [reply server/app/mutations/domain_authorizations/authorize.rb]: Ok, the reason for variable name change was that it did override `linked_service` from mutation (that is a string).

File: server/app/mutations/domain_authorizations/authorize.rb (hunk 1 above)
Comment (jakolehm) [reply server/app/mutations/domain_authorizations/authorize.rb]: Fixed.

Comment (jakolehm) [reply server/app/mutations/domain_authorizations/authorize.rb]: Fixed.

**Comment by jakolehm** [comment]
@jnummelin PTAL

**Comment by SpComb** [comment]
> Maybe a better way to validate this would be in the GridCertificates::RequestCertificate, similarly to how it's done for dns-01 challenges: have the server connect to the authorized domain on port :443

I can also take a go at implementing this method of external validation... the only issue would be if the server is unable to connect to the external domain for whatever reason.

File: server/app/mutations/domain_authorizations/authorize.rb [hunk 3]
```diff
@@ -23,11 +23,16 @@ def validate
...
+        if @lb_service.nil?
+          add_error(:linked_service, :not_found, "Linked service needs to point to existing service")
+        elsif @lb_service && @lb_service.net != 'host' && !@lb_service.ports.any? { |p| p['node_port'] == 443 }
```
Comment (jnummelin) [inline server/app/mutations/domain_authorizations/authorize.rb]: would it makes sense to have this kind of check on the `GridService` model? I mean something like `@lb_service.https_open?`

**Comment by jnummelin** [comment]
> I can also take a go at implementing this method of external validation... the only issue would be if the server is unable to connect to the external domain for whatever reason.

I don't think we can ever make it 100% reliable given how external things can influence, so maybe some override/force flag would make sense.

File: server/app/mutations/domain_authorizations/authorize.rb (hunk 3 above)
Comment (jakolehm) [reply server/app/mutations/domain_authorizations/authorize.rb]: Imho does not make really sense to move this logic into the `GridService` model. I can refactor this code if necessary ...

Comment (jnummelin) [reply server/app/mutations/domain_authorizations/authorize.rb]: for me having many conditionals and some of those negated, makes it hard to read. :) maybe simplify it by just removing the first `@lb_service` "condition", it shouldn't be falsey in the `elsif` branch?

Comment (jakolehm) [reply server/app/mutations/domain_authorizations/authorize.rb]: Refactored.

**Comment by SpComb** [comment]
>> Maybe a better way to validate this would be in the GridCertificates::RequestCertificate, similarly to how it's done for dns-01 challenges: have the server connect to the authorized domain on port :443
> 
> I can also take a go at implementing this method of external validation... the only issue would be if the server is unable to connect to the external domain for whatever reason.

Implemented in #3152... OTOH that might be a useless approach, because the ACME API will already return similar errors... they're maybe just a bit terse.

**Comment by kke** [comment]
@SpComb is this still going to 1.4.3?

**Comment by SpComb** [comment]
Bumping from 1.4.3 to 1.5.0 unless someone convinces me that we can't release 1.4.3 without this.

I haven't had a chance to actually test the validation here yet.

**Comment by kke** [comment]
@SpComb still going to test?
