### PR TITLE
Fix stack deploy service removal

### LINKED ISSUE #1769: Stack upgrade can remove linked-to services, breaking linking services
Having a service that links to a service in a different stack, and then using `kontena stack upgrade` to remove that linked-to service, results in a nil [`grid_service.grid_service_links[...].linked_grid_service`. This is normally impossible, as the `kontena service rm` -> server `DELETE /v1/services/:grid_name/:stack_name/:service_name` -> `GridServices::Delete` validation refuses to remove a service that is linked to.

This results in `kontena service ls` HTTP 500 errors:  #1741

The server's `StackDeployWorker#remove_services`  should not remove services that are still linked. The `Stacks::Update` mutation should also validate these.

## Example
```
$ kontena stack install --deploy links-test.yaml
$ kontena stack install --deploy links-test2.yaml
# edit the links-test.yaml to remove the test1 service
$ kontena stack upgrade --deploy links links-test.yaml
$ kontena service ls
 [error] Internal Server Error
```

The server error is on the `links2/test2` service, and running `kontena service rm links2/test2` fixes this situation.

#### `links-test.yaml`
```yaml
stack: test/links
services:
    test1:
        image: redis
    test2:
        image: redis
```

#### `links-test2.yaml`
```yaml
stack: test/links2
services:
    test2:
        image: redis
        links:
          - links/test1
```

### Server error
```

NoMethodError (undefined method `to_path' for nil:NilClass
Did you mean?  to_a):
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/_grid_service.json.jbuilder:37:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `method_missing'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/embedded/many.rb:404:in `method_missing'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/_grid_service.json.jbuilder:36:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/index.json.jbuilder:19:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block (2 levels) in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `_map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:180:in `array!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `block in set!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `set!'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/index.json.jbuilder:14:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/render.rb:216:in `render'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:33:in `block (3 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:448:in `is'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:24:in `block (2 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:376:in `get'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:23:in `block in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `route'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids_api.rb:37:in `block (2 levels) in <class:GridsApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids_api.rb:35:in `block in <class:GridsApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/server.rb:54:in `block (2 levels) in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/server.rb:53:in `block in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/app/middlewares/version_injector.rb:12:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/token_authentication.rb:73:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:140:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:46:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

127.0.0.1 - - [02/Feb/2017:12:08:16 +0200] "GET /v1/grids/development/services?stack= HTTP/1.1" 500 35 0.0759
```

### LINKED ISSUE #2116: e2e stack install with broken link specs broken
Broken by the #1976 changes in error outptu:

```
  3) stack install For a stack with a broken link Returns an error
     Failure/Error: expect(k.out).to match /Service validate failed for service 'a': Linked service 'nope' does not exist/
     
       expected "    *   Creating stack \e[36mlinks\e[0m  .. \\\r                                  \r\r    *   Creati...ocessable Entity:\r\n\tservices:\r\n\t  a:\r\n\t    links: Linked service 'nope' does not exist\r\n" to match /Service validate failed for service 'a': Linked service 'nope' does not exist/
       Diff:
       @@ -1,2 +1,6 @@
       -/Service validate failed for service 'a': Linked service 'nope' does not exist/
 [fail] Creating stack links      ks  .. \
       + [error] Kontena::Errors::StandardErrorHash : Unprocessable Entity:
       +	services:
       +	  a:
       +	    links: Linked service 'nope' does not exist
       
     # ./spec/features/stack/install_spec.rb:51:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:29:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:28:in `chdir'
     # ./spec/support/shell.rb:28:in `with_fixture_dir'
     # ./spec/features/stack/install_spec.rb:48:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1769
Also fixes #2116

The `StackRemoveWorker` used `GridService.destroy` to remove deployed stack services that are no longer in the newly deployed stack. This skipped all of the validations, node service pod terminate notifications and lb removals in the `GridServices::Delete` mutation.

* Fix the `Stacks::Update` mutation to validate removed services

    This will fail `kontena stack upgrade` early if removing a linked service.

* Fix the `Stacks::Deploy` -> `StackRemoveWorker` to use `GridServices::Delete` for service removal

  * This validates and fails if removing a linked service. Even with the `Stacks::Update` validation, this can still happen if a new linking service is created between the stack update and deploy.

  * Changes the stack service removal to also send notify nodes of the service instance/pod termination, and perform any LB service removal

* Add e2e specs

## TODO

* The stack deploy errors are only logged, not returned via the stacks deploy API

### CODE REVIEW

**Comment by SpComb** [comment]
@jakolehm any reason not to do the `GridServices::Delete` node service pods notify and lb removal in the stacks deploy worker?

File: server/spec/jobs/stack_deploy_worker_spec.rb [hunk 1]
```diff
@@ -59,10 +61,12 @@
           {name: 'lb', image: 'kontena/lb:latest', stateful: false }
         ]
       )
-      expect(outcome.success?).to be_truthy
+
       stack_rev = stack.latest_rev
-      expect(subject.wrapped_object).not_to receive(:remove_service)
```
Comment (SpComb) [inline server/spec/jobs/stack_deploy_worker_spec.rb]: Spec was bad, there is no `remove_service` method that gets called.

File: server/spec/mutations/stacks/deploy_spec.rb [hunk 2]
```diff
@@ -39,47 +44,16 @@
...
-        source: '...',
-        services: [
-          {name: 'nginx', image: 'nginx:latest', stateful: false }
-        ]
-      )
-      worker = Celluloid::Actor[:stack_deploy_worker]
-      redis = stack.grid_services.find_by(name: 'redis')
-      mutation = described_class.new(stack: stack)
-      mutation.run
-      sleep 0.01 until worker.mailbox.size == 0
```
Comment (SpComb) [inline server/spec/mutations/stacks/deploy_spec.rb]: This spec was flaky before... the actor can have tasks running even if the mailbox is empty
