### PR TITLE
Stack deploy error reporting

### LINKED ISSUE #2196: CLI: kontena stack deploy does not report instance deploy errors
The `kontena stack deploy` command (also used by `kontena stack install` and `upgrade`) does not report instance deploy errors:

```
$ kontena stack install test/test.yaml
 [done] Creating stack test      
 [done] Triggering deployment of stack test     
 [done] Waiting for deployment to start     
 [done] Deploying service foo     
halting deploy of development/test/foo, one or more instances failed
```

Workaround: In order to see why the deploy failed, re-deploy the failed service using the `kontena service deploy` command:

```
$ kontena service deploy test/foo
 [fail] Deploying service test/foo      
 [error] Kontena::Errors::StandardErrorArray : halting deploy of development/test/foo, one or more instances failed:
	⊗ Failed to deploy instance development/test/foo-1 to node core-01: GridServiceInstanceDeployer::ServiceError: Docker::Error::ServerError: Cannot restart container d07a6f80aed2de105223209d461fcb63b16....
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #2196

### CODE REVIEW

File: cli/lib/kontena/cli/stacks/deploy_command.rb [hunk 1]
```diff
@@ -21,7 +21,13 @@ def execute
       spinner "Waiting for deployment to start" do
         wait_for_deployment_to_start(deployment)
       end
-      wait_for_deploy_to_finish(deployment)
+      errors = wait_for_deploy_to_finish(deployment)
+      if errors.empty?
+        puts pastel.green("Finished")
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/deploy_command.rb]: `$stderr`

File: cli/lib/kontena/cli/stacks/stacks_helper.rb [hunk 2]
```diff
@@ -52,14 +53,18 @@ def wait_for_deploy_to_finish(deployment, timeout = 600)
         if deployment['state'] == 'error'
           deployment['service_deploys'].each do |service_deploy|
             if service_deploy['state'] == 'error'
-              error service_deploy['reason']
+              errors << pastel.red("#{service_deploy['service_id']} deploy failed: #{service_deploy['reason']}")
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: Just use `warn` or `$stderr.puts` to print out each of these errors, instead of using the `error` function that exits.

File: cli/lib/kontena/cli/stacks/stacks_helper.rb [hunk 3]
```diff
@@ -52,14 +53,18 @@ def wait_for_deploy_to_finish(deployment, timeout = 600)
...
+              service_deploy['instance_deploys'].each do |instance_deploy|
+                if instance_deploy['state'] == 'error'
+                  errors << pastel.red(" - #{instance_deploy['error']} on node #{instance_deploy['node']}")
+                end
+              end
             end
           end
-          abort
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: Keep the exit-on-error behavior.

File: cli/lib/kontena/cli/stacks/stacks_helper.rb [hunk 4]
```diff
@@ -52,14 +53,18 @@ def wait_for_deploy_to_finish(deployment, timeout = 600)
...
         end
       end
 
-      deployed
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: Not all callers of this function check the return value.

File: cli/lib/kontena/cli/stacks/deploy_command.rb (hunk 1 above)
Comment (kke) [inline cli/lib/kontena/cli/stacks/deploy_command.rb]: Success message doesn't belong to stderr

File: cli/lib/kontena/cli/stacks/stacks_helper.rb [hunk 5]
```diff
@@ -52,16 +53,25 @@ def wait_for_deploy_to_finish(deployment, timeout = 600)
...
+                  errors << pastel.red(" - #{instance_deploy['error']} on node #{instance_deploy['node']}")
+                end
+              end
             end
           end
-          abort
         end
       end
 
+      unless errors.empty?
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: The `deployment['state']` can be `error` even if none of the services or service instances were errored.

Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: Although sadly there is no stack-level `deployment['error']` message to show in these kinds of cases, it's only in the server logs.

This can happen in e.g. the #2128 case of deploying an upgraded stack after some other service has linked to a service that is being removed.

**Comment by kke** [comment]
image

File: cli/lib/kontena/cli/stacks/stacks_helper.rb [hunk 6]
```diff
@@ -32,6 +31,7 @@ def wait_for_deploy_to_finish(deployment, timeout = 600)
       deployed = false
       states = %w(success error)
       tracked_services = []
+      errors = []
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: unused array

File: cli/lib/kontena/cli/stacks/stacks_helper.rb [hunk 7]
```diff
@@ -52,7 +52,13 @@ def wait_for_deploy_to_finish(deployment, timeout = 600)
         if deployment['state'] == 'error'
           deployment['service_deploys'].each do |service_deploy|
             if service_deploy['state'] == 'error'
-              error service_deploy['reason']
+              $stderr.puts "Deployment of service #{pastel.cyan(service_deploy['service_id'])} failed:"
+              $stderr.puts "  - #{service_deploy['reason'].strip}"
+              service_deploy['instance_deploys'].each do |instance_deploy|
+                if instance_deploy['state'] == 'error'
+                  $stderr.puts "  - " + "#{instance_deploy['error'].strip} (on node #{pastel.cyan(instance_deploy['node'])})"
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: Does not say which instance number failed.

Comment (kke) [inline cli/lib/kontena/cli/stacks/stacks_helper.rb]: Is that interesting information?

File: cli/lib/kontena/cli/stacks/deploy_command.rb [hunk 8]
```diff
@@ -22,6 +22,7 @@ def execute
         wait_for_deployment_to_start(deployment)
       end
       wait_for_deploy_to_finish(deployment)
+      puts pastel.green("Finished")
```
Comment (SpComb) [inline cli/lib/kontena/cli/stacks/deploy_command.rb]: Kind of unnecesary
