### PR TITLE
Fix service scale to set service running state

### LINKED ISSUE #2290: Service can be deployed in initialized state
It is possible for a service to be deployed with running instances while the service itself is still in the `initialized` state. This seems like a weird inconsistency.

The server has explicit code to deal with services in the `initialized` state while deploying, but those should not be needed if the services were fixed to be `running`:

* [`GridServiceSchedulerWorker`](https://github.com/kontena/kontena/blob/416ac835903b145b7251e6da0dc13418f1c9a123/server/app/jobs/grid_service_scheduler_worker.rb#L33) `elsif service_deploy.grid_service.running? || service_deploy.grid_service.initialized?`
* [`GridServiceDeployer`](https://github.com/kontena/kontena/blob/cadde67cf43b55de032f548529787301c2f15fd5/server/app/services/grid_service_deployer.rb#L61) `unless self.grid_service.running? || self.grid_service.initialized?`

### Create and scale a service without deploying it
```
$ kontena service create redis-test redis
 [done] Creating redis-test service      
$ kontena service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ redis-test                                                 0 / 1      no       initialized                                                   
```
```
$ kontena service scale redis-test 1
 [done] Scaling redis-test to 1 instances      
⊛ Deployed instance test/null/redis-test-1 to node terom-test2-1
$ kontena service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ redis-test                                                 1 / 1      no       initialized                                                   
```

### Deploying stack with dependent services
Deploying a stack that has services using `volumes_from` to depend on eachother:

```
$ kontena service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ vols-from/web                                              1 / 1      no       initialized                                                   
⊝ vols-from/nginx                                            1 / 1      no       initialized                                                   
⊝ vols-from/redis                                            1 / 1      no       running   
```

### PR DESCRIPTION
**Pull request by SpComb**
Split out of #3277
Fixes #2290 `GridServices::Scale` can leave the service in the `initialized` state

Set the `GridService.state` to `running` for `GridServices::Scale` when deploying the service.

Includes `GridServices::Deploy` refactoring for #3277.

Services will no longer get deployed in the `initialized` state, removing some special cases.

### CODE REVIEW

**Comment by SpComb** [comment]
This is the first PR in the associated series of PRs to fix `kontena stack rm --wait`. The remainder are WiP waiting for this to get merged.

File: server/app/mutations/grid_services/helpers.rb [hunk 1]
```diff
@@ -42,5 +42,17 @@ def update_grid_service(grid_service, force: false)
...
     end
+
+    # @param grid_service [GridService]
+    # @param state [String] desired state
+    # @param force [Boolean] force-update revision
+    def deploy_grid_service(grid_service, state = 'running', force: false)
+      grid_service.deploy_requested_at = Time.now.utc
+      grid_service.state = state
+
+      if force ? update_grid_service(grid_service, force: true) : save_grid_service(grid_service)
```
Comment (jakolehm) [inline server/app/mutations/grid_services/helpers.rb]: A bit hard to read.

Comment (SpComb) [reply server/app/mutations/grid_services/helpers.rb]: This is existing code that was just moved from the `GridServices::Deploy#execute`. The control flow is for dealing with the non-exceptions-based mutations `add_error` case: do not create the deploy if the update/save fails.

Cleaning this up would probably be having the `update_grid_service`/`save_grid_service` return an error instead, but then it would get messy figuring out where to deal with those exceptions and convert them into mutations `add_error` instead.
