### PR TITLE
Always create HostNode with unique name and node_number

### LINKED ISSUE #2071: Race condition on reserve_node_number with concurrent node creates
From the logs:

```
E, [2017-04-05T10:55:04.134330 #98] ERROR -- WebsocketBackend: Moped::Errors::OperationFailure: The operation: #<Moped::Protocol::Command
api_1      |   @length=83
api_1      |   @request_id=847
api_1      |   @response_to=0
api_1      |   @op_code=2004
api_1      |   @flags=[]
api_1      |   @full_collection_name="kontena_development.$cmd"
api_1      |   @skip=0
api_1      |   @limit=-1
api_1      |   @selector={:getlasterror=>1, "w"=>1}
api_1      |   @fields=nil>
api_1      | failed with error 11000: "E11000 duplicate key error index: kontena_development.host_nodes.$grid_id_1_node_number_1 dup key: { : ObjectId('58e4cb98ea110f005400001a'), : null }"
api_1      | 
api_1      | See https://github.com/mongodb/mongo/blob/master/docs/errors.md
api_1      | for details about this error.
```

### LINKED ISSUE #2558: Difficult to get rid of a node that is missing a name and stuck as (initializing)
When a new agent first connects, the server will create a new `HostNode` with the node ID sent by the agent, but without any `name`. These nodes without any name show up in `kontena node list` as `(initializing)`:

```
NAME               VERSION     STATUS   INITIAL   LABELS
⊛ core-01          1.4.0.dev   online   1 / 1     test
⊛ core-02          1.4.0.dev   online   -         test=label,test=2,ephemeral=true
⊛ (initializing)               online   -
```

If the agent never manages to send the initial node info update, then the node will be stuck in that state. While the server API allows deleting such nodes using `DELETE /v1/nodes/:grid/:node_id` (vs the typical `DELETE /v1/nodes/:grid/:name`), and the cli `kontena node remove` command also accepts such a node ID as an alternative to the name, figuring out the node ID is very difficult - the only way is probably using `DEBUG=api kontena node list`, and picking it out from the raw JSON.

* Fix `kontena node list` to show the node ID instead of the name, if missing?
* Change the agent to send the hostname as a `Kontena-Node-Name` header in the initial websocket connect, so that the server can immediately create the new `HostNode`s with a name already in place, without needing to wait for the node info update RPC?

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2071, fixes #2542 by creating the nodes with a `node_number` set
Fixes #2558 by always having a node name available for `kontena node list`

* Send and validate both `Kontena-Node-ID` and `Kontena-Node-Name` headers in agent websocket connections
* Use `Grid.create_node!` to allocate the `node_number` before saving, retrying on `node_number` conflicts
* Create new `HostNode`s with the node name set for grid token connections, adding unique suffix if required
* Add validation and unique index on the `HostNode.name` (namespaced per grid)

* Validate the `HostNode.node_number` and change the unique index to be non-sparse

    It was already broken, seemingly failing with duplicate key errors on `node_number: null` with the `grid_id` set?

* Fix specs to use `grid.create_node!`

### CODE REVIEW

File: server/app/middlewares/websocket_backend.rb [hunk 1]
```diff
@@ -75,12 +75,32 @@ def call(env)
...
+  def create_node(grid, node_id, name, attrs)
+    node = grid.host_nodes.new(node_id: node_id, name: name, **attrs)
+    node.ensure_unique_name
+
+    if node.name != name
+      logger.warn "rename node #{node_id} on name collision: #{node.name}"
+    end
+
+    # XXX: this can still race with concurrent creates, and result in unique name index conflicts
+    node.save!
```
Comment (SpComb) [inline server/app/middlewares/websocket_backend.rb]: This can still fail with `Mongo::Error::OperationFailure`, but so can the `reserve_node_number`: #2071

The server `WebsocketBackend` does not close the agent websocket connection on unknown errors, so the agent will hang.

**Comment by SpComb** [comment]
WiP attempting to also fix #2071, and use the `node_number` as the name suffix at create-time.

File: server/app/models/grid.rb [hunk 2]
```diff
@@ -54,8 +56,43 @@ def to_json(args = {})
...
+
+      return node
+
+    rescue Mongo::Error::OperationFailure => exc
+      raise unless exc.message =~ /^E11000 duplicate key error/
+
+      if self.host_nodes.where(node_number: node.node_number).exists?
+        warn "retry node #{name} node_number allocation on error: #{exc}"
+        node.name = name
+        retry
```
Comment (SpComb) [inline server/app/models/grid.rb]: This retry is still missing specs.

File: server/app/models/grid.rb [hunk 3]
```diff
@@ -83,11 +92,10 @@ def create_node!(name, ensure_unique_name: false, **attrs)
 
       if self.host_nodes.where(node_number: node.node_number).exists?
         warn "retry node #{name} node_number allocation on error: #{exc}"
-        node.name = name
         retry
       elsif ensure_unique_name && self.host_nodes.where(name: node.name).exists?
         warn "rename node #{name} on name conflict: #{exc}"
-        node.name = "#{name}-#{node.node_number}"
```
Comment (SpComb) [inline server/app/models/grid.rb]: This logic was broken, it would re-use the wrong `node_number` for the suffix if that node_number happened to be allocated for a different node while this was retrying.

File: server/app/models/grid.rb [hunk 4]
```diff
@@ -83,11 +92,10 @@ def create_node!(name, ensure_unique_name: false, **attrs)
...
+        duplicate_name = true
```
Comment (SpComb) [inline server/app/models/grid.rb]: This logic was broken, it would re-use the wrong `node_number` for the suffix if that node_number happened to be allocated for a different node while this was retrying.

**Comment by SpComb** [comment]
@jakolehm PT(another)L
