### PR TITLE
Fix v1.1 server sharing of Moped::Session connections between threads

### LINKED ISSUE #1964: Server threads share Moped::Session connections
The server runs in a clustered puma configuration with two worker processes, each running a number of threads, including Celluloid threads, EventMachine threads, as well as custom threads. The `Moped::Session` class is not thread-safe: https://groups.google.com/forum/#!topic/mongoid/0pIRfVjTL_Y

> With Moped, you are "thread safe" as long as you only have 1 moped session instance on each thread, and don't share a Moped::Session across threads.

> With Mongoid, we automatically manage that session-per-thread requirement for Moped for you, so you would not need to worry about it in this case. If a new thread is spawned, Mongoid will create a new session on the thread.

Mongoid uses `Thread.current["[mongoid]:sessions"]` to keep track of a per-thread `Moped::Session`, ensuring that sessions are not shared across threads, and each thread has its own session. However, storing the result of something like `@db_session = ContainerLog.collection.session` bypasses this protection, meaning that the `@db_session` is now shared between any threads that access it:

```ruby
module Agent
  class MessageHandler
    attr_reader :db_session

    def initialize(...)
      ...
      @db_session = ContainerLog.collection.session.with(
        ...
      )
    end

    def run
      Thread.new {
        .... # something that calls on_node_stat(...)
      }
    end

    def on_node_stat(...)
      ....
      db_session[:host_node_stats].insert(stat)
    end
  end
end
```

Using the `Moped::Session` thread tracing implemented as part of #1965 reveals two such cases for a quick test of Kontena 1.1.4 with a single node connected.

The `Moped::Session[8] = ...` part shows which thread created the session and where. The following  Moped::Session[8] ! ...` part shows the conflicting access by a different thread.

## `MongoPubsub`
```
Moped::Session[8] = process=7 thread=#<Thread:0x0055d08cf862d8>:
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `new'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `create_session'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:43:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:37:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid.rb:65:in `default_session'
	/app/app/initializers/00_mongoid.rb:6:in `<top (required)>'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/app/app/boot.rb:22:in `block in require_glob'
	/app/app/boot.rb:21:in `each'
	/app/app/boot.rb:21:in `require_glob'
	/app/app/boot.rb:26:in `<top (required)>'
	config/puma.rb:8:in `require_relative'
	config/puma.rb:8:in `block in _load_from'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:426:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	/usr/bin/puma:22:in `load'
	/usr/bin/puma:22:in `<main>'
Moped::Session[8] ! process=7 thread=#<Celluloid::Thread:0x0055d090683b78>:
	/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:61:in `collection_names'
	/app/app/services/mongo_pubsub.rb:170:in `ensure_collection!'
	/app/app/services/mongo_pubsub.rb:142:in `tail!'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

## Kontena 1.1.x `Agent::MessageHandler`

This does not affect the current master RPC handlers, as those are Celluloid actors, which create their own session in their `initializer`?

```
Moped::Session[8] = process=11 thread=#<Thread:0x0055d08cf862d8>:
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `new'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `create_session'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:43:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:37:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid.rb:65:in `default_session'
	/app/app/initializers/00_mongoid.rb:6:in `<top (required)>'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/app/app/boot.rb:22:in `block in require_glob'
	/app/app/boot.rb:21:in `each'
	/app/app/boot.rb:21:in `require_glob'
	/app/app/boot.rb:26:in `<top (required)>'
	config/puma.rb:8:in `require_relative'
	config/puma.rb:8:in `block in _load_from'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:426:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	/usr/bin/puma:22:in `load'
	/usr/bin/puma:22:in `<main>'
Moped::Session[8] ! process=11 thread=#<Thread:0x0055d08fb9b0d0>:
	/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:50:in `[]'
	/app/app/services/agent/message_handler.rb:250:in `grid_container'
	/app/app/services/agent/message_handler.rb:100:in `on_container_event'
	/app/app/services/agent/message_handler.rb:64:in `handle_message'
	/app/app/services/agent/message_handler.rb:34:in `block (2 levels) in run'
	/app/app/services/agent/message_handler.rb:31:in `loop'
	/app/app/services/agent/message_handler.rb:31:in `block in run'
```

```
Moped::Session[8] ! process=11 thread=#<Thread:0x0055d08fb9b0d0>:
	/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:50:in `[]'
	/app/app/services/agent/message_handler.rb:250:in `grid_container'
	/app/app/services/agent/message_handler.rb:239:in `cached_container'
	/app/app/services/agent/message_handler.rb:116:in `on_container_log'
	/app/app/services/agent/message_handler.rb:66:in `handle_message'
	/app/app/services/agent/message_handler.rb:34:in `block (2 levels) in run'
	/app/app/services/agent/message_handler.rb:31:in `loop'
	/app/app/services/agent/message_handler.rb:31:in `block in run'
Moped::Session[8] = process=11 thread=#<Thread:0x0055d08cf862d8>:
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `new'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `create_session'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:43:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:37:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid.rb:65:in `default_session'
	/app/app/initializers/00_mongoid.rb:6:in `<top (required)>'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/app/app/boot.rb:22:in `block in require_glob'
	/app/app/boot.rb:21:in `each'
	/app/app/boot.rb:21:in `require_glob'
	/app/app/boot.rb:26:in `<top (required)>'
	config/puma.rb:8:in `require_relative'
	config/puma.rb:8:in `block in _load_from'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:426:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	/usr/bin/puma:22:in `load'
	/usr/bin/puma:22:in `<main>'
Moped::Session[8] ! process=11 thread=#<Thread:0x0055d08fb9b0d0>:
	/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:50:in `[]'
	/app/app/services/agent/message_handler.rb:140:in `flush_logs'
	/app/app/services/agent/message_handler.rb:134:in `on_container_log'
	/app/app/services/agent/message_handler.rb:66:in `handle_message'
	/app/app/services/agent/message_handler.rb:34:in `block (2 levels) in run'
	/app/app/services/agent/message_handler.rb:31:in `loop'
	/app/app/services/agent/message_handler.rb:31:in `block in run'
```

```
Moped::Session[8] = process=11 thread=#<Thread:0x0055d08cf862d8>:
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `new'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:66:in `create_session'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:43:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:37:in `default'
	/usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid.rb:65:in `default_session'
	/app/app/initializers/00_mongoid.rb:6:in `<top (required)>'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/app/app/boot.rb:22:in `block in require_glob'
	/app/app/boot.rb:21:in `each'
	/app/app/boot.rb:21:in `require_glob'
	/app/app/boot.rb:26:in `<top (required)>'
	config/puma.rb:8:in `require_relative'
	config/puma.rb:8:in `block in _load_from'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:426:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	/usr/bin/puma:22:in `load'
	/usr/bin/puma:22:in `<main>'
Moped::Session[8] ! process=11 thread=#<Thread:0x0055d08fb9b0d0>:
	/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:50:in `[]'
	/app/app/services/agent/message_handler.rb:205:in `on_node_stat'
	/app/app/services/agent/message_handler.rb:60:in `handle_message'
	/app/app/services/agent/message_handler.rb:34:in `block (2 levels) in run'
	/app/app/services/agent/message_handler.rb:31:in `loop'
	/app/app/services/agent/message_handler.rb:31:in `block in run'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1964 for 1.1.5

Backport of #1965 fixes for  + the v1.1 specific `Agent::MessageHandler` fixes.

This does not include the `Moped::Session` thread tracing/checking in #1965.

### CODE REVIEW

File: server/config/puma.rb [hunk 1]
```diff
@@ -4,6 +4,7 @@
 threads_count = Integer(ENV['MAX_THREADS'] || 8)
 threads threads_count, threads_count
 on_worker_boot do |worker_num|
+  require_relative '../lib/moped_session_tracer'
```
Comment (jakolehm) [inline server/config/puma.rb]: Should we track sessions only in debug mode?

**Comment by SpComb** [comment]
Not entirely happy merging this before I figure out what's going on in https://github.com/kontena/kontena/pull/1965#issuecomment-286357398, where travis specs are now failing with similar fixes.

**Comment by SpComb** [comment]
It seems like travis is getting some of these random monogdb errors now even without the #1965 changes:

* https://travis-ci.org/kontena/kontena/jobs/210930229

```
  An error occurred in an after hook

    NoMethodError: undefined method `length' for nil:NilClass

    occurred at /home/travis/build/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:56:in `block in collection_names'
```

So this is probably better than not..
