### PR TITLE
Abort deploy gracefully in exceptional cases

### LINKED ISSUE #2275: [1.2.2.dev] GridServiceDeploy can get stuck in pending state if deploy create races with service remove
There seems to be some race condition where a service can get removed after creating a `GridServiceDeploy`, but before running the deploy. The `GridServiceSchedulerWorker` will crash on the `GridServiceDeploy.grid_service` being `nil`, and the `GridServiceDeploy` will remain stuck in a pending state, being retried every 30s.

```
E, [2017-05-08T13:09:25.033175 #8694] ERROR -- : Actor crashed!
NoMethodError: undefined method `deploy_running?' for nil:NilClass
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:29:in `block in check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
	/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:24:in `with_lock'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:6:in `with_dlock'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:28:in `check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:12:in `block in watch'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `loop'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `watch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### PR DESCRIPTION
**Pull request by jnummelin**
Fixes `GridServiceSchedulerWorker#check_deploy_queue` to "gracefully" abort deploys in case of unhandled errors.

### TODO
- Should there be a specific check for removed service as happened in #2275? It would be probably nicer in logs instead of:
```
NoMethodError: undefined method `deploy_running?' for nil:NilClass
...
```

fixes #2275

### CODE REVIEW

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 1]
```diff
@@ -41,6 +41,10 @@ def check_deploy_queue
         return nil
       end
     end
+  rescue => exc
+    warn "aborting deploy on un-handled error: #{exc.message}"
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: I would consider this an `error`.

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 2]
```diff
@@ -41,6 +41,10 @@ def check_deploy_queue
...
+    warn exc.backtrace.join("\n") if exc.backtrace
+    service_deploy.abort! "service deploy aborted: #{exc.message}" if service_deploy
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Reminds me that we should figure out how to display these abort reasons to the user... doesn't happen ATM.

File: server/spec/jobs/grid_service_scheduler_worker_spec.rb [hunk 3]
```diff
@@ -45,9 +45,24 @@
 
     it "fails if fetch_deploy_item returns a non-pending deploy" do
       service_deploy = GridServiceDeploy.create(grid_service: service, created_at: 1.hour.ago, started_at: 1.hour.ago)
-
-      expect{subject.check_deploy_queue}.to raise_error(RuntimeError, "deploy not pending")
-    end
+      
+      subject.check_deploy_queue
```
Comment (SpComb) [inline server/spec/jobs/grid_service_scheduler_worker_spec.rb]: `expect(subject.check_deploy_queue).to be_nil`

File: server/app/jobs/grid_service_scheduler_worker.rb (hunk 2 above)
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Currently the CLI considers the aborted deploy to be a success, because it's in the `created` state, not the `error` state :/

```
    *   Deploying service redis-ha-stateful  .. \[API Client Response]: Headers: {Content-Type: application/json}  | Status: 200 | Body: 
{"id":"591074c8de35782c7f000000","created_at":"2017-05-08T13:38:16.300Z","queued_at":"2017-05-08T13:38:16.386+00:00","started_at":null,"finished_at":"2017-05-08T13:38:16.392+00:00","service_id":"development/null/redis-ha-stateful","state":"created","reason":"service deploy aborted: testing","instance_count":1,"instance_deploys":[]}
 [done] Deploying service redis-ha-stateful      
```

This is an omission in #2221... needs CLI changes to fix.

Comment (jnummelin) [inline server/app/jobs/grid_service_scheduler_worker.rb]: makes me also think that `service_deploy.abort!` should set the state to `:error`

**Comment by jnummelin** [comment]
Now when `GridServiceDeploy.abort!` set the state to `:error` CLI behaves nicely:
```
$ k service deploy lb_web/nginx
 [fail] Deploying service lb_web/nginx      
 [error] Kontena::Errors::StandardErrorArray : service deploy aborted: BoomBoomBoom
```

File: server/app/jobs/grid_service_scheduler_worker.rb [hunk 4]
```diff
@@ -41,6 +41,14 @@ def check_deploy_queue
         return nil
       end
     end
+  rescue => exc
+    error "aborting deploy on un-handled error: #{exc.message}"
+    error exc.backtrace.join("\n") if exc.backtrace
+    if service_deploy
```
Comment (SpComb) [inline server/app/jobs/grid_service_scheduler_worker.rb]: Double-conditional

File: server/app/models/grid_service_deploy.rb [hunk 5]
```diff
@@ -90,6 +90,6 @@ def aborted?
   #
   # @param reason [String]
   def abort!(reason = nil)
-    self.set(:finished_at => Time.now.utc, :reason => reason)
+    self.set(:finished_at => Time.now.utc, :reason => reason, :deploy_state => :error)
```
Comment (SpComb) [inline server/app/models/grid_service_deploy.rb]: Fixing this over in #2281

Comment (SpComb) [inline server/app/models/grid_service_deploy.rb]: Needs merge for  #2281

**Comment by jnummelin** [comment]
rebased for #2281 

@SpComb PTAL
