### PR TITLE
Fix service, stack deploy errors

### LINKED ISSUE #2127: Stack deploy and service deploy error states are broken
Regression from the #2097 `StackDeployWorker` refactoring: it no longer checks the `service_deploy.reload` -> `GridServiceDeploy.error?` state in addition to the `GridServices::Deploy.run` -> `outcome.success?`.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2127

* Add specs for `GridServiceInstanceDeployer#deploy` return value, and fix it to return the `GridServiceInstanceDeploy` in error cases
* Fix and add specs for `GridServiceDeployer`'s handling of the `Celluloid::Future` `f.value.error? -> GridServiceInstanceDeploy.error?` handling
* Fix the `StackDeployWorker` to `StackDeploy.error!` if any `GridServiceDeploy.error?`

## TODO
* e2e specs

### CODE REVIEW

File: server/app/services/grid_service_deployer.rb [hunk 1]
```diff
@@ -57,7 +57,9 @@ def deploy
       self.deploy_service_instance(total_instances, deploy_futures, instance_number, deploy_rev)
       sleep 0.1
     end
-    deploy_futures.select{|f| !f.ready?}.each{|f| f.value }
```
Comment (SpComb) [inline server/app/services/grid_service_deployer.rb]: I think this never noticed instance deploy errors from the tail-end instance deploy futures in cases where `deploy_service_instance` didn't wait for them.
