### PR TITLE
Agent Watchdog 

### LINKED ISSUE #2733: Agent can hang with all supervised actors having been terminated but the websocket still connected and the node online
background: One node started having elevated CPU/IO

slack_-_kontena_community

When I was finally able to get in with SSH `docker logs --tail 100 -f kontena-agent` showed:

```
E, [2017-08-23T01:33:48.907969 #1] ERROR -- : Actor crashed!
Docker::Error::TimeoutError: read timeout reached
        /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:52:in `rescue in request'
        /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
        /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:223:in `block (2 levels) in <class:Container>'
        /app/lib/kontena/service_pods/restarter.rb:25:in `perform'
        /app/lib/kontena/workers/container_health_check_worker.rb:110:in `restart_container'
        /app/lib/kontena/workers/container_health_check_worker.rb:59:in `handle_action'
        /app/lib/kontena/workers/container_health_check_worker.rb:49:in `check_status'
        /app/lib/kontena/workers/container_health_check_worker.rb:31:in `block in start'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
W, [2017-08-23T04:18:49.722194 #1]  WARN -- Kontena::WebsocketClient: connection closed with code 1006: 
I, [2017-08-23T04:18:49.975822 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://sensored
I, [2017-08-23T04:18:50.277794 #1]  INFO -- Kontena::WebsocketClient: connection established
W, [2017-08-23T16:05:00.297975 #1]  WARN -- Kontena::WebsocketClient: connection closed with code 1006: 
I, [2017-08-23T16:05:00.310322 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://sensored
I, [2017-08-23T16:05:07.731837 #1]  INFO -- Kontena::WebsocketClient: connection established
W, [2017-08-23T16:05:07.743849 #1]  WARN -- Kontena::WebsocketClient: connection closed with code 4020: agent clock offset 7.26s exceeds threshold
I, [2017-08-23T16:05:08.549544 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://sensored
I, [2017-08-23T16:05:08.641807 #1]  INFO -- Kontena::WebsocketClient: connection established
E, [2017-08-24T12:28:42.367322 #1] ERROR -- Kontena::RpcServer: NoMethodError: undefined method `remove_config' for nil:NilClass
E, [2017-08-24T12:28:42.371964 #1] ERROR -- Kontena::RpcServer: /app/lib/kontena/rpc/lb_api.rb:10:in `remove_service'
/app/lib/kontena/rpc_server.rb:44:in `handle_request'
```

notice the timestamps:
```
I, [2017-08-23T16:05:08.641807 #1]  INFO -- Kontena::WebsocketClient: connection established
E, [2017-08-24T12:28:42.367322 #1] ERROR -- Kontena::RpcServer: NoMethodError: undefined method `remove_config' for nil:NilClass
```

After I tried to run this again I started to get this:

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7efee113ef47 m=2
goroutine 0 [idle]:
goroutine 1 [runnable]:
syscall.Syscall(0x1, 0x1, 0xc42035e008, 0x81, 0x81, 0x81, 0x0)
        /usr/lib/go1.7/src/syscall/asm_linux_amd64.s:18 +0x5
```

and then the node went MIA and I had to restart it forcefully from google cloud admin panel.

So: because the etcd was healthy (and the node responded to ping), but the kontena-agent was stuck, the master tried to deploy services (and kept failing) -- grid logs showed a lot of lines like this.

```
2017-08-24T12:30:22.436Z service:deploy            service=mystack/worker           Failed to deploy service instance mygrid/mystack/worker-1 to node i-34zh.c.mygrid.internal: Timeout::Error: Timeout after waiting 300.0s until: service mygrid/mystack/worker-1 is running on node mygrid/i-34zh.c.mygrid.internal at 2017-08-24 12:25:20 UTC
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2733 by having the agent process exit within 10s if the `Celluloid::Supervision::Container` crashes

Implement a new `Kontena::Watchdog` used by the `Kontena::Agent`. This is a Celluloid actor that runs a polling function in a `defer` thread, and then aborts the main process thread on errors/timeouts.

The `Kontena::Agent` watchdog currently checks for the `@supervisor.alive?` case in #2733, but this could also be extended to cover other cases.

TODO: the watchdog timeout functionality isn't really used yet, but it would become relevant if the `Kontena::Agent` watchdog block starts to poll other actors for their health, and those polled actors might become stuck.

### Watchdog error
With a supervised actor that likes to crash a lot:

```
E, [2017-12-13T14:27:03.336939 #1] ERROR -- : Actor crashed!
RuntimeError: asdf
	/app/lib/kontena/workers/container_info_worker.rb:25:in `start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

The `Celluloid::Supervision::Container` actor will eventually hit a race condition and also crash:

```
E, [2017-12-13T14:27:03.342813 #1] ERROR -- : Error ( RuntimeError ) at start of supervised instance of Kontena::Workers::ContainerInfoWorker
E, [2017-12-13T14:27:03.343666 #1] ERROR -- : Actor crashed!
RuntimeError: a container instance went missing. This shouldn't be!
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-supervision-0.20.5/lib/celluloid/supervision/container.rb:118:in `restart_actor'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `block in call'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

The watchdog will hit an error on the next interval check:

```
E, [2017-12-13T16:35:52.617327 #1] ERROR -- Kontena::Watchdog: Celluloid::Supervision::Container died (RuntimeError)
/app/lib/kontena/agent.rb:147:in `block in watchdog'
/app/lib/kontena/watchdog.rb:48:in `block (2 levels) in ping'
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/app/lib/kontena/watchdog.rb:47:in `block in ping'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/watchdog.rb:46:in `ping'
/app/lib/kontena/watchdog.rb:32:in `block in start'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

The agent process will exit, without running any of Celluloid `at_exit` shutdown handlers. The host systemd can then restart the `kontena-agent.service` unit.

### Watchdog timeout

```
E, [2017-12-13T16:23:03.057953 #1] ERROR -- Kontena::Watchdog: execution expired (Timeout::Error)
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
/app/lib/kontena/agent.rb:149:in `block in watchdog'
/app/lib/kontena/watchdog.rb:47:in `block (2 levels) in ping'
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/app/lib/kontena/watchdog.rb:46:in `block in ping'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/watchdog.rb:45:in `ping'
/app/lib/kontena/watchdog.rb:32:in `block in start'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

The process exits.

### CODE REVIEW

File: agent/lib/kontena/watchdog.rb [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+
+  # kill the watched Thread
+  def abort(exc)
+    error exc
+
+    # only abort once
+    stop
+
+    # assume that the thread has abort_on_exception and it does not rescue non-StandardError
+    @thread.raise Abort, "#{exc.class}: #{exc.message}" if @abort
```
Comment (SpComb) [inline agent/lib/kontena/watchdog.rb]: May want to abort harder... Celluloid traps the `Abort` in the main thread and does its own shutdown, which is not really what we want in the case of watchdog failures:

```
E, [2017-12-13T15:20:58.464693 #1] ERROR -- Kontena::Watchdog: watchdog timeout after 39.094s @ /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/agent.rb:145:in `block in watchdog'
	/app/lib/kontena/watchdog.rb:56:in `block in ping'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate' (Timeout::Error)

I, [2017-12-13T15:20:58.612649 #1]  INFO -- Kontena::Workers::LogWorker: stop log streaming
I, [2017-12-13T15:20:58.624217 #1]  INFO -- Kontena::Workers::ContainerHealthCheckWorker: stopped to check status from /ingress-lb.lb-1
E, [2017-12-13T15:21:07.721385 #1] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
/app/lib/kontena/agent.rb:98:in `gets': Timeout::Error: watchdog timeout after 39.094s @ /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep' (Kontena::Watchdog::Abort)
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/agent.rb:145:in `block in watchdog'
	/app/lib/kontena/watchdog.rb:56:in `block in ping'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
	from /app/lib/kontena/agent.rb:98:in `run!'
	from /app/bin/kontena-agent:46:in `<main>'
```

**Comment by SpComb** [comment]
Hmm... the timeout logic is very complicated because of the barking warnings, but maybe the agent watchdog doesn't really need those as much as e.g. the server `EventMachine` watchdog does.

I'll simplify this to just use `Timeout.timeout` on the watchdog actor thread...

**Comment by SpComb** [comment]
Simplified to just use `Timeout.timeout` instead.

File: agent/lib/kontena/watchdog.rb [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    @timer.cancel
+  end
+
+  # Start new watchdog ping
+  def ping
+    start = Time.now
+
+    # use exclusive mode to prevent the task from suspending and causing the Timeout::Error to crash the actor thread instead
+    exclusive {
+      Timeout.timeout(@timeout) do
```
Comment (SpComb) [inline agent/lib/kontena/watchdog.rb]: BTW: using `Timeout.timeout` in a celluloid actor needs the `exclusive` mode, otherwise the block might cause the celluloid task fiber to suspend, and then the `Timeout::Error` will just abort the actor thread `run` loop and cause the `Watchdog` to crash without aborting:

```
E, [2017-12-13T16:20:37.495949 #1] ERROR -- : Actor crashed!
Timeout::Error: execution expired
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:33:in `while_time_remaining'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:11:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

Comment (jakolehm) [inline agent/lib/kontena/watchdog.rb]: Consider replacing `Timeout` with something less dangerous.

Comment (SpComb) [reply agent/lib/kontena/watchdog.rb]: What part of `Timeout` being too dangerous do you mean, though?

The general problem with `Timeout.timeout` is that the non-`StandardError` exception (`Timeout::Error`) can get raised anywhere, and that might leave some code in an inconsistent state. However, that's not really a problem here: after a timeout, the watchdog will be `exit!`'ing the process anyways, so any inconsistent state / side-effects of the `Timeout::Error` shouldn't really matter anymore.

If you mean the interaction between celluloid task `Fiber` vs the `Timeout.timeout` aborting the celluloid actor `Thread`, then I could change this back to using a `defer` thread to run the block... but I don't think that's a problem with the `exclusive { ... }`? There's even spec cases for both kinds of suspends.

Comment (jakolehm) [reply agent/lib/kontena/watchdog.rb]: It's not dangerous in this case. We can probably improve this later if Watchdog ever checks something more fragile.
