### PR TITLE
Fix crash in kontena external registry ls -q

### LINKED ISSUE #3050: cli: kontena external-registry ls -q gives exception when empty
```
$ kontena external-registry ls
NAME  USERNAME  EMAIL
```

```
$ kontena external-registry ls -q
 [error] NoMethodError : undefined method `map' for "name":String
```

```
E, [2017-11-16T11:00:44.252777 #75815] ERROR -- CLI: undefined method `map' for "name":String (NoMethodError)
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:72:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:35:in `generate_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:39:in `print_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/external_registries/list_command.rb:20:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/bin/kontena:18:in `<top (required)>'
/opt/kontena/embedded/bin/kontena:23:in `load'
/opt/kontena/embedded/bin/kontena:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #3050

A typo in the list-command caused `kontena external-registry ls -q` to crash with
```
NoMethodError : undefined method `map' for "name":String`
```

### CODE REVIEW

File: test/spec/features/external_registry/list_spec.rb [hunk 1]
```diff
@@ -0,0 +1,48 @@
+require 'spec_helper'
+
+describe 'external-registry ls' do
+  context 'when empty' do
+    it "outputs headers" do
+      k = run('kontena external registry ls')
```
Comment (SpComb) [inline test/spec/features/external_registry/list_spec.rb]: `kontena external-registry ls`

```
ERROR: No such sub-command 'external'

See: 'kontena --help'
```

File: test/spec/features/external_registry/list_spec.rb [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    before do
+      run 'kontena external-registry add -u foo -e foo@no.email -p secret registry.domain.com'
+    end
+
+    after do
+      run 'kontena external-registry rm --force registry.domain.com'
+    end
+
+    it "returns a list" do
+      k = run('kontena external registry ls')
```
Comment (SpComb) [inline test/spec/features/external_registry/list_spec.rb]: `kontena external-registry ls`

```
ERROR: No such sub-command 'external'

See: 'kontena --help'
```

File: test/spec/features/external_registry/list_spec.rb [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+      expect(k.out.lines.last).to include 'foo'
+      expect(k.out.lines.last).not_to include 'secret'
+      expect(k.out.lines.size).to eq 2
+    end
+
+    context '-q' do
+      it "outputs the registry name" do
+        k = run 'kontena external-registry ls -q'
+        expect(k.code).to be_zero
+        expect(k.out.strip).to eq 'registry.domain.com'
```
Comment (SpComb) [inline test/spec/features/external_registry/list_spec.rb]: TBH I don't know what's going on here, but I've seen this `stty` thing before... it must be something related to `TTY::Screen#size_from_stty` when run from Kommando... 

```
  3) external-registry ls when not empty -q outputs the registry name
     Failure/Error: expect(k.out.strip).to eq 'registry.domain.com'
     
       expected: "registry.domain.com"
            got: "stty: standard input\r\nregistry.domain.com"
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,3 @@
       +stty: standard input
        registry.domain.com
       
     # ./spec/features/external_registry/list_spec.rb:44:in `block (4 levels) in <top (required)>'
```

Closest I can get to reproing this is:

```
/kontena/test # stty size < /dev/null > /dev/null 
stty: standard input: Not a tty
```

Comment (kke) [reply test/spec/features/external_registry/list_spec.rb]: Maybe updating the tty-screen gem would help?

Comment (SpComb) [reply test/spec/features/external_registry/list_spec.rb]: The `test/Dockerfile.test` image I'm using to run the e2e specs seems to have the latest version of `tty-screen`:

```
irb(main):008:0> TTY::Screen.method(:size_from_stty).source_location
=> ["/usr/lib/ruby/gems/2.3.0/gems/tty-screen-0.6.2/lib/tty/screen.rb", 207]
```

Comment (kke) [reply test/spec/features/external_registry/list_spec.rb]: The same syntax is used in other `-q` tests.

```ruby
#spec/features/stack/list_spec.rb:
  context 'quiet mode' do
    it "returns an installed stack name" do
      with_fixture_dir("stack/simple") do
        run 'kontena stack install --no-deploy'
      end
      k = run 'kontena stack ls -q'
      expect(k.code).to eq(0)
      expect(k.out.lines.size).to eq(1)
      expect(k.out.strip).to eq "simple"
    end
  end
```

Comment (SpComb) [reply test/spec/features/external_registry/list_spec.rb]: Yeah, looks like the same `stty: standard input` is now tripping up other e2e specs as well:

```
 [done] Creating stack simple      
stty: standard input
NAME       STACK               SERVICES   STATE         EXPOSED PORTS
⊝ simple   test/simple:0.1.0   1          initialized
 [done] Removing stack simple      
  returns an installed stack (FAILED - 1)
```

```
Failures:

  1) stack list returns an installed stack
     Failure/Error: expect(k.out.lines.size).to eq(2)
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./spec/features/stack/list_spec.rb:21:in `block (2 levels) in <top (required)>'
```
