### PR TITLE
Avoid setting nil backtraces in rpc errors

### LINKED ISSUE #1997: Server exceptions with nil backtrace
The server may occasionally raise an exception while logging an exception with `exc.backtrace.join("\n")`, where the `exc.backtrace` appears to be nil:

```
E, [2017-03-16T12:51:29.783964 #7] ERROR -- GridServiceInstanceDeployer: failed to deploy service instance ... to node ...
E, [2017-03-16T12:51:29.784596 #7] ERROR -- GridServiceInstanceDeployer: Connection timeout (5s)
E, [2017-03-16T12:51:29.814434 #7] ERROR -- GridServiceDeployer: Unknown error (...): NoMethodError undefined method `join' for nil:NilClass
Did you mean?  JSON
E, [2017-03-16T12:51:29.815038 #7] ERROR -- GridServiceDeployer: /app/app/services/grid_service_instance_deployer.rb:27:in `rescue in deploy'
/app/app/services/grid_service_instance_deployer.rb:17:in `deploy'
/app/app/services/grid_service_deployer.rb:112:in `block in deploy_service_instance'
```

The exception looks like an `RpcClient::TimeoutError`, raised by the [`RpcClient`](https://github.com/kontena/kontena/blob/v1.1.5.rc2/server/app/services/rpc_client.rb#L80):

```ruby
raise RpcClient::TimeoutError.new(503, "Connection timeout (#{self.timeout}s)")
```

Does raising an exception with `raise Exception.new("foo")`, as opposed to `raise Exception, "foo"`, result in a `nil` `backtrace`?

### PR DESCRIPTION
**Pull request by kke**
Fixes #1997

Removes the `RpcClient::Error` `attr_accessor :message, backtrace` that broke exception formatting and resulted in a `nil` backtrace for `RpcClient::TimeoutError`s. Replaced with an optional `@remote_backtrace` that gets injected into the exception `backtrace`.

## Example
```
RpcClient::Error RuntimeError: eek
agent:/app/lib/kontena/service_pods/restarter.rb:24:in `perform'
agent:/app/lib/kontena/rpc/service_pods_api.rb:11:in `restart'
agent:/app/lib/kontena/rpc_server.rb:42:in `handle_request'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
agent:/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
<RPC>
/home/kontena/kontena/kontena/server/app/services/rpc_client.rb:59:in `request'
/home/kontena/kontena/kontena/server/app/services/docker/service_restarter.rb:20:in `request_restart_service'
/home/kontena/kontena/kontena/server/app/services/docker/service_restarter.rb:14:in `restart_service_instance'
/home/kontena/kontena/kontena/server/app/mutations/grid_services/restart.rb:32:in `restart_service_instance'
/home/kontena/kontena/kontena/server/app/mutations/grid_services/restart.rb:18:in `block in restart_service_instances'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:658:in `yield_document'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:123:in `block in each'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `block in each'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:78:in `each'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:122:in `each'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `each'
/home/kontena/kontena/kontena/server/app/mutations/grid_services/restart.rb:17:in `restart_service_instances'
/home/kontena/kontena/kontena/server/app/mutations/grid_services/restart.rb:9:in `block in execute'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

### CODE REVIEW

**Comment by SpComb** [comment]
I don't think overriding the standard `Exception#backtrace` with an empty array makes any sense either.

The server/agent `RpcServer::Error` is only used for local exceptions raised by the local handlers... There is no reason for it to take a `backtrace` as an argument?

The server/agent `RpcClient::Error` is raised for remote error responses, and the backtrace contains the backtrace from the remote side. IMO storing this as an attr named `backtrace` is a bug, as it overrides the standard `Exception#backtrace` that contains the **local** backtrace (which method did the RPC request). It should be called something like the `remote_backtrace` instead?

File: server/app/services/rpc_server.rb [hunk 1]
```diff
@@ -13,12 +13,12 @@ class RpcServer
   }
 
   class Error < StandardError
-    attr_accessor :code, :message, :backtrace
+    attr_reader :code
 
-    def initialize(code, message, backtrace = nil)
```
Comment (SpComb) [inline server/app/services/rpc_server.rb]: The `RpcServer::Error` are only used locally, and do not need any `remote_backtrace`.

File: agent/lib/kontena/rpc_server.rb [hunk 2]
```diff
@@ -17,12 +17,12 @@ class RpcServer
     }
 
     class Error < StandardError
-      attr_accessor :code, :message, :backtrace
+      attr_reader :code
 
-      def initialize(code, message, backtrace = nil)
```
Comment (SpComb) [inline agent/lib/kontena/rpc_server.rb]: The `RpcServer::Error` are only used locally, and do not need any `remote_backtrace`.

**Comment by SpComb** [comment]
Tested to fix #1997 
```
E, [2017-03-17T11:40:17.666636 #22268] ERROR -- GridServiceInstanceDeployer: failed to deploy service instance development/null/redis-1 to node core-01
E, [2017-03-17T11:40:17.666900 #22268] ERROR -- GridServiceInstanceDeployer: Connection timeout (2s)
E, [2017-03-17T11:40:17.667174 #22268] ERROR -- GridServiceInstanceDeployer: /home/kontena/kontena/kontena/server/app/services/rpc_client.rb:79:in `wait_for_response'
/home/kontena/kontena/kontena/server/app/services/rpc_client.rb:42:in `request'
/home/kontena/kontena/kontena/server/app/services/docker/service_creator.rb:80:in `request_create_service'
/home/kontena/kontena/kontena/server/app/services/docker/service_creator.rb:21:in `create_service_instance'
/home/kontena/kontena/kontena/server/app/services/grid_service_instance_deployer.rb:55:in `create_service_instance'
/home/kontena/kontena/kontena/server/app/services/grid_service_instance_deployer.rb:20:in `deploy'
/home/kontena/kontena/kontena/server/app/services/grid_service_deployer.rb:111:in `block in deploy_service_instance'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

File: server/app/services/cloud/rpc_server.rb [hunk 3]
```diff
@@ -7,12 +7,12 @@ class RpcServer
...
+      attr_reader :code
 
-      def initialize(code, message, backtrace = nil)
-        self.code = code
-        self.message = message
-        self.backtrace = backtrace
+      def initialize(code, message, remote_backtrace = nil)
+        @code = code
+        super(message)
+        set_backtrace(Array(backtrace) + (['<Remote backtrace>'] + Array(remote_backtrace))) if remote_backtrace
```
Comment (SpComb) [inline server/app/services/cloud/rpc_server.rb]: This doesn't seem to pick up the local backtrace:

```
E, [2017-03-17T11:43:09.761357 #24739] ERROR -- GridServiceInstanceDeployer: failed to deploy service instance development/null/redis-nonexist-1 to node core-01
E, [2017-03-17T11:43:09.762520 #24739] ERROR -- GridServiceInstanceDeployer: Celluloid::DeadActorError: attempted to call a dead actor: ensure_image
E, [2017-03-17T11:43:09.762625 #24739] ERROR -- GridServiceInstanceDeployer: <Remote backtrace>
/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/responses.rb:29:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
/app/lib/kontena/service_pods/creator.rb:156:in `ensure_image'
/app/lib/kontena/service_pods/creator.rb:29:in `perform'
/app/lib/kontena/rpc/service_pods_api.rb:16:in `create'
/app/lib/kontena/rpc_server.rb:38:in `handle_request'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

Comment (kke) [inline server/app/services/cloud/rpc_server.rb]: I don't know how you would raise such an error with a local backtrace.

```
raise Error, "foo"
#and
raise Error, 10, "Foo"
#and
raise Error, 10, "Foo", ["dang"]
```

will give you ArgumentError because of initialize expecting 2+ arguments

```
raise Error.new(10, 'foo', ['dang'])
```
will give you no local backtrace.

File: server/app/services/rpc_client.rb [hunk 4]
```diff
@@ -3,17 +3,17 @@
...
+    attr_reader :code
 
-    def initialize(code, message, backtrace = nil)
-      self.code = code
-      self.message = message
-      self.backtrace = backtrace
+    def initialize(code, message, remote_backtrace = nil)
+      @code = code
+      super(message)
+      set_backtrace(caller) unless backtrace
```
Comment (SpComb) [inline server/app/services/rpc_client.rb]: This feels very complicated, and ruby's Exceptions are confusing enough that I don't know the right way to do this... but could we avoid having to set the exception backtrace ourselves by doing this gluing later?

```ruby
def backtrace
  @remote_backtrace + super
end
```

File: server/app/services/scheduler/error.rb [hunk 5]
```diff
@@ -1,5 +1,3 @@
 module Scheduler
-  class Error < StandardError
-
-  end
+  Error = Class.new(StandardError)
```
Comment (SpComb) [inline server/app/services/scheduler/error.rb]: This is so weird... how does Ruby know that `Error.new.class.name => "Error"` :question:

File: server/app/services/rpc_client.rb (hunk 4 above)
Comment (kke) [inline server/app/services/rpc_client.rb]: yes

File: server/app/services/scheduler/error.rb (hunk 5 above)
Comment (kke) [inline server/app/services/scheduler/error.rb]: i suppose there's something in `Class` that figures out if self is constant.

```ruby
> foo = Class.new(StandardError)
> foo.new.class.name
=> nil
> Foo = Class.new(StandardError)
> Foo.new.class.name
=> "Foo"
```

Comment (SpComb) [inline server/app/services/scheduler/error.rb]: I guess I'm trying to say is: do we need to change these `class Error < ...` into something weirder and more unexpected?

Comment (kke) [inline server/app/services/scheduler/error.rb]: https://github.com/bbatsov/ruby-style-guide#single-line-classes

File: server/app/services/cloud/rpc_server.rb [hunk 6]
```diff
@@ -7,13 +7,16 @@ class RpcServer
     }
 
     class Error < StandardError
-      attr_reader :code
+      attr_reader :code, :remote_backtrace
```
Comment (SpComb) [inline server/app/services/cloud/rpc_server.rb]: Same thing re `RpcServer::Error`, the `Cloud::RpcServer::Error` doesn't have any remote backtrace.

In fact, this exception is not even used at all... all of the `Cloud::Rpc` handlers use the `RpcServer::Error`, not the `Cloud::RpcServer::Error` :confounded:

File: agent/lib/kontena/rpc_client.rb [hunk 7]
```diff
@@ -6,13 +6,16 @@ class RpcClient
...
       def initialize(code, message, remote_backtrace = nil)
         @code = code
+        @remote_backtrace = (['<Remote>:'] + remote_backtrace) if remote_backtrace
         super(message)
-        set_backtrace(caller) unless backtrace
-        set_backtrace(backtrace + (['<Remote backtrace>'] + Array(remote_backtrace))) if remote_backtrace
+      end
+
+      def backtrace
+        (super || caller) + Array(remote_backtrace)
```
Comment (SpComb) [inline agent/lib/kontena/rpc_client.rb]: Does `super` aka `Exception#backtrace` ever return nil? Using the `caller` of the `#backtrace` method does not sound like the right thing to return O_o

Comment (kke) [inline agent/lib/kontena/rpc_client.rb]: backtrace is nil when you do `Error.new`

Comment (kke) [inline agent/lib/kontena/rpc_client.rb]: maybe it should capture the caller in initialize yes.

Comment (SpComb) [inline agent/lib/kontena/rpc_client.rb]: It seems ruby is actually sane in this regard:

```
irb(main):001:0> begin
irb(main):002:1*  raise RuntimeError.new("asdf")
irb(main):003:1> rescue => error
irb(main):004:1>  puts "#{error} @:\n#{error.backtrace.join("\n")}"
irb(main):005:1> end
asdf @:
(irb):2:in `irb_binding'
/usr/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'
/usr/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'
/usr/lib/ruby/2.3.0/irb/context.rb:380:in `evaluate'
/usr/lib/ruby/2.3.0/irb.rb:489:in `block (2 levels) in eval_input'
/usr/lib/ruby/2.3.0/irb.rb:623:in `signal_status'
/usr/lib/ruby/2.3.0/irb.rb:486:in `block in eval_input'
/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'
/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'
/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/lib/ruby/2.3.0/irb.rb:485:in `eval_input'
/usr/lib/ruby/2.3.0/irb.rb:395:in `block in start'
/usr/lib/ruby/2.3.0/irb.rb:394:in `catch'
/usr/lib/ruby/2.3.0/irb.rb:394:in `start'
/usr/bin/irb:11:in `<main>'
=> nil
```

File: server/app/services/scheduler/error.rb (hunk 5 above)
Comment (SpComb) [inline server/app/services/scheduler/error.rb]: I didn't know we had a style guide :P But okay.

File: server/app/services/cloud/rpc_server.rb [hunk 8]
```diff
@@ -7,12 +7,17 @@ class RpcServer
...
-      attr_accessor :code, :message, :backtrace
+      attr_reader :code, :remote_backtrace
 
-      def initialize(code, message, backtrace = nil)
-        self.code = code
-        self.message = message
-        self.backtrace = backtrace
+      def initialize(code, message, remote_backtrace = nil)
+        @code = code
+        @remote_backtrace = (['<Remote>:'] + remote_backtrace) if remote_backtrace
```
Comment (SpComb) [inline server/app/services/cloud/rpc_server.rb]: The server `Cloud::RpcServer::Error` does not have a remote backtrace.

File: server/app/services/rpc_client.rb [hunk 9]
```diff
@@ -3,18 +3,22 @@
...
+      @code = code
+      @remote_backtrace = (['<Remote>:'] + remote_backtrace) if remote_backtrace
+      @caller = caller
+      super(message)
     end
-  end
 
-  class TimeoutError < Error
+    def backtrace
+      (super || @caller) + Array(remote_backtrace)
```
Comment (SpComb) [inline server/app/services/rpc_client.rb]: Is there some known case where this `@caller` would get used? I would just leave it out if not.

**Comment by SpComb** [comment]
Ping @kke 

Do we keep this `Exception#initialize` `@caller = caller` thing, or can we get rid of it?

File: server/app/services/rpc_client.rb (hunk 9 above)
Comment (kke) [inline server/app/services/rpc_client.rb]: All of the `raise Exception.new("foofoo")` which will otherwise get a nil backtrace.

**Comment by kke** [comment]
Well the idea was to avoid setting nil backtraces. Of course it could do `super || []` if we are not interested where the local exception was created.

File: server/app/services/rpc_client.rb (hunk 9 above)
Comment (SpComb) [inline server/app/services/rpc_client.rb]: `raise Exception.new(...)` does actually still get a backtrace:

```
irb(main):005:0* begin
irb(main):006:1*   raise RuntimeError.new("failed")
irb(main):007:1> rescue => error
irb(main):008:1>   puts "#{error.class}: #{error} @ #{error.backtrace}"
irb(main):009:1> end
RuntimeError: failed @ ["(irb):6:in `irb_binding'", "/usr/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'", "/usr/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'", "/usr/lib/ruby/2.3.0/irb/context.rb:380:in `evaluate'", "/usr/lib/ruby/2.3.0/irb.rb:489:in `block (2 levels) in eval_input'", "/usr/lib/ruby/2.3.0/irb.rb:623:in `signal_status'", "/usr/lib/ruby/2.3.0/irb.rb:486:in `block in eval_input'", "/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'", "/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'", "/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'", "/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'", "/usr/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'", "/usr/lib/ruby/2.3.0/irb.rb:485:in `eval_input'", "/usr/lib/ruby/2.3.0/irb.rb:395:in `block in start'", "/usr/lib/ruby/2.3.0/irb.rb:394:in `catch'", "/usr/lib/ruby/2.3.0/irb.rb:394:in `start'", "/usr/bin/irb:11:in `<main>'"]
```

**Comment by SpComb** [comment]
Seems there's definitely some weirdness going on when overriding the `Exception#backtrace`:
* `super` seems to always return `nil` ()
* ruby calls it implicitly while raising, well before anything else even tries to rescue it
* regardless of when raising with `new` or comma?

```
irb(main):002:0> def foo
irb(main):003:1>   raise RpcClient::TimeoutError.new(503, "Connection timeout (1s)")
irb(main):004:1> end
=> :foo
irb(main):005:0> 
irb(main):006:0* foo()
NoMethodError: undefined method `+' for nil:NilClass
	from /home/kontena/kontena/kontena/server/app/services/rpc_client.rb:15:in `backtrace'
	from (irb):3:in `foo'
	from (irb):6
	from /usr/bin/irb:11:in `<top (required)>'
```

```
irb(main):007:0> def foo
irb(main):008:1>   raise RpcClient::TimeoutError.new(503, "Connection timeout (1s)")
irb(main):009:1> rescue => error
irb(main):010:1>   $stderr.puts("failed: #{error}")
irb(main):011:1> end
=> :foo
irb(main):012:0> 
irb(main):013:0* foo()
failed: undefined method `+' for nil:NilClass
=> nil
```

Even with `super || []`, the backtrace is just empty:

```
irb(main):002:0> def foo
irb(main):003:1>   raise RpcClient::TimeoutError.new(503, "Connection timeout (1s)")
irb(main):004:1> end
=> :foo
irb(main):005:0> 
irb(main):006:0* foo()
RpcClient::TimeoutError: Connection timeout (1s)
irb(main):007:0>
```

So it doesn't seem like the approach of overriding the `def backtrace` works...

File: server/app/services/rpc_client.rb (hunk 4 above)
Comment (SpComb) [inline server/app/services/rpc_client.rb]: Seems like the `def backtrace` approach gets even more complicated... is the previous `initialize -> set_backtrace(caller)` thing better?

**Comment by kke** [comment]
There's `set_backtrace` method in exception but maybe the approach is wrong to begin with.

**Comment by SpComb** [comment]
The `def backtrace` -> `Array(super) + Array(remote_backtrace)` approach seems to result in the local backtrace always being missing.

File: server/spec/services/rpc_client_spec.rb [hunk 10]
```diff
@@ -9,7 +9,7 @@ def publish_response(id, response)
   end
 
   def publish_error(id, error)
-    MongoPubsub.publish(channel, {message: [1, id, error, nil]})
+    MongoPubsub.publish("#{channel}:#{id}", {message: [1, id, error, nil]})
```
Comment (SpComb) [inline server/spec/services/rpc_client_spec.rb]: This was causing the error spec to actually fail with a `RpcClient::TimeoutError` before.

**Comment by SpComb** [comment]
Travis failures are in the agent observable specs, ignoring.
