### PR TITLE
Fix e2e stack validate entrypoint spec to use --format=api-json

### LINKED ISSUE #3118: e2e spec: stack validate keywords entrypoint sets stack entrypoint
Probably broken by the #2887 fix... the spec was written against the 1.4 api-yaml style output.

Spec should be fixed to use `--format api-json` and pick up the entrypoint from the extended docker-compose file.

```
  20) stack validate keywords entrypoint sets stack entrypoint
      Failure/Error: expect(k.out).to match(/entrypoint.+?foo.+?entrypoint.+?foo2/m)
      
        expected "---\r\n# /kontena/test/spec/fixtures/stack/keywords/entrypoint.yml\r\nstack: test/simple\r\nversion:...docker-compose-entrypoint.yml\r\n      service: redis\r\n    environment: []\r\n    secrets: []\r\n" to match /entrypoint.+?foo.+?entrypoint.+?foo2/m
        Diff:
        @@ -1,2 +1,15 @@
        -/entrypoint.+?foo.+?entrypoint.+?foo2/m
        +---
        +# /kontena/test/spec/fixtures/stack/keywords/entrypoint.yml
        +stack: test/simple
        +version: 0.1.0
        +services:
        +  redis:
        +    image: redis:3-alpine
        +    entrypoint: foo
        +  redis2:
        +    extends:
        +      file: docker-compose-entrypoint.yml
        +      service: redis
        +    environment: []
        +    secrets: []
        
      # ./spec/features/stack/validate_spec.rb:8:in `block (5 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/validate_spec.rb:5:in `block (4 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #3118

### CODE REVIEW

File: test/spec/features/stack/validate_spec.rb [hunk 1]
```diff
@@ -3,9 +3,21 @@
...
-          expect(k.code).to be_zero
-          expect(k.out).to match(/entrypoint.+?foo.+?entrypoint.+?foo2/m)
+          k = run! 'kontena stack validate --format=api-json entrypoint.yml'
+          data = JSON.load(k.out)
+
+          expect(data).to match hash_including(
+            'services' => a_collection_containing_exactly(
+              hash_including(
+                'name' => 'redis',
+                'entrypoint' => 'foo',
```
Comment (kke) [inline test/spec/features/stack/validate_spec.rb]: Trailing comma

File: test/spec/features/stack/validate_spec.rb [hunk 2]
```diff
@@ -3,9 +3,21 @@
...
+              ),
+              hash_including(
+                'name' => 'redis2',
+                'entrypoint' => 'foo',
```
Comment (kke) [inline test/spec/features/stack/validate_spec.rb]: Here also

File: test/spec/features/stack/validate_spec.rb [hunk 3]
```diff
@@ -3,9 +3,21 @@
...
+              )
+            ),
```
Comment (kke) [inline test/spec/features/stack/validate_spec.rb]: And here

File: test/spec/features/stack/validate_spec.rb (hunk 1 above)
Comment (kke) [reply test/spec/features/stack/validate_spec.rb]: Not a problem, a matter of personal preference. Approved already with or without the commas.

There are upsides are simpler diffs in some cases and easier line moving, downside is mostly that it looks weird. 

And if you somehow manage to omit the closing bracket you may get something weird instead of an error.

Comment (SpComb) [reply test/spec/features/stack/validate_spec.rb]: Marking as `status/merge`, because I'm pretty sure there's already plenty of trailing commas around the codebase... it doesn't sound like a code style thing that we've been using so far.

Comment (kke) [reply test/spec/features/stack/validate_spec.rb]: (in 148 files to be exact, a couple of occurrences even by me)

File: test/spec/features/stack/validate_spec.rb (hunk 2 above)
Comment (SpComb) [inline test/spec/features/stack/validate_spec.rb]: Ugh, looks like I accidentially commited the test-to-make-sure-the-spec-actually-fails version, this should be `'entrypoint' => 'foo2'`
