### PR TITLE
Fix instance parsing in service logs

### LINKED ISSUE #1431: CLI: kontena service logs --instance does not work for stack services
The container query param is not formatted correctly:
```ruby
query_params[:container] = "#{name}-#{instance}" if instance
```

This means that `kontena service logs --instance 1 wordpress/mysql` results in `?container=wordpress/mysql-1`, which should be `?container=wordpress-mysql-1`.

#### `DEBUG=1 bundle exec bin/kontena service logs --instance 1 wordpress/mysql`
```
D, [2016-11-29T12:17:29.506807 #6853] DEBUG -- CONFIG: Loading configuration from /home/kontena/.kontena_client.json
D, [2016-11-29T12:17:29.507415 #6853] DEBUG -- CONFIG: Configuration loaded with 3 servers.
D, [2016-11-29T12:17:29.507441 #6853] DEBUG -- CONFIG: Current master: development
D, [2016-11-29T12:17:29.507469 #6853] DEBUG -- CONFIG: Current grid: development
Running #<Kontena::MainCommand:0x00000001642d40> -- callback matcher = 'nil'
Running #<Kontena::Cli::ServiceCommand:0x00000002aa69d0> -- callback matcher = 'nil'
Running #<Kontena::Cli::Services::LogsCommand:0x0000000163fa50> -- callback matcher = 'services logs'
D, [2016-11-29T12:17:29.558171 #6853] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true}
D, [2016-11-29T12:17:29.630461 #6853] DEBUG -- CLIENT: GET services/development/wordpress/mysql/container_logs: {:container=>"wordpress/mysql-1", :limit=>100} -> 200 OK: {"logs"=>[]}
```

### PR DESCRIPTION
**Pull request by jnummelin**
fixes #1431

### CODE REVIEW

File: cli/lib/kontena/cli/services/services_helper.rb [hunk 1]
```diff
@@ -283,6 +283,17 @@ def parse_service_id(service_id)
           end
         end
 
+        # Parses container name based on service name and instance number
+        # @param [String] service_name
+        # @param [Integer] instance_number
+        def parse_container_name(service_name, instance_number)
+          base = service_name.gsub('/', '-')
+          unless service_name.include?('/')
```
Comment (nevalla) [inline cli/lib/kontena/cli/services/services_helper.rb]: Should we only replace '/' with '-' if service_name includes '/', since we are checking the existence anyway.

Comment (jnummelin) [inline cli/lib/kontena/cli/services/services_helper.rb]: That's what effectively happens with the `gsub` :) To change that to be more explicit requires other if/else branching which IMO in this case is not really required.
