### PR TITLE
Fix exec console size

### LINKED ISSUE #2601: Cli exec does not set terminal size
Cli should send correct terminal size to container.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2601

### CODE REVIEW

File: cli/lib/kontena/cli/helpers/exec_helper.rb [hunk 1]
```diff
@@ -96,6 +96,12 @@ def websocket_exec_write(ws, msg)
     def websocket_exec_write_thread(ws, tty: nil)
       Thread.new do
         begin
+          if tty
+            console_height, console_width = IO.console.winsize
```
Comment (SpComb) [inline cli/lib/kontena/cli/helpers/exec_helper.rb]: Eventually this will also need a `SIGWINCH` signal handler to handle console resize.

File: agent/lib/kontena/actors/container_exec.rb [hunk 2]
```diff
@@ -27,30 +27,80 @@ def input(input)
...
+    def build_exec(command, stdin: false, tty: false)
+      opts = {
+        'Container' => @container.id,
+        'AttachStdin' => stdin,
+        'AttachStdout' => true,
+        'AttachStderr' => true,
+        'Tty' => tty,
+        'Cmd' => command
+      }
+      opts['Env'] = ['TERM=xterm'] if tty && stdin
```
Comment (jnummelin) [inline agent/lib/kontena/actors/container_exec.rb]: +1 for passing the envs from CLI

Comment (jakolehm) [inline agent/lib/kontena/actors/container_exec.rb]: Probably can be a separate PR?

File: cli/lib/kontena/cli/helpers/exec_helper.rb (hunk 1 above)
Comment (jakolehm) [inline cli/lib/kontena/cli/helpers/exec_helper.rb]: Probably can be a separate PR?

File: agent/lib/kontena/actors/container_exec.rb (hunk 2 above)
Comment (jnummelin) [inline agent/lib/kontena/actors/container_exec.rb]: Can be yes.

I'm not that familiar with the different terminal types and how/where they affect, but should the `TERM` for the exec actually match the client terminal type?

File: cli/lib/kontena/cli/helpers/exec_helper.rb (hunk 1 above)
Comment (jnummelin) [inline cli/lib/kontena/cli/helpers/exec_helper.rb]: IMO yes.

File: agent/lib/kontena/actors/container_exec.rb (hunk 2 above)
Comment (jnummelin) [inline agent/lib/kontena/actors/container_exec.rb]: Well, docker itself seems to default to `xterm`also: https://github.com/moby/moby/pull/26461/files#diff-3ed197c0a6f7a9ca73a3ee424e448ac1R130

So I guess it's fine to default to that.

File: agent/lib/kontena/actors/container_exec.rb [hunk 3]
```diff
@@ -27,30 +27,80 @@ def input(input)
...
+    def tty_resize(size)
+      return unless @container_exec
+
+      begin
+        @container_exec.resize({
+          'w' => size['width'], 'h' => size['height']
+        })
+      rescue Docker::Error::NotFoundError
+        sleep 0.1
+        retry if @container_exec
```
Comment (SpComb) [inline agent/lib/kontena/actors/container_exec.rb]: Still don't understand the retry. The container exec has an ID, and once Docker is done with that exec, and the `POST /exec/:id/resize` starts returning HTTP 404 errors, how is retrying going to help?

File: agent/lib/kontena/actors/container_exec.rb (hunk 2 above)
Comment (SpComb) [inline agent/lib/kontena/actors/container_exec.rb]: Separate issue: #2729

File: cli/lib/kontena/cli/helpers/exec_helper.rb (hunk 1 above)
Comment (SpComb) [inline cli/lib/kontena/cli/helpers/exec_helper.rb]: This does not fix #2601then. Edit that to only cover the initial terminal size, and I can create a new issue for the resize?

**Comment by SpComb** [comment]
Needs merge for #2743 (and probably also #2745 if merged)

File: agent/lib/kontena/actors/container_exec.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (SpComb) [reply agent/lib/kontena/actors/container_exec.rb]: Ping @jakolehm, I reckon this would be mergable after dropping this mystery `retry`?

**Comment by SpComb** [comment]
This would still be good to have for 1.4, because things like line wrapping and curses apps are broken in exec terminals.

Still also need some extra work to also allow reszing the exec terminal after starting it, though.

File: agent/lib/kontena/actors/container_exec.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (jakolehm) [reply agent/lib/kontena/actors/container_exec.rb]: I can remove retry after I test this more ... it's there because something is racy (in docker?) and it raised not found errors quite often.

File: server/app/services/docker/streaming_executor.rb [hunk 4]
```diff
@@ -63,7 +63,11 @@ def register_stdin_ws_events(shell, tty)
         else
           begin
             input = JSON.parse(event.data)
-            @client.notify('/containers/tty_input', @exec_session['id'], input['stdin']) if input.has_key?('stdin')
+            if input.has_key?('stdin')
+              @client.notify('/containers/tty_input', @exec_session['id'], input['stdin'])
+            elsif input.has_key?('console_size')
```
Comment (SpComb) [inline server/app/services/docker/streaming_executor.rb]: Maybe avoid introducing a new `console` term in the API, and use the `tty` naming for this, like `{ "tty_size": { "width": 80, "height": 24 } }`?

File: agent/lib/kontena/rpc/docker_container_api.rb [hunk 5]
```diff
@@ -152,6 +152,16 @@ def tty_input(id, input)
       end
 
       # @param [String] id
+      # @param [String] size
+      def tty_resize(id, size)
+        actor_id = "container_exec_#{id}"
+        executor = Celluloid::Actor[actor_id]
+        if executor
+          executor.tty_resize(size)
```
Comment (SpComb) [inline agent/lib/kontena/rpc/docker_container_api.rb]: `async` to not block the RPC server.

**Comment by jakolehm** [comment]
Without weird retry logic docker will say this:
```
Docker::Error::NotFoundError: containerd: process not found for container
```

File: agent/lib/kontena/rpc/docker_container_api.rb (hunk 5 above)
Comment (jakolehm) [reply agent/lib/kontena/rpc/docker_container_api.rb]: Done

File: cli/lib/kontena/cli/helpers/exec_helper.rb (hunk 1 above)
Comment (jakolehm) [reply cli/lib/kontena/cli/helpers/exec_helper.rb]: Edited #2601

File: server/app/services/docker/streaming_executor.rb (hunk 4 above)
Comment (jakolehm) [reply server/app/services/docker/streaming_executor.rb]: Done.

File: agent/lib/kontena/actors/container_exec.rb [hunk 6]
```diff
@@ -33,22 +33,45 @@ def input(input)
...
+
+      begin
+        @container_exec.resize({
+          'w' => size['width'], 'h' => size['height']
+        })
+        info "tty resized to #{size['width']}x#{size['height']}"
+      rescue Docker::Error::NotFoundError => exc
+        if exc.message.include?('process not found')
+          sleep 0.1
+          retry if @container_exec
```
Comment (SpComb) [inline agent/lib/kontena/actors/container_exec.rb]: > Without weird retry logic docker will say this: `Docker::Error::NotFoundError: containerd: process not found for container`

Does that happen if you `resize` before the exec has been `start!`ed? That only happens later in the `defer` block, so it's entirely possible for `tty_resize` run before the call to `start!`... although it's also hard to tell when the exec has actually started :confused: 

What happens if there's a `resize` after the exec has stopped? I'm worried about this getting stuck in an infinite retry loop.

Comment (jakolehm) [reply agent/lib/kontena/actors/container_exec.rb]: It sets `@container_exec` to `nil` in `ensure`. Should be safe?

File: cli/lib/kontena/cli/helpers/exec_helper.rb (hunk 1 above)
Comment (SpComb) [reply cli/lib/kontena/cli/helpers/exec_helper.rb]: Filed  #2839 for the missing `SIGWINCH` tty resize functionality in this PR.

File: agent/lib/kontena/actors/container_exec.rb (hunk 6 above)
Comment (SpComb) [reply agent/lib/kontena/actors/container_exec.rb]: Yeah, this looks very much like a race between the call to `@container_exec.resize` and the call to `@container_exec.start!`. In this case, it seems likely for the `resize` to happen before the `start!`:

```
D, [2017-09-19T09:31:40.700960 #1] DEBUG -- Kontena::RpcServer: rpc request: Kontena::Rpc::DockerContainerApi#create_exec ["b2cdc7e4da79574882f89d02fc582f0e23fead6e3c3b3e35fbac1fda7a09df5e"]
I, [2017-09-19T09:31:40.706165 #1]  INFO -- Kontena::Actors::ContainerExec: initialized (session 8b781dac-82e0-4298-a999-1741d5db6964)
D, [2017-09-19T09:31:40.727809 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#run_exec ["8b781dac-82e0-4298-a999-1741d5db6964", ["bash"], true, true]
I, [2017-09-19T09:31:40.728268 #1]  INFO -- Kontena::Actors::ContainerExec: starting command: ["bash"] (tty: true, stdin: true)
D, [2017-09-19T09:31:40.739328 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: exec_create: bash 
D, [2017-09-19T09:31:40.742052 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#tty_resize ["8b781dac-82e0-4298-a999-1741d5db6964", {"width"=>140, "height"=>39}]
I, [2017-09-19T09:31:40.748308 #1]  INFO -- Kontena::Actors::ContainerExec: resize tty to 140x39
D, [2017-09-19T09:31:40.749280 #1] DEBUG -- Kontena::Actors::ContainerExec: start exec 82b54c9c4779265a0ac18467aea7f25188440d2f17e8831ce7c8ab47f6c92406 with tty...
D, [2017-09-19T09:31:40.793657 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: exec_start: bash 
E, [2017-09-19T09:31:40.871032 #1] ERROR -- Kontena::Actors::ContainerExec: containerd: process not found for container
D, [2017-09-19T09:31:40.960604 #1] DEBUG -- Kontena::Actors::ContainerExec: tty exec output: "root@redis-1:/data# "
I, [2017-09-19T09:31:41.030233 #1]  INFO -- Kontena::Actors::ContainerExec: resize tty to 140x39
```

However, this race is tricky to fix, because it's not enough to wait for the call to `start!` to happen, the actual `POST /exec/.../start` request has to go through... Not possible to know when that has happened with the `docker-api` client. It looks like the Docker CLI waits for the `POST /exec/.../start` [request](https://github.com/docker/cli/blob/139fcd3ee95f37f3ac17b1200fb0a63908cb6781/cli/command/container/exec.go#L127) to complete in some form before doing the `POST /exec/.../resize`, and that might even be a `Connection: upgrade` `Upgrade: tcp` request with a [HTTP 101 Switching Protocols](https://github.com/moby/moby/blob/5c57ca17d50c392b7ad627fc1215d7a7e91e0c41/client/hijack.go#L183) response...

The `retry` with the `ensure` -> `@container_exec = nil` is an acceptable workaround, but IMO this kind of error handling retry code really needs some kind of comment explaining what happens and why this is needed... more than just the GitHub PR discussion.

File: agent/lib/kontena/actors/container_exec.rb [hunk 7]
```diff
@@ -67,6 +90,7 @@ def run(cmd, tty = false, stdin = false)
       info "#{cmd} exit with code #{exit_code}: #{cmd}"
       handle_exit(exit_code)
     ensure
+      @container_exec = nil
```
Comment (SpComb) [inline agent/lib/kontena/actors/container_exec.rb]: Maybe move this into the `defer { ... ensure }`, to make sure that it happens even if the actor thread is unable to see the `defer` thread future value? Similarly to how the `@read_pipe.close` is done.

TBH the Docker exec API rather confusing, because I have no idea at what point the `/exec/...` ID gets invalidated and starts returning HTTP 404 errors, there's no `DELETE`. But once the request to `POST /exec/.../start` returns, it's probably best to consider the `@container_exec.id` invalid.

File: agent/lib/kontena/actors/container_exec.rb (hunk 6 above)
Comment (SpComb) [reply agent/lib/kontena/actors/container_exec.rb]: TLDR: not feasible to fix the race condition, this `retry` is a good workaround, but it needs a comment explaining what's going on

File: agent/lib/kontena/actors/container_exec.rb (hunk 7 above)
Comment (SpComb) [reply agent/lib/kontena/actors/container_exec.rb]: Dunno how much it's worth trying to think about this... testing with something like `kontena service exec -it redis/redis bash -c 'sleep 0.008'` to invoke races between the exec exit and the resize, the Docker API itself errors out in the `resize`:

```
E, [2017-09-19T10:57:39.759795 #1] ERROR -- : Actor crashed!
Docker::Error::ServerError: write /var/run/docker/libcontainerd/containerd/b2cdc7e4da79574882f89d02fc582f0e23fead6e3c3b3e35fbac1fda7a09df5e/1c91deab68f7a0644389337cccce762a07bd8c99654e683764b3c34118a45653/control: bad file descriptor

	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/connection.rb:50:in `rescue in request'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/exec.rb:93:in `resize'
	/app/lib/kontena/actors/container_exec.rb:43:in `tty_resize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-09-19T10:57:39.760344 #1] ERROR -- Kontena::Actors::ContainerExec: task was terminated (Celluloid::TaskTerminated)
```
