### PR TITLE
Fix server node update grid notify

### LINKED ISSUE #2746: kontena node/labels update does not notify nodes
Affects 1.3 and 1.4. 

This means that changes to node `region` labels are not applied until weave is restarted manually on the nodes.

Very similar to #2584, shows up in the #2699 logging.. except that in 1.4, #2306 overrode `HostNodes::Update#notify_node`, it breaks differently on 1.4:

```
E, [2017-08-29T05:44:24.602482 #13] ERROR -- HostNodes::Update: wrong number of arguments (given 2, expected 1) (ArgumentError)
/app/app/mutations/host_nodes/update.rb:55:in `notify_node'
/app/app/mutations/host_nodes/common.rb:7:in `block in notify_grid'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
/app/app/mutations/host_nodes/common.rb:6:in `notify_grid'
/app/app/mutations/host_nodes/update.rb:25:in `block in execute'
/app/app/helpers/async_helper.rb:11:in `block in async_thread'
172.17.0.1 - - [29/Aug/2017:05:44:24 +0000] "PUT /v1/nodes/development/core-01 HTTP/1.1" 200 1726 0.1076
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2746

This was broken in 1.3 by #2144, and also in 1.4 by #2306. Shows up in the #2699 logging.

Fix the `notify_node` => `Agent::NodePlugger.new(node)` param, as well as the `start/stop_stateful_services` => `notify_node(...)` method collision.

Adds specs that now actually test that this actually works.

### CODE REVIEW

File: server/spec/mutations/host_nodes/update_spec.rb [hunk 1]
```diff
@@ -27,67 +32,115 @@
...
-          )
-          expect(mutation).to receive(:stop_stateful_services)
+        context 'with a running stateful service instance' do
+          let!(:stack) { grid.stacks.find_by(name: 'null') }
+          let!(:stateful_service) { grid.grid_services.create!(stack: stack, name: 'redis', image_name: 'redis:latest', stateful: true, state: 'running') }
+          let!(:stateful_service_instance1) { stateful_service.grid_service_instances.create!(host_node: node, instance_number: 1, desired_state: 'running') }
+
+          it 'stops stateful services when draining' do
+            expect(rpc_client).to receive(:notify).with('/service_pods/notify_update', 'stop') do
+              expect(stateful_service_instance1.desired_state).to eq 'stopped'
```
Comment (jnummelin) [inline server/spec/mutations/host_nodes/update_spec.rb]: Is this to validate that the desired state is `stopped` when the notification is sent? Maybe a `reload`   is in order?

Comment (SpComb) [reply server/spec/mutations/host_nodes/update_spec.rb]: Yes, sending them in the wrong order would be bad, or not actually saving the `desired_state` change. Reload is good.
