### PR TITLE
Fix agent LogWorker start/stop

### LINKED ISSUE #2232: Agent LogWorker can run multiple `watch_queue` and `process_queue` tasks
This is because both `initialize` and `on_connect` call `async.start`, which both unconditionally call `async.watch_queue` and `async.process_queue`. Those tasks may quit if the actor is `!queue_processing?` which is the case in `initialize`, but the `initialize -> start` task will wait for `Actor[:etcd_launcher].running?` before it calls `async.process_queue`, at which point it seems possible for the actor to already be `queue_processing?`, so the task stays running.

Example from a `Celluloid.dump`:

```
kontena-agent | Celluloid::Actor 0x2abead8ce0d8
kontena-agent | Celluloid::Cell 0x2abead8ce59c: Kontena::Workers::LogWorker
kontena-agent | State: Running (executing tasks)
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/wait.rb:33:in `while_time_remaining'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/wait.rb:11:in `for'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
kontena-agent | 
kontena-agent | 
kontena-agent | 	Tasks:
kontena-agent | 	  1) Celluloid::Task::Fibered[call]: sleeping
kontena-agent | 	      {:dangerous_suspend=>false, :method_name=>:watch_queue}
kontena-agent | 		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
kontena-agent | 
kontena-agent | 
kontena-agent | 	  2) Celluloid::Task::Fibered[call]: receiving
kontena-agent | 	      {:dangerous_suspend=>false, :method_name=>:process_queue}
kontena-agent | 		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
kontena-agent | 
kontena-agent | 
kontena-agent | 	  3) Celluloid::Task::Fibered[call]: sleeping
kontena-agent | 	      {:dangerous_suspend=>false, :method_name=>:watch_queue}
kontena-agent | 		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
kontena-agent | 
kontena-agent | 
kontena-agent | 	  4) Celluloid::Task::Fibered[call]: receiving
kontena-agent | 	      {:dangerous_suspend=>false, :method_name=>:process_queue}
kontena-agent | 		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
kontena-agent | 

kontena-agent | Thread 0x2abeaf2888e8 (future):
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:407:in `sleep'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:407:in `sleep'
kontena-agent | 	/app/lib/kontena/workers/log_worker.rb:89:in `block in process_queue'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
kontena-agent | 
kontena-agent | 
kontena-agent | Thread 0x2abeaddb8170 (future):
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:407:in `sleep'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:407:in `sleep'
kontena-agent | 	/app/lib/kontena/workers/log_worker.rb:89:in `block in process_queue'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

### LINKED ISSUE #2661: LogWorker shouldn't spam docker logs
See https://github.com/kontena/kontena/blob/master/agent/lib/kontena/workers/log_worker.rb#L69
I get this message logged seemly every few milliseconds: `WARN -- Kontena::Workers::LogWorker: queue size is 1600`.  I think this code should never log this same warning more frequently than say 5 seconds.

This isn't a bug; just an improvement.

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #2232, fixes  #2661

* Only run one `async.watch_queue` task from `initialize`
* Fix `start unless running?` and `stop if running?` to not race and launch duplicate tasks
* Shut down `process_queue` from `stop`

Not 100% sure about the `exclusive { ... }` blocks.

### CODE REVIEW

**Comment by jakolehm** [comment]
Should we not autostart `LogWorker` when supervisor is started? It will be started when connection is opened (or is there possible race cond)?

**Comment by SpComb** [comment]
> Should we not autostart LogWorker when supervisor is started? It will be started when connection is opened (or is there possible race cond)?

Hmm... it shouldn't start processing the queue if the websocket isn't connected yet. Need to fix that... which requires querying the websocket actor for its current state at startup. Doable with notifications, but also calls for `Observable` :heart:

File: agent/lib/kontena/workers/log_worker.rb [hunk 1]
```diff
@@ -17,70 +19,69 @@ class LogWorker
...
+
+        async.process_queue
+      }
     end
 
+    # Process items from @queue until nil
     def process_queue
       defer {
-        while queue_processing? && data = @queue.pop
+        while data = @queue.pop
```
Comment (SpComb) [inline agent/lib/kontena/workers/log_worker.rb]: Bad: this change means that it will empty out the `@queue` and drop any queued up log items when disconnecting, because the `@queue << nil` from `stop` will show up after any queued up messages.

Comment (SpComb) [reply agent/lib/kontena/workers/log_worker.rb]: Not anymore.
