### PR TITLE
Agent observable fixes

### LINKED ISSUE #2037: Observable race condition
Sometimes observable/observer actors are crashing.

Backtrace:
```
kontena-agent | RuntimeError: can't add a new key into hash during iteration
kontena-agent | 	/app/lib/kontena/observable.rb:53:in `add_observer'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
kontena-agent | 	(celluloid):0:in `remote procedure call'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
kontena-agent | 	/app/lib/kontena/observer.rb:85:in `block in observe'
kontena-agent | 	/app/lib/kontena/observer.rb:83:in `each'
kontena-agent | 	/app/lib/kontena/observer.rb:83:in `observe'
kontena-agent | 	/app/lib/kontena/workers/service_pod_manager.rb:25:in `start'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### PR DESCRIPTION
**Pull request by SpComb**
* Fixes #2037 `RuntimeError: can't add a new key into hash during iteration` race
* Fixes flaky `Kontena::Observable For chained observables propagates the observed value` spec
* Suppresses the agent rspec actor crash errors
* Avoid any remote actor calls while debug logging
* Have Observable log dead Observer actor cleanups
* Improved specs involving multiple concurrent observers

The `RuntimeError: can't add a new key into hash during iteration` crash was happening due to a race between the `Observable#notify_observers` loop and `Observable#add_observer`. This was possible because the `notify_observers` loop was accidentially doing a `observer.sync.to_s` call in the `debug` logging...

### CODE REVIEW

File: agent/lib/kontena/observable.rb [hunk 1]
```diff
@@ -58,12 +61,14 @@ def add_observer(observer, observe)
...
     def notify_observers
       observers.each do |observe, observer|
-        begin
-          debug "notify: #{observer} <- #{@observable_value}"
+        if observer.alive?
+          debug "notify: #{observe} <- #{@observable_value.inspect[0..64] + '...'}"
 
           # XXX: is the Observable's Celluloid.current_actor guranteed to match the Actor[:node_info_worker] Celluloid::Proxy::Cell by identity?
           observer.async.update_observe(observe, Celluloid.current_actor, @observable_value)
-        rescue Celluloid::DeadActorError => error
```
Comment (SpComb) [inline agent/lib/kontena/observable.rb]: It seems like it was the `observer.to_s` that was raising the `Celluloid::DeadActorError`, and that `observer.async.*` can not raise `Celluloid::DeadActorError`

File: agent/lib/kontena/observer.rb [hunk 2]
```diff
@@ -55,6 +63,8 @@ def observed(observe)
     # @param observable [Celluloid::Proxy::Cell<Observable>]
     # @param value [Object, nil] observed value
     def update_observe(observe, observable, value)
+      debug "observe Observable<#{observable.__klass__}> -> #{value}"
```
Comment (SpComb) [inline agent/lib/kontena/observer.rb]: This `__klass__` is some `Celluloid::Proxy::AbstractCall` thing.

File: agent/lib/kontena/observer.rb [hunk 3]
```diff
@@ -68,6 +78,10 @@ def update_observe(observe, observable, value)
     # Yield happens once each Observable is ready, and whenever they are updated.
     # Yields to block happens from different async tasks.
     #
+    # The block must be idempotent: it is not guaranteed to receive every Observable update.
+    # It is only guaranteed to receive later Observable updates in the correct order,
+    # and it may receive some Observable updates multiple times.
```
Comment (SpComb) [inline agent/lib/kontena/observer.rb]: This naturally happens if the Observer crashes, restarts and re-observes, but it can also happen during the initial `observe` cycle, if the initial `add_observer` returns nil, but then the observable updates with some value before the initial `async.observed` happens

```
D, [2017-03-31T17:05:09.484644 #13147] DEBUG -- : observer: Observer<> <- nil...
D, [2017-03-31T17:05:09.485523 #13147] DEBUG -- : update: 1
D, [2017-03-31T17:05:09.485864 #13147] DEBUG -- : observe Observable<#<Class:0x00000002557e98>> -> 
D, [2017-03-31T17:05:09.486180 #13147] DEBUG -- : notify: Observer<> <- 1...
D, [2017-03-31T17:05:09.499476 #13147] DEBUG -- : observe Observable<#<Class:0x00000002557e98>> -> 1
D, [2017-03-31T17:05:09.513581 #13147] DEBUG -- : observed  -> 1
D, [2017-03-31T17:05:09.520398 #13147] DEBUG -- : observed 1 -> 1
```
