### PR TITLE
Fix network startup ordering

### LINKED ISSUE #1270: Docker startup ordering with the kontena-ipam plugin
The following has to happen at boot:

* Docker starts
   * Docker spins waiting for the kontena-ipam plugin to appear
   * Docker times out and leaves any auto-restarting kontena network containers stopped
* Docker automatically restarts the weaver, kontena-etcd and kontena-ipam-plugin containers
  * The weave container is waiting for the weave bridge
  * The kontena-etcd container is in a crash-restart loop waiting for the weave bridge expose `10.81.0.X` IP
  * The kontena-ipam-plugin container is in a crash-restart loop waiting for etcd
* Docker starts the kontena-agent
  * The kontena agent does `weaveexec attach-router`, which creates the weave bridge and allows weave to continue
  * The kontena agent does `weaveexec expose`, which configures the weave bridge 
* The kontena-etcd restarts and gets up and running
* The kontena-ipam-plugin restarts and gets up and running

Only at this point can the kontena agent start doing things like creating new service containers, starting stopped containers, migrating containers etc.

### `Kontena::Workers::ContainerStarterWorker`

```
kontena-agent | I, [2016-11-02T10:24:38.170103 #1]  INFO -- Kontena::Workers::ContainerStarterWorker: starting container: /redis-4
kontena-agent | E, [2016-11-02T10:24:53.223148 #1] ERROR -- : Actor crashed!
kontena-agent | Docker::Error::NotFoundError: plugin not found
kontena-agent | 
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:46:in `rescue in request'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:176:in `start!'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:190:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:190:in `block (2 levels) in <class:Container>'
kontena-agent | 	/app/lib/kontena/workers/container_starter_worker.rb:36:in `ensure_container_running'
kontena-agent | 	/app/lib/kontena/workers/container_starter_worker.rb:28:in `block in start'
kontena-agent | 	/app/lib/kontena/workers/container_starter_worker.rb:27:in `each'
kontena-agent | 	/app/lib/kontena/workers/container_starter_worker.rb:27:in `start'
kontena-agent | 	/app/lib/kontena/workers/container_starter_worker.rb:22:in `on_overlay_start'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### `Kontena::NetworkAdapters::Weave`

The `start` -> `ensure_kontena_network` requires both `kontena-etcd` and `kontena-ipam-plugin` to be running.

```
kontena-agent | I, [2016-11-02T11:22:34.928925 #1]  INFO -- Kontena::NetworkAdapters::Weave: bridge exposed: 10.81.0.2/16
kontena-agent | I, [2016-11-02T11:22:39.794418 #1]  INFO -- Kontena::Launchers::IpamPlugin: ipam image pulled: kontena/ipam-plugin:latest
kontena-agent | I, [2016-11-02T11:22:39.794606 #1]  INFO -- Kontena::Launchers::IpamPlugin: node info received, launching ipam...
kontena-agent | I, [2016-11-02T11:22:39.936687 #1]  INFO -- Kontena::Launchers::IpamPlugin: started ipam-plugin service
kontena-agent | I, [2016-11-02T11:22:41.765291 #1]  INFO -- Kontena::NetworkAdapters::Weave: creating default kontena network...
kontena-agent | E, [2016-11-02T11:22:56.810904 #1] ERROR -- Kontena::NetworkAdapters::Weave: Docker::Error::NotFoundError: plugin not found
kontena-agent | 
kontena-agent | D, [2016-11-02T11:22:56.818981 #1] DEBUG -- NetworkAdapters::Weave: /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/network.rb:48:in `create'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:272:in `ensure_kontena_network'
kontena-agent | /app/lib/kontena/network_adapters/weave.rb:198:in `start'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### PR DESCRIPTION
**Pull request by jnummelin**
This PR fixes startup issues with new network components. The startup events are refactored into two separate events now, namely `ipam:start` and `network_adapter:start`. The latter is used as before to indicate that the network itself (weave) is started and etcd and others can continue to bootstrap. Combined these two now indicate that it is safe to ensure the existence of the default `kontena` network.

The `NetworkCreatorWorker` emits `network:ready` event when the default network is created to indicate that it is safe to start the network migrator and left-over container starter.

fixes #1270

### CODE REVIEW

File: agent/lib/kontena/workers/network_create_worker.rb [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    def ipam_started(topic, data)
+      debug 'ipam_started'
+      @ipam_started = true
+      ensure_default_network
+    end
+
+    
+    def create_network(name, driver, ipam_driver, subnet, ip_range = nil)
+      opts = {
+        'Driver': driver,
```
Comment (jakolehm) [inline agent/lib/kontena/workers/network_create_worker.rb]: is this really valid syntax? `:` vs `=>` ?

Comment (jnummelin) [inline agent/lib/kontena/workers/network_create_worker.rb]: yes.
```
2.3.1 :001 > opts = {'Driver':'foo'}
 => {:Driver=>"foo"}
```
IMO it's bit more readable this way since the target for the data is Docker remote API with json payload.

File: agent/lib/kontena/launchers/ipam_plugin.rb [hunk 2]
```diff
@@ -40,6 +40,14 @@ def image_exists?
       @image_pulled
     end
 
+    def running?
```
Comment (SpComb) [inline agent/lib/kontena/launchers/ipam_plugin.rb]: Is this used anywhere?

Some kind of signal that etcd + kontena-ipam is running would be good, although the Docker/libnetwork timeouts when first attempting to use the network API should cover most of that.

Comment (jnummelin) [inline agent/lib/kontena/launchers/ipam_plugin.rb]: Just pushed some improvement for this. Now it emits the start event only when ipam is running. And it should not be running without etcd. :)

File: agent/lib/kontena/launchers/ipam_plugin.rb [hunk 3]
```diff
@@ -34,12 +34,22 @@ def on_node_info(topic, info)
 
     def start(info)
       create_container(@image_name, info)
+      sleep 1 until running?
```
Comment (jnummelin) [inline agent/lib/kontena/launchers/ipam_plugin.rb]: Yes, there seems to be short window where the ipam container is running but not crashed yet. Maybe agent could poll the `/IpamDriver.GetCapabilities` endpoint?

**Comment by SpComb** [comment]
ATM it looks like the `Kontena::Launchers:IpamPlugin` starts on `agent:node_info`, but that's pretty early; shouldn't it wait for  network_adapter:start` and ideally some signal from the etcd launcher?

**Comment by jnummelin** [comment]
I switched to launch IPAM after weave has been started.

File: agent/lib/kontena/launchers/ipam_plugin.rb [hunk 4]
```diff
@@ -27,14 +27,17 @@ def ensure_image
       info "ipam image pulled: #{@image_name}"
     end
 
-    def on_node_info(topic, info)
+    def on_network_start(topic, info)
       info "node info received, launching ipam..."
```
Comment (SpComb) [inline agent/lib/kontena/launchers/ipam_plugin.rb]: Tweak the log message still, it's not "node info received" anymore

**Comment by jakolehm** [comment]
LGTM

**Comment by SpComb** [comment]
LGTM

Startup ordering seems much improved. Probably not quite a 0.17 release yet, but closer :)
```
kontena-agent | D, [2016-11-04T14:33:26.721690 #1] DEBUG -- RpcServer: rpc notification: Kontena::Rpc::AgentApi#node_info ...
kontena-agent | E, [2016-11-04T14:33:27.162780 #1] ERROR -- Kontena::NetworkAdapters::Weave: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "...", "--trusted-subnets", ""]
kontena-agent | weave is already running; you can stop it with 'weave stop-router'.
kontena-agent | 
kontena-agent | I, [2016-11-04T14:33:27.181337 #1]  INFO -- Kontena::NetworkAdapters::Weave: attaching router
kontena-agent | D, [2016-11-04T14:33:28.026219 #1] DEBUG -- NetworkAdapters::Weave: weaveexec ok: ["--local", "attach-router"]
kontena-agent | D, [2016-11-04T14:33:28.186158 #1] DEBUG -- NetworkAdapters::Weave: weaveexec ok: ["--local", "connect", "--replace", "192.168.66.101"]
kontena-agent | I, [2016-11-04T14:33:28.195529 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers 192.168.66.101
kontena-agent | I, [2016-11-04T14:33:28.195754 #1]  INFO -- Kontena::NetworkAdapters::Weave: using trusted subnets: 
kontena-agent | D, [2016-11-04T14:33:28.423699 #1] DEBUG -- NetworkAdapters::Weave: weaveexec ok: ["--local", "expose", "ip:10.81.0.2/16"]
kontena-agent | I, [2016-11-04T14:33:28.440107 #1]  INFO -- Kontena::NetworkAdapters::Weave: bridge exposed: 10.81.0.2/16
kontena-agent | D, [2016-11-04T14:33:28.685965 #1] DEBUG -- NetworkAdapters::Weave: weaveexec ok: ["--local", "launch-plugin"]
kontena-agent | I, [2016-11-04T14:33:28.704170 #1]  INFO -- Kontena::Launchers::IpamPlugin: network started, launching ipam...
kontena-agent | I, [2016-11-04T14:33:28.714488 #1]  INFO -- Kontena::Workers::WeaveWorker: attaching network to existing containers
kontena-agent | I, [2016-11-04T14:33:28.764920 #1]  INFO -- Kontena::Launchers::Etcd: etcd is already running
kontena-agent | D, [2016-11-04T14:33:28.769875 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /kontena-agent
kontena-agent | I, [2016-11-04T14:33:28.774652 #1]  INFO -- Kontena::Launchers::IpamPlugin: ipam-plugin container exists but not running, starting it
kontena-agent | D, [2016-11-04T14:33:28.779421 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /weaveplugin
kontena-agent | D, [2016-11-04T14:33:28.784353 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /kontena-etcd
kontena-agent | D, [2016-11-04T14:33:28.801717 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /weave
kontena-agent | D, [2016-11-04T14:33:28.801791 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /kontena-ipam-plugin
kontena-agent | D, [2016-11-04T14:33:28.803362 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /weaveplugin
kontena-agent | D, [2016-11-04T14:33:28.803853 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /kontena-agent
kontena-agent | D, [2016-11-04T14:33:28.804393 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /weave
kontena-agent | D, [2016-11-04T14:33:28.815677 #1] DEBUG -- Workers::ContainerLogWorker: starting to stream logs from /kontena-cadvisor
kontena-agent | D, [2016-11-04T14:33:28.829257 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /kontena-ipam-plugin
kontena-agent | D, [2016-11-04T14:33:28.834292 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /kontena-etcd
kontena-agent | D, [2016-11-04T14:33:28.840054 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /kontena-cadvisor
kontena-agent | D, [2016-11-04T14:33:28.850740 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /kontena-etcd
kontena-agent | D, [2016-11-04T14:33:39.586935 #1] DEBUG -- Workers::WeaveWorker: did not find ip for container: /kontena-ipam-plugin
kontena-agent | I, [2016-11-04T14:33:39.989576 #1]  INFO -- Kontena::Workers::NetworkCreateWorker: network and ipam ready, ensuring default network existence
kontena-agent | I, [2016-11-04T14:33:39.997504 #1]  INFO -- Kontena::Workers::ContainerStarterWorker: network ready, check if some containers need to be started
kontena-agent | I, [2016-11-04T14:33:39.997604 #1]  INFO -- Kontena::Workers::ContainerNetworkMigratorWorker: network ready, check if containers need to be migrated
kontena-agent | I, [2016-11-04T14:33:40.077397 #1]  INFO -- Kontena::Workers::ContainerStarterWorker: starting container: /redis-6
kontena-agent | I, [2016-11-04T14:33:43.171269 #1]  INFO -- Kontena::Workers::ContainerStarterWorker: starting container: /redis-4
```

The `Kontena::Workers::NetworkCreateWorker` is able to wait the 10s for weave + etcd + kontena-ipam to start.
