### PR TITLE
Replace server timeout { sleep until ... } loops with non-interrupting wait_until { ... } loops

### LINKED ISSUE #1986: Server Timeout::Errors will corrupt Moped::Connections
Each `Moped::Session` uses a shared `ConnectionPool` of `Moped::Connection`s. The [`Moped::Connection#read`](https://github.com/mongoid/moped/blob/v2.0.7/lib/moped/connection.rb#L117
) method will first read the 36-byte header, and then read the rest of the response body. If this sequence of `Moped::Connection#read` -> `read_data` operations is interrupted, then all or part of the mongo response may be left un-read on the `Moped::Connection` socket. This means that any future operations that use the same `Moped::Connection` will either receive the result of the previous operation (if it failed before reading the response header), or some random part of the previous result that is not a valid mongo response header (if it failed while reading the response body).

The way that the [`Moped::Node#connection`](https://github.com/mongoid/moped/blob/v2.0.7/lib/moped/node.rb#L116) is used for sending commands and receiving responses is thus not exception-safe: the [`ConnectionPool#with`](https://github.com/mperham/connection_pool/blob/v2.2.0/lib/connection_pool.rb#L59) method will return the `Moped::Connection` raising an exception with a partially read response in its socket back to the connection pool, to be re-used by a future operation...

The most obvious way to trigger this kind of issue is by the use of `Timeout::timeout` with moped operations... this is a [bad idea](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/), and is likely to lead to runaway errors in the server: https://github.com/mongoid/moped/issues/89#issuecomment-9385318

> We've been able to reduce the issue dramatically by removing our health check:
> ```
> Timeout::timeout(3) { !Mongoid.default_session.collections.nil? }
> ```
> We realized this because errors would happen right after a healthcheck would timeout. So the issue is that not all the data is read off of the socket and the next request will contain residual data from the previous request when its read.

Unfortunately, the server contains a lot of [code like](https://github.com/kontena/kontena/blob/v1.1.4/server/app/models/distributed_lock.rb#L16):

```ruby
Timeout.timeout(timeout) do
    sleep X until mongo_query()
end
```

These timeouts work fine as long as they happen within the `sleep`, but if the timeout happens within the `mongo_query()`, then this will leave the `Moped::Connection` in a broken state, and then lead to further mongoid/moped query failures or even corruption within the same process - these `Moped::Connection` are shared across all threads in the same process.

## Example

Modify the `DistributedLock#with_lock` to spend less time sleeping, making the `Timeout::Error` more likely to raise within the ``Moped::Connection#read`:

```patch
--- a/server/app/models/distributed_lock.rb
+++ b/server/app/models/distributed_lock.rb
@@ -14,7 +14,9 @@ class DistributedLock
     begin
       if timeout.to_f > 0.0
         Timeout.timeout(timeout) do
-          sleep 0.01 until lock_id = self.obtain_lock(name)
+          until lock_id = self.obtain_lock(name) do
+
+          end
         end
       else
         lock_id = self.obtain_lock(name)
@@ -22,7 +24,8 @@ class DistributedLock
       if lock_id
         return yield
       end
-    rescue Timeout::Error
+    rescue Timeout::Error => error
+      warn "Timeout while obtaining lock: #{error}\n#{error.backtrace.join("\n")}"
       return false
     ensure
       self.release_lock(name, lock_id) if lock_id
```

This leads to all manner of interesting failures in the `DistributedLock.with_lock returns false if getting lock timeouts` spec:

### Timeout while write

Not sure what happens here, the first thread gets a `Moped::Errors::ConnectionFailure` from its `obtain_lock` after the second thread times out while writing the `obtain_lock` operation.

```
Timeout while obtaining lock: execution expired
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:62:in `write'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:62:in `block in write'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:119:in `handle_socket_errors'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:62:in `write'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:174:in `block in write'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:225:in `with_connection'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:173:in `write'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:604:in `block (2 levels) in flush'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:663:in `read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:90:in `command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:73:in `block in command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb:25:in `execute'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:83:in `command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:309:in `block in modify'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:374:in `with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:308:in `modify'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/find_and_modify.rb:44:in `result'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:182:in `find_and_modify'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `find_and_modify'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:44:in `obtain_lock'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:18:in `block in with_lock'
/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:17:in `with_lock'
/home/kontena/kontena/kontena/server/spec/models/distributed_lock_spec.rb:31:in `block (4 levels) in <top (required)>'
F

Failures:

  1) DistributedLock.with_lock returns false if getting lock timeouts
     Failure/Error: described_class.with_lock('foo1') { sleep 0.1 }
     Moped::Errors::ConnectionFailure:
       Could not connect to a primary node for replica set #<Moped::Cluster:17287680 @seeds=[<Moped::Node resolved_address="127.0.0.1:27017">]>
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:254:in `with_primary'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:39:in `rescue in with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:29:in `with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:83:in `command'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:309:in `block in modify'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:374:in `with'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:308:in `modify'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/find_and_modify.rb:44:in `result'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:182:in `find_and_modify'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `find_and_modify'
     # ./app/models/distributed_lock.rb:44:in `obtain_lock'
     # ./app/models/distributed_lock.rb:18:in `block in with_lock'
     # ./app/models/distributed_lock.rb:17:in `with_lock'
     # ./spec/models/distributed_lock_spec.rb:27:in `block (4 levels) in <top (required)>'
```

### Timeout while read

In this case, the spec's first thread's `release_lock` operation gets the error response from the second thread's `obtain_lock` operation, which timed out after sending the operation, but before reading the header.

```
Timeout while obtaining lock: execution expired
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:47:in `read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:47:in `block in read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:119:in `handle_socket_errors'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb:47:in `read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:195:in `read_data'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:117:in `block in read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:225:in `with_connection'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:115:in `read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/protocol/query.rb:213:in `receive_replies'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:153:in `block in receive_replies'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:152:in `map'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:152:in `receive_replies'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:605:in `block (2 levels) in flush'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:663:in `read'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:90:in `command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:73:in `block in command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb:25:in `execute'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:83:in `command'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:309:in `block in modify'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:374:in `with'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:308:in `modify'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/find_and_modify.rb:44:in `result'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:182:in `find_and_modify'
/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `find_and_modify'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:43:in `obtain_lock'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:17:in `block in with_lock'
/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:16:in `with_lock'
/home/kontena/kontena/kontena/server/spec/models/distributed_lock_spec.rb:31:in `block (4 levels) in <top (required)>'

  An error occurred in an after hook
    NoMethodError: undefined method `length' for nil:NilClass
    occurred at /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:56:in `block in collection_names'

F

Failures:

  1) DistributedLock.with_lock returns false if getting lock timeouts
     Failure/Error: described_class.with_lock('foo1') { sleep 0.1 }
     Moped::Errors::OperationFailure:
       The operation: #<Moped::Protocol::Command
         @length=153
         @request_id=77
         @response_to=0
         @op_code=2004
         @flags=[]
         @full_collection_name="kontena_test.$cmd"
         @skip=0
         @limit=-1
         @selector={:count=>"distributed_locks", :query=>{"name"=>"foo1", "lock_id"=>"eb7055a10d04b3a71010a729a12b7d81"}}
         @fields=nil>
       failed with error 11000: "exception: E11000 duplicate key error index: kontena_test.distributed_locks.$name_1 dup key: { : \"foo1\" }"
       
       See https://github.com/mongodb/mongo/blob/master/docs/errors.md
       for details about this error.
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:63:in `block in execute'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `map'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
     # ./vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
     # ./vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
     # ./vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
     # ./vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
     # ./vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
     # ./vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
     # ./vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:663:in `read'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:90:in `command'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:73:in `block in command'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb:25:in `execute'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'
     # ./vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:42:in `count'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:60:in `block in count'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:457:in `try_cache'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:60:in `count'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:87:in `destroy'
     # ./vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `destroy'
     # ./app/models/distributed_lock.rb:56:in `release_lock'
     # ./app/models/distributed_lock.rb:31:in `with_lock'
     # ./spec/models/distributed_lock_spec.rb:27:in `block (4 levels) in <top (required)>'

Finished in 0.11129 seconds (files took 1.16 seconds to load)
1 example, 1 failure
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1986 to not interrupt moped operations.

This differs from the [agent's `WaitHelper`](https://github.com/kontena/kontena/blob/master/agent/lib/kontena/helpers/wait_helper.rb) in some ways:

* Renamed to `wait_until { condition }` to more closely match the `sleep interval until condition` that this is replacing
* The `wait_until!` method correctly returns the result
* The `wait_until` method only yields once if the interval is longer than the timeout
* The `wait_until` method does not yield if the timeout is zero
* The `wait_until` method takes the message as an optional first positional argument
* The debug and exception messages contains timing information
* More debug messages

This differs from the existing `Timeout::timeout` in some ways:

* Does not impose any timeout on the actual block operation - you need to use e.g. moped's own timeout mechanisms instead

### CODE REVIEW

File: server/app/models/distributed_lock.rb [hunk 1]
```diff
@@ -13,17 +15,16 @@ def self.with_lock(name, timeout = 60)
     lock_id = nil
     begin
       if timeout.to_f > 0.0
-        Timeout.timeout(timeout) do
-          sleep 0.01 until lock_id = self.obtain_lock(name)
-        end
+        lock_id = WaitHelper.wait(timeout: timeout) { self.obtain_lock(name) }
```
Comment (jakolehm) [inline server/app/models/distributed_lock.rb]: Why not include `WaitHelper` ?

**Comment by jnummelin** [comment]
There is one missed `Timeout::timeout` call in `GridCertificates::GetCertificate` mutation

File: server/app/helpers/wait_helper.rb [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+    loop do
+      return nil if _wait_now > wait_until
+
+      value = yield
+
+      if value
+        return value
+      else
+        debug "wait... #{message}"
```
Comment (jnummelin) [inline server/app/helpers/wait_helper.rb]: Should this be guarded with `if message`? Seeing just random `wait...` entries in the log might be confusing.

Comment (SpComb) [inline server/app/helpers/wait_helper.rb]: They will have the including class name for context.

```
D, [2017-03-16T09:08:49.254409 #27900] DEBUG -- StackRemoveWorker: wait... 
```

Comment (jnummelin) [inline server/app/helpers/wait_helper.rb]: Yes, but it still gives no idea what it's waiting for. It's on `DEBUG` so should not matter that much. :)

**Comment by SpComb** [comment]
> There is one missed Timeout::timeout call in GridCertificates::GetCertificate mutation

It doesn't do any mongo operations AFAIK, so I didn't touch it... it looks like the `acme_client` configures a timeout, so this could be replaced with `wait`, but then I would need to test it... ain't got no time for that.

File: server/app/models/distributed_lock.rb (hunk 1 above)
Comment (SpComb) [inline server/app/models/distributed_lock.rb]: Because this is a class method, so just `include WaitHelper` doesn't let you call `self.wait`

```
  1) DistributedLock.with_lock returns false if getting lock timeouts
     Failure/Error: described_class.with_lock('foo1') { sleep 0.1 }
     NoMethodError:
       undefined method `wait' for DistributedLock:Class
       Did you mean?  with
     # ./app/models/distributed_lock.rb:19:in `with_lock'
     # ./spec/models/distributed_lock_spec.rb:27:in `block (4 levels) in <top (required)>'
```

Is there a better way to get this working?

File: server/app/helpers/wait_helper.rb (hunk 2 above)
Comment (SpComb) [inline server/app/helpers/wait_helper.rb]: Cherry-picked from  #1988

**Comment by SpComb** [comment]
>> There is one missed Timeout::timeout call in GridCertificates::GetCertificate mutation
> 
> It doesn't do any mongo operations AFAIK, so I didn't touch it... it looks like the acme_client configures a timeout, so this could be replaced with wait, but then I would need to test it... ain't got no time for that.

Cherry-picked from  #1988

**Comment by SpComb** [comment]
>>> There is one missed Timeout::timeout call in GridCertificates::GetCertificate mutation
>>
>>   It doesn't do any mongo operations AFAIK, so I didn't touch it... it looks like the acme_client configures a timeout, so this could be replaced with wait, but then I would need to test it... ain't got no time for that.
> 
> Cherry-picked from #1988

The replacement wait was broken, un-pushed this bit. Let's just leave it as it is.

File: server/app/models/distributed_lock.rb (hunk 1 above)
Comment (SpComb) [inline server/app/models/distributed_lock.rb]: This changes the default `sleep` interval from 0.01 to 0.5. Looking at the calls to `with_dlock` in the server:

```ruby
    with_dlock("check_deploy_queue:#{service_deploy.grid_service_id}", 10) do
    with_dlock(DLOCK_KEY, nil) do
    with_dlock('mongodb_migrate', 60) do
```

I don't suppose this makes tooooooo much of a difference?

Comment (SpComb) [inline server/app/models/distributed_lock.rb]: Might still be a good idea to bump this down to 0.05 or something, just to keep it as similar as possible.

**Comment by SpComb** [comment]
Renamed `wait` -> `wait_until`

File: server/app/helpers/wait_helper.rb [hunk 3]
```diff
@@ -28,7 +28,7 @@ def wait(timeout: WAIT_TIMEOUT, interval: WAIT_INTERVAL, message: nil, &block)
       if value
         return value
       else
-        debug "wait... #{message}" if message
```
Comment (SpComb) [inline server/app/helpers/wait_helper.rb]: Eh... somehow accidentially reverted this change. Must have still had it open in my editor.

File: server/app/helpers/wait_helper.rb [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+
+  # Wait until given block returns truthy value, raising on timeout
+  #
+  # @return [Object] Last return value of the block
+  # @raise [Timeout::Error] If block does not return truthy value within given timeout
+  def wait_until!(**opts, &block)
+    if value = wait_until(**opts, &block)
+      return value
+    else
+      raise Timeout::Error
```
Comment (jnummelin) [inline server/app/helpers/wait_helper.rb]: Would it make sense to put in some "context" for the error? Now the logs don't show much on these:
```
E, [2017-03-16T09:45:47.758033 #16] ERROR -- GridServiceInstanceDeployer: Timeout::Error
api_1      | E, [2017-03-16T09:45:47.758132 #16] ERROR -- GridServiceInstanceDeployer: /app/app/helpers/wait_helper.rb:45:in `wait_until!'
api_1      | /app/app/services/grid_service_instance_deployer.rb:36:in `wait_for_service_to_start'
api_1      | /app/app/services/grid_service_instance_deployer.rb:22:in `deploy'
api_1      | /app/app/services/grid_service_deployer.rb:112:in `block in deploy_service_instance'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
```
It would help debugging if there would be something like:
```
E, [2017-03-16T09:45:47.758033 #16] ERROR -- GridServiceInstanceDeployer: Timeout::Error: service startup
```

Comment (SpComb) [inline server/app/helpers/wait_helper.rb]: AFAIK the `GridServiceInstanceDeployer: Timeout::Error` is equivalent to what it currently logs when using `Timeout::timeout { ... }`

Yes, this could be improved to log something like `Timeout after 300s while waiting until service is running` if each of the callers passes in a `message: ...`.

Comment (jnummelin) [inline server/app/helpers/wait_helper.rb]: Yes, pull in the provided message somehow if given

**Comment by SpComb** [comment]
Changed the `wait_until(message)` to be an optional positional parameter, similar to e.g. https://github.com/rubytools/waitutil

Added messages to all the server waits:

```
D, [2017-03-16T14:14:28.474436 #22752] DEBUG -- StackRemoveWorker: waiting 532.8s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:28.976228 #22752] DEBUG -- StackRemoveWorker: waiting 533.3s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:29.477632 #22752] DEBUG -- StackRemoveWorker: waiting 533.8s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:29.979917 #22752] DEBUG -- StackRemoveWorker: waiting 534.4s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:30.481552 #22752] DEBUG -- StackRemoveWorker: waiting 534.9s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:30.986080 #22752] DEBUG -- StackRemoveWorker: waiting 535.4s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:31.488383 #22752] DEBUG -- StackRemoveWorker: waiting 535.9s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:31.992230 #22752] DEBUG -- StackRemoveWorker: waiting 536.4s of 600.0s until: service development/redis/redis is gone
D, [2017-03-16T14:14:32.496606 #22752] DEBUG -- StackRemoveWorker: waiting 536.9s of 600.0s until: service development/redis/redis is gone
```

File: server/app/jobs/grid_service_remove_worker.rb [hunk 5]
```diff
@@ -21,18 +22,19 @@ def remove_grid_service(grid_service)
       wait_instance_removal(grid_service, grid_service.containers.scoped.count * 30)
 
       grid_service.destroy
-    rescue Timeout::Error
-      error "service remove timed out #{grid_service.to_path}"
+    rescue => error
```
Comment (SpComb) [inline server/app/jobs/grid_service_remove_worker.rb]: Also catching things like RPC errors now... although irrelevant after #1873

**Comment by SpComb** [comment]
See #1991 for the zero-timeout edgecase breaking the `GridServiceRemoveWorker`.
