### PR TITLE
test: add run! helper that raises on errors

### LINKED ISSUE #3059: e2e entrypoints spec uses uncommited run! method
The e2e specs for stack/service entrypoints in #2950 mistakenly use the non-existant `run!` helper - the the specs still passed on my machine, but I never ended up commiting the exception-raising `run!` helper as part of that PR-fix.

```
  19) stack service entrypoint for a stack service with an entrypoint configures the container with the nested /w/w entrypoint
      Failure/Error: run! 'kontena stack install sleep.yml'
      
      NoMethodError:
        undefined method `run!' for #<RSpec::ExampleGroups::StackServiceEntrypoint::ForAStackServiceWithAnEntrypoint:0x0000562c84719420>
        Did you mean?  run
      # ./spec/features/stack/services/entrypoint_spec.rb:7:in `block (4 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/services/entrypoint_spec.rb:6:in `block (3 levels) in <top (required)>'

  20) stack service entrypoint for a stack service with an entrypoint in network_mode=host configures the container with the correct entrypoint
      Failure/Error: run! 'kontena stack install etcdctl-watch.yml'
      
      NoMethodError:
        undefined method `run!' for #<RSpec::ExampleGroups::StackServiceEntrypoint::ForAStackServiceWithAnEntrypointInNetworkModeHost:0x0000562c83ef8700>
        Did you mean?  run
      # ./spec/features/stack/services/entrypoint_spec.rb:26:in `block (4 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/services/entrypoint_spec.rb:25:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #3059

### CODE REVIEW

File: test/spec/support/shell.rb [hunk 1]
```diff
@@ -8,6 +19,16 @@ def run(cmd, opts = {})
...
   end
 
+  # @param [String] cmd
+  # @param [Hash] opts
+  # @raise [Error]
+  # @return [Kommando]
+  def run!(cmd, **opts)
+    k = run(cmd, **opts)
+    raise Error.new(cmd, k.code, k.out) if k.code != 0
+    return k
```
Comment (kke) [inline test/spec/support/shell.rb]: doesn't need `return`

could even be:
```ruby
def run(!cmd, **opts)
  run(cmd, **opts).tap do |k|
    raise Error.new(cmd, k.code, k.out) unless k.code.zero?
  end
end
```

Comment (SpComb) [reply test/spec/support/shell.rb]: I personally like the explicit `return` in this kind of case. The `tap` reads okay as well, should I change it to use that?

Comment (kke) [reply test/spec/support/shell.rb]: Explicit return statement adds an extra method call compared to just `k`. but this is in test helper so it doesn't make any difference.
