### PR TITLE
Agent: Fix WebsocketClient reconnect

### LINKED ISSUE #1601: Agent WebsocketClient gets stuck on connection close
The Agent `Kontena::WebsocketClient` uses `Faye::WebSocket::Client` with `EventMachine` for the control channel to the master server. The client implements a keepalive timer, where every 30s it will send a websocket ping to the server, and wait up to 2000ms for a response.

If the `WebsocketClient` does not receive a pong response within 2000ms, it will call `@ws.close`, and mark itself as disconnected once it gets `@ws.on :close`. This triggers a reconnect using a new websocket. 

However, the [`Faye::WebSocket::Client#close`](https://github.com/faye/faye-websocket-ruby/blob/0.10.1/lib/faye/websocket/api.rb#L74) method calls the [`Websocket::Driver#close`](https://github.com/faye/websocket-driver-ruby/blob/0.6.3/lib/websocket/driver/hybi.rb#L147) method, which actually sends a websocket close frame... the `:close` event is only triggered once the server replies (or on some other protocol error). In the case of a dead TCP connection, this means that the `@ws.close` called after the keepalvie timeout does *NOT* provide any gurarantees as to when the `:close` event will be omitted.

This is easy to repro by blackholing the master from a node: `sudo ip ro add blackhole 192.168.66.1/32`

The agent notices that the websocket is dead, but it does not actually reconnect... not until the blackhole route is removed (`ip ro del blackhole 192.168.66.1/32`), and the TCP socket resumes sending (`ss -t` -> `Send-Q == 0`):

```
kontena-agent | I, [2016-12-30T12:06:56.173340 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
.... wait until dropping the blackhole route ....
kontena-agent | I, [2016-12-30T12:07:42.437398 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
kontena-agent | I, [2016-12-30T12:07:42.593559 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T12:07:42.638189 #1]  INFO -- Kontena::WebsocketClient: connection established
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #1601 

* Fix Agent to abort on errors in the EventMachine thread

    Previously these would be silently ignored, and the websocket client would just stop working.

* Fix leaking `@ping_timer` that prevented keepalive/reconnect from triggering after a reconnect

    The @ping_timer remains until closed, so as to avoid extra keepalives while closing.

* Implement `#close` method with force-close timeout

    Forces a `@ws.on :close` event after a timeout, which causes the `@ws` to be thrown away and replaced with a new one.

    This is effectively a user-side version of the upstream https://github.com/faye/faye-websocket-ruby/commit/07be5a24ef446db5d7e461ca1eaa9fa6aa7b7f21 commit, but with stronger guarantees.

    This may leak the abandoned websocket client sockets if the server never TCP RSTs them. Fixing that would need to figure out how to force-close the `Faye::WebSocket::Client`'s internal EM connection.

* Stop sending Websocket messages immediately on the keepalive close

    The `QueueWorker` will keep hold of any messages, and then re-send them after reconnecting. It's probably best to minimize the number of messages sent on the dead websocket, that will most likely end up getting dropped.

TODO specs?

## Example

Testing with `ip ro add/del blackhole 192.168.66.1/32`

```
kontena-agent | D, [2016-12-30T13:40:10.647665 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:11.070912 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:12.073107 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:12.459706 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:13.074962 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:13.645983 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:13.908269 #1] DEBUG -- WebsocketClient: verify-connection tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:13.909178 #1] DEBUG -- WebsocketClient: verify_connection: @ping_timer=
kontena-agent | D, [2016-12-30T13:40:14.076385 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:15.078673 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | I, [2016-12-30T13:40:15.911645 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
kontena-agent | I, [2016-12-30T13:40:15.916687 #1]  INFO -- Kontena::Workers::QueueWorker: stopped processing of msg queue
kontena-agent | I, [2016-12-30T13:40:15.919133 #1]  INFO -- Kontena::Workers::LogWorker: stopped log streaming
kontena-agent | D, [2016-12-30T13:40:16.080114 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:17.082237 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:18.084099 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:18.910061 #1] DEBUG -- WebsocketClient: verify-connection tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:18.910449 #1] DEBUG -- WebsocketClient: verify_connection: @ping_timer=#<EventMachine::Timer:0x00565518c2d828>
kontena-agent | D, [2016-12-30T13:40:19.084680 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | D, [2016-12-30T13:40:20.086466 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=true
kontena-agent | W, [2016-12-30T13:40:20.921435 #1]  WARN -- Kontena::WebsocketClient: Hit close timeout, abandoning existing websocket connection
kontena-agent | I, [2016-12-30T13:40:20.923993 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:21.087955 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:21.088610 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:21.174002 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:22.174663 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:22.175565 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:22.230152 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:23.231309 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:23.233078 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:23.284991 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:23.911556 #1] DEBUG -- WebsocketClient: verify-connection tick: connected?=false
kontena-agent | D, [2016-12-30T13:40:24.286559 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:24.287392 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:24.334933 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:25.336393 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:25.337118 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:25.398034 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:26.399181 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:26.399547 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:26.431377 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:27.432953 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:27.433607 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:27.516533 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:28.524151 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:28.526196 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:28.548311 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | D, [2016-12-30T13:40:28.913249 #1] DEBUG -- WebsocketClient: verify-connection tick: connected?=false
kontena-agent | D, [2016-12-30T13:40:29.549401 #1] DEBUG -- WebsocketClient: ensure-connect tick: connected?=false
kontena-agent | I, [2016-12-30T13:40:29.550106 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T13:40:29.604503 #1]  INFO -- Kontena::WebsocketClient: connection established
kontena-agent | D, [2016-12-30T13:40:29.627441 #1] DEBUG -- RpcServer: rpc notification: Kontena::Rpc::AgentApi#master_info [{"version"=>"1.0.3"}]
kontena-agent | I, [2016-12-30T13:40:29.629762 #1]  INFO -- Kontena::Workers::QueueWorker: started to process msg queue
kontena-agent | I, [2016-12-30T13:40:29.631893 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
kontena-agent | I, [2016-12-30T13:40:29.640915 #1]  INFO -- Kontena::Workers::LogWorker: started log streaming
kontena-agent | D, [2016-12-30T13:40:29.653758 #1] DEBUG -- RpcServer: rpc notification: Kontena::Rpc::AgentApi#node_info [{"id"=>"XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5", "connected"=>true, "created_at"=>"2016-10-27T08:15:31.084Z", "updated_at"=>"2016-12-30T12:05:30.471Z", "last_seen_at"=>"2016-12-30T13:40:29.615Z", "name"=>"core-01", "os"=>"CoreOS 1185.5.0 (MoreOS)", "engine_root_dir"=>"/var/lib/docker", "driver"=>"overlay", "kernel_version"=>"4.7.3-coreos-r3", "labels"=>nil, "mem_total"=>1045471232, "mem_limit"=>0, "cpus"=>1, "public_ip"=>"82.181.116.101", "private_ip"=>"192.168.66.101", "agent_version"=>"1.0.3", "docker_version"=>"1.11.2", "peer_ips"=>["192.168.66.103"], "node_number"=>1, "initial_member"=>true, "grid"=>{"id"=>"development", "name"=>"development", "initial_size"=>1, "token"=>"tBsoco4sBClMtIOD/bHeIqS1KYM0kZMG7B960jNWWQXMOxqhOf8W1QgiNJlW9u6B/qS+rfS2ZLpC/ZJsyPNj0A==", "stats"=>{"statsd"=>nil}, "trusted_subnets"=>[]}, "resource_usage"=>{"memory"=>{"total"=>1045471232, "free"=>77860864, "buffers"=>25952256, "cached"=>231133184, "active"=>547962880, "inactive"=>134123520, "used"=>967610368}, "load"=>{"1m"=>0.69970703125, "5m"=>0.5859375, "15m"=>0.51611328125}, "filesystem"=>[{"name"=>"/var/lib/docker", "free"=>11573723136, "available"=>10690527232, "used"=>5144670208, "total"=>16718393344}]}}]
kontena-agent | D, [2016-12-30T13:40:29.680681 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:29.682186 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:29.684115 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:29.685798 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:29.744114 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:29.804550 #1] DEBUG -- WebsocketClient: send message with ws?=true...
kontena-agent | D, [2016-12-30T13:40:29.854067 #1] DEBUG -- WebsocketClient: send message with ws?=true...
```

### CODE REVIEW

File: agent/lib/kontena/agent.rb [hunk 1]
```diff
@@ -155,7 +155,10 @@ def supervise_lb
 
     def start_em
       EM.epoll
-      Thread.new { EventMachine.run } unless EventMachine.reactor_running?
+      Thread.new {
+        Thread.abort_on_exception = true
```
Comment (jakolehm) [inline agent/lib/kontena/agent.rb]: Does this set abort globally?

Comment (SpComb) [inline agent/lib/kontena/agent.rb]: Right, I read the docs too hastily, that should be set on `Thread.current`

**Comment by SpComb** [comment]
How reasonable is it to try and write specs for `WebsocketClient`'s EM timer state machine, or just manual testing?

File: agent/lib/kontena/websocket_client.rb [hunk 2]
```diff
@@ -177,5 +182,28 @@ def verify_connection
...
+    def close
+      return if @close_timer
+
+      # stop sending messages, queue them up until reconnected
+      Celluloid::Notifications.publish('websocket:disconnect', nil)
+
+      # send close frame; this will get stuck if the server is not replying
+      ws.close(1000)
+
+      @close_timer = EM::Timer.new(CLOSE_TIMEOUT) do
```
Comment (SpComb) [inline agent/lib/kontena/websocket_client.rb]: If we upgrade to a faye-websocket release that includes https://github.com/faye/faye-websocket-ruby/commit/07be5a24ef446db5d7e461ca1eaa9fa6aa7b7f21, then there will be two concurrent timeouts...

Perhaps we should detect the presence of a `Faye::Websocket::Client.CLOSE_TIMEOUT`? We could still keep this timeout, but just make sure that it's longer than the faye close timeout?

File: agent/lib/kontena/websocket_client.rb [hunk 3]
```diff
@@ -177,5 +182,28 @@ def verify_connection
...
+
+    # Abort the connection, closing the websocket, with a timeout
+    def close
+      return if @close_timer
+
+      # stop sending messages, queue them up until reconnected
+      Celluloid::Notifications.publish('websocket:disconnect', nil)
+
+      # send close frame; this will get stuck if the server is not replying
+      ws.close(1000)
```
Comment (jakolehm) [inline agent/lib/kontena/websocket_client.rb]: Should we call close inside close timer?

Comment (SpComb) [inline agent/lib/kontena/websocket_client.rb]: The `@close_timer` does what `ws.close` should have done, but didn't.

File: agent/lib/kontena/websocket_client.rb (hunk 2 above)
Comment (jakolehm) [inline agent/lib/kontena/websocket_client.rb]: Detect sounds good.

File: agent/lib/kontena/websocket_client.rb (hunk 3 above)
Comment (jakolehm) [inline agent/lib/kontena/websocket_client.rb]: Oh, yes.. I did not mean to call it twice. But now I just realized that close does not block ever.

**Comment by SpComb** [comment]
Added some basic specs for `#close`, but that doesn't cover all the possible interactions and connection/timer states.

**Comment by SpComb** [comment]
Quick testing of 1.0.4.rc1 on DO seems to behave well when blackholing, restarting, resestting the master.

The old websocket connections remain hung in the background while it's attempting to reconnect, but then they eventually go away once the server returns, the node's TCP retransmit kicks in, and the server then replies with a RST for the invalid connection.
